import React from "react";
import { Button, Card, InlineStack, Layout, Page, Text } from "@shopify/polaris";
import CommonForm from "@/Components/Common/CommonForm";
import DismissibleBanner from "@/Components/Common/DismissibleBanner";
import { PremiumButton } from "@/Components/Common/PremiumBadge";

let options = [
  { label: "", value: "" },
  { label: "AccountingService", value: "accountingService" },
  { label: "AdultEntertainment", value: "adultEntertainment" },
  { label: "AmusementPark", value: "AmusementPark" },
  { label: "AnimalShetter", value: "animalShetter" },
  { label: "ArtGallery", value: "artGallery" },
  { label: "AutoBodyShop", value: "autoBodyShop" },
  { label: "AutoDealer", value: "autoDealer" },
  { label: "AutoPartsStore", value: "autoPartsStore" },
  { label: "AutoRental", value: "autoRental" },
  { label: "AutoRepair", value: "autoRepair" },
  { label: "AutoWash", value: "autoWash" },
  { label: "AutomatedTeller", value: "automatedTeller" },
  { label: "Bakery", value: "bakery" },
  { label: "BankOrCreditUnion", value: "bankOrCreditUnion" },
  { label: "BarOrPub", value: "barOrPub" },
  { label: "BeautySalon", value: "beautySalon" },
  { label: "BikeStore", value: "bikeStore" },
  { label: "BookStore", value: "bookStore" },
  { label: "BowlingAlley", value: "bowlingAlley" },
  { label: "Brewery", value: "brewery" },
  { label: "CafeOrCoffeeShop", value: "cafeOrCoffeeShop" },
  { label: "Casino", value: "casino" },
  { label: "ChildCare", value: "childCare" },
  { label: "ClothingStore", value: "clothingStore" },
  { label: "ComedyClub", value: "comedyClub" },
  { label: "ComputerStore", value: "computerStore" },
  { label: "ConvenienceStore", value: "convenienceStore" },
  { label: "DaySpa", value: "daySpa" },
  { label: "Dentist", value: "dentist" },
  { label: "Dermatology", value: "dermatology" },
  { label: "DepartmentStore", value: "departmentStore" },
  { label: "DietNutrition", value: "dietNutrition" },
  { label: "Distillery", value: "distillery" },
  { label: "Electrician", value: "electrician" },
  { label: "ElectronicsStore", value: "electronicsStore" },
  { label: "Emergency", value: "emergency" },
  { label: "ExerciseGym", value: "exerciseGym" },
  { label: "FastfoodRestaurant", value: "fastfoodRestaurant" },
  { label: "FireStation", value: "fireStation" },
  { label: "Florist", value: "florist" },
  { label: "FurnitureStore", value: "furnitureStore" },
  { label: "GasStation", value: "gasStation" },
  { label: "GardenStore", value: "gardenStore" },
  { label: "GeneralContractor", value: "generalContractor" },
  { label: "Geriatric", value: "geriatric" },
  { label: "GolfCourse", value: "golfCourse" },
  { label: "GroceryStore", value: "groceryStore" },
  { label: "Gynecologic", value: "Gynecologic" },
  { label: "HVACBusiness", value: "HVACBusiness" },
  { label: "HairSalon", value: "hairSalon" },
  { label: "HardwareStore", value: "hardwareStore" },
  { label: "HealthAndBeautyBusiness", value: "healthAndBeautyBusiness" },
  { label: "HealthClub", value: "healthClub" },
  { label: "HobbyShop", value: "hobbyShop" },
  { label: "HomeGoodsStore", value: "homeGoodsStore" },
  { label: "Hospital", value: "hospital" },
  { label: "Hostel", value: "hostel" },
  { label: "Hotel", value: "hotel" },
  { label: "HousePainter", value: "housePainter" },
  { label: "IceCreamShop", value: "iceCreamShop" },
  { label: "InsuranceAgency", value: "insuranceAgency" },
  { label: "InternetCafe", value: "internetCafe" },
  { label: "JewelryStore", value: "jewelryStore" },
  { label: "Library", value: "library" },
  { label: "LiquorStore", value: "liquorStore" },
  { label: "Locksmith", value: "locksmith" },
  { label: "MedicalClinic", value: "medicalClinic" },
  { label: "MensClothingStore", value: "mensClothingStore" },
  { label: "MobilePhoneStore", value: "mobilePhoneStore" },
  { label: "MovieRentalStore", value: "movieRentalStore" },
  { label: "Motel", value: "motel" },
  { label: "MotorcycleDealer", value: "motorcycleDealer" },
  { label: "MotorcycleRepair", value: "motorcycleRepair" },
  { label: "MovieTheater", value: "movieTheater" },
  { label: "MovingCompany", value: "movingCompany" },
  { label: "MusicStore", value: "musicStore" },
  { label: "NailSalon", value: "nailSalon" },
  { label: "NightClub", value: "nightClub" },
  { label: "Obstetric", value: "obstetric" },
  { label: "OfficeEquipmentStore", value: "officeEquipmentStore" },
  { label: "Oncologic", value: "oncologic" },
  { label: "Optician", value: "optician" },
  { label: "Optometric", value: "optometric" },
  { label: "OryCleaningOrLaundry", value: "oryCleaningOrLaundry" },
  { label: "Otolaryngologic", value: "otolaryngologic" },
  { label: "OutletStore", value: "outletStore" },
  { label: "PawnShop", value: "pawnShop" },
  { label: "PetStore", value: "petStore" },
  { label: "Pharmacy", value: "pharmacy" },
  { label: "Physician", value: "physician" },
  { label: "PlasticSurgery", value: "plasticSurgery" },
  { label: "Plumber", value: "plumber" },
  { label: "PoliceStation", value: "policeStation" },
  { label: "ProfessionalService", value: "professionalService" },
  { label: "Psychiatric", value: "psychiatric" },
  { label: "PublicHealth", value: "publicHealth" },
  { label: "PublicSwimmingPool", value: "publicSwimmingPool" },
  { label: "RealEstateAgent", value: "realEstateAgent" },
  { label: "Resort", value: "resort" },
  { label: "Restaurant", value: "restaurant" },
  { label: "RoofingContractor", value: "roofingContractor" },
  { label: "ShoeStore", value: "shoeStore" },
  { label: "ShoppingCenter", value: "shoppingCenter" },
  { label: "SkiResort", value: "skiResort" },
  { label: "SportsClub", value: "sportsClub" },
  { label: "sportingGoodsStore", value: "sportingGoodsStore" },
  { label: "TattooParior", value: "tattooParior" },
  { label: "TireShop", value: "tireShop" },
  { label: "ToyStore", value: "toyStore" },
  { label: "TravelAgency", value: "travelAgency" },
  { label: "WholesaleStore", value: "wholesaleStore" },
  { label: "Winery", value: "winery" },
];

export const formFields = [
  {
    id: "businessImages",
    name: "businessImages",
    label: "Business Images",
    actionTitle: "Add Image",
    type: "imagePicker",
    helpText: "Enter the URL of the image representing the business, such as building signage or a logo.",
    allowMultiple: true,
    fileType: "image",
    accept: "image/*",
    min: 2,
    max: 5,
  },
  {
    id: "currenciesSelect",
    name: "currenciesSelect",
    label: "Multiselect Example",
    type: "multiSelect",
    placeholder: "-------Select Currency-------",
    errormsg: "currency is required",
    options: [...options],
  },
  {
    id: "oneImage",
    name: "oneImage",
    label: "oneImage Images",
    actionTitle: "Add Image",
    type: "imagePicker",
    helpText: "Enter the URL of the image representing the business, such as building signage or a logo.",
    allowMultiple: false,
    fileType: "image",
    accept: "image/*",
    min: 1,
  },
  {
    nested: "group",
    groupSize: 1,
    section: true,
    subfields: [
      {
        nested: "group",
        groupSize: 2,
        section: false,
        subfields: [
          {
            id: "businessImages1",
            name: "businessImages1",
            label: "Business Images",
            validated: true,
            errormsg: "Business Images is required",
            type: "text",
            helpText: "Enter the URL of the image representing the business, such as building signage or a logo.",
          },
          {
            id: "businessImages2",
            name: "businessImages2",
            label: "Business Images 2",
            validated: true,
            errormsg: "Business Images2 is required",
            type: "text",
            helpText:
              "Enter the URL of the image of your local business, such as a photo of the business exterior.",
          },
        ],
      },
      {
        nested: "group",
        groupSize: 3,
        section: false,
        subfields: [
          {
            id: "priceRange",
            name: "priceRange",
            label: "Price Range",
            validated: true,
            errormsg: "Price Range is required",
            type: "text",
            helpText: "Enter the price range of the business, for example '$10-50', or currency signs - '$$$'",
          },
          {
            id: "businessType",
            name: "businessType",
            label: "Business Type",
            options: [...options],
            type: "customSelector",
            validated: true,
            errormsg: "Business Type is required",
          },
          {
            id: "businessName",
            name: "businessName",
            label: "Business Name",
            validated: true,
            errormsg: "Business Name is required",
            type: "text",
          },
          ,
        ],
      },
    ],
  },
  {
    nested: "group",
    groupSize: 1,
    section: true,
    subfields: [
      {
        nested: "group",
        groupSize: 2,
        section: false,
        subfields: [
          {
            id: "streetAddress",
            name: "streetAddress",
            label: "Street Address",
            type: "text",
            helpText: "Enter the street address of the business.",
            validated: true,
            errormsg: "Street Address is required",
          },
          {
            id: "addressLocality",
            name: "addressLocality",
            label: "Locality",
            type: "text",
            helpText: "Enter the city where the business is located.",
            validated: true,
            errormsg: "Locality is required",
          },
        ],
      },
      {
        nested: "group",
        groupSize: 3,
        section: false,
        subfields: [
          {
            id: "region",
            name: "region",
            label: "Region",
            type: "text",
            helpText: "Enter the state or province",
            validated: true,
            errormsg: "Region is required",
          },
          {
            id: "postalCode",
            name: "postalCode",
            label: "Postal Code",
            type: "text",
            validated: true,
            errormsg: "Postal Code is required",
          },
          {
            id: "telephone",
            name: "telephone",
            label: "Telephone",
            type: "text",
          },
        ],
      },
    ],
  },
  {
    id: "workingDays",
    name: "workingDays",
    label: "Working Days",
    nested: "array",
    minimum: 1,
    allowDrag: true,
    subfields: [
      {
        nested: "object",
        id: "DaysOfWeek",
        name: "DaysOfWeek",
        label: "Working Days",
        groupSize: 7,
        section: false,
        subfields: [
          {
            id: "monday",
            name: "monday",
            label: "Monday",
            type: "checkbox",
          },
          {
            id: "tuesday",
            name: "tuesday",
            label: "Tuesday",
            type: "checkbox",
          },
          {
            id: "wednesday",
            name: "wednesday",
            label: "Wednesday",
            type: "checkbox",
          },
          {
            id: "thursday",
            name: "thursday",
            label: "Thursday",
            type: "checkbox",
          },
          {
            id: "friday",
            name: "friday",
            label: "Friday",
            type: "checkbox",
          },
          {
            id: "saturday",
            name: "saturday",
            label: "Saturday",
            type: "checkbox",
          },
          {
            id: "sunday",
            name: "sunday",
            label: "Sunday",
            type: "checkbox",
          },
        ],
      },
      {
        nested: "group",
        groupSize: 2,
        section: false,
        subfields: [
          {
            id: "opens",
            name: "opens",
            label: "Opening Time",
            type: "time",
            helpText: "Enter the opening time of the business.",
            validated: true,
            errormsg: "Opening time is required",
          },
          {
            id: "closes",
            name: "closes",
            label: "Closing time",
            type: "time",
            helpText: "Enter the closing time of the business.",
            validated: true,
            errormsg: "closing time is required",
          },
        ],
      },
    ],
  },
  {
    id: "name",
    name: "name",
    label: "Name",
    validated: true,
    type: "text",
    errormsg: "Name is required",
    showPremium: true,
  },
  {
    id: "author",
    name: "author",
    label: "Author",
    validated: true,
    type: "text",
    errormsg: "Author is required",
  },
  {
    id: "description",
    name: "description",
    label: "Description",
    validated: true,
    type: "text",
    errormsg: "Description is required",
  },
  {
    id: "prepTime",
    name: "prepTime",
    label: "Preparation Time",
    nested: "object",
    groupSize: 3,
    subfields: [
      {
        nested: "group",
        groupSize: 2,
        section: false,
        subfields: [
          {
            id: "day",
            name: "day",
            label: "Days",
            validated: true,
            type: "number",
            min: 0,
            errormsg: "Days is required",
          },
          {
            id: "hours",
            name: "hours",
            label: "Hours",
            validated: true,
            type: "number",
            min: 0,
            errormsg: "Hours is required",
          },
          {
            id: "minutes",
            name: "minutes",
            label: "Minutes",
            validated: true,
            type: "number",
            min: 0,
            errormsg: "Minutes is required",
          },
        ],
      },
    ],
  },
  {
    id: "cookTime",
    name: "cookTime",
    label: "Cook Time",
    nested: "object",
    groupSize: 3,
    subfields: [
      {
        id: "day",
        name: "day",
        label: "Days",
        validated: true,
        type: "number",
        min: 0,
        errormsg: "Days is required",
      },
      {
        id: "hours",
        name: "hours",
        label: "Hours",
        validated: true,
        type: "number",
        min: 0,
        errormsg: "Hours is required",
      },
      {
        id: "minutes",
        name: "minutes",
        label: "Minutes",
        validated: true,
        type: "number",
        min: 0,
        errormsg: "Minutes is required",
      },
    ],
  },
  {
    id: "totalTime",
    name: "totalTime",
    label: "Total Time",
    nested: "object",
    groupSize: 3,
    subfields: [
      {
        id: "day",
        name: "day",
        label: "Days",
        validated: true,
        type: "number",
        min: 0,
        errormsg: "Days is required",
      },
      {
        id: "hours",
        name: "hours",
        label: "Hours",
        validated: true,
        type: "number",
        min: 0,
        errormsg: "Hours is required",
      },
      {
        id: "minutes",
        name: "minutes",
        label: "Minutes",
        validated: true,
        type: "number",
        min: 0,
        errormsg: "Minutes is required",
      },
    ],
  },
  {
    id: "keywords",
    name: "keywords",
    label: "Keywords",
    validated: true,
    type: "text",
    errormsg: "Keywords is required",
  },
  {
    id: "recipeYield",
    name: "recipeYield",
    label: "Recipe Yield",
    validated: true,
    type: "text",
    errormsg: "Recipe Yield is required",
  },
  {
    id: "recipeCategory",
    name: "recipeCategory",
    label: "Recipe Category",
    validated: true,
    type: "text",
    errormsg: "Recipe Category is required",
  },
  {
    id: "recipeCuisine",
    name: "recipeCuisine",
    label: "Recipe Cuisine",
    validated: true,
    type: "text",
    errormsg: "Recipe Cuisine is required",
  },
  {
    id: "nutrition",
    name: "nutrition",
    label: "Nutrition",
    validated: true,
    type: "text",
    errormsg: "Nutrition is required",
  },
  {
    id: "recipeIngredient",
    name: "recipeIngredient",
    minimum: 1,
    label: "Recipe Ingredients",
    nested: "array",
    groupSize: 2,
    subfields: [
      {
        id: "name",
        name: "name",
        label: "Name",
        validated: true,
        type: "text",
        errormsg: "Name is required",
      },
    ],
  },
  {
    id: "recipeInstructions",
    name: "recipeInstructions",
    minimum: 1,
    label: "Recipe Instructions",
    nested: "array",
    groupSize: 2,
    showCollapsible: true,
    allowDrag: true,
    CollapsibleLabel: `"abc"`,
    subfields: [
      {
        id: "name",
        name: "name",
        label: "Name",
        validated: true,
        type: "text",
        errormsg: "Name is required",
      },
      {
        id: "text",
        name: "text",
        label: "Text",
        validated: true,
        type: "text",
        errormsg: "Text is required",
      },
      {
        id: "url",
        name: "url",
        label: "Url",
        validated: true,
        type: "url",
        errormsg: "Url is required",
      },
      {
        id: "image",
        name: "image",
        label: "Image",
        validated: true,
        type: "text",
        errormsg: "Image is required",
      },
    ],
  },
  {
    id: "ratingValue",
    name: "ratingValue",
    label: "Rating Value",
    validated: true,
    type: "text",
    errormsg: "Rating Value is required",
  },
  {
    id: "ratingCount",
    name: "ratingCount",
    label: "Rating Count",
    validated: true,
    type: "text",
    errormsg: "Rating Count is required",
  },
  {
    id: "video",
    name: "video",
    label: "Video",
    nested: "object",
    groupSize: 3,
    subfields: [
      {
        id: "name",
        name: "name",
        label: "Name",
        validated: true,
        type: "text",
        errormsg: "Name is required",
      },
      {
        id: "description",
        name: "description",
        label: "Description",
        validated: true,
        type: "text",
        errormsg: "Description is required",
      },
      {
        id: "thumbnailUrl",
        name: "thumbnailUrl",
        label: "Thumbnail Url",
        validated: true,
        type: "url",
        errormsg: "Thumbnail Url is required",
      },
      {
        id: "contentUrl",
        name: "contentUrl",
        label: "Content Url",
        validated: true,
        type: "url",
        errormsg: "Content Url is required",
      },
      {
        id: "embedUrl",
        name: "embedUrl",
        label: "Embed Url",
        validated: true,
        type: "url",
        errormsg: "Embed Url is required",
      },
      {
        id: "uploadDate",
        name: "uploadDate",
        label: "Upload Date",
        validated: true,
        type: "date",
        errormsg: "Upload Date is required",
      },
    ],
  },
];

export const initialValues = {
  oneImage: undefined,
  businessImages: [],
  businessImages1: "",
  businessImages2: "",
  businessType: "",
  businessName: "",
  priceRange: "",
  streetAddress: "",
  addressLocality: "",
  region: "",
  postalCode: "",
  telephone: "",
  workingDays: [
    {
      DaysOfWeek: {},
      opens: "",
      closes: "",
    },
  ],
  name: "Test",
  author: "Test dfdfdf",
  description: "Test",
  prepTime: {
    day: "1",
    hours: "1",
    minutes: "1",
  },
  cookTime: {
    day: "0",
    hours: "1",
    minutes: "1",
  },
  totalTime: {
    day: "1",
    hours: "1",
    minutes: "1",
  },
  keywords: "1",
  recipeYield: "1",
  recipeCategory: "1",
  recipeCuisine: "1",
  nutrition: "1",
  recipeIngredient: [
    {
      name: "1",
    },
  ],
  recipeInstructions: [
    {
      name: "test",
      text: "Test",
      image: "Test",
      url: "htts://www.test.com",
    },
  ],
  ratingValue: "Test",
  ratingCount: "Test",
  video: {
    name: "Test",
    description: "Test",
    thumbnailUrl: "htts://www.test.com",
    contentUrl: "htts://www.test.com",
    embedUrl: "htts://www.test.com",
    uploadDate: "2023-06-01",
  },
};

function FormPreview() {
  const handleSubmit = (values) => {
    console.log("form values s", values);
  };

  return (
    <Page
      primaryAction={
        <PremiumButton title="Unlock Currency Rule with our Premium Plan" subTitle="Unlock advanced features!">
          <Button variant="primary" size="medium">
            Add Currency
          </Button>
        </PremiumButton>
      }
    >
      <DismissibleBanner
        bannerName="formPreviewBanner"
        bannerText={
          <Text variant="bodySm" as="p" tone="critical">
            If both of these are disable then user can not see the dropdown.
          </Text>
        }
        title="abc"
        tone="critical"
      />
      <br />
      <Layout>
        <Layout.Section>
          <Card>
            <CommonForm
              onSubmit={handleSubmit}
              initialValues={initialValues}
              formFields={formFields}
              title="Test From"
            />
          </Card>
        </Layout.Section>
      </Layout>
    </Page>
  );
}

export default FormPreview;
