/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Head over to utils/shopify.js to create your webhooks
 *  and write your webhook functions in server/webhooks.
 * If you don't know the format, use the `createwebhook` snippet when using VSCode
 *  to get a boilerplate function for webhooks.
 * To update this file, run `npm run update:config` or `bun run update:config`
 */
import { DeliveryMethod } from "@shopify/shopify-api";
import shopify from "../../utils/shopify.js";
import { appUninstallHandler, shopUpdateHandler } from "./webhook.js";

const webhookHandler = async (req, res) => {
  const topic = req.headers["x-shopify-topic"] || "";
  const shop = req.headers["x-shopify-shop-domain"] || "";
  const apiVersion = req.headers["x-shopify-api-version"] || "";
  const webhookId = req.headers["x-shopify-webhook-id"] || "";

  try {
    const validateWebhook = await shopify.webhooks.validate({
      rawBody: req.body,
      rawRequest: req,
      rawResponse: res,
    });

    if (validateWebhook.valid) {
    } else {
      return res.status(400).send({ error: true });
    }

    //SWITCHCASE
    switch (validateWebhook.topic) {
      case "APP_UNINSTALLED":
        await appUninstallHandler(topic, shop, req.body);
        break;
      case "SHOP_UPDATE":
        await shopUpdateHandler(topic, shop, req.body);
        break;
      default:
        throw new Error(`Can't find a handler for ${validateWebhook.topic}`);
    }
    //SWITCHCASE END
    // console.log(`--> Processed ${topic} webhook for ${shop}`);
    return res.status(200).send({ message: "ok" });
  } catch (e) {
    console.error(`---> Error while registering ${topic} webhook for ${shop}`, e);
    if (!res.headersSent) {
      return res.status(500).send(e.message);
    }
  }
};

export const webhookRegistrar = async () => {
  await shopify.webhooks.addHandlers({
    APP_UNINSTALLED: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks/app_uninstalled",
      callback: appUninstallHandler,
    },
    SHOP_UPDATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks/shop_update",
      callback: shopUpdateHandler,
    },
  });
};

export default webhookHandler;
