import mongoose from "mongoose";

const Schema = mongoose.Schema;

const annoucementSchema = new Schema({
  shopUrl: { type: String, required: true },

  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Users",
  },
  animationId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Animation",
  },
  slideType: { type: String },
  shipping: {
    shippingBarMessage: {
      messageStart: { type: String },
      shippingPrice: { type: Number },
      messageEnd: { type: String },
    },
    progressMessage: {
      progressStart: { type: String },
      shippingPrice: { type: Number },
      progressEnd: { type: String },
    },
    goalMessage: { type: String },
    currencyPosition: { type: String },
    moneyClass: { type: Boolean },
    currencySymbol: { type: String },
    shippingColor: { type: String },
    shippingSize: { type: Number },
    shippingWeight: { type: String },
    mobileshippingWeight: { type: String },
    mobileshippingColor: { type: String },
    mobileshippingSize: { type: Number },
  },
  // selectedTypeItem: { type: Array },
  timerCustomOpt: { type: Boolean },
  timerSeparator: { type: Boolean },
  timerTextOption: {
    hourText: { type: String },
    minuteText: { type: String },
    dayText: { type: String },
    secondText: { type: String },
  },
  url: { include: [{ type: String }], exclude: [{ type: String }] },
  index: { type: Number },
  timerName: { type: String },
  slideHeight: { type: String },
  openEnabled: { type: Boolean },
  timerEnabled: { type: Boolean },
  slideEnabled: { type: Boolean, default: true },
  timer: { type: Date },
  timerColor: { type: String },
  timerTextColor: { type: String },
  slideMessage: { type: String },
  fontStyle: { type: String },
  type: { type: Array },
  fontSize: { type: Number },
  fontColor: { type: String },
  fontFamily: { type: String },
  fontFamilyEnabled: { type: Boolean },
  backgroundColor: { type: String },
  btnName: { type: String },
  btnColor: { type: String },
  btnFontSize: { type: String },
  textColor: { type: String },
  targetLink: { type: String },
  btnLink: { type: String },
  btnCopiedText: { type: String },
  fontWeight: { type: String },
  btnTextColor: { type: String },
  viewMode: { type: String },
  textToolEditor: { type: Boolean },
  textEditor: { type: String },
  textHoverColor: { type: String },
  timerType: { type: String },
  timerTextSize: { type: Number },
  countryData: [{ type: String }],
  btnRadius: { type: Number },
  // selectedCountryItem: [{ type: Object }],
  displayTime: {
    show: { type: Boolean },
    startTime: { type: Date },
    endTime: { type: Date },
  },
  repeatedTimer: {
    repeatTimerCreateDate: { type: Date },
    repeatedHours: { type: Number },
    repeatedTimeEnd: { type: Date },
  },
  removeTimer: { type: Boolean },
  btnHoverColor: { type: String },
  utmSource: { type: Object },
  excludeUtm: { type: String },
  showVisitors: { type: Array },
  customUrl: { type: String },
  btnTextHoverColor: { type: String },
  callToAction: { type: Boolean },
  callToActionOption: {
    buttonType: { type: String },
  },
  advanceOption: { type: Boolean },
  isMobileStyle: { type: Boolean },
  mobilefontColor: { type: String },
  mobilefontStyle: { type: String },
  mobilefontSize: { type: Number },
  mobilefontWeight: { type: String },
  mobilebackgroundColor: { type: String },
  mobiletextColor: { type: String },
  mobiletextHoverColor: { type: String },
  mobilebtnColor: { type: String },
  mobilebtnTextColor: { type: String },
  mobilebtnFontSize: { type: String },
  mobilebtnRadius: { type: Number },
  mobilebtnHoverColor: { type: String },
  mobilebtnTextHoverColor: { type: String },
  mobiletimerColor: { type: String },
  mobiletimerTextColor: { type: String },
  mobiletimerTextSize: { type: Number },
  created: { type: Date, default: Date.now },
  updated: { type: Date, default: Date.now },
  htmlDesign: { type: Array },
  htmlLayout: { type: Object },
  campaignTitle: { type: String },
  // animation depedency
  slidePosition: { type: String },
  animationType: { type: String },
  customPosition: { type: String },
  slidePadding: { type: Number, default: 5 },
  textAnimationTime: { type: Number, default: 15 },
  textAnimationBg: { type: String },
  textAnimationPadding: { type: Number, default: 15 },
  textAnimationWidth: { type: Number },
  textAnimationSliderWidth: { type: Number },
  animationTime: { type: Number, default: 1500 },
  autoplayTime: { type: Number, default: 5000 },
  rmvBtnColor: { type: String },
  rmvBtnEnabled: { type: Boolean, default: false },
  clicks: { type: Number },
  submits: { type: Number },
  views: { type: Number },
  utmCode: { type: Boolean, default: false },
});
const index = { shopUrl: 1 };
annoucementSchema.index(index);
const annoucement = mongoose.model("Annoucement", annoucementSchema);
export default annoucement;
