import modifyData from "../Language/cs.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Povoleno",
    Disabled: "Zakázáno",
    "Embed is currently disabled": "Vkládání je momentálně zakázáno",
    "Enable App": "Povolit aplikaci",
    "1. Click on Enable App.": "1. Klikněte na Povolit aplikaci.",
    "Well done!! you have successfully enable our app.": "Výborně!! úspěšně jste povolili naši aplikaci.",
    "2. Enable": "2. Povolit",
    "App Embed as shown in image and save setting.":
      "App Vložit, jak je znázorněno na obrázku a uložit nastavení.",
    "Multi Announcement Bar": "Vícenásobná oznamovací lišta",
    "Click on the Enable Now button to enable it.": "Klepnutím na tlačítko Povolit nyní jej povolíte.",
    "Enable Announcement Bar to get started": "Chcete-li začít, povolte panel oznámení",
    "Enable Now": "Povolit nyní",
    "Sync Status": "Stav synchronizace",
    Done: "Hotovo",
    No: "Ne",
    Found: "Nalezeno",
    Add: "Přidat",
    Search: "Vyhledávání",
    Showing: "Zobrazení",
    of: "z",
    "results, at most": "maximálně výsledky",
    "per page": "na stránku",
    "Oops! Something went wrong.": "Jejda! Něco se pokazilo.",
    "Let's try that again, please refresh the page.": "Zkusme to znovu, obnovte stránku.",
    "If you're still stuck, contact us by chat support or":
      "Pokud jste stále uvízli, kontaktujte nás prostřednictvím chatové podpory nebo",
    "support@webrexstudio.com": "podpora@webrexstudio.com",
    "so we can help!": "takže můžeme pomoci!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Vyberte libovolné 3 funkce, které chcete nastavit na vysokou prioritu nebo které vás nejvíce zajímají",
    "Add ": "Přidat ",
    "These is premium feature": "Toto je prémiová funkce",
    "Go to pricing": "Přejděte na ceník",
    Save: "Uložit",
    Minimum: "Minimální",
    Maximum: "Maximum",
    "images are required": "obrázky jsou povinné",
    and: "a",
    "images are allowed": "obrázky jsou povoleny",
    Disconnect: "Odpojit",
    "Sign In with Google": "Přihlaste se pomocí Google",
    "Oops! Something went wrong. Admin token is malformed":
      "Jejda! Něco se pokazilo. Administrátorský token má chybný formát",
    "If you're still stuck, contact": "Pokud stále uvíznete, kontaktujte",
    Premium: "Pojistné",
    Unlock: "Odemknout",
    "Unlock advanced features!": "Odemkněte pokročilé funkce!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Všechna práva vyhrazena.",
    "Privacy Policy": "Zásady ochrany osobních údajů",
    "Terms of Service": "Podmínky služby",
    "Go to Shopify App": "Přejděte do aplikace Shopify",
    "Review Us": "Zkontrolujte nás",
    Cancel: "zrušení",
    "Review Popup Show": "Recenze Popup Show",
    "click on review us": "klikněte na recenzi nás",
    "Note: Feel free to leave a star rating without writing a review!":
      "Poznámka: Neváhejte zanechat hodnocení hvězdičkami, aniž byste napsali recenzi!",
    Help: "Pomoc",
    "Help Button Click": "Klepněte na tlačítko Nápověda",
    Confirm: "Potvrdit",
    On: "Na",
    Off: "Vypnuto",
    Price: "Cena",
    Settings: "Nastavení",
    Animation: "Animace",
    "My Profile": "Můj profil",
    "My Subscription": "Moje předplatné",
    "Store Name": "Jméno obchodu",
    "Store URL": "Adresa URL obchodu",
    "Email ID": "ID e-mailu",
    "Phone Number": "Telefonní číslo",
    Country: "Země",
    Currency: "Měna",
    "Subscription Name": "Název předplatného",
    "Select language": "Zvolte jazyk",
    "Announcement setting": "Nastavení oznámení",
    "Animation setting": "Nastavení animace",
    Selector: "Volič",
    "Save Setting": "Uložit nastavení",
    "My Announcements": "Moje oznámení",
    "Add bar": "Přidat lištu",
    Number: "Číslo",
    Title: "Titul",
    "Create At": "Vytvořit v",
    "Slide Activation": "Aktivace snímku",
    Status: "Postavení",
    Actions: "Akce",
    "Save order": "Uložit objednávku",
    "Reorder Slides": "Změnit pořadí snímků",
    position: "pozice",
    Top: "Horní",
    "Sticky Top": "Lepkavý top",
    "Bottom Fix": "Oprava dna",
    "Custom Position": "Vlastní pozice",
    "Custom Position *Add Class or id of Selected Element.":
      "Vlastní pozice *Přidat třídu nebo id vybraného prvku.",
    "Bar Padding (px)": "Pruhové odsazení (px)",
    "Add Remove Button": "Přidat tlačítko Odebrat",
    "Choose icon color": "Vyberte barvu ikony",
    "Custom css": "Vlastní css",
    fadeIn: "fadeIn",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "fadeInUp",
    bounceInDown: "bounceInDown",
    bounceInLeft: "bounceInLeft",
    bounceInUp: "bounceInUp",
    zoomIn: "přiblížit",
    zoomInDown: "zoomInDown",
    zoomInLeft: "zoomInLeft",
    slideInLeft: "slideInLeft",
    slideInUp: "slideInUp",
    slideInDown: "slideInDown",
    lightSpeedIn: "lightSpeedIn",
    rollIn: "rollIn",
    flash: "blikat",
    shake: "otřást",
    flip: "převrátit",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "odeznít",
    fadeOutDown: "FadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "FadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fadeOutUp",
    bounceOutDown: "bounceOutDown",
    bounceOutRight: "bounceOutRight",
    bounceOutUp: "bounceOutUp",
    zoomOut: "oddálit",
    zoomOutDown: "zoomOutDown",
    zoomOutRight: "zoomOutRight",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "vysunout dolů",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "zavést",
    flipInY: "flipInY",
    "Text Animation": "Animace textu",
    "Animation In": "Animace In",
    "Animation Out": "Animace ven",
    "Auto play time (time in MS)": "Čas automatického přehrávání (čas v MS)",
    "Animation time (time in MS)": "Čas animace (čas v MS)",
    "Auto play time (time in Second)": "Čas automatického přehrávání (čas v sekundách)",
    "Background Color": "Barva pozadí",
    "Space between slide(px)": "Mezera mezi snímky (px)",
    visible: "viditelné",
    invisible: "neviditelný",
    "Promotional & Countdown Bar": "Propagační a odpočítávací lišta",
    "Free Shipping Bar": "Bar doprava zdarma",
    "Add Slide": "Přidat snímek",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Pro ZDARMA plán je viditelný pouze 1 snímek. Chcete-li aktivovat všechny snímky, přihlaste se k odběru prémiového tarifu.",
    Pricing: "Ceny",
    "No Animation Found": "Nebyla nalezena žádná animace",
    "No Preview, Add announcement Bar": "Žádný náhled, Přidat panel oznámení",
    "Update successfully": "Aktualizace proběhla úspěšně",
    Enable: "Umožnit",
    Disable: "Zakázat",
    successfully: "úspěšně",
    "Delete successfully": "Úspěšně smazat",
    "Copy successfully": "Úspěšně zkopírujte",
    "Reorder successfully": "Přeobjednat úspěšně",
    "Announcement Message": "Oznamovací zpráva",
    "Call to Action": "Výzva k akci",
    Timer: "Časovač",
    Style: "Styl",
    "Background Type": "Typ pozadí",
    "Mobile Style": "Mobilní styl",
    "Schedule Display": "Zobrazení plánu",
    Update: "Aktualizace",
    "Change Font": "Změnit písmo",
    "Font Family": "Rodina písem",
    "Font Style": "Styl fontu",
    Normal: "Normální",
    Italic: "kurzíva",
    Oblique: "Šikmý",
    Unset: "Nenastaveno",
    "Font Weight": "Tloušťka písma",
    Bold: "tučně",
    "Message Font Size": "Velikost písma zprávy",
    "Message Text color": "Barva textu zprávy",
    Type: "Typ",
    None: "Žádný",
    Button: "Knoflík",
    "Entire clickable bar": "Celá klikací lišta",
    "Add a simple link": "Přidejte jednoduchý odkaz",
    "Add coupon placement": "Přidat umístění kupónu",
    "Linked Url": "Propojená adresa URL",
    "Background Hover Color": "Barva pozadí přechodu",
    "Text Hover Color": "Barva přechodu textu",
    "Button Text": "Text tlačítka",
    "Copied Text": "Zkopírovaný text",
    "Open in the new tab": "Otevřít na nové kartě",
    URL: "URL",
    "Font Size": "Velikost písma",
    "Button Radius": "Poloměr tlačítka",
    "Button color": "Barva tlačítka",
    "Button Text color": "Tlačítko Barva textu",
    "Button Hover Color": "Barva tlačítka přechodu",
    "button Text HoverColor": "tlačítko Text HoverColor",
    "Timer Setting": "Nastavení časovače",
    "Timer Type": "Typ časovače",
    Date: "datum",
    "Select Reapt Time": "Vyberte možnost Reapt Time",
    "repeated Hours": "opakované hodiny",
    "Normal Timer": "Normální časovač",
    "Auto repeat timer": "Časovač automatického opakování",
    Minute: "Minuta",
    Hour: "Hodina",
    Day: "Den",
    "Remove Timer When Time End": "Odebrat časovač při konci času",
    "Timer Separator": "Oddělovač časovače",
    "Countdown Timer color": "Barva odpočítávacího časovače",
    "Timer Text Size": "Velikost textu časovače",
    "Timer Text Setting": "Nastavení textu časovače",
    "Day Text": "Den Text",
    "Hour Text": "Hodinový text",
    "Minute Text": "Text minuty",
    "Second Text": "Druhý text",
    "Background Image": "Obrázek na pozadí",
    "Gradient Background": "Přechod pozadí",
    "Style & Color For Mobile": "Styl & Barva Pro Mobil",
    "Timer Background": "Pozadí časovače",
    "Timer Text Color": "Barva textu časovače",
    "Button Color": "Barva tlačítka",
    "Button Text Color": "Barva textu tlačítka",
    "Button Text Hover Color": "Barva textu tlačítka",
    "Button Text Size": "Velikost textu tlačítka",
    "Always Display": "Vždy zobrazit",
    "Only Display Within The Following Period Of Time": "Zobrazit pouze v následujícím časovém období",
    "Start Time": "Doba spuštění",
    "End Time": "Čas ukončení",
    "Advance Setting": "Pokročilé nastavení",
    "Country Filter": "Filtr země",
    Visibility: "Viditelnost",
    "Desktop and Mobile": "Desktop a Mobile",
    "Only Desktop": "Pouze Desktop",
    "Only Mobile": "Pouze mobilní",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "CÍLENÍ NA ZDROJ UŽIVATELŮ (Návštěvníci přicházející z odkazu, který obsahuje následující kód UTM, např. Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Vyberte možnost Stránka",
    Include: "Zahrnout",
    Exclude: "Vyloučit",
    "Currency Configuration": "Konfigurace měny",
    Message: "Zpráva",
    "Currency Symbol": "Symbol měny",
    "Currency Position": "Měnová pozice",
    Before: "Před",
    After: "Po",
    "money Class": "peněžní třída",
    "Initial Message": "Počáteční zpráva",
    "Shipping Goal": "Cíl přepravy",
    "Progress Message": "Zpráva o pokroku",
    "Progress goal": "Cíl postupu",
    "Goal Message": "Zpráva o cíli",
    "Shipping Price Color": "Cena dopravy Barva",
    "Shipping Price Size": "Cena dopravy Velikost",
    "Shipping Font Weight": "Hmotnost písma zásilky",
    "* When user first time visit": "* Při první návštěvě uživatele",
    "* When user add item to the cart e.g": "* Když uživatel přidá položku do košíku, např.:",
    "* When cart value is greater than": "* Když je hodnota košíku vyšší než",
    "Show On Selected Countries": "Zobrazit ve vybraných zemích",
    "Show On Selected Pages": "Zobrazit na vybraných stránkách",
    All: "Všechno",
    Home: "Domov",
    Cart: "Vozík",
    Collection: "Sbírka",
    Product: "Produkt",
    Custom: "Zvyk",
    Page: "Strana",
    Blog: "Blog",
    "Url is required": "Adresa URL je povinná",
    "Day Text is required": "Denní text je povinný",
    "Hour Text is required": "Hodinový text je povinný",
    "Minute Text is required": "Je vyžadován text minuty",
    "Second Text is required": "Je vyžadován druhý text",
    "Start Time is required": "Je vyžadován čas zahájení",
    "End Time is required": "Čas ukončení je povinný",
    "Created successfully": "Úspěšně vytvořeno",
    "United States": "Spojené státy",
    Canada: "Kanada",
    Australia: "Austrálie",
    "New Zealand": "Nový Zéland",
    Germany: "Německo",
    India: "Indie",
    Afghanistan: "Afghánistán",
    "land Islands": "suchozemské ostrovy",
    Albania: "Albánie",
    Algeria: "Alžírsko",
    "American Samoa": "Americká Samoa",
    AndorrA: "AndorrA",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarktida",
    "Antigua and Barbuda": "Antigua a Barbuda",
    Argentina: "Argentina",
    Armenia: "Arménie",
    Aruba: "Aruba",
    Austria: "Rakousko",
    Azerbaijan: "Ázerbajdžán",
    Bahamas: "Bahamy",
    Bahrain: "Bahrajn",
    Bangladesh: "Bangladéš",
    Barbados: "Barbados",
    Belarus: "Bělorusko",
    Belgium: "Belgie",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermudy",
    Bhutan: "Bhútán",
    Bolivia: "Bolívie",
    "Bosnia and Herzegovina": "Bosna a Hercegovina",
    Botswana: "Botswana",
    "Bouvet Island": "Bouvetův ostrov",
    Brazil: "Brazílie",
    "British Indian Ocean Territory": "Britské indickooceánské území",
    "Brunei Darussalam": "Brunej Darussalam",
    Bulgaria: "Bulharsko",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Kambodža",
    Cameroon: "Kamerun",
    "Cape Verde": "Kapverdy",
    "Cayman Islands": "Kajmanské ostrovy",
    "Central African Republic": "Středoafrická republika",
    Chad: "Čad",
    Chile: "Chile",
    China: "Čína",
    "Christmas Island": "Vánoční ostrov",
    "Cocos (Keeling) Islands": "Kokosové (Keelingovy) ostrovy",
    Colombia: "Kolumbie",
    Comoros: "Komory",
    Congo: "Kongo",
    "Congo, The Democratic Republic of the": "Kongo, Demokratická republika",
    "Cook Islands": "Cookovy ostrovy",
    "Costa Rica": "Kostarika",
    "Cote D'Ivoire": "Pobřeží slonoviny",
    Croatia: "Chorvatsko",
    Cuba: "Kuba",
    Cyprus: "Kypr",
    "Czech Republic": "Česká republika",
    Denmark: "Dánsko",
    Djibouti: "Džibutsko",
    Dominica: "Dominika",
    "Dominican Republic": "Dominikánská republika",
    Ecuador: "Ekvádor",
    Egypt: "Egypt",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Rovníková Guinea",
    Eritrea: "Eritrea",
    Estonia: "Estonsko",
    Ethiopia: "Etiopie",
    "Falkland Islands (Malvinas)": "Falklandské ostrovy (Malvíny)",
    "Faroe Islands": "Faerské ostrovy",
    Fiji: "Fidži",
    Finland: "Finsko",
    France: "Francie",
    "French Guiana": "Francouzská Guyana",
    "French Polynesia": "Francouzská Polynésie",
    "French Southern Territories": "Francouzská jižní území",
    Gabon: "Gabon",
    Gambia: "Gambie",
    Georgia: "Gruzie",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Řecko",
    Greenland: "Grónsko",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Heardův ostrov a Mcdonaldovy ostrovy",
    "Holy See (Vatican City State)": "Svatý stolec (Vatikánský městský stát)",
    Honduras: "Honduras",
    "Hong Kong": "Hongkong",
    Hungary: "Maďarsko",
    Iceland: "Island",
    Indonesia: "Indonésie",
    "Iran, Islamic Republic Of": "Írán, Islámská republika",
    Iraq: "Irák",
    Ireland: "Irsko",
    "Isle of Man": "Ostrov Man",
    Israel: "Izrael",
    Italy: "Itálie",
    Jamaica: "Jamaica",
    Japan: "Japonsko",
    Jersey: "Trikot",
    Jordan: "Jordán",
    Kazakhstan: "Kazachstán",
    Kenya: "Keňa",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Korea, Lidově demokratická republika",
    "Korea, Republic of": "Korejská republika",
    Kuwait: "Kuvajt",
    Kyrgyzstan: "Kyrgyzstán",
    "Lao People'S Democratic Republic": "Laoská lidově demokratická republika",
    Latvia: "Lotyšsko",
    Lebanon: "Libanon",
    Lesotho: "Lesotho",
    Liberia: "Libérie",
    "Libyan Arab Jamahiriya": "Libyjská arabská džamahiríja",
    Liechtenstein: "Lichtenštejnsko",
    Lithuania: "Litva",
    Luxembourg: "Lucembursko",
    Macao: "Macao",
    "Macedonia, The Former Yugoslav Republic of": "Makedonie, Bývalá jugoslávská republika",
    Madagascar: "Madagaskar",
    Malawi: "Malawi",
    Malaysia: "Malajsie",
    Maldives: "Maledivy",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Marshallovy ostrovy",
    Martinique: "Martinik",
    Mauritania: "Mauritánie",
    Mauritius: "Mauricius",
    Mayotte: "Mayotte",
    Mexico: "Mexiko",
    "Micronesia, Federated States of": "Mikronésie, Federativní státy",
    "Moldova, Republic of": "Moldavsko, republika",
    Monaco: "Monako",
    Mongolia: "Mongolsko",
    Montenegro: "Černá Hora",
    Montserrat: "Montserrat",
    Morocco: "Maroko",
    Mozambique: "Mosambik",
    Myanmar: "Myanmar",
    Namibia: "Namibie",
    Nauru: "Nauru",
    Nepal: "Nepál",
    Netherlands: "Holandsko",
    "Netherlands Antilles": "Nizozemské Antily",
    "New Caledonia": "Nová Kaledonie",
    Nicaragua: "Nikaragua",
    Niger: "Niger",
    Nigeria: "Nigérie",
    Niue: "Niue",
    "Norfolk Island": "Ostrov Norfolk",
    "Northern Mariana Islands": "Severní Mariany",
    Norway: "Norsko",
    Oman: "Omán",
    Pakistan: "Pákistán",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Palestinské území, okupované",
    Panama: "Panama",
    "Papua New Guinea": "Papua-Nová Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Filipíny",
    Pitcairn: "Pitcairn",
    Poland: "Polsko",
    Portugal: "Portugalsko",
    "Puerto Rico": "Portoriko",
    Qatar: "Katar",
    Reunion: "Shledání",
    Romania: "Rumunsko",
    "Russian Federation": "Ruská Federace",
    RWANDA: "RWANDA",
    "Saint Helena": "Svatá Helena",
    "Saint Kitts and Nevis": "Svatý Kryštof a Nevis",
    "Saint Lucia": "Svatá Lucie",
    "Saint Pierre and Miquelon": "Saint Pierre a Miquelon",
    "Saint Vincent and the Grenadines": "Svatý Vincent a Grenadiny",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Svatý Tomáš a Princův ostrov",
    "Saudi Arabia": "Saudská arábie",
    Senegal: "Senegal",
    Serbia: "Srbsko",
    Seychelles: "Seychely",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapur",
    Slovakia: "Slovensko",
    Slovenia: "Slovinsko",
    "Solomon Islands": "Solomonovy ostrovy",
    Somalia: "Somálsko",
    "South Africa": "Jižní Afrika",
    "South Georgia and the South Sandwich Islands": "Jižní Georgie a Jižní Sandwichovy ostrovy",
    Spain: "Španělsko",
    "Sri Lanka": "Srí Lanka",
    Sudan: "Súdán",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard a Jan Mayen",
    Swaziland: "Svazijsko",
    Sweden: "Švédsko",
    Switzerland: "Švýcarsko",
    "Syrian Arab Republic": "Syrská Arabská republika",
    "Taiwan, Province of China": "Taiwan, provincie Číny",
    Tajikistan: "Tádžikistán",
    "Tanzania, United Republic of": "Tanzanie, Sjednocená republika",
    Thailand: "Thajsko",
    "Timor-Leste": "Východní Timor",
    Togo: "Jít",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd a Tobago",
    Tunisia: "Tunisko",
    Turkey: "krocan",
    Turkmenistan: "Turkmenistán",
    "Turks and Caicos Islands": "ostrovy Turks a Cacois",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukrajina",
    "United Arab Emirates": "Spojené arabské emiráty",
    "United Kingdom": "Spojené království",
    "United States Minor Outlying Islands": "Menší odlehlé ostrovy Spojených států amerických",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistán",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands, British": "Britské Panenské ostrovy",
    "Virgin Islands, U.S.": "Panenské ostrovy, USA",
    "Wallis and Futuna": "Wallis a Futuna",
    "Western Sahara": "západní Sahara",
    Yemen: "Jemen",
    Zambia: "Zambie",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Odemkněte všechna schémata s naším prémiovým plánem",
    "Billed Monthly": "Účtováno měsíčně",
    "Billed Annually": "Účtováno ročně",
    "Save 30%": "Ušetřete 30 %",
    Premium100Title:
      "Jako první uživatel vás ujišťujeme, že všechny naše prémiové funkce si budete užívat bez jakýchkoli nákladů. Není třeba se starat o stránku s cenami, protože můžete volně přistupovat ke všem našim prémiovým funkcím bez jakýchkoli poplatků. Neodinstalujte prosím naši aplikaci, abyste mohli nadále využívat naši službu.",
    Premium100ReviewLine:
      " Pokud se vám naše aplikace líbí, zanechte nám recenzi. To nám pomůže získat motivaci k vývoji nových funkcí.",
    "Check Our Current Pricing": "Podívejte se na naši aktuální cenu",
    "Leave Review": "Zanechat recenzi",
    "We're sorry to see you go!": "Je nám líto, že odcházíte!",
    "Cancel Plan": "Zrušit plán",
    "Sync Plan": "Plán synchronizace",
    "Disccount applied": "Uplatněna sleva",
    Apply: "Aplikovat",
    "Your code(s)": "Váš kód(y)",
    "and discount have been applied successfully": "a sleva byla úspěšně uplatněna",
    "Your entered promocode is not correct, Enter a valid code":
      "Váš zadaný propagační kód není správný, zadejte platný kód",
    "days trial left": "zbývá zkušební dny",
    Upgrade: "Vylepšit",
    "days free trial, No Credit card required":
      "dní bezplatná zkušební verze, není vyžadována žádná kreditní karta",
    Month: "Měsíc",
    Year: "Rok",
    Unlimited: "Neomezený",
    "Enter Promocode": "Zadejte propagační kód",
    "Please Choose a Cancellation Reason": "Vyberte prosím důvod zrušení",
    "No Longer Needed?": "Již není třeba?",
    "Didn't Meet Expectations": "Nesplnilo očekávání",
    "Cost Concerns": "Obavy z nákladů",
    "Technical Issues": "Technické problémy",
    "Found an Alternative": "Našel Alternativu",
    Complexity: "Složitost",
    "Lack of Features": "Nedostatek funkcí",
    "Poor Customer Support": "Špatná zákaznická podpora",
    "Business Closure or Change": "Uzavření nebo změna podnikání",
    "Temporary Pause": "Dočasná pauza",
    "Performance Issues": "Problémy s výkonem",
    Other: "jiný",
    "Mention Your Specific Reason Here": "Zde uveďte svůj konkrétní důvod",
    Start: "Start",
    "Day Free Trial": "Denní bezplatná zkušební verze",
    "Please Select One Option": "Vyberte jednu možnost",
    "Plan cancelled successfully": "Plán byl úspěšně zrušen",
    "7 days free trial, No Credit card required":
      "7denní bezplatná zkušební verze, není vyžadována žádná kreditní karta",
    "Your remaining trial days are": "Zbývající zkušební dny jsou",
    "You have used": "Použili jste",
    "days.": "dní.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Nezbývají žádné zkušební dny. Již jste využili 7denní bezplatnou zkušební verzi.",
    "Upgrade your plan now": "Upgradujte svůj plán hned teď",
    "Unlimited Slides": "Neomezené snímky",
    "20+ Animation In & Out": "20+ animací dovnitř a ven",
    "Live Chat Support": "Podpora živého chatu",
    "Priority, 24*7 Urgent setup and support": "Priorita, 24*7 Naléhavé nastavení a podpora",
    "Rich Text Editor": "Rich Text Editor",
    "One Slide(banner)": "Jeden snímek (banner)",
    "Repeated Countdown timer": "Opakovaný časovač odpočítávání",
    "Fully Customisable": "Plně přizpůsobitelné",
    "Background-image": "Obrázek na pozadí",
    "Custom Css": "Vlastní Css",
    "Enable Our App": "Povolte naši aplikaci",
    "Book Onboarding Demo": "Kniha Onboarding Demo",
    Next: "Další",
    Finish: "Dokončit",
    Prev: "Předchozí",
    "App is not enable please click on the Enable App button to enable it.":
      "Aplikace není povolena, kliknutím na tlačítko Povolit aplikaci ji povolte.",
    "This field is required": "Toto pole je povinné",
    disableButtonTooltip: "Nemůžete upgradovat měsíční plán, protože máte roční plán!",
    "Choose plan": "Vyberte plán",
    "Purchase Plan": "Plán nákupu",
    Continue: "Pokračovat",
    "Image Optimization": "Optimalizace obrazu",
    "AI Metatags": "Metatagy AI",
    "Grand Total": "Celkový součet",
    "Metatags Edit": "Upravit metatagy",
    Products: "produkty",
    "Upgrade plan": "Plán upgradu",
    "Your product count is": "Počet vašich produktů je",
    "so your suitable plan is": "takže váš vhodný plán je",
    "Enjoy a": "Užijte si a",
    "lifetime discount": "doživotní sleva",
    discountBanner:
      " Využijte doživotní slevu, zajistěte si trvalé úspory a vylepšete své zkušenosti s našimi prémiovými produkty a službami.",
    "Images for Optimization every year after trial period end":
      "Obrázky pro optimalizaci každý rok po skončení zkušebního období",
    "AI Meta Tags Credit for every year after trial period end":
      "Kredit AI Meta Tags za každý rok po skončení zkušebního období",
    "Images for Optimization every month after trial period end":
      "Obrázky pro optimalizaci každý měsíc po skončení zkušebního období",
    "AI Meta Tags Credit for every Month after trial period end":
      "Kredit AI Meta Tags za každý měsíc po skončení zkušebního období",
    "Optimize your google page speed": "Optimalizujte rychlost své stránky Google",
    "50 Product Meta tags Optimize, Image alt": "50 Meta tagy produktu Optimalizovat, Obrázek alt",
    "Product Meta tags Optimize, Image alt": "Meta tagy produktu Optimalizovat, Obrázek alt",
    "AI ImageAltText Credit for every year after trial period end":
      "Kredit AI ImageAltText za každý rok po skončení zkušebního období",
    "25 AI ImageAltText Credit": "25 kreditů AI ImageAltText",
    "AI ImageAltText Credit for every Month after trial period end":
      "Kredit AI ImageAltText za každý měsíc po skončení zkušebního období",
    "Contact Bar": "Kontaktní lišta",
    "Add To Cart Bar": "Přidat do košíku Bar",
    "Multiple Position": "Více pozic",
    lowMsgStart: "Tato nabídka je speciálně navržena pro vás, protože jste právě spustili svůj obchod Shopify",
    lowMsgMiddle: "Náš",
    lowMsgEnd: "sleva je náš způsob, jak vás podpořit v těchto náročných, ale vzrušujících časech.",
    mediumMsgStart: "Tato nabídka je speciálně navržena pro vás, protože jste spustili svůj obchod Shopify",
    mediumMsgMiddle: "Náš",
    mediumMsgEnd: "sleva je náš způsob, jak vás podpořit v těchto náročných, ale vzrušujících časech.",
    importantMsgStart: "Tato nabídka je speciálně navržena pro vás, protože jste spustili svůj obchod Shopify",
    importantMsgMiddle: "Náš",
    importantMsgEnd: "sleva je náš způsob, jak vás podpořit v těchto náročných, ale vzrušujících časech.",
    veryImportantMsgStart: "Tato nabídka je speciálně navržena pro vás, protože jste otevřeli svůj obchod Shopify",
    veryImportantMsgMiddle: "Jste pro nás velmi důležitý a vyspělý obchodník. Náš",
    veryImportantMsgEnd: "sleva je ukázat, jak moc pro nás znamenáte.",
    generalMsg:
      "Naše aplikace Shopify je přizpůsobena potřebám zavedených firem, jako je ta vaše. Je navržen tak, aby bezproblémově zvládal velké objemy a složité operace. ",
    lowTitleStart: "Speciální podpora pro nové podnikatele:",
    lowTitleEnd: "Sleva, jak jste právě začali",
    mediumTitleStart: "Speciální podpora pro podnikatele:",
    mediumTitleEnd: "Sleva, jak jste začali",
    importantTitleStart: "Speciální podpora pro podnikatele:",
    importantTitleEnd: "Sleva, jak jste začali",
    veryImportantTitleStart: "Gratuluji k bytí",
    veryImportantTitleEnd: "v Shopify",
    month: "Měsíc",
    "year and": "rok a",
    ago: "před",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Přidejte kredit AI (1 kredit AI / 10¢) (10 kreditů AI / 1 $)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Přidat obrázek altText Kredit AI (1 Kredit AI / 4¢) (25 Kredit AI / 1 $)",
    "Monthly AI AltText Credit": "Měsíční kredit AI AltText",
    "Yearly AI AltText Credit": "Roční kredit AI AltText",
    "Purchase AI AltText Credit": "Kupte si kredit AI AltText",
    "ImageAltText Credit": "Kredit ImageAltText",
    "Your credits are finished; please upgrade your plan.": "Vaše kredity jsou hotové; upgradujte svůj plán.",
    "Your credits are finished; you can buy more credits from here.":
      "Vaše kredity jsou hotové; zde si můžete koupit další kredity.",
    "This offer expire in": "Tato nabídka vyprší v",
    "Hurry Up!": "Pospěš si!",
    Current: "Aktuální",
    "Discount applied": "Uplatněna sleva",
    "trial left": "soud odešel",
    "info banner":
      "Když kliknete na tlačítko Skenovat obrázek domovské stránky, naše aplikace naskenuje pouze obrázek domovské stránky. Chcete-li tento obrázek optimalizovat, klikněte na tlačítko Optimalizovat ručně",
    "Optimize Images": "Optimalizace obrázků",
    image: "obraz",
    images: "snímky",
    Filename: "Název souboru",
    Images: "snímky",
    Setting: "Nastavení",
    "Saved(in %)": "Uloženo (v %)",
    Action: "Akce",
    "Product Image": "Obrázek produktu",
    "product image": "obrázek produktu",
    gif: "gif",
    Homepage: "Domovská stránka",
    "Manage Announcement": "Spravovat oznámení",
    "No Announcements Found": "Nebyla nalezena žádná oznámení",
    Position: "Pozice",
    "Campaign Title": "Název kampaně",
    Visible: "Viditelné",
    Invisible: "Neviditelný",
    Views: "Pohledy",
    Clicks: "kliknutí",
    Submits: "Odešle",
    "Above Add to cart Button": "Nahoře Tlačítko Přidat do košíku",
    "Below Add to cart Button": "Níže tlačítko Přidat do košíku",
    Targeting: "Cílení",
    "Rotating Animation Setting": "Nastavení rotující animace",
    "Marquee Animation Setting": "Nastavení animace výběru",
    "Show to visitors coming form then specific website":
      "Ukázat návštěvníkům přicházející formulář a poté konkrétní web",
    "Add your website URL": "Přidejte adresu URL svého webu",
    "Banner Display Start Time": "Čas zahájení zobrazení banneru",
    "Banner Display End Time": "Čas ukončení zobrazení banneru",
    "Create Campaign": "Vytvořit kampaň",
    "Select Announcement Bar": "Vyberte Panel oznámení",
    "Please select template.": "Vyberte šablonu.",
    Previous: "Předchozí",
    "Promotion bar": "Propagační lišta",
    "Add To Cart": "Přidat do košíku",
    Embeded: "Vloženo",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Upozorněte zákazníky na nadcházející výprodeje, nabídky nebo nastavte upozornění na zásoby.",
    "Increase your order value by using or Free Shipping Bar.":
      "Zvyšte hodnotu své objednávky pomocí nebo lišty Doprava zdarma.",
    "Conveniently add items to your cart with a single click!":
      "Pohodlně přidejte položky do košíku jediným kliknutím!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Vyberte si, chcete-li se přihlásit k odběru a dostávat speciální slevy přímo do vaší schránky",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Zvýrazněte své speciální nabídky pomocí vložené lišty, která se zobrazuje před a za tlačítkem Přidat do košíku.",
    Select: "Vybrat",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Přidat kód UTM Skrýt banner (např.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Zahrnout Utm",
    "Exclude Utm": "Vyloučit Utm",
    "Campaign Design": "Návrh kampaně",
    "Background Setting": "Nastavení pozadí",
    "Target Setting": "Nastavení cíle",
    Scheduling: "Plánování",
    Rotating: "Rotující",
    Marquee: "Stan",
    "Repeat Timer Date": "Datum opakování časovače",
    "Select Repeat Time": "Vyberte Čas opakování",
    "Repeated Hours": "Opakované hodiny",
    Border: "Pohraniční",
    Bashed: "Zbitý",
    "Multi Rotating": "Vícenásobné otáčení",
    Contacts: "Kontakty",
    Email: "E-mailem",
    "First Name": "Jméno",
    "Last Name": "Příjmení",
    Phone: "Telefon",
    "You have unsaved changes": "Máte neuložené změny",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Vaše kampaň obsahuje neuložené změny. Pokud odejdete bez uložení, změny budou ztraceny.",
    "Leave widthout saving": "Nechte ukládání šířky",
    "Save Changes": "Uložit změny",
    Announcement: "Oznámení",
    Feedback: "Zpětná vazba",
    "Recipe Instructions": "Návod na recept",
    "Visit Help Center": "Navštivte centrum nápovědy",
    "Schedule Meeting": "Naplánujte schůzku",
    "Setup guide": "Průvodce nastavením",
    "Use this personalized guide to get your store up and running":
      "Pomocí tohoto personalizovaného průvodce zprovozněte svůj obchod",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Chcete-li začít přijímat akce, musíte povolit naši aplikaci. Kliknutím na tlačítko se dostanete na stránku rozšíření, poté stačí kliknout na uložit a vrátit se sem",
    "Enable our app": "Povolte naši aplikaci",
    "Learn more": "Zjistěte více",
    "Skip it": "Přeskoč to",
    steps: "kroky",
    minutes: "minut",
    "Mark as done": "označit jako hotové",
    "Mark as not done": "Označit jako nedokončené",
    "You have completed all the steps": "Dokončili jste všechny kroky",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Aktivujte a analyzujte rychlost svého webu, abyste svůj obchod umístili výše ve výsledcích vyhledávání.",
    "Google Page Speed Optimization": "Google Page Speed Optimization",
    "Activate Google Page Speed": "Aktivujte Google Page Speed",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Povolte nástroj Google Page Speed k posouzení výkonu vašeho webu a identifikaci příležitostí ke zvýšení rychlosti",
    "Enable Speed Analysis": "Povolit analýzu rychlosti",
    "Review Speed Analysis Report": "Zkontrolujte zprávu o analýze rychlosti",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Prozkoumejte podrobnou zprávu o analýze rychlosti, abyste porozuměli aktuálním metrikám rychlosti vašeho webu a určili oblasti pro zlepšení.",
    "Go to Reports": "Přejděte na Přehledy",
    Hello: "Ahoj",
    "Let's get your store ready for success": "Připravme váš obchod na úspěch",
    "Finish later": "Dokončete později",
    "Continue onboarding": "Pokračujte v registraci",
    "Check image optimization features": "Zkontrolujte funkce optimalizace obrazu",
    "Explore Optimization Features": "Prozkoumejte funkce optimalizace",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Seznamte se s řadou dostupných nástrojů pro optimalizaci obrázků. Podívejte se, jak můžete zlepšit rychlost načítání stránky a SEO optimalizací velikostí a formátů obrázků.",
    "Go to Image Optimization": "Přejděte na Optimalizace obrazu",
    "Automate Your Image Workflow": "Automatizujte svůj pracovní postup s obrázky",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Nastavte automatizaci pro bezproblémovou optimalizaci nových obrázků při jejich nahrávání a zajištění konzistentního výkonu na celém webu.",
    "Go to Automation": "Přejděte do části Automatizace",
    "Execute a Bulk Optimization": "Proveďte hromadnou optimalizaci",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Proveďte hromadnou optimalizaci pro efektivní vylepšení více obrázků najednou, což může výrazně prodloužit dobu načítání vašeho webu.",
    "Go to bulk operations": "Přejděte na hromadné operace",
    "Broken Links Management": "Správa nefunkčních odkazů",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatizujte detekci a opravu nefunkčních odkazů, abyste zlepšili uživatelskou zkušenost a hodnocení SEO.",
    "Review Detected Broken Links": "Zkontrolujte zjištěné nefunkční odkazy",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Prohlédněte si seznam nefunkčních odkazů automaticky identifikovaných naším systémem, abyste pochopili jejich dopad na navigaci na vašem webu.",
    "View Broken Links": "Zobrazit nefunkční odkazy",
    "Address Broken Links": "Adresa nefunkční odkazy",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Využijte naše nástroje k rychlé opravě nebo přesměrování nefunkčních odkazů, zlepšení integrity vašich stránek a spokojenosti uživatelů.",
    "Resolve Broken Links": "Vyřešte nefunkční odkazy",
    "Automate for Efficiency": "Automatizace pro efektivitu",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Nastavte si automatickou opravu, abyste si udrželi náskok před všemi budoucími nefunkčními odkazy a zajistili tak nepřetržitý stav webu.",
    "Enable Automation": "Povolit automatizaci",
    "Meta Tags Management": "Správa meta tagů",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Optimalizujte viditelnost svých stránek a hodnocení ve vyhledávačích pomocí naší uživatelsky přívětivé funkce Meta Tags.",
    "Explore Meta Tag Options": "Prozkoumejte možnosti metaznaček",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Seznamte se s různými možnostmi úpravy a automatizace meta tagů, které jsou k dispozici pro jednotlivé produkty a stránky.",
    "Explore Meta Tags": "Prozkoumejte Meta Tagy",
    "Edit and Optimize": "Upravit a optimalizovat",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Ponořte se do úprav meta názvů, popisů a alternativních textů obrázků, abyste zlepšili SEO a uživatelskou přístupnost svého webu.",
    "Start Editing": "Začněte upravovat",
    "Automate for Consistency": "Automatizujte pro konzistenci",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Nastavte pravidla automatizace pro své metaznačky, aby byla zachována konzistence a efektivita na vašich produktových stránkách.",
    "Set Automation": "Nastavte automatizaci",
    "Schema Markup": "Označení schématu",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Využijte značky Schema ke zlepšení zastoupení svého obsahu ve výsledcích vyhledávání a přilákejte více kliknutí.",
    "Learn About Schema Options": "Další informace o možnostech schématu",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Seznamte se s různými typy značek schématu, které jsou k dispozici, jako je produkt, místní firma, časté dotazy a další, abyste pochopili jejich výhody.",
    "Explore Schema Types": "Prozkoumejte typy schémat",
    "Activate Key Schemas": "Aktivujte schémata klíčů",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Vyberte a povolte pro svůj web klíčová schémata, jako je schéma produktu pro elektronický obchod nebo schéma místní firmy pro fyzické obchody.",
    "Go to Schemas": "Přejděte na Schémata",
    "Customize Schema Details": "Přizpůsobte podrobnosti schématu",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Upravte nastavení každého typu schématu tak, aby ve výsledcích vyhledávání přesně reprezentovalo vaši firmu nebo produkty.",
    "Test and Validate Schemas": "Testujte a ověřujte schémata",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Otestujte svá schémata pomocí nástrojů, jako je nástroj Google na testování strukturovaných dat, abyste se ujistili, že jsou správně implementována.",
    "Test Schemas": "Testovací schémata",
    "Add Breadcrumbs": "Přidejte strouhanku",
    "Add Breadcrumbs to your store": "Přidejte Breadcrumbs do svého obchodu",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Chcete-li získat lepší uživatelský dojem, musíte do svého obchodu přidat strouhanku.",
    "How to add breadcrumbs": "Jak přidat strouhanku",
    "Understand how to add and configure breadcrumbs in your store.":
      "Pochopte, jak přidat a nakonfigurovat strouhanku ve vašem obchodě.",
    "Google search console": "Vyhledávací konzole Google",
    "Connect google search console to sync it with our app.":
      "Připojte vyhledávací konzoli Google a synchronizujte ji s naší aplikací.",
    "How to connect GSC.": "Jak připojit GSC.",
    "Understand how to connect and use google search console in our app.":
      "Pochopte, jak se v naší aplikaci připojit a používat vyhledávací konzoli Google.",
    "Go to GSC": "Přejděte na GSC",
    "Go to Breadcrumbs Design": "Přejděte do části Návrh struktury",
    "Start Onboarding": "Spusťte registraci",
    "Go to Homepage": "Jít na domovskou stránku",
    "Go to Onboarding": "Přejděte na Přihlášení",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Prozkoumejte naši uživatelsky přívětivou příručku aplikace navrženou tak, aby vám lépe porozuměla. Začněte kliknutím na 'Start onboarding' a na domovskou stránku se můžete kdykoli vrátit.",
    "Please enable our app extension.": "Povolte prosím naše rozšíření o aplikaci.",
    "Generate Meta tags": "Generování meta tagů",
    "Test description a litle bit longer that title": "Popis testu trochu delší než nadpis",
    "Suggested for you": "Navrženo pro vás",
    "Enable Google page speed": "Povolit rychlost stránky Google",
    "Connect GSC": "Připojte GSC",
    "Enable Image Optimize Automation": "Povolit automatizaci optimalizace obrazu",
    "Automate Meta tags": "Automatizujte meta tagy",
    "Automate Broken Links": "Automatizujte nefunkční odkazy",
    "Enhance SEO with automatically generated meta tags.":
      "Vylepšete SEO pomocí automaticky generovaných metaznaček.",
    "Improve website performance by optimizing images.": "Zlepšete výkon webových stránek optimalizací obrázků.",
    "Boost website speed by enabling Google Page Speed.":
      "Zvyšte rychlost webu povolením rychlosti stránky Google.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Zlepšete viditelnost vyhledávání připojením ke službě Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Zefektivněte optimalizaci obrazu pomocí automatizovaných procesů.",
    "Improve SEO by automating the generation of meta tags.": "Zlepšete SEO automatizací generování meta tagů.",
    "Improve UX with automated detect and handle, broken links.":
      "Vylepšete uživatelské prostředí pomocí automatické detekce a zpracování nefunkčních odkazů.",
    "Learn About Add Announcement": "Další informace o Přidat oznámení",
    "Skip And Add Announcement": "Přeskočit a přidat oznámení",
    "Learn more about": "Dozvědět se víc o",
    "Add Announcement": "Přidat oznámení",
    "Announcement Bar": "Oznamovací lišta",
    "Rate us!": "Ohodnoťte nás!",
    "How would you Love this app?": "Jak by se vám tato aplikace líbila?",
    "Enter Your Feedback Here": "Zde zadejte svůj názor",
    "Leave Us a Review !!": "Zanechte nám recenzi!!",
    "If you like our app features then please leave us a review !!":
      "Pokud se vám líbí naše funkce aplikace, zanechte nám prosím recenzi !!",
    "If you like our free features then please leave us a review !!":
      "Pokud se vám líbí naše bezplatné funkce, zanechte nám prosím recenzi!!",
    "Update Successfully": "Aktualizace proběhla úspěšně",
    "Uninstall App": "Odinstalovat aplikaci",
    "Contact Our Support": "Kontaktujte naši podporu",
    "Leave a message": "Zanechat vzkaz",
    "Please Choose a UnInstallation Reason": "Vyberte prosím důvod odinstalace",
    "Are you facing any issues understanding the features of our app?":
      "Máte nějaké problémy s pochopením funkcí naší aplikace?",
    "Please Choose at least one reason": "Vyberte prosím alespoň jeden důvod",
    "Thank You For Reaching Out": "Děkujeme, že jste nás oslovili",
    "Contact Support": "Kontaktujte podporu",
    "Get Help from Our Support Team": "Získejte pomoc od našeho týmu podpory",
    "Select a reason": "Vyberte důvod",
    "Not getting how to use or setup": "Nedostáváte, jak používat nebo nastavovat",
    "Poor customer support": "Špatná zákaznická podpora",
    "Performance issues": "Problémy s výkonem",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Náš tým podpory je momentálně nedostupný o víkendech a bude k dispozici ve všední dny podle vašeho časového pásma od ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " protože působíme z Indie. Stále můžete zanechat zprávu. Očekávejte prosím určité zpoždění v naší odpovědi. Děkujeme vám za vaši trpělivost.",
    "Our support team is partially available according to your time zone from ":
      "Náš tým podpory je částečně k dispozici podle vašeho časového pásma od ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " protože působíme z Indie. Během této doby mohou odpovědi trvat 30 minut až hodinu. Zanechte prosím zprávu a my vám odpovíme co nejdříve. Děkujeme vám za vaši trpělivost.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Náš tým podpory je momentálně nedostupný a bude dostupný podle vašeho časového pásma od ",
    to: "na",
    "Did not meet my expectations": "Nesplnil má očekávání",
    "Feature Limitations": "Omezení funkcí",
    "Banner doesn't set in my app": "V mé aplikaci není nastaven banner",
    "Banner is not show properly": "Banner se nezobrazuje správně",
    "Confusing Set Multi Position and Multi Animation": "Matoucí nastavení více pozic a více animací",
    "Sync Profile": "Synchronizovat profil",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
