import modifyData from "../Language/en.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Enabled",
    Disabled: "Disabled",
    "Embed is currently disabled": "Embed is currently disabled",
    "Enable App": "Enable App",
    "1. Click on Enable App.": "1. Click on Enable App.",
    "Well done!! you have successfully enable our app.": "Well done!! you have successfully enable our app.",
    "2. Enable": "2. Enable",
    "App Embed as shown in image and save setting.": "App Embed as shown in image and save setting.",
    "Multi Announcement Bar": "Multi Announcement Bar",
    "Click on the Enable Now button to enable it.": "Click on the Enable Now button to enable it.",
    "Enable Announcement Bar to get started": "Enable Announcement Bar to get started",
    "Enable Now": "Enable Now",
    "Sync Status": "Sync Status",
    "To see our app features, you need to activate the": "To see our app features, you need to activate the",
    "block in your store's theme customization.": "block in your store's theme customization.",
    Done: "Done",
    No: "No",
    Add: "Add",
    Search: "Search",
    Showing: "Showing",
    of: "of",
    "results, at most": "results, at most",
    "per page": "per page",
    "Oops! Something went wrong.": "Oops! Something went wrong.",
    "Let's try that again, please refresh the page.": "Let's try that again, please refresh the page.",
    "If you're still stuck, contact us by chat support or": "If you're still stuck, contact us by chat support or",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "so we can help!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Select any 3 feature that you want to setup on high priority or most interested",
    "Add ": "Add ",
    "These is premium feature": "These is premium feature",
    "Go to pricing": "Go to pricing",
    Save: "Save",
    Minimum: "Minimum",
    Maximum: "Maximum",
    "images are required": "images are required",
    and: "and",
    "images are allowed": "images are allowed",
    Disconnect: "Disconnect",
    "Sign In with Google": "Sign In with Google",
    "Oops! Something went wrong. Admin token is malformed": "Oops! Something went wrong. Admin token is malformed",
    "If you're still stuck, contact": "If you're still stuck, contact",
    Premium: "Premium",
    Unlock: "Unlock",
    "Unlock advanced features!": "Unlock advanced features!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. All rights reserved.",
    "Privacy Policy": "Privacy Policy",
    "Terms of Service": "Terms of Service",
    "Go to Shopify App": "Go to Shopify App",
    "Review Us": "Review Us",
    Cancel: "Cancel",
    "Review Popup Show": "Review Popup Show",
    "click on review us": "click on review us",
    "Note: Feel free to leave a star rating without writing a review!":
      "Note: Feel free to leave a star rating without writing a review!",
    Help: "Help",
    "Help Button Click": "Help Button Click",
    Confirm: "Confirm",
    On: "On",
    Off: "Off",
    Price: "Price",
    Settings: "Settings",
    Animation: "Animation",
    "My Profile": "My Profile",
    "My Subscription": "My Subscription",
    "Store Name": "Store Name",
    "Store URL": "Store URL",
    "Email ID": "Email ID",
    "Phone Number": "Phone Number",
    Country: "Country",
    Currency: "Currency",
    "Subscription Name": "Subscription Name",
    "Select language": "Select language",
    "Announcement setting": "Announcement setting",
    "Animation setting": "Animation setting",
    Selector: "Selector",
    "Save Setting": "Save Setting",
    "My Announcements": "My Announcements",
    "Add bar": "Add bar",
    Number: "Number",
    Title: "Title",
    "Create At": "Create At",
    "Slide Activation": "Slide Activation",
    Status: "Status",
    Actions: "Actions",
    "Save order": "Save order",
    "Reorder Slides": "Reorder Slides",
    position: "position",
    Top: "Top",
    "Sticky Top": "Sticky Top",
    "Bottom Fix": "Bottom Fix",
    "Custom Position": "Custom Position",
    "Custom Position *Add Class or id of Selected Element.":
      "Custom Position *Add Class or id of Selected Element.",
    "Bar Padding (px)": "Bar Padding (px)",
    "Add Remove Button": "Add Remove Button",
    "Choose icon color": "Choose icon color",
    "Custom css": "Custom css",
    fadeIn: "fadeIn",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "fadeInUp",
    bounceInDown: "bounceInDown",
    bounceInLeft: "bounceInLeft",
    bounceInUp: "bounceInUp",
    zoomIn: "zoomIn",
    zoomInDown: "zoomInDown",
    zoomInLeft: "zoomInLeft",
    slideInLeft: "slideInLeft",
    slideInUp: "slideInUp",
    slideInDown: "slideInDown",
    lightSpeedIn: "lightSpeedIn",
    rollIn: "rollIn",
    flash: "flash",
    shake: "shake",
    flip: "flip",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "fadeOut",
    fadeOutDown: "fadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fadeOutUp",
    bounceOutDown: "bounceOutDown",
    bounceOutRight: "bounceOutRight",
    bounceOutUp: "bounceOutUp",
    zoomOut: "zoomOut",
    zoomOutDown: "zoomOutDown",
    zoomOutRight: "zoomOutRight",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "rollOut",
    flipInY: "flipInY",
    "Text Animation": "Text Animation",
    "Animation In": "Animation In",
    "Animation Out": "Animation Out",
    "Auto play time (time in MS)": "Auto play time (time in MS)",
    "Animation time (time in MS)": "Animation time (time in MS)",
    "Auto play time (time in Second)": "Auto play time (time in Second)",
    "Background Color": "Background Color",
    "Space between slide(px)": "Space between slide(px)",
    visible: "visible",
    invisible: "invisible",
    "Promotional & Countdown Bar": "Promotional & Countdown Bar",
    "Free Shipping Bar": "Free Shipping Bar",
    "Add Slide": "Add Slide",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.",
    Pricing: "Pricing",
    "No Animation Found": "No Animation Found",
    "No Preview, Add announcement Bar": "No Preview, Add announcement Bar",
    "Update successfully": "Update successfully",
    Enable: "Enable",
    Disable: "Disable",
    successfully: "successfully",
    "Delete successfully": "Delete successfully",
    "Copy successfully": "Copy successfully",
    "Reorder successfully": "Reorder successfully",
    "Announcement Message": "Announcement Message",
    "Call to Action": "Call to Action",
    Timer: "Timer",
    Style: "Style",
    "Background Type": "Background Type",
    "Mobile Style": "Mobile Style",
    "Schedule Display": "Schedule Display",
    Update: "Update",
    "Change Font": "Change Font",
    "Font Family": "Font Family",
    "Font Style": "Font Style",
    Normal: "Normal",
    Italic: "Italic",
    Oblique: "Oblique",
    Unset: "Unset",
    "Font Weight": "Font Weight",
    Bold: "Bold",
    "Message Font Size": "Message Font Size",
    "Message Text color": "Message Text color",
    Type: "Type",
    None: "None",
    Button: "Button",
    "Entire clickable bar": "Entire clickable bar",
    "Add a simple link": "Add a simple link",
    "Add coupon placement": "Add coupon placement",
    "Linked Url": "Linked Url",
    "Background Hover Color": "Background Hover Color",
    "Text Hover Color": "Text Hover Color",
    "Button Text": "Button Text",
    "Copied Text": "Copied Text",
    "Open in the new tab": "Open in the new tab",
    URL: "URL",
    "Font Size": "Font Size",
    "Button Radius": "Button Radius",
    "Button color": "Button color",
    "Button Text color": "Button Text color",
    "Button Hover Color": "Button Hover Color",
    "button Text HoverColor": "button Text HoverColor",
    "Timer Setting": "Timer Setting",
    "Timer Type": "Timer Type",
    Date: "Date",
    "Select Reapt Time": "Select Reapt Time",
    "repeated Hours": "repeated Hours",
    "Normal Timer": "Normal Timer",
    "Auto repeat timer": "Auto repeat timer",
    Minute: "Minute",
    Hour: "Hour",
    Day: "Day",
    "Remove Timer When Time End": "Remove Timer When Time End",
    "Timer Separator": "Timer Separator",
    "Countdown Timer color": "Countdown Timer color",
    "Timer Text Size": "Timer Text Size",
    "Timer Text Setting": "Timer Text Setting",
    "Day Text": "Day Text",
    "Hour Text": "Hour Text",
    "Minute Text": "Minute Text",
    "Second Text": "Second Text",
    "Background Image": "Background Image",
    "Gradient Background": "Gradient Background",
    "Style & Color For Mobile": "Style & Color For Mobile",
    "Timer Background": "Timer Background",
    "Timer Text Color": "Timer Text Color",
    "Button Color": "Button Color",
    "Button Text Color": "Button Text Color",
    "Button Text Hover Color": "Button Text Hover Color",
    "Button Text Size": "Button Text Size",
    "Always Display": "Always Display",
    "Only Display Within The Following Period Of Time": "Only Display Within The Following Period Of Time",
    "Start Time": "Start Time",
    "End Time": "End Time",
    "Advance Setting": "Advance Setting",
    "Country Filter": "Country Filter",
    Visibility: "Visibility",
    "Desktop and Mobile": "Desktop and Mobile",
    "Only Desktop": "Only Desktop",
    "Only Mobile": "Only Mobile",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Select Page",
    Include: "Include",
    Exclude: "Exclude",
    "Currency Configuration": "Currency Configuration",
    Message: "Message",
    "Currency Symbol": "Currency Symbol",
    "Currency Position": "Currency Position",
    Before: "Before",
    After: "After",
    "money Class": "money Class",
    "Initial Message": "Initial Message",
    "Shipping Goal": "Shipping Goal",
    "Progress Message": "Progress Message",
    "Progress goal": "Progress goal",
    "Goal Message": "Goal Message",
    "Shipping Price Color": "Shipping Price Color",
    "Shipping Price Size": "Shipping Price Size",
    "Shipping Font Weight": "Shipping Font Weight",
    "* When user first time visit": "* When user first time visit",
    "* When user add item to the cart e.g": "* When user add item to the cart e.g:",
    "* When cart value is greater than": "* When cart value is greater than",
    "Show On Selected Countries": "Show On Selected Countries",
    "Show On Selected Pages": "Show On Selected Pages",
    All: "All",
    Home: "Home",
    Cart: "Cart",
    Collection: "Collection",
    Product: "Product",
    Custom: "Custom",
    Page: "Page",
    Blog: "Blog",
    "Url is required": "Url is required",
    "Day Text is required": "Day Text is required",
    "Hour Text is required": "Hour Text is required",
    "Minute Text is required": "Minute Text is required",
    "Second Text is required": "Second Text is required",
    "Start Time is required": "Start Time is required",
    "End Time is required": "End Time is required",
    "Created successfully": "Created successfully",
    "United States": "United States",
    Canada: "Canada",
    Australia: "Australia",
    "New Zealand": "New Zealand",
    Germany: "Germany",
    India: "India",
    Afghanistan: "Afghanistan",
    "land Islands": "land Islands",
    Albania: "Albania",
    Algeria: "Algeria",
    "American Samoa": "American Samoa",
    AndorrA: "AndorrA",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarctica",
    "Antigua and Barbuda": "Antigua and Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Aruba: "Aruba",
    Austria: "Austria",
    Azerbaijan: "Azerbaijan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrain",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belgium",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermuda",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    "Bosnia and Herzegovina": "Bosnia and Herzegovina",
    Botswana: "Botswana",
    "Bouvet Island": "Bouvet Island",
    Brazil: "Brazil",
    "British Indian Ocean Territory": "British Indian Ocean Territory",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Cambodia",
    Cameroon: "Cameroon",
    "Cape Verde": "Cape Verde",
    "Cayman Islands": "Cayman Islands",
    "Central African Republic": "Central African Republic",
    Chad: "Chad",
    Chile: "Chile",
    China: "China",
    "Christmas Island": "Christmas Island",
    "Cocos (Keeling) Islands": "Cocos (Keeling) Islands",
    Colombia: "Colombia",
    Comoros: "Comoros",
    Congo: "Congo",
    "Congo, The Democratic Republic of the": "Congo, The Democratic Republic of the",
    "Cook Islands": "Cook Islands",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Cote D'Ivoire",
    Croatia: "Croatia",
    Cuba: "Cuba",
    Cyprus: "Cyprus",
    "Czech Republic": "Czech Republic",
    Denmark: "Denmark",
    Djibouti: "Djibouti",
    Dominica: "Dominica",
    "Dominican Republic": "Dominican Republic",
    Ecuador: "Ecuador",
    Egypt: "Egypt",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatorial Guinea",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Ethiopia: "Ethiopia",
    "Falkland Islands (Malvinas)": "Falkland Islands (Malvinas)",
    "Faroe Islands": "Faroe Islands",
    Fiji: "Fiji",
    Finland: "Finland",
    France: "France",
    "French Guiana": "French Guiana",
    "French Polynesia": "French Polynesia",
    "French Southern Territories": "French Southern Territories",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Greece",
    Greenland: "Greenland",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Heard Island and Mcdonald Islands",
    "Holy See (Vatican City State)": "Holy See (Vatican City State)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Hungary",
    Iceland: "Iceland",
    Indonesia: "Indonesia",
    "Iran, Islamic Republic Of": "Iran, Islamic Republic Of",
    Iraq: "Iraq",
    Ireland: "Ireland",
    "Isle of Man": "Isle of Man",
    Israel: "Israel",
    Italy: "Italy",
    Jamaica: "Jamaica",
    Japan: "Japan",
    Jersey: "Jersey",
    Jordan: "Jordan",
    Kazakhstan: "Kazakhstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Korea, Democratic People'S Republic of",
    "Korea, Republic of": "Korea, Republic of",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kyrgyzstan",
    "Lao People'S Democratic Republic": "Lao People'S Democratic Republic",
    Latvia: "Latvia",
    Lebanon: "Lebanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    "Libyan Arab Jamahiriya": "Libyan Arab Jamahiriya",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lithuania",
    Luxembourg: "Luxembourg",
    Macao: "Macao",
    "Macedonia, The Former Yugoslav Republic of": "Macedonia, The Former Yugoslav Republic of",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldives",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Marshall Islands",
    Martinique: "Martinique",
    Mauritania: "Mauritania",
    Mauritius: "Mauritius",
    Mayotte: "Mayotte",
    Mexico: "Mexico",
    "Micronesia, Federated States of": "Micronesia, Federated States of",
    "Moldova, Republic of": "Moldova, Republic of",
    Monaco: "Monaco",
    Mongolia: "Mongolia",
    Montenegro: "Montenegro",
    Montserrat: "Montserrat",
    Morocco: "Morocco",
    Mozambique: "Mozambique",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Netherlands",
    "Netherlands Antilles": "Netherlands Antilles",
    "New Caledonia": "New Caledonia",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    "Norfolk Island": "Norfolk Island",
    "Northern Mariana Islands": "Northern Mariana Islands",
    Norway: "Norway",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Palestinian Territory, Occupied",
    Panama: "Panama",
    "Papua New Guinea": "Papua New Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Philippines",
    Pitcairn: "Pitcairn",
    Poland: "Poland",
    Portugal: "Portugal",
    "Puerto Rico": "Puerto Rico",
    Qatar: "Qatar",
    Reunion: "Reunion",
    Romania: "Romania",
    "Russian Federation": "Russian Federation",
    RWANDA: "RWANDA",
    "Saint Helena": "Saint Helena",
    "Saint Kitts and Nevis": "Saint Kitts and Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
    "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tome and Principe",
    "Saudi Arabia": "Saudi Arabia",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Seychelles: "Seychelles",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovakia",
    Slovenia: "Slovenia",
    "Solomon Islands": "Solomon Islands",
    Somalia: "Somalia",
    "South Africa": "South Africa",
    "South Georgia and the South Sandwich Islands": "South Georgia and the South Sandwich Islands",
    Spain: "Spain",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard and Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Sweden",
    Switzerland: "Switzerland",
    "Syrian Arab Republic": "Syrian Arab Republic",
    "Taiwan, Province of China": "Taiwan, Province of China",
    Tajikistan: "Tajikistan",
    "Tanzania, United Republic of": "Tanzania, United Republic of",
    Thailand: "Thailand",
    "Timor-Leste": "Timor-Leste",
    Togo: "Togo",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd and Tobago",
    Tunisia: "Tunisia",
    Turkey: "Turkey",
    Turkmenistan: "Turkmenistan",
    "Turks and Caicos Islands": "Turks and Caicos Islands",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraine",
    "United Arab Emirates": "United Arab Emirates",
    "United Kingdom": "United Kingdom",
    "United States Minor Outlying Islands": "United States Minor Outlying Islands",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Viet Nam",
    "Virgin Islands, British": "Virgin Islands, British",
    "Virgin Islands, U.S.": "Virgin Islands, U.S.",
    "Wallis and Futuna": "Wallis and Futuna",
    "Western Sahara": "Western Sahara",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Unlock All Schema with our Premium Plan",
    "Billed Monthly": "Billed Monthly",
    "Billed Annually": "Billed Annually",
    "Save 30%": "Save 30%",
    Premium100Title:
      "As an early user, we assure you that all our premium feature you will enjoy at no cost to you. There is no need to be concerned about the pricing page as you can freely access all our premium feature without any charges. Please don't uninstall our app to continue enjoying our service.",
    Premium100ReviewLine:
      " If you like our app please leave us review. That's help us to get motivated developing new features.",
    "Check Our Current Pricing": "Check Our Current Pricing",
    "Leave Review": "Leave Review",
    "We're sorry to see you go!": "We're sorry to see you go!",
    "Cancel Plan": "Cancel Plan",
    "Sync Plan": "Sync Plan",
    "Disccount applied": "Disccount applied",
    Apply: "Apply",
    "Your code(s)": "Your code(s)",
    "and discount have been applied successfully": "and discount have been applied successfully",
    "Your entered promocode is not correct, Enter a valid code":
      "Your entered promocode is not correct, Enter a valid code",
    "days trial left": "days trial left",
    Upgrade: "Upgrade",
    "days free trial, No Credit card required": "days free trial, No Credit card required",
    Month: "Month",
    Year: "Year",
    Unlimited: "Unlimited",
    "Enter Promocode": "Enter Promocode",
    "Please Choose a Cancellation Reason": "Please Choose a Cancellation Reason",
    "No Longer Needed?": "No Longer Needed?",
    "Didn't Meet Expectations": "Didn't Meet Expectations",
    "Cost Concerns": "Cost Concerns",
    "Technical Issues": "Technical Issues",
    "Found an Alternative": "Found an Alternative",
    Complexity: "Complexity",
    "Lack of Features": "Lack of Features",
    "Poor Customer Support": "Poor Customer Support",
    "Business Closure or Change": "Business Closure or Change",
    "Temporary Pause": "Temporary Pause",
    "Performance Issues": "Performance Issues",
    Other: "Other",
    "Mention Your Specific Reason Here": "Mention Your Specific Reason Here",
    Start: "Start",
    "Day Free Trial": "Day Free Trial",
    "Please Select One Option": "Please Select One Option",
    "Plan cancelled successfully": "Plan cancelled successfully",
    "7 days free trial, No Credit card required": "7 days free trial, No Credit card required",
    "Your remaining trial days are": "Your remaining trial days are",
    "You have used": "You have used",
    "days.": "days.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "No trial days remaining. You have already used the 7-day free trial.",
    "Upgrade your plan now": "Upgrade your plan now",
    "Unlimited Slides": "Unlimited Slides",
    "20+ Animation In & Out": "20+ Animation In & Out",
    "Live Chat Support": "Live Chat Support",
    "Priority, 24*7 Urgent setup and support": "Priority, 24*7 Urgent setup and support",
    "Rich Text Editor": "Rich Text Editor",
    "One Slide(banner)": "One Slide(banner)",
    "Repeated Countdown timer": "Repeated Countdown timer",
    "Fully Customisable": "Fully Customisable",
    "Background-image": "Background-image",
    "Custom Css": "Custom Css",
    "Analytics data": "Analytics data",
    "Enable Our App": "Enable Our App",
    "Book Onboarding Demo": "Book Onboarding Demo",
    Next: "Next",
    Finish: "Finish",
    Prev: "Prev",
    "App is not enable please click on the Enable App button to enable it.":
      "App is not enable please click on the Enable App button to enable it.",
    "This field is required": "This field is required",
    "Store customization services": "Store customization services",
    free: "free",
    trial: "trial",
    "Affordable SEO services": "Affordable SEO services",
    "We'll work on your store for 10 hours completely": "We'll work on your store for 10 hours completely",
    "of charge.🚀": "of charge.🚀",
    Enjoy: "Enjoy",
    "half-price customization": "half-price customization",
    "for another": "for another",
    "10 hours": "10 hours",
    "after the free period.": "after the free period.",
    "After your discounted hours, we'll continue at our regular rate of just":
      "After your discounted hours, we'll continue at our regular rate of just",
    "Start Your Free Customization": "Start Your Free Customization",
    "First 10 hours free": "First 10 hours free",
    "Next 10 hours": "Next 10 hours",
    "After discount period": "After discount period",
    "Theme Customization – Tailored Shopify Design & Features":
      "Theme Customization – Tailored Shopify Design & Features",
    "Transform your Shopify store with advanced design changes, custom functionalities, and deep theme-level enhancements. Built for brands needing flexibility, precision, and performance.":
      "Transform your Shopify store with advanced design changes, custom functionalities, and deep theme-level enhancements. Built for brands needing flexibility, precision, and performance.",
    "Premium Shopify professional theme design": "Premium Shopify professional theme design",
    "Custom design modifications": "Custom design modifications",
    "Product and collection page enhancements": "Product and collection page enhancements",
    "Custom animation integrations": "Custom animation integrations",
    "Shopify Liquid & JavaScript custom coding": "Shopify Liquid & JavaScript custom coding",
    "Fix HTML/CSS/JavaScript issues": "Fix HTML/CSS/JavaScript issues",
    "Add/modify comparison sliders": "Add/modify comparison sliders",
    "Integrate search functionality changes": "Integrate search functionality changes",
    "Fix Shopify theme bugs and layout errors": "Fix Shopify theme bugs and layout errors",
    "Resolve mobile responsiveness issues": "Resolve mobile responsiveness issues",
    "Handle responsiveness conflicts": "Handle responsiveness conflicts",
    "Add custom filter options": "Add custom filter options",
    "Setup multiple payment options": "Setup multiple payment options",
    "Add metafields & metaobjects integration": "Add metafields & metaobjects integration",
    "SEO-friendly store setup": "SEO-friendly store setup",
    "Optimize structure for speed & accessibility": "Optimize structure for speed & accessibility",
    "Shopify Plus checkout customization": "Shopify Plus checkout customization",
    "Migrate from any CMS to Shopify": "Migrate from any CMS to Shopify",
    "Start your free services": "Start your free services",
    Pay: "Pay",
    "Webrex One time Charge": "Webrex One time Charge",
    "one-time charge": "one-time charge",
    "Add total amount in Dollar($)": "Add total amount in Dollar($)",
    "Plan Name": "Plan Name",
    "Choose your conversion rate optimization plans": "Choose your conversion rate optimization plans",
    "Affordable CRO services": "Affordable CRO services",
    "Special offer": "Special offer",
    "Upgrade current plan": "Upgrade current plan",
    plan: "plan",
    "One-Time Exclusive Offer": "One-Time Exclusive Offer",
    "🎊Congratulations!!🎊": "🎊Congratulations!!🎊",
    "🎉 Special One-Time Offer!": "🎉 Special One-Time Offer!",
    "You've been selected for our exclusive 180-day free trial offer. This is a limited-time opportunity to experience our premium features at no cost.":
      "You've been selected for our exclusive 180-day free trial offer. This is a limited-time opportunity to experience our premium features at no cost.",
    "Enjoy a 180-Day Free Trial of Our Premium Plan": "Enjoy a 180-Day Free Trial of Our Premium Plan",
    "What happens after 180 days?": "What happens after 180 days?",
    "After your 180-day free trial period, your plan will automatically cancel from our app and you will not get charged anything from shopify after 180 day. After 180 day If you wish to continue using our premium features after the trial, you can upgrade your plan from our pricing section at any time.":
      "After your 180-day free trial period, your plan will automatically cancel from our app and you will not get charged anything from shopify after 180 day. After 180 day If you wish to continue using our premium features after the trial, you can upgrade your plan from our pricing section at any time.",
    "❌ Don't uninstall app and enjoy 180 day premium plan free.":
      "❌ Don't uninstall app and enjoy 180 day premium plan free.",
    "This is a one-time offer. If you uninstall the app, you won't be able to get this offer again.":
      "This is a one-time offer. If you uninstall the app, you won't be able to get this offer again.",
    "Choose your theme customization plan": "Choose your theme customization plan",
    "Budget-friendly store customization": "Budget-friendly store customization",
    "Choose your store customization plan": "Choose your store customization plan",
    "Custom store design and development": "Custom store design and development",
    "Get instant credit means you can skip the trial and receive your credit immediately":
      "Get instant credit means you can skip the trial and receive your credit immediately",
    "Skip the trial and subscribe now": "Skip the trial and subscribe now",
    "Get instant credit": "Get instant credit",
    "Core Web Vitals Optimization": "Core Web Vitals Optimization",
    "Speed up your site to boost SEO and reduce bounce rates.":
      "Speed up your site to boost SEO and reduce bounce rates.",
    "Audit and fix Largest Contentful Paint (LCP) delays.": "Audit and fix Largest Contentful Paint (LCP) delays.",
    "Eliminate Cumulative Layout Shift (CLS) by setting image/video dimensions.":
      "Eliminate Cumulative Layout Shift (CLS) by setting image/video dimensions.",
    "Defer non-critical JavaScript and CSS.": "Defer non-critical JavaScript and CSS.",
    "Convert images to WebP/AVIF formats.": "Convert images to WebP/AVIF formats.",
    "Implement lazy loading for images and videos.": "Implement lazy loading for images and videos.",
    "Minify CSS, JavaScript, and HTML files.": "Minify CSS, JavaScript, and HTML files.",
    "Remove unused code from theme files.": "Remove unused code from theme files.",
    "Preload critical fonts and assets.": "Preload critical fonts and assets.",
    "Optimize third-party scripts (e.g., chatbots, analytics).":
      "Optimize third-party scripts (e.g., chatbots, analytics).",
    "Integrate a global CDN (e.g., Cloudflare).": "Integrate a global CDN (e.g., Cloudflare).",
    "Fix render-blocking resources.": "Fix render-blocking resources.",
    "Reduce server response time via Shopify Plus.": "Reduce server response time via Shopify Plus.",
    "Compress text files with Brotli/Gzip.": "Compress text files with Brotli/Gzip.",
    "Audit and optimize Shopify apps for performance.": "Audit and optimize Shopify apps for performance.",
    "Monitor Core Web Vitals monthly and re-optimize.": "Monitor Core Web Vitals monthly and re-optimize.",
    "20-40% faster load times → 10-25% higher conversions.":
      "20-40% faster load times → 10-25% higher conversions.",
    "Mobile-First Redesign": "Mobile-First Redesign",
    "Dominate mobile shoppers (70%+ of traffic).": "Dominate mobile shoppers (70%+ of traffic).",
    "15-30% higher mobile conversions.": "15-30% higher mobile conversions.",
    "Redesign mobile menus for thumb-friendly navigation.": "Redesign mobile menus for thumb-friendly navigation.",
    "Optimize product grids for mobile screens (2 columns → 1).":
      "Optimize product grids for mobile screens (2 columns → 1).",
    "Add sticky “Add to Cart” buttons on PDPs.": "Add sticky “Add to Cart” buttons on PDPs.",
    "Simplify checkout to 3 steps or fewer.": "Simplify checkout to 3 steps or fewer.",
    "Increase button sizes (minimum 48x48px).": "Increase button sizes (minimum 48x48px).",
    "Optimize font sizes for readability without zooming.": "Optimize font sizes for readability without zooming.",
    "Implement swipeable image galleries.": "Implement swipeable image galleries.",
    "Test mobile-specific popups (e.g., exit-intent).": "Test mobile-specific popups (e.g., exit-intent).",
    "Auto-format phone numbers for tap-to-call.": "Auto-format phone numbers for tap-to-call.",
    "Add Apple Pay/Google Pay one-tap checkout.": "Add Apple Pay/Google Pay one-tap checkout.",
    "Fix mobile-specific layout shifts (CLS).": "Fix mobile-specific layout shifts (CLS).",
    "Reduce mobile page weight to <2MB.": "Reduce mobile page weight to <2MB.",
    "Hide non-essential desktop elements on mobile.": "Hide non-essential desktop elements on mobile.",
    "Monthly mobile UX testing on real devices.": "Monthly mobile UX testing on real devices.",
    "5 days": "5 days",
    "A/B Testing & Personalization": "A/B Testing & Personalization",
    "Data-driven experiments to maximize ROI.": "Data-driven experiments to maximize ROI.",
    "10-20% uplift in key metrics.": "10-20% uplift in key metrics.",
    "AB test headlines, subheadlines, and CTAs.": "A/B test headlines, subheadlines, and CTAs.",
    "Test pricing strategies (e.g., 49 vs. 49* vs. 49.99).":
      "Test pricing strategies (e.g., 49 vs. 49* vs. 49.99).",
    "Experiment with button colors and placements.": "Experiment with button colors and placements.",
    "Personalize product recommendations by browsing history.":
      "Personalize product recommendations by browsing history.",
    "Test free shipping thresholds vs. discounts.": "Test free shipping thresholds vs. discounts.",
    "Dynamic content for returning vs. new visitors.": "Dynamic content for returning vs. new visitors.",
    "AI-driven product sorting (e.g., Trending Now).": "AI-driven product sorting (e.g., Trending Now).",
    "Geo-targeted banners (e.g., Local delivery available!).":
      "Geo-targeted banners (e.g., Local delivery available!).",
    "Test urgency tactics (3 left in stock vs. Selling fast).":
      "Test urgency tactics (3 left in stock vs. Selling fast).",
    "Experiment with trust badges placement.": "Experiment with trust badges placement.",
    "Split-test checkout flow (one-page vs. multi-step).": "Split-test checkout flow (one-page vs. multi-step).",
    "Test video vs. image hero banners.": "Test video vs. image hero banners.",
    "Personalized email/SMS campaigns.": "Personalized email/SMS campaigns.",
    "AI chatbots for product recommendations.": "AI chatbots for product recommendations.",
    "Monthly test reports and scaling winners.": "Monthly test reports and scaling winners.",
    "Exit-Intent & Cart Recovery": "Exit-Intent & Cart Recovery",
    "Recover 15-30% of abandoned carts.": "Recover 15-30% of abandoned carts.",
    "Recover $1,000s in lost revenue monthly.": "Recover $1,000s in lost revenue monthly.",
    "Exit-intent popups with time-sensitive discounts": "Exit-intent popups with time-sensitive discounts",
    "Automated SMS reminders with product images": "Automated SMS reminders with product images",
    "Email sequences with personalized recommendations": "Email sequences with personalized recommendations",
    "Offer free shipping if cart value is $X away": "Offer free shipping if cart value is $X away",
    "Test exit offers (10% off vs. free gift)": "Test exit offers (10% off vs. free gift)",
    "Display live stock counters in cart": "Display live stock counters in cart",
    "Add Save Cart feature for logged-in users": "Add a 'Save Cart' feature for logged-in users",
    "Retarget abandoners via Facebook/Google Ads": "Retarget abandoners via Facebook/Google Ads",
    "Push notifications for cart reminders": "Push notifications for cart reminders",
    "Integrate urgency timers": "Integrate urgency timers ('Offer expires in 10:00')",
    "Post-purchase surveys to identify drop-off reasons": "Post-purchase surveys to identify drop-off reasons",
    "Offer installment payments (e.g., Klarna) at checkout":
      "Offer installment payments (e.g., Klarna) at checkout",
    "Re-engage users with Did you forget something emails":
      "Re-engage users with 'Did you forget something?' emails",
    "AB test popup designs (minimalist vs. bold)": "A/B test popup designs (minimalist vs. bold)",
    "Monthly cart recovery rate analysis": "Monthly cart recovery rate analysis",
    "What We Can Do": "What We Can Do",
    "Upsell/Cross-Sell Engine": "Upsell/Cross-Sell Engine",
    "Increase average order value (AOV).": "Increase average order value (AOV).",
    "20-40% higher AOV.": "20-40% higher AOV.",
    "Post-purchase one-click upsells (e.g., 'Add a case for 20% off')":
      "Post-purchase one-click upsells (e.g., 'Add a case for 20% off')",
    "'Frequently Bought Together' AI-powered widgets": "'Frequently Bought Together' AI-powered widgets",
    "Product bundles (e.g., 'Complete Skincare Kit')": "Product bundles (e.g., 'Complete Skincare Kit')",
    "'Complete the Look' recommendations on PDPs": "'Complete the Look' recommendations on PDPs",
    "Volume discounts (e.g., 'Buy 2, Save 15%')": "Volume discounts (e.g., 'Buy 2, Save 15%')",
    "Subscription prompts for replenishable products": "Subscription prompts for replenishable products",
    "Pre-purchase upsells (e.g., 'Upgrade to Premium')": "Pre-purchase upsells (e.g., 'Upgrade to Premium')",
    "Post-checkout upsell pages with limited-time offers": "Post-checkout upsell pages with limited-time offers",
    "Dynamic upsells based on cart contents": "Dynamic upsells based on cart contents",
    "'Customers Also Viewed' carousels": "'Customers Also Viewed' carousels",
    "Loyalty-linked upsells (e.g., 'Redeem points for $10 off')":
      "Loyalty-linked upsells (e.g., 'Redeem points for $10 off')",
    "Seasonal upsell campaigns (e.g., holiday gift sets)": "Seasonal upsell campaigns (e.g., holiday gift sets)",
    "AI-driven product recommendations": "AI-driven product recommendations",
    "A/B test upsell timing (pre- vs. post-purchase)": "A/B test upsell timing (pre- vs. post-purchase)",
    "Monthly AOV tracking and strategy tweaks": "Monthly AOV tracking and strategy tweaks",
    "Trust & Social Proof Toolkit": "Trust & Social Proof Toolkit",
    "Build credibility to reduce buyer hesitation.": "Build credibility to reduce buyer hesitation.",
    "10-20% lower checkout abandonment.": "10-20% lower checkout abandonment.",
    "User-generated content (UGC) galleries": "User-generated content (UGC) galleries",
    "Display customer reviews with photos/videos": "Display customer reviews with photos/videos",
    "Trust badges (SSL, money-back guarantee, secure checkout)":
      "Trust badges (SSL, money-back guarantee, secure checkout)",
    "Influencer testimonials and unboxing videos": "Influencer testimonials and unboxing videos",
    "Live sales notifications ('12 people bought today')": "Live sales notifications ('12 people bought today')",
    "Press mentions (e.g., 'Featured in Vogue')": "Press mentions (e.g., 'Featured in Vogue')",
    "Social media follower counters": "Social media follower counters",
    "'As Seen On' logos (media, influencers)": "'As Seen On' logos (media, influencers)",
    "Free shipping/returns banners": "Free shipping/returns banners",
    "Display payment security icons (Shop Pay, PayPal)": "Display payment security icons (Shop Pay, PayPal)",
    "Add a 'Verified Buyer' badge to reviews": "Add a 'Verified Buyer' badge to reviews",
    "Show real-time inventory levels ('Only 3 left!')": "Show real-time inventory levels ('Only 3 left!')",
    "Case studies with before/after results": "Case studies with before/after results",
    "Trustpilot or Google Reviews integration": "Trustpilot or Google Reviews integration",
    "Monthly UGC campaigns to refresh content": "Monthly UGC campaigns to refresh content",
    "Checkout Friction Fixes": "Checkout Friction Fixes",
    "Streamline checkout for higher completion rates.": "Streamline checkout for higher completion rates.",
    "15-25% higher checkout completion.": "15-25% higher checkout completion.",
    "Customize Shopify Plus checkout (branded colors/fonts)":
      "Customize Shopify Plus checkout (branded colors/fonts)",
    "Enable guest checkout": "Enable guest checkout",
    "Add address autocomplete": "Add address autocomplete",
    "Simplify checkout to one page": "Simplify checkout to one page",
    "Offer multiple payment options (Shop Pay, Klarna, crypto)":
      "Offer multiple payment options (Shop Pay, Klarna, crypto)",
    "Display trust badges during checkout": "Display trust badges during checkout",
    "Add a progress indicator (e.g., 'Step 1 of 3')": "Add a progress indicator (e.g., 'Step 1 of 3')",
    "Pre-fill saved customer data (for returning users)": "Pre-fill saved customer data (for returning users)",
    "Hide unnecessary fields (e.g., company name)": "Hide unnecessary fields (e.g., company name)",
    "Add a 'Save Cart' option for later": "Add a 'Save Cart' option for later",
    "Test free shipping thresholds": "Test free shipping thresholds",
    "Post-purchase upsell integration": "Post-purchase upsell integration",
    "Mobile-optimized checkout buttons": "Mobile-optimized checkout buttons",
    "A/B test checkout button labels ('Pay Now' vs. 'Complete Order')":
      "A/B test checkout button labels ('Pay Now' vs. 'Complete Order')",
    "Monthly checkout abandonment analysis": "Monthly checkout abandonment analysis",
    "Loyalty Program Setup": "Loyalty Program Setup",
    "Boost retention and lifetime value (CLV).": "Boost retention and lifetime value (CLV).",
    "30%+ higher repeat purchase rates.": "30%+ higher repeat purchase rates.",
    "Automated win-back emails for inactive users": "Automated win-back emails for inactive users",
    "Loyalty-linked exclusive content (e.g., tutorials)": "Loyalty-linked exclusive content (e.g., tutorials)",
    "SMS loyalty alerts (e.g., 'Redeem your 500 points!')": "SMS loyalty alerts (e.g., 'Redeem your 500 points!')",
    "Integrate loyalty tiers with discounts": "Integrate loyalty tiers with discounts",
    "A/B test reward structures": "A/B test reward structures",
    "Post-purchase loyalty signup prompts": "Post-purchase loyalty signup prompts",
    "NFT-based loyalty passes (for Web3 integration)": "NFT-based loyalty passes (for Web3 integration)",
    "Quarterly program refreshes (new rewards, challenges)":
      "Quarterly program refreshes (new rewards, challenges)",
    "CLV tracking and ROI reporting": "CLV tracking and ROI reporting",
    "Tiered loyalty programs (Silver/Gold/Platinum)": "Tiered loyalty programs (Silver/Gold/Platinum)",
    "Points for purchases, reviews, and referrals": "Points for purchases, reviews, and referrals",
    "VIP perks (early access to sales, birthday discounts)":
      "VIP perks (early access to sales, birthday discounts)",
    "Customizable rewards (products, discounts, cashback)": "Customizable rewards (products, discounts, cashback)",
    "Referral campaigns with double-sided rewards": "Referral campaigns with double-sided rewards",
    "Gamification (spin-to-win, points milestones)": "Gamification (spin-to-win, points milestones)",
    "SEO-Driven Product Listings": "SEO-Driven Product Listings",
    "Drive organic traffic to high-converting pages.": "Drive organic traffic to high-converting pages.",
    "20-30% more organic traffic.": "20-30% more organic traffic.",
    "Optimize product titles with keywords (e.g., 'Vitamin C Serum for Glowing Skin')":
      "Optimize product titles with keywords (e.g., 'Vitamin C Serum for Glowing Skin')",
    "Write unique, keyword-rich meta descriptions": "Write unique, keyword-rich meta descriptions",
    "Add schema markup for product ratings/price": "Add schema markup for product ratings/price",
    "Fix broken links and redirects": "Fix broken links and redirects",
    "Optimize image alt text (e.g., 'Organic Argan Oil Shampoo')":
      "Optimize image alt text (e.g., 'Organic Argan Oil Shampoo')",
    "Internal linking between related products": "Internal linking between related products",
    "Target low-competition long-tail keywords": "Target low-competition long-tail keywords",
    "Create SEO-friendly collection pages": "Create SEO-friendly collection pages",
    "Publish blog content around product FAQs": "Publish blog content around product FAQs",
    "Optimize URL slugs (short, keyword-focused)": "Optimize URL slugs (short, keyword-focused)",
    "Submit sitemap to Google Search Console": "Submit sitemap to Google Search Console",
    "Fix duplicate content issues": "Fix duplicate content issues",
    "Add FAQ schema to product pages": "Add FAQ schema to product pages",
    "Optimize breadcrumb navigation": "Optimize breadcrumb navigation",
    "Monthly keyword ranking tracking": "Monthly keyword ranking tracking",
    "Seasonal Campaigns": "Seasonal Campaigns",
    "Maximize revenue during peak periods.": "Maximize revenue during peak periods.",
    "2-3x higher revenue during peak seasons.": "2-3x higher revenue during peak seasons.",
    "Black Friday/Cyber Monday landing pages": "Black Friday/Cyber Monday landing pages",
    "Holiday gift guides with curated bundles": "Holiday gift guides with curated bundles",
    "Countdown timers for limited-time offers": "Countdown timers for limited-time offers",
    "Themed email/SMS campaigns (e.g., '12 Days of Deals')":
      "Themed email/SMS campaigns (e.g., '12 Days of Deals')",
    "Exclusive VIP early access to sales": "Exclusive VIP early access to sales",
    "Create urgency with 'Last Chance' popups": "Create urgency with 'Last Chance' popups",
    "Partner with influencers for holiday unboxings": "Partner with influencers for holiday unboxings",
    "Seasonal product launches (e.g., 'Summer Skincare Kit')":
      "Seasonal product launches (e.g., 'Summer Skincare Kit')",
    "Geo-targeted campaigns for regional holidays": "Geo-targeted campaigns for regional holidays",
    "Post-holiday 'B-Stock' clearance sales": "Post-holiday 'B-Stock' clearance sales",
    "Valentine's Day/Christmas-specific bundles": "Valentine's Day/Christmas-specific bundles",
    "Integrate holiday-themed trust elements (e.g., 'Gift Guarantee')":
      "Integrate holiday-themed trust elements (e.g., 'Gift Guarantee')",
    "A/B test holiday discount structures (% vs. $ off)": "A/B test holiday discount structures (% vs. $ off)",
    "Retarget holiday visitors with abandoned cart offers": "Retarget holiday visitors with abandoned cart offers",
    "Post-campaign analysis to refine future strategies": "Post-campaign analysis to refine future strategies",
    "7 days": "7 days",
    "4 days": "4 days",
    "10 days": "10 days",
    "14 days": "14 days",
    "Purchase plan": "Purchase plan",
    "View details": "View details",
    "Contact us": "Contact us",
    Close: "Close",
    "Scale your SEO with flexible plans": "Scale your SEO with flexible plans",
    "Choose your custom SEO package": "Choose your custom SEO package",
    "Google search console set-up": "Google search console set-up",
    "Google Search Console is key for a Shopify store, offering insights into how your site appears in search results and helping fix visibility issues. It tracks keyword performance, indexing, and site errors to boost SEO and traffic.":
      "Google Search Console is key for a Shopify store, offering insights into how your site appears in search results and helping fix visibility issues. It tracks keyword performance, indexing, and site errors to boost SEO and traffic.",
    "Blog addition in ecommerce store": "Blog addition in ecommerce store",
    "Adding a blog to your Shopify store helps improve SEO by targeting relevant keywords and driving organic traffic. It also builds trust and engagement with customers by providing valuable content related to your products or niche.":
      "Adding a blog to your Shopify store helps improve SEO by targeting relevant keywords and driving organic traffic. It also builds trust and engagement with customers by providing valuable content related to your products or niche.",
    "Google Tag Manager/Google Analytics Set Up": "Google Tag Manager/Google Analytics Set Up",
    "Google Tag Manager and Google Analytics setup is crucial for Shopify stores to accurately track customer behavior and sales performance. It helps store owners make data-driven decisions to boost conversions and optimize marketing efforts.":
      "Google Tag Manager and Google Analytics setup is crucial for Shopify stores to accurately track customer behavior and sales performance. It helps store owners make data-driven decisions to boost conversions and optimize marketing efforts.",
    "One time on-page SEO ": "One time on-page SEO ",
    "Keyword research": "Keyword research",
    "Keyword Research is crucial in eCommerce because it helps identify high-converting search terms your potential customers use when shopping online. This drives targeted traffic to your product pages, increasing visibility and sales.":
      "Keyword Research is crucial in eCommerce because it helps identify high-converting search terms your potential customers use when shopping online. This drives targeted traffic to your product pages, increasing visibility and sales.",
    "Google my business Page / local boost": "Google my business Page / local boost",
    "A Google My Business page boosts local eCommerce sales by increasing your visibility in local search results and Google Maps. It helps build trust with potential customers through reviews, business details, and easy access to contact or visit your store.":
      "A Google My Business page boosts local eCommerce sales by increasing your visibility in local search results and Google Maps. It helps build trust with potential customers through reviews, business details, and easy access to contact or visit your store.",
    "Our support team will contact you shortly to proceed further.":
      "Our support team will contact you shortly to proceed further.",
    "On-page SEO is crucial for eCommerce as it helps improve search engine rankings, driving more organic traffic to your site. It also enhances user experience, leading to higher conversion rates and customer satisfaction.":
      "On-page SEO is crucial for eCommerce as it helps improve search engine rankings, driving more organic traffic to your site. It also enhances user experience, leading to higher conversion rates and customer satisfaction.",
    "We will prepare the keyword research report in excel format where you will get multiple sheets with proper research of highly searched volume keywords. We will analyze your category pages, sub-category pages and product level pages keywords.":
      "We will prepare the keyword research report in excel format where you will get multiple sheets with proper research of highly searched volume keywords. We will analyze your category pages, sub-category pages and product level pages keywords.",
    "Keyword classification": "Keyword classification",
    "Transactional Keywords": "Transactional Keywords",
    "Informational Keywords": "Informational Keywords",
    "Commercial Keywords": "Commercial Keywords",
    "Navigation Keywords": "Navigation Keywords",
    "Branded Keyword": "Branded Keyword",
    "Intent-Based Keywords": "Intent-Based Keywords",
    "What's included": "What's included",
    "1. Niche & Competitor Analysis": "1. Niche & Competitor Analysis",
    "Identify top 5 competitors": "Identify top 5 competitors",
    "Analyze niche difficulty": "Analyze niche difficulty",
    "2. Primary Keyword Set - Collection": "2. Primary Keyword Set - Collection",
    "up to 10 collection and sub collection keywords": "up to 10 collection and sub collection keywords",
    "Buyer-intent & SEO-friendly": "Buyer-intent & SEO-friendly",
    "3. Long-Tail Keyword Suggestions - Product": "3. Long-Tail Keyword Suggestions - Product",
    "up to 50 products, long-tail keywords for specific product pages":
      "up to 50 products, long-tail keywords for specific product pages",
    "Includes search volume & keyword difficulty, intent/classification, CPC, traffic, URL, competition and SERP feature":
      "Includes search volume & keyword difficulty, intent/classification, CPC, traffic, URL, competition and SERP feature",
    "4. Delivery in Google Sheet": "4. Delivery in Google Sheet",
    "Clear, organized format": "Clear, organized format",
    "We will create your GMB page if not created and will optimize as per market standard which includes local keyword research also. Weekly 1 optimized GMB update will be there on any random products":
      "We will create your GMB page if not created and will optimize as per market standard which includes local keyword research also. Weekly 1 optimized GMB update will be there on any random products",
    "1. GMB Profile Setup or Audit": "1. GMB Profile Setup or Audit",
    "Creation or audit of existing listing": "Creation or audit of existing listing",
    "Business name, category, description, services, hours, etc.":
      "Business name, category, description, services, hours, etc.",
    "2. Basic Optimization": "2. Basic Optimization",
    "Add logo, cover photo, and 3-5 high-quality images and videos.":
      "Add logo, cover photo, and 3-5 high-quality images and videos.",
    "Set service areas & attributes": "Set service areas & attributes",
    "Ensure NAP consistency (Name, Address, Phone)": "Ensure NAP consistency (Name, Address, Phone)",
    "Link Social Profiles.": "Link Social Profiles.",
    "3. Keyword-Rich Business Description": "3. Keyword-Rich Business Description",
    "Perform local keyword research (10-20 keywords)": "Perform local keyword research (10-20 keywords)",
    "SEO-optimized description (up to 750 characters)": "SEO-optimized description (up to 750 characters)",
    "4. Initial Posts (2 Posts)": "4. Initial Posts (2 Posts)",
    "Google updates or promotional post": "Google updates or promotional post",
    "Includes image + call-to-action (CTA)": "Includes image + call-to-action (CTA)",
    "5. 1 Week Support": "5. 1 Week Support",
    "Minor edits or Q&A via chat/email after delivery": "Minor edits or Q&A via chat/email after delivery",
    "We will set up and integrate Google Search Console, addressing all potential indexing issues such as 404 errors, soft 404s, crawled but not indexed, discovered but not indexed, merchant listing problems, video indexing errors, and blocks from robots.txt. Each issue will be thoroughly analysed, and necessary actions will be taken as needed. Additionally, we will continuously monitor the sitemap within the Search Console.":
      "We will set up and integrate Google Search Console, addressing all potential indexing issues such as 404 errors, soft 404s, crawled but not indexed, discovered but not indexed, merchant listing problems, video indexing errors, and blocks from robots.txt. Each issue will be thoroughly analysed, and necessary actions will be taken as needed. Additionally, we will continuously monitor the sitemap within the Search Console.",
    "1. GSC Setup & Verification": "1. GSC Setup & Verification",
    "Proper integration with your eCommerce site (Shopify, WooCommerce, etc.)":
      "Proper integration with your eCommerce site (Shopify, WooCommerce, etc.)",
    "Verify ownership via DNS, HTML tag, or GA/GTAG": "Verify ownership via DNS, HTML tag, or GA/GTAG",
    "2. Basic Site Performance Overview": "2. Basic Site Performance Overview",
    "Traffic performance (clicks, impressions, CTR)": "Traffic performance (clicks, impressions, CTR)",
    "Top-performing keywords & pages": "Top-performing keywords & pages",
    "3. Index Coverage Check": "3. Index Coverage Check",
    "Review crawl issues, indexing errors, and submit sitemap":
      "Review crawl issues, indexing errors, and submit sitemap",
    "Fix or highlight critical issues (e.g. 404s, blocked pages)":
      "Fix or highlight critical issues (e.g. 404s, blocked pages)",
    "4. Mobile Usability Check": "4. Mobile Usability Check",
    "Detect and report any mobile issues affecting rankings":
      "Detect and report any mobile issues affecting rankings",
    "5. Basic Reporting + Recommendations": "5. Basic Reporting + Recommendations",
    "Simple PDF/Excel report with": "Simple PDF/Excel report with",
    "Top 10 queries": "Top 10 queries",
    "Top 5 underperforming product pages": "Top 5 underperforming product pages",
    "Quick-win keyword opportunities": "Quick-win keyword opportunities",
    "6. 1 Week of Follow-Up Support": "6. 1 Week of Follow-Up Support",
    "Minor help or clarifications post-delivery": "Minor help or clarifications post-delivery",
    "If predefined keywords are available, we will research trending online topics related to those product-specific terms. Otherwise, we’ll first identify 5–10 strong transactional or informational keywords based on the products, then analyze top trending blogs. Based on this, we will create four keyword- and trend-driven blog posts each month.":
      "If predefined keywords are available, we will research trending online topics related to those product-specific terms. Otherwise, we’ll first identify 5–10 strong transactional or informational keywords based on the products, then analyze top trending blogs. Based on this, we will create four keyword- and trend-driven blog posts each month.",
    "1. Blog Setup & Integration": "1. Blog Setup & Integration",
    "Enable blog feature on your eCommerce platform (Shopify, WooCommerce, etc.)":
      "Enable blog feature on your eCommerce platform (Shopify, WooCommerce, etc.)",
    "Basic layout setup using store’s existing theme/design":
      "Basic layout setup using store’s existing theme/design",
    "Add blog to menu/navigation if requested": "Add blog to menu/navigation if requested",
    "2. Internal Linking": "2. Internal Linking",
    "Link blog content to 1–2 relevant product/category pages":
      "Link blog content to 1–2 relevant product/category pages",
    "3. Basic SEO Settings": "3. Basic SEO Settings",
    "Slug optimization, meta title, and schema (if platform allows)":
      "Slug optimization, meta title, and schema (if platform allows)",
    "4. Four SEO-Friendly Blog Posts (800–1000 words)": "4. Four SEO-Friendly Blog Posts (800–1000 words)",
    'Topic tailored to your niche/products (e.g. "Top 5 Benefits of Using [Product]")':
      'Topic tailored to your niche/products (e.g. "Top 5 Benefits of Using [Product]")',
    "Includes:": "Includes:",
    "Keyword optimization": "Keyword optimization",
    "Engaging headline": "Engaging headline",
    "Meta Title/Description": "Meta Title/Description",
    "1–2 free images": "1–2 free images",
    "5. Quick Guide for Future Posts": "5. Quick Guide for Future Posts",
    "A simple guide or template to help you publish more posts yourself":
      "A simple guide or template to help you publish more posts yourself",
    "1. Google Analytics 4 Setup": "1. Google Analytics 4 Setup",
    "Create or connect GA4 property": "Create or connect GA4 property",
    "Link GA4 to GTM": "Link GA4 to GTM",
    "Configure basic data stream settings": "Configure basic data stream settings",
    "2. Standard Event Tracking (Basic Ecom)": "2. Standard Event Tracking (Basic Ecom)",
    "Pageview tracking": "Pageview tracking",
    "Button click or form submission (e.g., Add to Cart, Buy Now – 1 custom event)":
      "Button click or form submission (e.g., Add to Cart, Buy Now – 1 custom event)",
    "3. GTM Debugging & Preview": "3. GTM Debugging & Preview",
    "Test implementation using GTM Preview mode": "Test implementation using GTM Preview mode",
    "Ensure tags & triggers are working properly": "Ensure tags & triggers are working properly",
    "4. GA4 + GTM Documentation": "4. GA4 + GTM Documentation",
    "Simple walkthrough doc or Loom video on how to check data & manage tags":
      "Simple walkthrough doc or Loom video on how to check data & manage tags",
    "5. Seven Days Support": "5. Seven Days Support",
    "For small adjustments or follow-up questions": "For small adjustments or follow-up questions",
    "Shopify SEO Audit": "Shopify SEO Audit",
    "Review of Shopify store SEO settings": "Review of Shopify store SEO settings",
    "Identify indexing, speed, and structural issues": "Identify indexing, speed, and structural issues",
    "Check for duplicate content, missing metadata, or app-related SEO conflicts":
      "Check for duplicate content, missing metadata, or app-related SEO conflicts",
    "Shopify-Specific Settings": "Shopify-Specific Settings",
    "1. Shopify SEO Audit": "2. Shopify SEO Audit",
    "2. Shopify-Specific Settings": "2. Shopify-Specific Settings",
    "Navigation and internal link structure audit": "Navigation and internal link structure audit",
    "App recommendations for SEO (e.g., Schema, Image Optimizers)":
      "App recommendations for SEO (e.g., Schema, Image Optimizers)",
    "URL structure recommendations (for collections, products, blogs)":
      "URL structure recommendations (for collections, products, blogs)",
    "Contact form set up": "Contact form set up",
    "Google Tools Setup": "Google Tools Setup",
    "Google Analytics (GA4) setup": "Google Analytics (GA4) setup",
    "Google Search Console setup": "Google Search Console setup",
    "Google Business Profile (if applicable)": "Google Business Profile (if applicable)",
    "Technical SEO Fixes": "Technical SEO Fixes",
    "3. Google Tools Setup": "3. Google Tools Setup",
    "4. Technical SEO fixes": "4. Technical SEO fixes",
    "Speed optimization (basic improvements or recommendations)":
      "Speed optimization (basic improvements or recommendations)",
    "Mobile-friendliness check": "Mobile-friendliness check",
    "XML sitemap & robots.txt optimization": "XML sitemap & robots.txt optimization",
    "Canonical tags setup": "Canonical tags setup",
    "Indexing & crawl issues resolution (Google Search Console)":
      "Indexing & crawl issues resolution (Google Search Console)",
    Includes: "Includes",
    "Schema with warnings": "Schema with warnings",
    "1 week": "1 week",
    delivery: "delivery",
    "3 days": "3 days",
    "2 week": "2 week",
    "30 days": "30 days",
    "3 week": "3 week",
    "Google analytics & tag manager setup": "Google analytics & tag manager setup",
    Index: "Index",
    Created: "Created",
    Install: "Install",
    "Discover more free apps": "Discover more free apps",
    disableButtonTooltip: "You cannot upgrade the monthly plan as you are on a yearly plan !",
    "Choose plan": "Choose plan",
    "Purchase Plan": "Purchase Plan",
    Continue: "Continue",
    "Image Optimization": "Image Optimization",
    "AI Metatags": "AI Metatags",
    "Grand Total": "Grand Total",
    "Metatags Edit": "Metatags Edit",
    Products: "Products",
    "Upgrade plan": "Upgrade plan",
    "Your product count is": "Your product count is",
    "so your suitable plan is": "so your suitable plan is",
    "Enjoy a": "Enjoy a",
    "lifetime discount": "lifetime discount",
    discountBanner:
      " Embrace a lifetime discount, securing perpetual savings and enhancing your experience with our premium products and services.",
    "Images for Optimization every year after trial period end":
      "Images for Optimization every year after trial period end",
    "AI Meta Tags Credit for every year after trial period end":
      "AI Meta Tags Credit for every year after trial period end",
    "Images for Optimization every month after trial period end":
      "Images for Optimization every month after trial period end",
    "AI Meta Tags Credit for every Month after trial period end":
      "AI Meta Tags Credit for every Month after trial period end",
    "Optimize your google page speed": "Optimize your google page speed",
    "50 Product Meta tags Optimize, Image alt": "50 Product Meta tags Optimize, Image alt",
    "Product Meta tags Optimize, Image alt": "Product Meta tags Optimize, Image alt",
    "AI ImageAltText Credit for every year after trial period end":
      "AI ImageAltText Credit for every year after trial period end",
    "25 AI ImageAltText Credit": "25 AI ImageAltText Credit",
    "AI ImageAltText Credit for every Month after trial period end":
      "AI ImageAltText Credit for every Month after trial period end",
    "Contact Bar": "Contact Bar",
    "Add To Cart Bar": "Add To Cart Bar",
    "Multiple Position": "Multiple Position",
    lowMsgStart: "This offer is specially designed for you, as you've just started your Shopify store",
    lowMsgMiddle: "Our",
    lowMsgEnd: "discount is our way of supporting you during these challenging yet exciting times.",
    mediumMsgStart: "This offer is specially designed for you, as you've started your Shopify store",
    mediumMsgMiddle: "Our",
    mediumMsgEnd: "discount is our way of supporting you during these challenging yet exciting times.",
    importantMsgStart: "This offer is specially designed for you, as you've started your Shopify store",
    importantMsgMiddle: "Our",
    importantMsgEnd: "discount is our way of supporting you during these challenging yet exciting times.",
    veryImportantMsgStart: "This offer is specially designed for you, as you've opened your Shopify store",
    veryImportantMsgMiddle: "You are a very important and mature merchant to us. Our",
    veryImportantMsgEnd: "discount is to show how much you mean to us.",
    generalMsg:
      "Our Shopify app is tailored to meet the needs of established businesses like yours. It's designed to handle high volumes and complex operations seamlessly. ",
    lowTitleStart: "Special Support for New Entrepreneurs:",
    lowTitleEnd: "Discount as you just started",
    mediumTitleStart: "Special Support for Entrepreneurs:",
    mediumTitleEnd: "Discount as you started",
    importantTitleStart: "Special Support for Entrepreneurs:",
    importantTitleEnd: "Discount as you started",
    veryImportantTitleStart: "Congratulations on being",
    veryImportantTitleEnd: "in Shopify",
    month: "month",
    "year and": "year and",
    ago: "ago",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )": "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )",
    "Monthly AI AltText Credit": "Monthly AI AltText Credit",
    "Yearly AI AltText Credit": "Yearly AI AltText Credit",
    "Purchase AI AltText Credit": "Purchase AI AltText Credit",
    "ImageAltText Credit": "ImageAltText Credit",
    "Your credits are finished; please upgrade your plan.": "Your credits are finished; please upgrade your plan.",
    "Your credits are finished; you can buy more credits from here.":
      "Your credits are finished; you can buy more credits from here.",
    "This offer expire in": "This offer expire in",
    "Hurry Up!": "Hurry Up!",
    Current: "Current",
    "Discount applied": "Discount applied",
    "trial left": "trial left",
    "info banner":
      "When you click the Scan Homepage Image button, our app will only scan the homepage image.To optimize this image, please click Optimize button manually",
    "Optimize Images": "Optimize Images",
    image: "image",
    images: "images",
    Filename: "Filename",
    Images: "Images",
    Setting: "Setting",
    "Saved(in %)": "Saved(in %)",
    Action: "Action",
    "Product Image": "Product Image",
    "product image": "product image",
    gif: "gif",
    Homepage: "Homepage",
    "Manage Announcement": "Manage Announcement",
    "No Announcements Found": "No Announcements Found",
    Position: "Position",
    "Campaign Title": "Campaign Title",
    Visible: "Visible",
    Invisible: "Invisible",
    Views: "Views",
    Clicks: "Clicks",
    Submits: "Submits",
    "Above Add to cart Button": "Above Add to cart Button",
    "Below Add to cart Button": "Below Add to cart Button",
    Targeting: "Targeting",
    "Rotating Animation Setting": "Rotating Animation Setting",
    "Marquee Animation Setting": "Marquee Animation Setting",
    "Show to visitors coming form then specific website": "Show to visitors coming form then specific website",
    "Add your website URL": "Add your website URL",
    "Banner Display Start Time": "Banner Display Start Time",
    "Banner Display End Time": "Banner Display End Time",
    "Create Campaign": "Create Campaign",
    "Select Announcement Bar": "Select Announcement Bar",
    "Please select template.": "Please select template.",
    Previous: "Previous",
    "Promotion bar": "Promotion bar",
    "Add To Cart": "Add To Cart",
    Embeded: "Embeded",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Alert customers of upcoming sales, offers, or set inventory alerts.",
    "Increase your order value by using or Free Shipping Bar.":
      "Increase your order value by using or Free Shipping Bar.",
    "Conveniently add items to your cart with a single click!":
      "Conveniently add items to your cart with a single click!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Select to subscribe and receive special discounts directly to your inbox",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.",
    Select: "Select",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Include Utm",
    "Exclude Utm": "Exclude Utm",
    "Campaign Design": "Campaign Design",
    "Background Setting": "Background Setting",
    "Target Setting": "Target Setting",
    Scheduling: "Scheduling",
    Rotating: "Rotating",
    Marquee: "Marquee",
    "Repeat Timer Date": "Repeat Timer Date",
    "Select Repeat Time": "Select Repeat Time",
    "Repeated Hours": "Repeated Hours",
    Border: "Border",
    Bashed: "Bashed",
    "Multi Rotating": "Multi Rotating",
    Contacts: "Contacts",
    Email: "Email",
    "First Name": "First Name",
    "Last Name": "Last Name",
    Phone: "Phone",
    "You have unsaved changes": "You have unsaved changes",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Your campaign has unsaved changes. Changes will be lost if you leave without saving.",
    "Leave widthout saving": "Leave widthout saving",
    "Save Changes": "Save Changes",
    Announcement: "Announcement",
    Feedback: "Feedback",
    "Recipe Instructions": "Recipe Instructions",
    "Visit Help Center": "Visit Help Center",
    "Schedule Meeting": "Schedule Meeting",
    "Setup guide": "Setup guide",
    "Use this personalized guide to get your store up and running":
      "Use this personalized guide to get your store up and running",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here",
    "Enable our app": "Enable our app",
    "Learn more": "Learn more",
    "Skip it": "Skip it",
    steps: "steps",
    minutes: "minutes",
    "Mark as done": "Mark as done",
    "Mark as not done": "Mark not as done",
    "You have completed all the steps": "You have completed all the steps",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Activate and analyze your site's speed, to rank your store higher on search results.",
    "Google Page Speed Optimization": "Google Page Speed Optimization",
    "Activate Google Page Speed": "Activate Google Page Speed",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement",
    "Enable Speed Analysis": "Enable Speed Analysis",
    "Review Speed Analysis Report": "Review Speed Analysis Report",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.",
    "Go to Reports": "Go to Reports",
    Hello: "Hello",
    "Let's get your store ready for success": "Let's get your store ready for success",
    "Finish later": "Finish later",
    "Continue onboarding": "Continue onboarding",
    "Check image optimization features": "Check image optimization features",
    "Explore Optimization Features": "Explore Optimization Features",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.",
    "Go to Image Optimization": "Go to Image Optimization",
    "Automate Your Image Workflow": "Automate Your Image Workflow",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.",
    "Go to Automation": "Go to Automation",
    "Execute a Bulk Optimization": "Execute a Bulk Optimization",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.",
    "Go to bulk operations": "Go to bulk operations",
    "Broken Links Management": "Broken Links Management",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automate the detection and repair of broken links to enhance user experience and SEO rankings.",
    "Review Detected Broken Links": "Review Detected Broken Links",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.",
    "View Broken Links": "View Broken Links",
    "Address Broken Links": "Address Broken Links",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.",
    "Resolve Broken Links": "Resolve Broken Links",
    "Automate for Efficiency": "Automate for Efficiency",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.",
    "Enable Automation": "Enable Automation",
    "Meta Tags Management": "Meta Tags Management",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.",
    "Explore Meta Tag Options": "Explore Meta Tag Options",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Get acquainted with the various meta tag editing and automation options available for individual products and pages.",
    "Explore Meta Tags": "Explore Meta Tags",
    "Edit and Optimize": "Edit and Optimize",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.",
    "Start Editing": "Start Editing",
    "Automate for Consistency": "Automate for Consistency",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.",
    "Set Automation": "Set Automation",
    "Schema Markup": "Schema Markup",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.",
    "Learn About Schema Options": "Learn About Schema Options",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.",
    "Explore Schema Types": "Explore Schema Types",
    "Activate Key Schemas": "Activate Key Schemas",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.",
    "Go to Schemas": "Go to Schemas",
    "Customize Schema Details": "Customize Schema Details",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Customize the settings of each schema type to accurately represent your business or products in search results.",
    "Test and Validate Schemas": "Test and Validate Schemas",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.",
    "Test Schemas": "Test Schemas",
    "Add Breadcrumbs": "Add Breadcrumbs",
    "Add Breadcrumbs to your store": "Add Breadcrumbs to your store",
    "To get better user experience you need to add breadcrumbs to your store.":
      "To get better user experience you need to add breadcrumbs to your store.",
    "How to add breadcrumbs": "How to add breadcrumbs",
    "Understand how to add and configure breadcrumbs in your store.":
      "Understand how to add and configure breadcrumbs in your store.",
    "Google search console": "Google search console",
    "Connect google search console to sync it with our app.":
      "Connect google search console to sync it with our app.",
    "How to connect GSC.": "How to connect GSC.",
    "Understand how to connect and use google search console in our app.":
      "Understand how to connect and use google search console in our app.",
    "Go to GSC": "Go to GSC",
    "Go to Breadcrumbs Design": "Go to Breadcrumbs Design",
    "Start Onboarding": "Start Onboarding",
    "Go to Homepage": "Go to Homepage",
    "Go to Onboarding": "Go to Onboarding",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.",
    "Please enable our app extension.": "Please enable our app extension.",
    "Generate Meta tags": "Generate Meta tags",
    "Test description a litle bit longer that title": "Test description a litle bit longer that title",
    "Suggested for you": "Suggested for you",
    "Enable Google page speed": "Enable Google page speed",
    "Connect GSC": "Connect GSC",
    "Enable Image Optimize Automation": "Enable Image Optimize Automation",
    "Automate Meta tags": "Automate Meta tags",
    "Automate Broken Links": "Automate Broken Links",
    "Enhance SEO with automatically generated meta tags.": "Enhance SEO with automatically generated meta tags.",
    "Improve website performance by optimizing images.": "Improve website performance by optimizing images.",
    "Boost website speed by enabling Google Page Speed.": "Boost website speed by enabling Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Enhance search visibility by connecting to Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Streamline image optimization with automated processes.",
    "Improve SEO by automating the generation of meta tags.":
      "Improve SEO by automating the generation of meta tags.",
    "Improve UX with automated detect and handle, broken links.":
      "Improve UX with automated detect and handle, broken links.",
    "Learn About Add Announcement": "Learn About Add Announcement",
    "Skip And Add Announcement": "Skip And Add Announcement",
    "Learn more about": "Learn more about",
    "Add Announcement": "Add Announcement",
    "Announcement Bar": "Announcement Bar",
    "Rate us!": "Rate us!",
    "How would you Love this app?": "How would you Love this app?",
    "Enter Your Feedback Here": "Enter Your Feedback Here",
    "Leave Us a Review !!": "Leave Us a Review !!",
    "If you like our app features then please leave us a review !!":
      "If you like our app features then please leave us a review !!",
    "If you like our free features then please leave us a review !!":
      "If you like our free features then please leave us a review !!",
    "Update Successfully": "Update Successfully",
    "Uninstall App": "Uninstall App",
    "Contact Our Support": "Contact Our Support",
    "Leave a message": "Leave a message",
    "Please Choose a UnInstallation Reason": "Please Choose a UnInstallation Reason",
    "Are you facing any issues understanding the features of our app?":
      "Are you facing any issues understanding the features of our app?",
    "Please Choose at least one reason": "Please Choose at least one reason",
    "Thank You For Reaching Out": "Thank You For Reaching Out",
    "Contact Support": "Contact Support",
    "Get Help from Our Support Team": "Get Help from Our Support Team",
    "Select a reason": "Select a reason",
    "Not getting how to use or setup": "Not getting how to use or setup",
    "Poor customer support": "Poor customer support",
    "Performance issues": "Performance issues",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.",
    "Our support team is partially available according to your time zone from ":
      "Our support team is partially available according to your time zone from ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Our support team is currently unavailable and will be available according to your time zone from ",
    to: "to",
    "Did not meet my expectations": "Did not meet my expectations",
    "Feature Limitations": "Feature Limitations",
    "Banner doesn't set in my app": "Banner doesn't set in my app",
    "Banner is not show properly": "Banner is not show properly",
    "Confusing Set Multi Position and Multi Animation": "Confusing Set Multi Position and Multi Animation",
    "Sync Profile": "Sync Profile",
  },
};

let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
