import modifyData from "../Language/es.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Activado",
    Disabled: "Desactivado",
    "Embed is currently disabled": "Insertar está actualmente deshabilitado",
    "Enable App": "Habilitar aplicación",
    "1. Click on Enable App.": "1. Haga clic en Habilitar aplicación.",
    "Well done!! you have successfully enable our app.":
      "¡¡Bien hecho!! Ha habilitado con éxito nuestra aplicación.",
    "2. Enable": "2. Habilitar",
    "App Embed as shown in image and save setting.":
      "Incruste la aplicación como se muestra en la imagen y guarde la configuración.",
    "Multi Announcement Bar": "Barra de anuncios múltiples",
    "Click on the Enable Now button to enable it.": "Haga clic en el botón Habilitar ahora para habilitarlo.",
    "Enable Announcement Bar to get started": "Habilite la barra de anuncios para comenzar",
    "Enable Now": "Habilitado ahora",
    "Sync Status": "Estado de sincronización",
    Done: "Hecho",
    No: "No",
    Found: "Encontró",
    Add: "Agregar",
    Search: "Buscar",
    Showing: "Demostración",
    of: "de",
    "results, at most": "resultados, como máximo",
    "per page": "por página",
    "Oops! Something went wrong.": "¡Ups! Algo salió mal.",
    "Let's try that again, please refresh the page.": "Intentemos eso nuevamente, actualice la página.",
    "If you're still stuck, contact us by chat support or":
      "Si todavía estás atascado, contáctanos por chat de soporte o",
    "support@webrexstudio.com": "soporte@webrexstudio.com",
    "so we can help!": "para que podamos ayudar!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Seleccione cualquiera de las 3 funciones que desee configurar como de alta prioridad o como las que más le interesen",
    "Add ": "Agregar ",
    "These is premium feature": "Esta es una característica premium",
    "Go to pricing": "Ir a precios",
    Save: "Ahorrar",
    Minimum: "Mínimo",
    Maximum: "Máximo",
    "images are required": "Se requieren imágenes",
    and: "y",
    "images are allowed": "se permiten imágenes",
    Disconnect: "Desconectar",
    "Sign In with Google": "Inicia sesión con Google",
    "Oops! Something went wrong. Admin token is malformed":
      "¡Ups! Algo salió mal. El token de administrador tiene un formato incorrecto",
    "If you're still stuck, contact": "Si todavía estás atascado, contacta",
    Premium: "De primera calidad",
    Unlock: "desbloquear",
    "Unlock advanced features!": "¡Desbloquea funciones avanzadas!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Reservados todos los derechos.",
    "Privacy Policy": "política de privacidad",
    "Terms of Service": "Términos de servicio",
    "Go to Shopify App": "Ir a la aplicación Shopify",
    "Review Us": "Revisanos",
    Cancel: "Cancelar",
    "Review Popup Show": "Revisar la ventana emergente",
    "click on review us": "haga clic en revisarnos",
    "Note: Feel free to leave a star rating without writing a review!":
      "Nota: ¡Siéntete libre de dejar una calificación de estrellas sin escribir una reseña!",
    Help: "Ayuda",
    "Help Button Click": "Haga clic en el botón Ayuda",
    Confirm: "Confirmar",
    On: "En",
    Off: "Apagado",
    Price: "Precio",
    Settings: "Ajustes",
    Animation: "Animación",
    "My Profile": "Mi perfil",
    "My Subscription": "Mi suscripción",
    "Store Name": "Nombre de la tienda",
    "Store URL": "URL de la tienda",
    "Email ID": "Identificación de correo",
    "Phone Number": "Número de teléfono",
    Country: "País",
    Currency: "Divisa",
    "Subscription Name": "Nombre de suscripción",
    "Select language": "Seleccione el idioma",
    "Announcement setting": "Configuración de anuncios",
    "Animation setting": "Configuración de animación",
    Selector: "Selector",
    "Save Setting": "Guardar configuración",
    "My Announcements": "Mis anuncios",
    "Add bar": "Agregar barra",
    Number: "Número",
    Title: "Título",
    "Create At": "Crear en",
    "Slide Activation": "Activación de diapositivas",
    Status: "Estado",
    Actions: "Comportamiento",
    "Save order": "Guardar pedido",
    "Reorder Slides": "Reordenar diapositivas",
    position: "posición",
    Top: "Arriba",
    "Sticky Top": "Parte superior adhesiva",
    "Bottom Fix": "Arreglo inferior",
    "Custom Position": "Posición personalizada",
    "Custom Position *Add Class or id of Selected Element.":
      "Posición personalizada *Agregar clase o identificación del elemento seleccionado.",
    "Bar Padding (px)": "Relleno de barra (px)",
    "Add Remove Button": "Agregar botón Quitar",
    "Choose icon color": "Elige el color del icono",
    "Custom css": "CSS personalizado",
    fadeIn: "fundirse",
    fadeInDown: "desvanecerse hacia abajo",
    fadeInDownBig: "desvanecerseInDownBig",
    fadeInLeft: "desvanecerse a la izquierda",
    fadeInLeftBig: "desvanecerse en la izquierda grande",
    fadeInUp: "desvanecerse",
    bounceInDown: "rebotar hacia abajo",
    bounceInLeft: "rebote en la izquierda",
    bounceInUp: "reboteenarriba",
    zoomIn: "acercarse",
    zoomInDown: "acercar hacia abajo",
    zoomInLeft: "zoomInIzquierda",
    slideInLeft: "deslizar hacia la izquierda",
    slideInUp: "deslizarse hacia arriba",
    slideInDown: "deslizarse hacia abajo",
    lightSpeedIn: "velocidad de luz en",
    rollIn: "llegar",
    flash: "destello",
    shake: "agitar",
    flip: "voltear",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "desvanecerse",
    fadeOutDown: "desvanecerseAbajo",
    fadeOutDownBig: "desvanecerseAfueraAbajoGrande",
    fadeOutRight: "desvanecerse hacia la derecha",
    fadeOutRightBig: "desvanecerseFueraDerechaGrande",
    fadeOutUp: "desvanecerse",
    bounceOutDown: "rebotarAbajo",
    bounceOutRight: "rebotar hacia la derecha",
    bounceOutUp: "rebotar hacia arriba",
    zoomOut: "disminuir el zoom",
    zoomOutDown: "alejar hacia abajo",
    zoomOutRight: "alejar hacia la derecha",
    slideOutRight: "deslizar hacia afuera a la derecha",
    slideOutUp: "deslizarse hacia arriba",
    slideOutDown: "deslizarse hacia afueraabajo",
    lightSpeedOut: "luzVelocidadOut",
    rollOut: "desenrollar",
    flipInY: "flipinY",
    "Text Animation": "Animación de texto",
    "Animation In": "Animación en",
    "Animation Out": "Animación fuera",
    "Auto play time (time in MS)": "Tiempo de reproducción automática (tiempo en MS)",
    "Animation time (time in MS)": "Tiempo de animación (tiempo en MS)",
    "Auto play time (time in Second)": "Tiempo de reproducción automática (tiempo en segundos)",
    "Background Color": "Color de fondo",
    "Space between slide(px)": "Espacio entre diapositivas (px)",
    visible: "visible",
    invisible: "invisible",
    "Promotional & Countdown Bar": "Barra promocional y de cuenta regresiva",
    "Free Shipping Bar": "Barra de envío gratis",
    "Add Slide": "Agregar diapositiva",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Solo 1 diapositiva es visible para el plan GRATUITO. Para activar Todas las diapositivas, suscríbase al Plan Premium.",
    Pricing: "Precios",
    "No Animation Found": "No se encontró ninguna animación",
    "No Preview, Add announcement Bar": "Sin vista previa, agregar barra de anuncios",
    "Update successfully": "Actualizar correctamente",
    Enable: "Permitir",
    Disable: "Desactivar",
    successfully: "exitosamente",
    "Delete successfully": "Eliminar exitosamente",
    "Copy successfully": "Copiar con éxito",
    "Reorder successfully": "Reordenar exitosamente",
    "Announcement Message": "Mensaje de anuncio",
    "Call to Action": "Llamada a la acción",
    Timer: "Temporizador",
    Style: "Estilo",
    "Background Type": "Tipo de fondo",
    "Mobile Style": "Estilo móvil",
    "Schedule Display": "Visualización de programación",
    Update: "Actualizar",
    "Change Font": "Cambiar fuente",
    "Font Family": "Familia tipográfica",
    "Font Style": "Estilo de fuente",
    Normal: "Normal",
    Italic: "Itálico",
    Oblique: "Oblicuo",
    Unset: "Desarmado",
    "Font Weight": "Peso de fuente",
    Bold: "Atrevido",
    "Message Font Size": "Tamaño de fuente del mensaje",
    "Message Text color": "Color del texto del mensaje",
    Type: "Tipo",
    None: "Ninguno",
    Button: "Botón",
    "Entire clickable bar": "Toda la barra en la que se puede hacer clic",
    "Add a simple link": "Añade un enlace sencillo",
    "Add coupon placement": "Agregar ubicación de cupón",
    "Linked Url": "URL vinculada",
    "Background Hover Color": "Color de fondo al pasar el cursor",
    "Text Hover Color": "Color de desplazamiento del texto",
    "Button Text": "Botón de texto",
    "Copied Text": "Texto copiado",
    "Open in the new tab": "Abrir en la nueva pestaña",
    URL: "URL",
    "Font Size": "Tamaño de fuente",
    "Button Radius": "Radio del botón",
    "Button color": "Color del boton",
    "Button Text color": "Color del texto del botón",
    "Button Hover Color": "Color del botón al pasar el cursor",
    "button Text HoverColor": "botón Texto HoverColor",
    "Timer Setting": "Configuración del temporizador",
    "Timer Type": "Tipo de temporizador",
    Date: "Fecha",
    "Select Reapt Time": "Seleccione el tiempo de recuperación",
    "repeated Hours": "Horas repetidas",
    "Normal Timer": "Temporizador normal",
    "Auto repeat timer": "Temporizador de repetición automática",
    Minute: "Minuto",
    Hour: "Hora",
    Day: "Día",
    "Remove Timer When Time End": "Eliminar el temporizador cuando finalice el tiempo",
    "Timer Separator": "Separador de temporizador",
    "Countdown Timer color": "Color del temporizador de cuenta regresiva",
    "Timer Text Size": "Tamaño del texto del temporizador",
    "Timer Text Setting": "Configuración de texto del temporizador",
    "Day Text": "Texto del día",
    "Hour Text": "Texto de hora",
    "Minute Text": "Texto minuto",
    "Second Text": "Segundo texto",
    "Background Image": "Imagen de fondo",
    "Gradient Background": "Fondo degradado",
    "Style & Color For Mobile": "Estilo y color para dispositivos móviles",
    "Timer Background": "Fondo del temporizador",
    "Timer Text Color": "Color del texto del temporizador",
    "Button Color": "Color del boton",
    "Button Text Color": "Color del texto del botón",
    "Button Text Hover Color": "Color del texto del botón al pasar el cursor",
    "Button Text Size": "Tamaño del texto del botón",
    "Always Display": "Mostrar siempre",
    "Only Display Within The Following Period Of Time": "Mostrar solo dentro del siguiente período de tiempo",
    "Start Time": "Hora de inicio",
    "End Time": "Hora de finalización",
    "Advance Setting": "Configuración avanzada",
    "Country Filter": "Filtro de país",
    Visibility: "Visibilidad",
    "Desktop and Mobile": "Escritorio y móvil",
    "Only Desktop": "Solo escritorio",
    "Only Mobile": "Sólo Móvil",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "ORIENTACIÓN POR FUENTE DE USUARIO (visitantes que provienen de un enlace que incluye el siguiente código UTM, por ejemplo.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Seleccionar página",
    Include: "Incluir",
    Exclude: "Excluir",
    "Currency Configuration": "Configuración de moneda",
    Message: "Mensaje",
    "Currency Symbol": "Símbolo de moneda",
    "Currency Position": "Posición de moneda",
    Before: "Antes",
    After: "Después",
    "money Class": "clase de dinero",
    "Initial Message": "Mensaje inicial",
    "Shipping Goal": "Objetivo de envío",
    "Progress Message": "Mensaje de progreso",
    "Progress goal": "Meta de progreso",
    "Goal Message": "Mensaje de objetivo",
    "Shipping Price Color": "Precio de envío Color",
    "Shipping Price Size": "Tamaño del precio de envío",
    "Shipping Font Weight": "Peso de fuente de envío",
    "* When user first time visit": "* Cuando el usuario visita por primera vez",
    "* When user add item to the cart e.g": "* Cuando el usuario agrega un artículo al carrito, por ejemplo:",
    "* When cart value is greater than": "* Cuando el valor del carrito es mayor que",
    "Show On Selected Countries": "Mostrar en países seleccionados",
    "Show On Selected Pages": "Mostrar en páginas seleccionadas",
    All: "Todo",
    Home: "Hogar",
    Cart: "Carro",
    Collection: "Recopilación",
    Product: "Producto",
    Custom: "Costumbre",
    Page: "Página",
    Blog: "Blog",
    "Url is required": "La URL es obligatoria",
    "Day Text is required": "Se requiere texto del día",
    "Hour Text is required": "Se requiere texto de hora",
    "Minute Text is required": "Se requiere texto minuto",
    "Second Text is required": "Se requiere el segundo texto",
    "Start Time is required": "Se requiere hora de inicio",
    "End Time is required": "Se requiere hora de finalización",
    "Created successfully": "Creado con éxito",
    "United States": "Estados Unidos",
    Canada: "Canadá",
    Australia: "Australia",
    "New Zealand": "Nueva Zelanda",
    Germany: "Alemania",
    India: "India",
    Afghanistan: "Afganistán",
    "land Islands": "islas terrestres",
    Albania: "Albania",
    Algeria: "Argelia",
    "American Samoa": "Samoa Americana",
    AndorrA: "AndorraA",
    Angola: "Angola",
    Anguilla: "Anguila",
    Antarctica: "Antártida",
    "Antigua and Barbuda": "Antigua y Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Aruba: "Aruba",
    Austria: "Austria",
    Azerbaijan: "Azerbaiyán",
    Bahamas: "bahamas",
    Bahrain: "Bahréin",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Bielorrusia",
    Belgium: "Bélgica",
    Belize: "Belice",
    Benin: "Benín",
    Bermuda: "islas Bermudas",
    Bhutan: "Bután",
    Bolivia: "bolivia",
    "Bosnia and Herzegovina": "Bosnia y Herzegovina",
    Botswana: "Botsuana",
    "Bouvet Island": "Isla Bouvet",
    Brazil: "Brasil",
    "British Indian Ocean Territory": "Territorio Británico del Océano Índico",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Camboya",
    Cameroon: "Camerún",
    "Cape Verde": "Cabo Verde",
    "Cayman Islands": "Islas Caimán",
    "Central African Republic": "República Centroafricana",
    Chad: "Chad",
    Chile: "Chile",
    China: "Porcelana",
    "Christmas Island": "Isla de Navidad",
    "Cocos (Keeling) Islands": "Islas Cocos (Keeling)",
    Colombia: "Colombia",
    Comoros: "Comoras",
    Congo: "Congo",
    "Congo, The Democratic Republic of the": "Congo, República Democrática del",
    "Cook Islands": "Islas Cook",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Costa de Marfil",
    Croatia: "Croacia",
    Cuba: "Cuba",
    Cyprus: "Chipre",
    "Czech Republic": "República Checa",
    Denmark: "Dinamarca",
    Djibouti: "Yibuti",
    Dominica: "república dominicana",
    "Dominican Republic": "República Dominicana",
    Ecuador: "Ecuador",
    Egypt: "Egipto",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guinea Ecuatorial",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Ethiopia: "Etiopía",
    "Falkland Islands (Malvinas)": "Islas Malvinas (Falkland)",
    "Faroe Islands": "Islas Faroe",
    Fiji: "Fiyi",
    Finland: "Finlandia",
    France: "Francia",
    "French Guiana": "Guayana Francesa",
    "French Polynesia": "Polinesia francés",
    "French Southern Territories": "Territorios Franceses del Sur",
    Gabon: "Gabón",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Grecia",
    Greenland: "Groenlandia",
    Grenada: "Granada",
    Guadeloupe: "Guadalupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernesey",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bisáu",
    Guyana: "Guayana",
    Haiti: "Haití",
    "Heard Island and Mcdonald Islands": "Isla Heard e Islas Mcdonald",
    "Holy See (Vatican City State)": "Santa Sede (Estado de la Ciudad del Vaticano)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Hungría",
    Iceland: "Islandia",
    Indonesia: "Indonesia",
    "Iran, Islamic Republic Of": "Irán (República Islámica de",
    Iraq: "Irak",
    Ireland: "Irlanda",
    "Isle of Man": "Isla del hombre",
    Israel: "Israel",
    Italy: "Italia",
    Jamaica: "Jamaica",
    Japan: "Japón",
    Jersey: "Jersey",
    Jordan: "Jordán",
    Kazakhstan: "Kazajstán",
    Kenya: "Kenia",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "República de Corea, Popular Democrática de",
    "Korea, Republic of": "Corea, república de",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kirguistán",
    "Lao People'S Democratic Republic": "República Democrática Popular Lao",
    Latvia: "Letonia",
    Lebanon: "Líbano",
    Lesotho: "Lesoto",
    Liberia: "Liberia",
    "Libyan Arab Jamahiriya": "Jamahiriya Árabe Libia",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lituania",
    Luxembourg: "Luxemburgo",
    Macao: "macao",
    "Macedonia, The Former Yugoslav Republic of": "Macedonia, Antigua República Yugoslava de",
    Madagascar: "Madagascar",
    Malawi: "Malaui",
    Malaysia: "Malasia",
    Maldives: "Maldivas",
    Mali: "Malí",
    Malta: "Malta",
    "Marshall Islands": "Islas Marshall",
    Martinique: "Martinica",
    Mauritania: "Mauritania",
    Mauritius: "Mauricio",
    Mayotte: "Mayotte",
    Mexico: "México",
    "Micronesia, Federated States of": "Micronesia, Estados Federados de",
    "Moldova, Republic of": "Moldavia, República de",
    Monaco: "Mónaco",
    Mongolia: "Mongolia",
    Montenegro: "Montenegro",
    Montserrat: "Montserrat",
    Morocco: "Marruecos",
    Mozambique: "Mozambique",
    Myanmar: "Birmania",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Países Bajos",
    "Netherlands Antilles": "Antillas Holandesas",
    "New Caledonia": "Nueva Caledonia",
    Nicaragua: "Nicaragua",
    Niger: "Níger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    "Norfolk Island": "Isla Norfolk",
    "Northern Mariana Islands": "Islas Marianas del Norte",
    Norway: "Noruega",
    Oman: "Omán",
    Pakistan: "Pakistán",
    Palau: "Palaos",
    "Palestinian Territory, Occupied": "Territorio Palestino, Ocupado",
    Panama: "Panamá",
    "Papua New Guinea": "Papúa Nueva Guinea",
    Paraguay: "Paraguay",
    Peru: "Perú",
    Philippines: "Filipinas",
    Pitcairn: "Pitcairn",
    Poland: "Polonia",
    Portugal: "Portugal",
    "Puerto Rico": "Puerto Rico",
    Qatar: "Katar",
    Reunion: "Reunión",
    Romania: "Rumania",
    "Russian Federation": "Federación Rusa",
    RWANDA: "RUANDA",
    "Saint Helena": "santa elena",
    "Saint Kitts and Nevis": "San Cristóbal y Nieves",
    "Saint Lucia": "Santa Lucía",
    "Saint Pierre and Miquelon": "San Pedro y Miquelón",
    "Saint Vincent and the Grenadines": "San Vicente y las Granadinas",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Santo Tomé y Príncipe",
    "Saudi Arabia": "Arabia Saudita",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Seychelles: "Seychelles",
    "Sierra Leone": "Sierra Leona",
    Singapore: "Singapur",
    Slovakia: "Eslovaquia",
    Slovenia: "Eslovenia",
    "Solomon Islands": "Islas Salomón",
    Somalia: "Somalia",
    "South Africa": "Sudáfrica",
    "South Georgia and the South Sandwich Islands": "Georgia del sur y las islas Sandwich del sur",
    Spain: "España",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudán",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard y Jan Mayen",
    Swaziland: "Suazilandia",
    Sweden: "Suecia",
    Switzerland: "Suiza",
    "Syrian Arab Republic": "República Árabe Siria",
    "Taiwan, Province of China": "Taiwan, provincia de China",
    Tajikistan: "Tayikistán",
    "Tanzania, United Republic of": "Tanzania, República Unida de",
    Thailand: "Tailandia",
    "Timor-Leste": "Timor Oriental",
    Togo: "Ir",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd y Tobago",
    Tunisia: "Túnez",
    Turkey: "Pavo",
    Turkmenistan: "Turkmenistán",
    "Turks and Caicos Islands": "Islas Turcas y Caicos",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ucrania",
    "United Arab Emirates": "Emiratos Árabes Unidos",
    "United Kingdom": "Reino Unido",
    "United States Minor Outlying Islands": "Islas menores alejadas de los Estados Unidos",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistán",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands, British": "Islas Vírgenes, Británicas",
    "Virgin Islands, U.S.": "Islas Vírgenes, EE.UU.",
    "Wallis and Futuna": "Wallis y Futuna",
    "Western Sahara": "Sahara Occidental",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabue",
    "Unlock All Schema with our Premium Plan": "Desbloquee todos los esquemas con nuestro plan Premium",
    "Billed Monthly": "Facturado mensualmente",
    "Billed Annually": "Facturado anualmente",
    "Save 30%": "Ahorra 30%",
    Premium100Title:
      "Como usuario inicial, le aseguramos que podrá disfrutar de todas nuestras funciones premium sin costo alguno para usted. No hay necesidad de preocuparse por la página de precios, ya que puede acceder libremente a todas nuestras funciones premium sin ningún cargo. No desinstale nuestra aplicación para continuar disfrutando de nuestro servicio.",
    Premium100ReviewLine:
      " Si te gusta nuestra aplicación, déjanos una reseña. Eso nos ayuda a motivarnos a desarrollar nuevas funciones.",
    "Check Our Current Pricing": "Consulte nuestros precios actuales",
    "Leave Review": "Deje opinión",
    "We're sorry to see you go!": "¡Sentimos verte partir!",
    "Cancel Plan": "Cancelar plan",
    "Sync Plan": "Plan de sincronización",
    "Disccount applied": "Descuento aplicado",
    Apply: "Aplicar",
    "Your code(s)": "Tu(s) código(s)",
    "and discount have been applied successfully": "y el descuento se ha aplicado correctamente",
    "Your entered promocode is not correct, Enter a valid code":
      "Su código de promoción ingresado no es correcto, ingrese un código válido",
    "days trial left": "días de prueba restantes",
    Upgrade: "Mejora",
    "days free trial, No Credit card required": "días de prueba gratuita, no se requiere tarjeta de crédito",
    Month: "Mes",
    Year: "Año",
    Unlimited: "Ilimitado",
    "Enter Promocode": "Introduce el código de promoción",
    "Please Choose a Cancellation Reason": "Por favor elija un motivo de cancelación",
    "No Longer Needed?": "¿Ya no es necesario?",
    "Didn't Meet Expectations": "No cumplió con las expectativas",
    "Cost Concerns": "Preocupaciones por los costos",
    "Technical Issues": "Problemas técnicos",
    "Found an Alternative": "Encontré una alternativa",
    Complexity: "Complejidad",
    "Lack of Features": "Falta de características",
    "Poor Customer Support": "Mala atención al cliente",
    "Business Closure or Change": "Cierre o cambio de negocio",
    "Temporary Pause": "Pausa temporal",
    "Performance Issues": "Problemas de desempeño",
    Other: "Otro",
    "Mention Your Specific Reason Here": "Mencione su motivo específico aquí",
    Start: "Comenzar",
    "Day Free Trial": "Prueba gratuita de un día",
    "Please Select One Option": "Por favor selecciona una opcion",
    "Plan cancelled successfully": "Plan cancelado exitosamente",
    "7 days free trial, No Credit card required": "Prueba gratuita de 7 días, no se requiere tarjeta de crédito",
    "Your remaining trial days are": "Los días de prueba restantes son",
    "You have used": "has usado",
    "days.": "días.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "No quedan días de prueba. Ya has utilizado la prueba gratuita de 7 días.",
    "Upgrade your plan now": "Actualiza tu plan ahora",
    "Unlimited Slides": "Diapositivas ilimitadas",
    "20+ Animation In & Out": "Más de 20 animaciones dentro y fuera",
    "Live Chat Support": "Soporte de chat en vivo",
    "Priority, 24*7 Urgent setup and support":
      "Prioridad, configuración y soporte urgentes 24 horas al día, 7 días a la semana",
    "Rich Text Editor": "Editor de texto enriquecido",
    "One Slide(banner)": "Una diapositiva (banner)",
    "Repeated Countdown timer": "Temporizador de cuenta atrás repetido",
    "Fully Customisable": "Totalmente personalizable",
    "Background-image": "Imagen de fondo",
    "Custom Css": "CSS personalizado",
    "Enable Our App": "Habilite nuestra aplicación",
    "Book Onboarding Demo": "Reservar demostración de incorporación",
    Next: "Próximo",
    Finish: "Finalizar",
    Prev: "Anterior",
    "App is not enable please click on the Enable App button to enable it.":
      "La aplicación no está habilitada, haga clic en el botón Habilitar aplicación para habilitarla.",
    "This field is required": "Este campo es obligatorio",
    disableButtonTooltip: "¡No puedes actualizar el plan mensual porque tienes un plan anual!",
    "Choose plan": "Elige plan",
    "Purchase Plan": "Plan de compra",
    Continue: "Continuar",
    "Image Optimization": "Optimización de imagen",
    "AI Metatags": "Metaetiquetas de IA",
    "Grand Total": "Gran total",
    "Metatags Edit": "Metaetiquetas Editar",
    Products: "Productos",
    "Upgrade plan": "Plan de actualización",
    "Your product count is": "Su recuento de productos es",
    "so your suitable plan is": "entonces tu plan adecuado es",
    "Enjoy a": "Disfruta de un",
    "lifetime discount": "descuento de por vida",
    discountBanner:
      " Aproveche un descuento de por vida, obtenga ahorros perpetuos y mejore su experiencia con nuestros productos y servicios premium.",
    "Images for Optimization every year after trial period end":
      "Imágenes para optimización cada año después de finalizar el período de prueba",
    "AI Meta Tags Credit for every year after trial period end":
      "Crédito de metaetiquetas de IA por cada año después de finalizar el período de prueba",
    "Images for Optimization every month after trial period end":
      "Imágenes para optimización todos los meses después de finalizar el período de prueba",
    "AI Meta Tags Credit for every Month after trial period end":
      "Crédito de metaetiquetas AI por cada mes después de finalizar el período de prueba",
    "Optimize your google page speed": "Optimice la velocidad de su página de Google",
    "50 Product Meta tags Optimize, Image alt": "50 metaetiquetas de producto Optimizar, imagen alternativa",
    "Product Meta tags Optimize, Image alt": "Metaetiquetas del producto Optimizar, Imagen alternativa",
    "AI ImageAltText Credit for every year after trial period end":
      "Crédito AI ImageAltText por cada año después de finalizar el período de prueba",
    "25 AI ImageAltText Credit": "25 créditos de texto alternativo de imagen AI",
    "AI ImageAltText Credit for every Month after trial period end":
      "Crédito AI ImageAltText por cada mes después de finalizar el período de prueba",
    "Contact Bar": "Barra de contacto",
    "Add To Cart Bar": "Barra Añadir al carrito",
    "Multiple Position": "Posición múltiple",
    lowMsgStart: "Esta oferta está especialmente diseñada para ti, ya que acabas de iniciar tu tienda Shopify.",
    lowMsgMiddle: "Nuestro",
    lowMsgEnd: "El descuento es nuestra forma de apoyarlo durante estos tiempos desafiantes pero emocionantes.",
    mediumMsgStart: "Esta oferta está especialmente diseñada para ti, ya que iniciaste tu tienda Shopify.",
    mediumMsgMiddle: "Nuestro",
    mediumMsgEnd: "El descuento es nuestra forma de apoyarlo durante estos tiempos desafiantes pero emocionantes.",
    importantMsgStart: "Esta oferta está especialmente diseñada para ti, ya que iniciaste tu tienda Shopify.",
    importantMsgMiddle: "Nuestro",
    importantMsgEnd:
      "El descuento es nuestra forma de apoyarlo durante estos tiempos desafiantes pero emocionantes.",
    veryImportantMsgStart: "Esta oferta está especialmente diseñada para ti, ya que has abierto tu tienda Shopify",
    veryImportantMsgMiddle: "Eres un comerciante muy importante y maduro para nosotros. Nuestro",
    veryImportantMsgEnd: "El descuento es para mostrar lo mucho que significas para nosotros.",
    generalMsg:
      "Nuestra aplicación Shopify está diseñada para satisfacer las necesidades de empresas establecidas como la suya. Está diseñado para manejar grandes volúmenes y operaciones complejas sin problemas. ",
    lowTitleStart: "Apoyo Especial para Nuevos Emprendedores:",
    lowTitleEnd: "Descuento como acabas de empezar",
    mediumTitleStart: "Apoyo Especial a Emprendedores:",
    mediumTitleEnd: "Descuento como empezaste",
    importantTitleStart: "Apoyo Especial a Emprendedores:",
    importantTitleEnd: "Descuento como empezaste",
    veryImportantTitleStart: "Felicitaciones por ser",
    veryImportantTitleEnd: "en Shopify",
    month: "mes",
    "year and": "año y",
    ago: "atrás",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Agregar crédito AI (1 crédito AI/10¢) (10 crédito AI/$1)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Agregar imagen Texto alternativo Crédito AI (1 crédito AI/4¢) (25 crédito AI/$1)",
    "Monthly AI AltText Credit": "Crédito mensual de texto alternativo de IA",
    "Yearly AI AltText Credit": "Crédito anual de texto alternativo de IA",
    "Purchase AI AltText Credit": "Comprar crédito de texto alternativo AI",
    "ImageAltText Credit": "Crédito de texto alternativo de imagen",
    "Your credits are finished; please upgrade your plan.":
      "Tus créditos están terminados; por favor actualice su plan.",
    "Your credits are finished; you can buy more credits from here.":
      "Tus créditos están terminados; Puedes comprar más créditos desde aquí.",
    "This offer expire in": "Esta oferta vence en",
    "Hurry Up!": "¡Apresúrate!",
    Current: "Actual",
    "Discount applied": "Descuento aplicado",
    "trial left": "prueba izquierda",
    "info banner":
      "Cuando hace clic en el botón Escanear imagen de la página de inicio, nuestra aplicación solo escaneará la imagen de la página de inicio. Para optimizar esta imagen, haga clic en el botón Optimizar manualmente",
    "Optimize Images": "Optimizar imágenes",
    image: "imagen",
    images: "imágenes",
    Filename: "Nombre del archivo",
    Images: "Imágenes",
    Setting: "Configuración",
    "Saved(in %)": "Guardado (en %)",
    Action: "Acción",
    "Product Image": "Imagen del producto",
    "product image": "Imagen del producto",
    gif: "gif",
    Homepage: "Página principal",
    "Manage Announcement": "Administrar anuncio",
    "No Announcements Found": "No se encontraron anuncios",
    Position: "Posición",
    "Campaign Title": "Título de la campaña",
    Visible: "Visible",
    Invisible: "Invisible",
    Views: "Puntos de vista",
    Clicks: "Clics",
    Submits: "envía",
    "Above Add to cart Button": "Arriba Botón Añadir al carrito",
    "Below Add to cart Button": "Debajo del botón Añadir al carrito",
    Targeting: "Orientación",
    "Rotating Animation Setting": "Configuración de animación giratoria",
    "Marquee Animation Setting": "Configuración de animación de marquesina",
    "Show to visitors coming form then specific website":
      "Mostrar a los visitantes que vienen desde un sitio web específico",
    "Add your website URL": "Añade la URL de tu sitio web",
    "Banner Display Start Time": "Hora de inicio de visualización del banner",
    "Banner Display End Time": "Hora de finalización de la visualización del banner",
    "Create Campaign": "Crear campaña",
    "Select Announcement Bar": "Seleccionar barra de anuncios",
    "Please select template.": "Por favor seleccione plantilla.",
    Previous: "Anterior",
    "Promotion bar": "Barra de promoción",
    "Add To Cart": "Añadir a la cesta",
    Embeded: "Integrado",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Alerte a los clientes sobre próximas ventas y ofertas, o establezca alertas de inventario.",
    "Increase your order value by using or Free Shipping Bar.":
      "Aumente el valor de su pedido utilizando nuestra barra de envío gratuito.",
    "Conveniently add items to your cart with a single click!":
      "¡Agregue artículos a su carrito cómodamente con un solo clic!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Selecciona para suscribirte y recibir descuentos especiales directamente en tu bandeja de entrada",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Resalte sus ofertas especiales con una barra incorporada, que se muestra antes y después del botón Agregar al carrito.",
    Select: "Seleccionar",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Agregar código UTM para ocultar banner (p. ej. Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Incluir UTM",
    "Exclude Utm": "Excluir UTM",
    "Campaign Design": "Diseño de campaña",
    "Background Setting": "Configuración de fondo",
    "Target Setting": "Establecimiento de objetivos",
    Scheduling: "Programación",
    Rotating: "Giratorio",
    Marquee: "Marquesina",
    "Repeat Timer Date": "Temporizador de repetición de fecha",
    "Select Repeat Time": "Seleccionar tiempo de repetición",
    "Repeated Hours": "Horas repetidas",
    Border: "Borde",
    Bashed: "Golpeado",
    "Multi Rotating": "Rotación múltiple",
    Contacts: "Contactos",
    Email: "Correo electrónico",
    "First Name": "Nombre de pila",
    "Last Name": "Apellido",
    Phone: "Teléfono",
    "You have unsaved changes": "Tiene cambios sin guardar",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Su campaña tiene cambios no guardados. Los cambios se perderán si sales sin guardarlos.",
    "Leave widthout saving": "Dejar guardado en ancho",
    "Save Changes": "Guardar cambios",
    Announcement: "Anuncio",
    Feedback: "Comentario",
    "Recipe Instructions": "Instrucciones de receta",
    "Visit Help Center": "Visita el Centro de ayuda",
    "Schedule Meeting": "Programar reunión",
    "Setup guide": "Guia de preparacion",
    "Use this personalized guide to get your store up and running":
      "Utilice esta guía personalizada para poner en funcionamiento su tienda",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Para comenzar a recibir acciones, necesita habilitar nuestra aplicación. Al hacer clic en el botón, accederá a la página de extensiones, luego solo necesita hacer clic en guardar allí y volver aquí.",
    "Enable our app": "Habilita nuestra aplicación",
    "Learn more": "Aprende más",
    "Skip it": "Saltarlo",
    steps: "pasos",
    minutes: "minutos",
    "Mark as done": "marcar como hecho",
    "Mark as not done": "Marcar no como hecho",
    "You have completed all the steps": "Has completado todos los pasos.",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Active y analice la velocidad de su sitio para clasificar su tienda más arriba en los resultados de búsqueda.",
    "Google Page Speed Optimization": "Optimización de la velocidad de la página de Google",
    "Activate Google Page Speed": "Activar la velocidad de la página de Google",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Habilite la herramienta Google Page Speed para evaluar el rendimiento de su sitio e identificar oportunidades para mejorar la velocidad.",
    "Enable Speed Analysis": "Habilitar análisis de velocidad",
    "Review Speed Analysis Report": "Revisar el informe de análisis de velocidad",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Examine el informe de análisis de velocidad detallado para comprender las métricas de velocidad actuales de su sitio e identificar áreas de mejora.",
    "Go to Reports": "Ir a Informes",
    Hello: "Hola",
    "Let's get your store ready for success": "Preparemos su tienda para el éxito",
    "Finish later": "Terminar más tarde",
    "Continue onboarding": "Continuar incorporando",
    "Check image optimization features": "Verifique las funciones de optimización de imágenes",
    "Explore Optimization Features": "Explorar las funciones de optimización",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Familiarícese con la gama de herramientas de optimización de imágenes disponibles. Vea cómo puede mejorar la velocidad de carga de la página y el SEO optimizando los tamaños y formatos de las imágenes.",
    "Go to Image Optimization": "Ir a optimización de imagen",
    "Automate Your Image Workflow": "Automatice su flujo de trabajo de imágenes",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Configure la automatización para optimizar sin problemas las nuevas imágenes a medida que se cargan, garantizando un rendimiento constante en todo su sitio.",
    "Go to Automation": "Ir a Automatización",
    "Execute a Bulk Optimization": "Ejecutar una optimización masiva",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Realice una optimización masiva para mejorar de manera eficiente varias imágenes a la vez, lo que puede aumentar significativamente el tiempo de carga de su sitio.",
    "Go to bulk operations": "Ir a operaciones masivas",
    "Broken Links Management": "Gestión de enlaces rotos",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatice la detección y reparación de enlaces rotos para mejorar la experiencia del usuario y las clasificaciones SEO.",
    "Review Detected Broken Links": "Revisar enlaces rotos detectados",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Examine la lista de enlaces rotos identificados automáticamente por nuestro sistema para comprender su impacto en la navegación de su sitio.",
    "View Broken Links": "Ver enlaces rotos",
    "Address Broken Links": "Abordar enlaces rotos",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Utilice nuestras herramientas para reparar o redirigir rápidamente enlaces rotos, mejorando la integridad de su sitio y la satisfacción del usuario.",
    "Resolve Broken Links": "Resolver enlaces rotos",
    "Automate for Efficiency": "Automatizar para lograr eficiencia",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Configure una solución automatizada para anticiparse a futuros enlaces rotos, garantizando la salud continua del sitio.",
    "Enable Automation": "Habilitar la automatización",
    "Meta Tags Management": "Gestión de metaetiquetas",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Optimice la visibilidad de su sitio y la clasificación en los motores de búsqueda con nuestra función de metaetiquetas fácil de usar.",
    "Explore Meta Tag Options": "Explorar las opciones de metaetiquetas",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Familiarícese con las diversas opciones de automatización y edición de metaetiquetas disponibles para productos y páginas individuales.",
    "Explore Meta Tags": "Explorar metaetiquetas",
    "Edit and Optimize": "Editar y optimizar",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Sumérgete en la edición de metatítulos, descripciones y textos alternativos de imágenes para mejorar el SEO de tu sitio y la accesibilidad del usuario.",
    "Start Editing": "Comenzar a editar",
    "Automate for Consistency": "Automatizar para lograr coherencia",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Configure reglas de automatización para sus metaetiquetas para mantener la coherencia y la eficiencia en las páginas de sus productos.",
    "Set Automation": "Establecer automatización",
    "Schema Markup": "Marcado de esquema",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Utilice el marcado Schema para mejorar la representación de su contenido en los resultados de búsqueda y atraer más clics.",
    "Learn About Schema Options": "Más información sobre las opciones de esquema",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Familiarícese con los diferentes tipos de marcas de esquema disponibles, como Producto, Negocio local, Preguntas frecuentes y más, para comprender sus beneficios.",
    "Explore Schema Types": "Explorar tipos de esquemas",
    "Activate Key Schemas": "Activar esquemas de claves",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Elija y habilite esquemas cruciales para su sitio, como el esquema de producto para comercio electrónico o el esquema de negocio local para tiendas físicas.",
    "Go to Schemas": "Ir a esquemas",
    "Customize Schema Details": "Personalizar detalles del esquema",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Personalice la configuración de cada tipo de esquema para representar con precisión su empresa o productos en los resultados de búsqueda.",
    "Test and Validate Schemas": "Probar y validar esquemas",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Pruebe sus esquemas utilizando herramientas como la herramienta de prueba de datos estructurados de Google para asegurarse de que se implementen correctamente.",
    "Test Schemas": "Esquemas de prueba",
    "Add Breadcrumbs": "Agregar pan rallado",
    "Add Breadcrumbs to your store": "Añade Breadcrumbs a tu tienda",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Para obtener una mejor experiencia de usuario, debe agregar rutas de navegación a su tienda.",
    "How to add breadcrumbs": "Cómo agregar pan rallado",
    "Understand how to add and configure breadcrumbs in your store.":
      "Comprenda cómo agregar y configurar rutas de navegación en su tienda.",
    "Google search console": "consola de búsqueda de google",
    "Connect google search console to sync it with our app.":
      "Conecte Google Search Console para sincronizarlo con nuestra aplicación.",
    "How to connect GSC.": "Cómo conectar GSC.",
    "Understand how to connect and use google search console in our app.":
      "Comprenda cómo conectarse y utilizar Google Search Console en nuestra aplicación.",
    "Go to GSC": "Ir al GSC",
    "Go to Breadcrumbs Design": "Ir al diseño de migas de pan",
    "Start Onboarding": "Iniciar la incorporación",
    "Go to Homepage": "Ir a la página de inicio",
    "Go to Onboarding": "Ir a incorporación",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      'Explore nuestra guía de aplicaciones fácil de usar diseñada para mejorar su comprensión. Haga clic en "Iniciar incorporación" para comenzar y podrá volver a la página de inicio en cualquier momento.',
    "Please enable our app extension.": "Habilite nuestra extensión de aplicación.",
    "Generate Meta tags": "Generar metaetiquetas",
    "Test description a litle bit longer that title":
      "La descripción de la prueba es un poco más larga que el título.",
    "Suggested for you": "Sugerido para ti",
    "Enable Google page speed": "Habilitar la velocidad de la página de Google",
    "Connect GSC": "Conectar GSC",
    "Enable Image Optimize Automation": "Habilitar la automatización de optimización de imágenes",
    "Automate Meta tags": "Automatizar metaetiquetas",
    "Automate Broken Links": "Automatizar enlaces rotos",
    "Enhance SEO with automatically generated meta tags.":
      "Mejore el SEO con metaetiquetas generadas automáticamente.",
    "Improve website performance by optimizing images.":
      "Mejore el rendimiento del sitio web optimizando las imágenes.",
    "Boost website speed by enabling Google Page Speed.":
      "Aumente la velocidad del sitio web habilitando Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Mejore la visibilidad de la búsqueda conectándose a Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Optimice la optimización de imágenes con procesos automatizados.",
    "Improve SEO by automating the generation of meta tags.":
      "Mejore el SEO automatizando la generación de metaetiquetas.",
    "Improve UX with automated detect and handle, broken links.":
      "Mejore la UX con detección y manejo automatizados de enlaces rotos.",
    "Learn About Add Announcement": "Más información sobre cómo agregar anuncio",
    "Skip And Add Announcement": "Saltar y agregar anuncio",
    "Learn more about": "Aprender más acerca de",
    "Add Announcement": "Agregar anuncio",
    "Announcement Bar": "Barra de anuncios",
    "Rate us!": "¡Nos califica!",
    "How would you Love this app?": "¿Cómo te encantaría esta aplicación?",
    "Enter Your Feedback Here": "Ingrese sus comentarios aquí",
    "Leave Us a Review !!": "¡¡Déjanos una reseña!!",
    "If you like our app features then please leave us a review !!":
      "Si te gustan las funciones de nuestra aplicación, ¡déjanos un comentario!",
    "If you like our free features then please leave us a review !!":
      "Si te gustan nuestras funciones gratuitas, ¡déjanos una reseña!",
    "Update Successfully": "Actualizar correctamente",
    "Uninstall App": "Desinstalar aplicación",
    "Contact Our Support": "Póngase en contacto con nuestro soporte",
    "Leave a message": "Dejar un mensaje",
    "Please Choose a UnInstallation Reason": "Elija un motivo de desinstalación",
    "Are you facing any issues understanding the features of our app?":
      "¿Tiene algún problema para comprender las funciones de nuestra aplicación?",
    "Please Choose at least one reason": "Por favor elija al menos un motivo",
    "Thank You For Reaching Out": "Gracias por comunicarte",
    "Contact Support": "Soporte de contacto",
    "Get Help from Our Support Team": "Obtenga ayuda de nuestro equipo de soporte",
    "Select a reason": "Seleccione una razón",
    "Not getting how to use or setup": "No entiendo cómo usarlo o configurarlo",
    "Poor customer support": "Mala atención al cliente",
    "Performance issues": "Problemas de desempeño",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Nuestro equipo de soporte actualmente no está disponible los fines de semana y estará disponible los días laborables según su zona horaria desde ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " ya que operamos desde la India. Aún puedes dejar un mensaje. Espere algún retraso en nuestra respuesta. Gracias por su paciencia.",
    "Our support team is partially available according to your time zone from ":
      "Nuestro equipo de soporte está parcialmente disponible según su zona horaria desde ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " ya que operamos desde la India. Las respuestas pueden tardar entre 30 minutos y una hora durante este tiempo. Por favor deje un mensaje y le responderemos lo antes posible. Gracias por su paciencia.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Nuestro equipo de soporte no está disponible actualmente y estará disponible según su zona horaria desde ",
    to: "a",
    "Did not meet my expectations": "No cumplió mis expectativas",
    "Feature Limitations": "Limitaciones de funciones",
    "Banner doesn't set in my app": "El banner no se configura en mi aplicación",
    "Banner is not show properly": "El banner no se muestra correctamente",
    "Confusing Set Multi Position and Multi Animation":
      "Conjunto confuso de posiciones múltiples y animación múltiple",
    "Sync Profile": "Sincronizar perfil",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
