import modifyData from "../Language/fr.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Activé",
    Disabled: "Désactivé",
    "Embed is currently disabled": "L'intégration est actuellement désactivée",
    "Enable App": "Activer l'application",
    "1. Click on Enable App.": "1. Cliquez sur Activer l'application.",
    "Well done!! you have successfully enable our app.":
      "Bien joué!! vous avez activé avec succès notre application.",
    "2. Enable": "2. Activer",
    "App Embed as shown in image and save setting.":
      "Intégrez l'application comme indiqué dans l'image et enregistrez les paramètres.",
    "Multi Announcement Bar": "Barre d'annonces multiples",
    "Click on the Enable Now button to enable it.": "Cliquez sur le bouton Activer maintenant pour l'activer.",
    "Enable Announcement Bar to get started": "Activer la barre d'annonce pour commencer",
    "Enable Now": "Activer maintenant",
    "Sync Status": "Statut de synchronisation",
    Done: "Fait",
    No: "Non",
    Found: "Trouvé",
    Add: "Ajouter",
    Search: "Recherche",
    Showing: "Affichage",
    of: "de",
    "results, at most": "des résultats, tout au plus",
    "per page": "par page",
    "Oops! Something went wrong.": "Oops! Quelque chose s'est mal passé.",
    "Let's try that again, please refresh the page.": "Essayons à nouveau, veuillez actualiser la page.",
    "If you're still stuck, contact us by chat support or":
      "Si vous êtes toujours bloqué, contactez-nous par chat ou",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "pour que nous puissions vous aider !",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Sélectionnez les 3 fonctionnalités que vous souhaitez configurer en haute priorité ou les plus intéressées",
    "Add ": "Ajouter ",
    "These is premium feature": "Il s'agit d'une fonctionnalité premium",
    "Go to pricing": "Aller aux tarifs",
    Save: "Sauvegarder",
    Minimum: "Le minimum",
    Maximum: "Maximum",
    "images are required": "les images sont obligatoires",
    and: "et",
    "images are allowed": "les images sont autorisées",
    Disconnect: "Déconnecter",
    "Sign In with Google": "Connectez-vous avec Google",
    "Oops! Something went wrong. Admin token is malformed":
      "Oops! Quelque chose s'est mal passé. Le jeton d'administrateur est mal formé",
    "If you're still stuck, contact": "Si vous êtes toujours bloqué, contactez",
    Premium: "Prime",
    Unlock: "Ouvrir",
    "Unlock advanced features!": "Débloquez des fonctionnalités avancées !",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Tous droits réservés.",
    "Privacy Policy": "politique de confidentialité",
    "Terms of Service": "Conditions d'utilisation",
    "Go to Shopify App": "Accédez à l'application Shopify",
    "Review Us": "Évaluez-nous",
    Cancel: "Annuler",
    "Review Popup Show": "Affichage contextuel de la revue",
    "click on review us": "cliquez sur nous évaluer",
    "Note: Feel free to leave a star rating without writing a review!":
      "Remarque : N'hésitez pas à laisser une note sans écrire d'avis !",
    Help: "Aide",
    "Help Button Click": "Cliquez sur le bouton d'aide",
    Confirm: "Confirmer",
    On: "Sur",
    Off: "Désactivé",
    Price: "Prix",
    Settings: "Paramètres",
    Animation: "Animation",
    "My Profile": "Mon profil",
    "My Subscription": "Mon abonnement",
    "Store Name": "Nom du magasin",
    "Store URL": "URL du magasin",
    "Email ID": "Identifiant de courrier électronique",
    "Phone Number": "Numéro de téléphone",
    Country: "Pays",
    Currency: "Devise",
    "Subscription Name": "Nom de l'abonnement",
    "Select language": "Choisir la langue",
    "Announcement setting": "Paramètre d'annonce",
    "Animation setting": "Paramètre d'animation",
    Selector: "Sélecteur",
    "Save Setting": "Sauvegarder les paramètres",
    "My Announcements": "Mes annonces",
    "Add bar": "Ajouter une barre",
    Number: "Nombre",
    Title: "Titre",
    "Create At": "Créer à",
    "Slide Activation": "Activation des diapositives",
    Status: "Statut",
    Actions: "Actions",
    "Save order": "Enregistrer la commande",
    "Reorder Slides": "Réorganiser les diapositives",
    position: "position",
    Top: "Haut",
    "Sticky Top": "Haut collant",
    "Bottom Fix": "Correction inférieure",
    "Custom Position": "Position personnalisée",
    "Custom Position *Add Class or id of Selected Element.":
      "Position personnalisée *Ajouter une classe ou un identifiant de l'élément sélectionné.",
    "Bar Padding (px)": "Rembourrage de barre (px)",
    "Add Remove Button": "Ajouter un bouton Supprimer",
    "Choose icon color": "Choisir la couleur de l'icône",
    "Custom css": "CSS personnalisé",
    fadeIn: "fondu",
    fadeInDown: "fonduInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fondu à gauche",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "fonduInUp",
    bounceInDown: "rebondir vers le bas",
    bounceInLeft: "rebondir à gauche",
    bounceInUp: "rebondInUp",
    zoomIn: "agrandir",
    zoomInDown: "zoomInDown",
    zoomInLeft: "zoomInGauche",
    slideInLeft: "slideInGauche",
    slideInUp: "slideInUp",
    slideInDown: "slideInDown",
    lightSpeedIn: "lumièreVitesseIn",
    rollIn: "rouler",
    flash: "éclair",
    shake: "secouer",
    flip: "retourner",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "disparaître",
    fadeOutDown: "fondu vers le bas",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fondu à droite",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fondu vers le haut",
    bounceOutDown: "rebondir vers le bas",
    bounceOutRight: "rebondir à droite",
    bounceOutUp: "rebondOutUp",
    zoomOut: "Dézoomer",
    zoomOutDown: "zoomOutDown",
    zoomOutRight: "zoom arrièredroite",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "dérouler",
    flipInY: "flipInY",
    "Text Animation": "Animation de texte",
    "Animation In": "Animation dans",
    "Animation Out": "Sortie d'animation",
    "Auto play time (time in MS)": "Temps de lecture automatique (temps en MS)",
    "Animation time (time in MS)": "Temps d'animation (temps en MS)",
    "Auto play time (time in Second)": "Temps de lecture automatique (durée en seconde)",
    "Background Color": "Couleur de l'arrière plan",
    "Space between slide(px)": "Espace entre les diapositives (px)",
    visible: "visible",
    invisible: "invisible",
    "Promotional & Countdown Bar": "Barre promotionnelle et compte à rebours",
    "Free Shipping Bar": "Livraison gratuite de la barre",
    "Add Slide": "Ajouter une diapositive",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Une seule diapositive est visible pour le plan GRATUIT. Pour activer Toutes les diapositives, abonnez-vous au forfait Premium.",
    Pricing: "Tarifs",
    "No Animation Found": "Aucune animation trouvée",
    "No Preview, Add announcement Bar": "Pas d'aperçu, ajouter une barre d'annonce",
    "Update successfully": "Mise à jour réussie",
    Enable: "Activer",
    Disable: "Désactiver",
    successfully: "avec succès",
    "Delete successfully": "Supprimer avec succès",
    "Copy successfully": "Copier avec succès",
    "Reorder successfully": "Réorganiser avec succès",
    "Announcement Message": "Message d'annonce",
    "Call to Action": "Appel à l'action",
    Timer: "Minuteur",
    Style: "Style",
    "Background Type": "Type d'arrière-plan",
    "Mobile Style": "Style mobile",
    "Schedule Display": "Affichage du calendrier",
    Update: "Mise à jour",
    "Change Font": "Changer la police",
    "Font Family": "Famille de polices",
    "Font Style": "Le style de police",
    Normal: "Normale",
    Italic: "Italique",
    Oblique: "Oblique",
    Unset: "Désarmé",
    "Font Weight": "Poids de la police",
    Bold: "Audacieux",
    "Message Font Size": "Taille de la police des messages",
    "Message Text color": "Couleur du texte du message",
    Type: "Taper",
    None: "Aucun",
    Button: "Bouton",
    "Entire clickable bar": "Barre cliquable entière",
    "Add a simple link": "Ajouter un lien simple",
    "Add coupon placement": "Ajouter un emplacement de coupon",
    "Linked Url": "URL liée",
    "Background Hover Color": "Couleur de survol d’arrière-plan",
    "Text Hover Color": "Couleur de survol du texte",
    "Button Text": "Texte du bouton",
    "Copied Text": "Texte copié",
    "Open in the new tab": "Ouvrir dans le nouvel onglet",
    URL: "URL",
    "Font Size": "Taille de police",
    "Button Radius": "Rayon du bouton",
    "Button color": "Couleur du bouton",
    "Button Text color": "Couleur du texte du bouton",
    "Button Hover Color": "Couleur du survol du bouton",
    "button Text HoverColor": "bouton Texte HoverColor",
    "Timer Setting": "Réglage de la minuterie",
    "Timer Type": "Type de minuterie",
    Date: "Date",
    "Select Reapt Time": "Sélectionnez l'heure de répétition",
    "repeated Hours": "Heures répétées",
    "Normal Timer": "Minuterie normale",
    "Auto repeat timer": "Minuterie de répétition automatique",
    Minute: "Minute",
    Hour: "Heure",
    Day: "Jour",
    "Remove Timer When Time End": "Supprimer la minuterie à la fin du temps",
    "Timer Separator": "Séparateur de minuterie",
    "Countdown Timer color": "Couleur du compte à rebours",
    "Timer Text Size": "Taille du texte du minuteur",
    "Timer Text Setting": "Réglage du texte de la minuterie",
    "Day Text": "Texte du jour",
    "Hour Text": "Texte de l'heure",
    "Minute Text": "Texte des minutes",
    "Second Text": "Deuxième texte",
    "Background Image": "Image de fond",
    "Gradient Background": "Fond Dégradé",
    "Style & Color For Mobile": "Style et couleur pour mobile",
    "Timer Background": "Fond de minuterie",
    "Timer Text Color": "Couleur du texte de la minuterie",
    "Button Color": "Couleur du bouton",
    "Button Text Color": "Couleur du texte du bouton",
    "Button Text Hover Color": "Couleur de survol du texte du bouton",
    "Button Text Size": "Taille du texte du bouton",
    "Always Display": "Toujours afficher",
    "Only Display Within The Following Period Of Time": "Afficher uniquement dans la période suivante",
    "Start Time": "Heure de début",
    "End Time": "Heure de fin",
    "Advance Setting": "Réglage avancé",
    "Country Filter": "Filtrer les pays",
    Visibility: "Visibilité",
    "Desktop and Mobile": "Ordinateur de bureau et mobile",
    "Only Desktop": "Uniquement le bureau",
    "Only Mobile": "Uniquement mobile",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "CIBLAGE DE SOURCE UTILISATEUR (Visiteurs provenant d'un lien incluant ce code UTM suivant, par exemple.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Sélectionner une page",
    Include: "Inclure",
    Exclude: "Exclure",
    "Currency Configuration": "Configuration de la devise",
    Message: "Message",
    "Currency Symbol": "Symbole de la monnaie",
    "Currency Position": "Position de la devise",
    Before: "Avant",
    After: "Après",
    "money Class": "classe d'argent",
    "Initial Message": "Message initial",
    "Shipping Goal": "Objectif d'expédition",
    "Progress Message": "Message de progression",
    "Progress goal": "Objectif de progression",
    "Goal Message": "Message d'objectif",
    "Shipping Price Color": "Prix d'expédition Couleur",
    "Shipping Price Size": "Taille du prix d'expédition",
    "Shipping Font Weight": "Poids de la police d'expédition",
    "* When user first time visit": "* Lors de la première visite de l'utilisateur",
    "* When user add item to the cart e.g": "* Lorsque l'utilisateur ajoute un article au panier, par exemple :",
    "* When cart value is greater than": "* Lorsque la valeur du panier est supérieure à",
    "Show On Selected Countries": "Afficher sur les pays sélectionnés",
    "Show On Selected Pages": "Afficher sur les pages sélectionnées",
    All: "Tous",
    Home: "Maison",
    Cart: "Chariot",
    Collection: "Collection",
    Product: "Produit",
    Custom: "Coutume",
    Page: "Page",
    Blog: "Blog",
    "Url is required": "L'URL est obligatoire",
    "Day Text is required": "Le texte du jour est requis",
    "Hour Text is required": "Le texte de l'heure est requis",
    "Minute Text is required": "Le texte du procès-verbal est requis",
    "Second Text is required": "Un deuxième texte est requis",
    "Start Time is required": "L'heure de début est requise",
    "End Time is required": "L'heure de fin est requise",
    "Created successfully": "Créé avec succès",
    "United States": "États-Unis",
    Canada: "Canada",
    Australia: "Australie",
    "New Zealand": "Nouvelle-Zélande",
    Germany: "Allemagne",
    India: "Inde",
    Afghanistan: "Afghanistan",
    "land Islands": "îles terrestres",
    Albania: "Albanie",
    Algeria: "Algérie",
    "American Samoa": "Samoa américaines",
    AndorrA: "Andorre",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarctique",
    "Antigua and Barbuda": "Antigua-et-Barbuda",
    Argentina: "Argentine",
    Armenia: "Arménie",
    Aruba: "Aruba",
    Austria: "L'Autriche",
    Azerbaijan: "Azerbaïdjan",
    Bahamas: "Bahamas",
    Bahrain: "Bahreïn",
    Bangladesh: "Bangladesh",
    Barbados: "Barbade",
    Belarus: "Biélorussie",
    Belgium: "Belgique",
    Belize: "Bélize",
    Benin: "Bénin",
    Bermuda: "Bermudes",
    Bhutan: "Bhoutan",
    Bolivia: "Bolivie",
    "Bosnia and Herzegovina": "Bosnie Herzégovine",
    Botswana: "Botswana",
    "Bouvet Island": "Île Bouvet",
    Brazil: "Brésil",
    "British Indian Ocean Territory": "Territoire britannique de l'océan Indien",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgarie",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Cambodge",
    Cameroon: "Cameroun",
    "Cape Verde": "Cap-Vert",
    "Cayman Islands": "Îles Caïmans",
    "Central African Republic": "République centrafricaine",
    Chad: "Tchad",
    Chile: "Chili",
    China: "Chine",
    "Christmas Island": "L'île de noël",
    "Cocos (Keeling) Islands": "Îles Cocos (Keeling)",
    Colombia: "Colombie",
    Comoros: "Comores",
    Congo: "Congo",
    "Congo, The Democratic Republic of the": "Congo, République Démocratique du",
    "Cook Islands": "les Îles Cook",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Côte d'Ivoire",
    Croatia: "Croatie",
    Cuba: "Cuba",
    Cyprus: "Chypre",
    "Czech Republic": "République tchèque",
    Denmark: "Danemark",
    Djibouti: "Djibouti",
    Dominica: "Dominique",
    "Dominican Republic": "République dominicaine",
    Ecuador: "Équateur",
    Egypt: "Egypte",
    "El Salvador": "Le Salvador",
    "Equatorial Guinea": "Guinée Équatoriale",
    Eritrea: "Érythrée",
    Estonia: "Estonie",
    Ethiopia: "Ethiopie",
    "Falkland Islands (Malvinas)": "Îles Falkland (Malvinas)",
    "Faroe Islands": "Îles Féroé",
    Fiji: "Fidji",
    Finland: "Finlande",
    France: "France",
    "French Guiana": "Guyane Française",
    "French Polynesia": "Polynésie française",
    "French Southern Territories": "Terres australes françaises",
    Gabon: "Gabon",
    Gambia: "Gambie",
    Georgia: "Géorgie",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Grèce",
    Greenland: "Groenland",
    Grenada: "Grenade",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernesey",
    Guinea: "Guinée",
    "Guinea-Bissau": "Guinée-Bissau",
    Guyana: "Guyane",
    Haiti: "Haïti",
    "Heard Island and Mcdonald Islands": "Île Heard et îles McDonald",
    "Holy See (Vatican City State)": "Saint-Siège (État de la Cité du Vatican)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Hongrie",
    Iceland: "Islande",
    Indonesia: "Indonésie",
    "Iran, Islamic Republic Of": "Iran (République islamique d",
    Iraq: "Irak",
    Ireland: "Irlande",
    "Isle of Man": "île de Man",
    Israel: "Israël",
    Italy: "Italie",
    Jamaica: "Jamaïque",
    Japan: "Japon",
    Jersey: "Jersey",
    Jordan: "Jordan",
    Kazakhstan: "Kazakhstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "République populaire démocratique de Corée",
    "Korea, Republic of": "Corée, République de",
    Kuwait: "Koweit",
    Kyrgyzstan: "Kirghizistan",
    "Lao People'S Democratic Republic": "République démocratique populaire lao",
    Latvia: "Lettonie",
    Lebanon: "Liban",
    Lesotho: "Lesotho",
    Liberia: "Libéria",
    "Libyan Arab Jamahiriya": "Jamahiriya arabe libyenne",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lituanie",
    Luxembourg: "Luxembourg",
    Macao: "Macao",
    "Macedonia, The Former Yugoslav Republic of": "Macédoine, ancienne République yougoslave de",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaisie",
    Maldives: "Maldives",
    Mali: "Mali",
    Malta: "Malte",
    "Marshall Islands": "Iles Marshall",
    Martinique: "Martinique",
    Mauritania: "Mauritanie",
    Mauritius: "Maurice",
    Mayotte: "Mayotte",
    Mexico: "Mexique",
    "Micronesia, Federated States of": "Micronésie, États fédérés de",
    "Moldova, Republic of": "Moldavie, République de",
    Monaco: "Monaco",
    Mongolia: "Mongolie",
    Montenegro: "Monténégro",
    Montserrat: "Montserrat",
    Morocco: "Maroc",
    Mozambique: "Mozambique",
    Myanmar: "Birmanie",
    Namibia: "Namibie",
    Nauru: "Nauru",
    Nepal: "Népal",
    Netherlands: "Pays-Bas",
    "Netherlands Antilles": "Antilles néerlandaises",
    "New Caledonia": "Nouvelle Calédonie",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Nioué",
    "Norfolk Island": "l'ile de Norfolk",
    "Northern Mariana Islands": "Îles Mariannes du Nord",
    Norway: "Norvège",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palaos",
    "Palestinian Territory, Occupied": "Territoire palestinien occupé",
    Panama: "Panama",
    "Papua New Guinea": "Papouasie Nouvelle Guinée",
    Paraguay: "Paraguay",
    Peru: "Pérou",
    Philippines: "Philippines",
    Pitcairn: "Pitcairn",
    Poland: "Pologne",
    Portugal: "le Portugal",
    "Puerto Rico": "Porto Rico",
    Qatar: "Qatar",
    Reunion: "Réunion",
    Romania: "Roumanie",
    "Russian Federation": "Fédération Russe",
    RWANDA: "RWANDA",
    "Saint Helena": "Sainte-Hélène",
    "Saint Kitts and Nevis": "Saint-Christophe-et-Niévès",
    "Saint Lucia": "Sainte-Lucie",
    "Saint Pierre and Miquelon": "Saint-Pierre-et-Miquelon",
    "Saint Vincent and the Grenadines": "Saint-Vincent-et-les-Grenadines",
    Samoa: "Samoa",
    "San Marino": "Saint Marin",
    "Sao Tome and Principe": "Sao Tomé et Principe",
    "Saudi Arabia": "Arabie Saoudite",
    Senegal: "Sénégal",
    Serbia: "Serbie",
    Seychelles: "les Seychelles",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapour",
    Slovakia: "Slovaquie",
    Slovenia: "Slovénie",
    "Solomon Islands": "Les îles Salomon",
    Somalia: "Somalie",
    "South Africa": "Afrique du Sud",
    "South Georgia and the South Sandwich Islands": "Géorgie du Sud et îles Sandwich du Sud",
    Spain: "Espagne",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Soudan",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard et Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Suède",
    Switzerland: "Suisse",
    "Syrian Arab Republic": "République arabe syrienne",
    "Taiwan, Province of China": "Taiwan, Province de Chine",
    Tajikistan: "Tadjikistan",
    "Tanzania, United Republic of": "Tanzanie, République-Unie de",
    Thailand: "Thaïlande",
    "Timor-Leste": "Timor-Leste",
    Togo: "Aller",
    Tokelau: "Tokélaou",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd et Tobago",
    Tunisia: "Tunisie",
    Turkey: "Turquie",
    Turkmenistan: "Turkménistan",
    "Turks and Caicos Islands": "îles Turques-et-Caïques",
    Tuvalu: "Tuvalu",
    Uganda: "Ouganda",
    Ukraine: "Ukraine",
    "United Arab Emirates": "Emirats Arabes Unis",
    "United Kingdom": "Royaume-Uni",
    "United States Minor Outlying Islands": "Îles mineures éloignées des États-Unis",
    Uruguay: "Uruguay",
    Uzbekistan: "Ouzbékistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Viet Nam",
    "Virgin Islands, British": "Îles Vierges britanniques",
    "Virgin Islands, U.S.": "Îles Vierges, États-Unis",
    "Wallis and Futuna": "Wallis et Futuna",
    "Western Sahara": "Sahara occidental",
    Yemen: "Yémen",
    Zambia: "Zambie",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Débloquez tous les schémas avec notre plan Premium",
    "Billed Monthly": "Facturé mensuellement",
    "Billed Annually": "Facturé annuellement",
    "Save 30%": "Économisez 30 %",
    Premium100Title:
      "En tant qu'utilisateur précoce, nous vous assurons que vous profiterez gratuitement de toutes nos fonctionnalités premium. Vous n'avez pas à vous soucier de la page de tarification car vous pouvez accéder librement à toutes nos fonctionnalités premium sans aucun frais. Veuillez ne pas désinstaller notre application pour continuer à profiter de notre service.",
    Premium100ReviewLine:
      " Si vous aimez notre application, laissez-nous votre avis. Cela nous aide à nous motiver à développer de nouvelles fonctionnalités.",
    "Check Our Current Pricing": "Vérifiez nos prix actuels",
    "Leave Review": "Laisser un avis",
    "We're sorry to see you go!": "Nous sommes désolés de te voir partir!",
    "Cancel Plan": "Annuler le forfait",
    "Sync Plan": "Plan de synchronisation",
    "Disccount applied": "Remise appliquée",
    Apply: "Appliquer",
    "Your code(s)": "Votre(vos) code(s)",
    "and discount have been applied successfully": "et la remise a été appliquée avec succès",
    "Your entered promocode is not correct, Enter a valid code":
      "Votre code promo saisi n'est pas correct, saisissez un code valide",
    "days trial left": "jours d'essai restants",
    Upgrade: "Mise à niveau",
    "days free trial, No Credit card required": "jours d'essai gratuit, aucune carte de crédit requise",
    Month: "Mois",
    Year: "Année",
    Unlimited: "Illimité",
    "Enter Promocode": "Saisir le code promotionnel",
    "Please Choose a Cancellation Reason": "Veuillez choisir un motif d'annulation",
    "No Longer Needed?": "Ne sont plus nécessaires?",
    "Didn't Meet Expectations": "N'a pas répondu aux attentes",
    "Cost Concerns": "Problèmes de coûts",
    "Technical Issues": "Problèmes techniques",
    "Found an Alternative": "J'ai trouvé une alternative",
    Complexity: "Complexité",
    "Lack of Features": "Manque de fonctionnalités",
    "Poor Customer Support": "Mauvais support client",
    "Business Closure or Change": "Fermeture ou changement d'entreprise",
    "Temporary Pause": "Pause temporaire",
    "Performance Issues": "Les problèmes de performance",
    Other: "Autre",
    "Mention Your Specific Reason Here": "Mentionnez votre raison spécifique ici",
    Start: "Commencer",
    "Day Free Trial": "Essai gratuit d'une journée",
    "Please Select One Option": "Veuillez sélectionner une option",
    "Plan cancelled successfully": "Plan annulé avec succès",
    "7 days free trial, No Credit card required": "Essai gratuit de 7 jours, aucune carte de crédit requise",
    "Your remaining trial days are": "Vos jours d'essai restants sont",
    "You have used": "Vous avez utilisé",
    "days.": "jours.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Il ne reste plus aucun jour d'essai. Vous avez déjà utilisé l'essai gratuit de 7 jours.",
    "Upgrade your plan now": "Mettez à niveau votre forfait maintenant",
    "Unlimited Slides": "Diapositives illimitées",
    "20+ Animation In & Out": "20+ animations entrantes et sortantes",
    "Live Chat Support": "Assistance par chat en direct",
    "Priority, 24*7 Urgent setup and support": "Priorité, 24h/24 et 7j/7, configuration et assistance urgentes",
    "Rich Text Editor": "Éditeur de texte enrichi",
    "One Slide(banner)": "Une diapositive (bannière)",
    "Repeated Countdown timer": "Compte à rebours répété",
    "Fully Customisable": "Entièrement personnalisable",
    "Background-image": "Image de fond",
    "Custom Css": "CSS personnalisé",
    "Enable Our App": "Activer notre application",
    "Book Onboarding Demo": "Réserver une démo d'intégration",
    Next: "Suivant",
    Finish: "Finition",
    Prev: "Précédent",
    "App is not enable please click on the Enable App button to enable it.":
      "L'application n'est pas activée, veuillez cliquer sur le bouton Activer l'application pour l'activer.",
    "This field is required": "Ce champ est obligatoire",
    disableButtonTooltip:
      "Vous ne pouvez pas mettre à niveau le forfait mensuel car vous êtes sur un forfait annuel !",
    "Choose plan": "Choisir le forfait",
    "Purchase Plan": "Plan d'achat",
    Continue: "Continuer",
    "Image Optimization": "Optimisation des images",
    "AI Metatags": "Balises méta IA",
    "Grand Total": "Total",
    "Metatags Edit": "Balises méta Modifier",
    Products: "Des produits",
    "Upgrade plan": "Plan de mise à niveau",
    "Your product count is": "Votre nombre de produits est",
    "so your suitable plan is": "donc votre plan approprié est",
    "Enjoy a": "Profitez d'un",
    "lifetime discount": "réduction à vie",
    discountBanner:
      " Bénéficiez d'une remise à vie, garantissant des économies perpétuelles et améliorant votre expérience avec nos produits et services haut de gamme.",
    "Images for Optimization every year after trial period end":
      "Images pour l'optimisation chaque année après la fin de la période d'essai",
    "AI Meta Tags Credit for every year after trial period end":
      "Crédit de balises méta AI pour chaque année après la fin de la période d'essai",
    "Images for Optimization every month after trial period end":
      "Images à optimiser chaque mois après la fin de la période d'essai",
    "AI Meta Tags Credit for every Month after trial period end":
      "Crédit de balises méta AI pour chaque mois après la fin de la période d'essai",
    "Optimize your google page speed": "Optimisez la vitesse de votre page Google",
    "50 Product Meta tags Optimize, Image alt": "50 balises Meta de produit Optimiser, Image alt",
    "Product Meta tags Optimize, Image alt": "Balises méta du produit Optimiser, Image alt",
    "AI ImageAltText Credit for every year after trial period end":
      "Crédit AI ImageAltText pour chaque année après la fin de la période d'essai",
    "25 AI ImageAltText Credit": "25 Crédit AI ImageAltText",
    "AI ImageAltText Credit for every Month after trial period end":
      "Crédit AI ImageAltText pour chaque mois après la fin de la période d'essai",
    "Contact Bar": "Barre de contact",
    "Add To Cart Bar": "Barre Ajouter au panier",
    "Multiple Position": "Positions multiples",
    lowMsgStart:
      "Cette offre est spécialement conçue pour vous, car vous venez de démarrer votre boutique Shopify",
    lowMsgMiddle: "Notre",
    lowMsgEnd: "la réduction est notre façon de vous soutenir pendant ces temps difficiles mais passionnants.",
    mediumMsgStart:
      "Cette offre est spécialement conçue pour vous, alors que vous avez démarré votre boutique Shopify",
    mediumMsgMiddle: "Notre",
    mediumMsgEnd: "la réduction est notre façon de vous soutenir pendant ces temps difficiles mais passionnants.",
    importantMsgStart:
      "Cette offre est spécialement conçue pour vous, alors que vous avez démarré votre boutique Shopify",
    importantMsgMiddle: "Notre",
    importantMsgEnd:
      "la réduction est notre façon de vous soutenir pendant ces temps difficiles mais passionnants.",
    veryImportantMsgStart:
      "Cette offre est spécialement conçue pour vous, puisque vous avez ouvert votre boutique Shopify",
    veryImportantMsgMiddle: "Vous êtes pour nous un commerçant très important et mature. Notre",
    veryImportantMsgEnd: "la réduction est de montrer à quel point vous comptez pour nous.",
    generalMsg:
      "Notre application Shopify est conçue pour répondre aux besoins des entreprises établies comme la vôtre. Il est conçu pour gérer des volumes élevés et des opérations complexes de manière transparente. ",
    lowTitleStart: "Soutien spécial aux nouveaux entrepreneurs :",
    lowTitleEnd: "Remise alors que vous venez de commencer",
    mediumTitleStart: "Soutien spécial aux entrepreneurs :",
    mediumTitleEnd: "Remise dès que vous avez commencé",
    importantTitleStart: "Soutien spécial aux entrepreneurs :",
    importantTitleEnd: "Remise dès que vous avez commencé",
    veryImportantTitleStart: "Félicitations d'être",
    veryImportantTitleEnd: "dans Shopify",
    month: "mois",
    "year and": "année et",
    ago: "il y a",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Ajouter un crédit AI (1 crédit AI/10 ¢) (10 crédits AI/1 $)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Ajouter une image altText Crédit AI (1 crédit AI/4 ¢) (25 crédits AI/1 $)",
    "Monthly AI AltText Credit": "Crédit mensuel AI AltText",
    "Yearly AI AltText Credit": "Crédit annuel AI AltText",
    "Purchase AI AltText Credit": "Acheter du crédit AI AltText",
    "ImageAltText Credit": "Crédit ImageAltText",
    "Your credits are finished; please upgrade your plan.":
      "Vos crédits sont terminés ; veuillez mettre à niveau votre forfait.",
    "Your credits are finished; you can buy more credits from here.":
      "Vos crédits sont terminés ; vous pouvez acheter plus de crédits ici.",
    "This offer expire in": "Cette offre expire dans",
    "Hurry Up!": "Dépêche-toi!",
    Current: "Actuel",
    "Discount applied": "Remise appliquée",
    "trial left": "procès restant",
    "info banner":
      "Lorsque vous cliquez sur le bouton Analyser l'image de la page d'accueil, notre application analysera uniquement l'image de la page d'accueil. Pour optimiser cette image, veuillez cliquer manuellement sur le bouton Optimiser.",
    "Optimize Images": "Optimiser les images",
    image: "image",
    images: "images",
    Filename: "Nom de fichier",
    Images: "Images",
    Setting: "Paramètre",
    "Saved(in %)": "Économisé(en %)",
    Action: "Action",
    "Product Image": "Image du produit",
    "product image": "image du produit",
    gif: "gif",
    Homepage: "Page d'accueil",
    "Manage Announcement": "Gérer l'annonce",
    "No Announcements Found": "Aucune annonce trouvée",
    Position: "Position",
    "Campaign Title": "Titre de la campagne",
    Visible: "Visible",
    Invisible: "Invisible",
    Views: "Vues",
    Clicks: "Clics",
    Submits: "Soumet",
    "Above Add to cart Button": "Bouton Ajouter au panier ci-dessus",
    "Below Add to cart Button": "Ci-dessous le bouton Ajouter au panier",
    Targeting: "Ciblage",
    "Rotating Animation Setting": "Paramètres d'animation rotatifs",
    "Marquee Animation Setting": "Paramètre d'animation de chapiteau",
    "Show to visitors coming form then specific website": "Montrer aux visiteurs venant d'un site Web spécifique",
    "Add your website URL": "Ajoutez l'URL de votre site Web",
    "Banner Display Start Time": "Heure de début d'affichage de la bannière",
    "Banner Display End Time": "Heure de fin d'affichage de la bannière",
    "Create Campaign": "Créer une campagne",
    "Select Announcement Bar": "Sélectionner la barre d'annonce",
    "Please select template.": "Veuillez sélectionner un modèle.",
    Previous: "Précédent",
    "Promotion bar": "Barre de promotion",
    "Add To Cart": "Ajouter au panier",
    Embeded: "Intégré",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Alertez les clients des ventes et des offres à venir ou définissez des alertes d'inventaire.",
    "Increase your order value by using or Free Shipping Bar.":
      "Augmentez la valeur de votre commande en utilisant notre barre de livraison gratuite.",
    "Conveniently add items to your cart with a single click!":
      "Ajoutez facilement des articles à votre panier en un seul clic !",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Sélectionnez pour vous abonner et recevoir des remises spéciales directement dans votre boîte de réception",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Mettez en valeur vos offres spéciales avec une barre intégrée, affichée avant et après le bouton Ajouter au panier.",
    Select: "Sélectionner",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Ajouter un code UTM pour masquer la bannière (par exemple, Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Inclure UTM",
    "Exclude Utm": "Exclure UTM",
    "Campaign Design": "Conception de campagne",
    "Background Setting": "Réglage de l'arrière-plan",
    "Target Setting": "Définition des objectifs",
    Scheduling: "Programmation",
    Rotating: "Tournant",
    Marquee: "Chapiteau",
    "Repeat Timer Date": "Répéter la date de la minuterie",
    "Select Repeat Time": "Sélectionner l'heure de répétition",
    "Repeated Hours": "Heures répétées",
    Border: "Frontière",
    Bashed: "Défoncé",
    "Multi Rotating": "Multi-rotation",
    Contacts: "Contacts",
    Email: "E-mail",
    "First Name": "Prénom",
    "Last Name": "Nom de famille",
    Phone: "Téléphone",
    "You have unsaved changes": "Vous avez des changements non enregistrés",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Votre campagne comporte des modifications non enregistrées. Les modifications seront perdues si vous quittez sans enregistrer.",
    "Leave widthout saving": "Laisser l'économie de largeur",
    "Save Changes": "Sauvegarder les modifications",
    Announcement: "Annonce",
    Feedback: "Retour",
    "Recipe Instructions": "Instructions pour la recette",
    "Visit Help Center": "Visitez le centre d'aide",
    "Schedule Meeting": "Planifier une réunion",
    "Setup guide": "Guide d'installation",
    "Use this personalized guide to get your store up and running":
      "Utilisez ce guide personnalisé pour rendre votre boutique opérationnelle",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Pour commencer à obtenir les actions dont vous avez besoin pour activer notre application, cliquez sur le bouton pour accéder à la page des extensions, puis il vous suffit de cliquer sur Enregistrer ici et de revenir ici.",
    "Enable our app": "Activer notre application",
    "Learn more": "Apprendre encore plus",
    "Skip it": "Sauter",
    steps: "pas",
    minutes: "minutes",
    "Mark as done": "marque comme Terminé",
    "Mark as not done": "Marquer comme terminé",
    "You have completed all the steps": "Vous avez complété toutes les étapes",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Activez et analysez la vitesse de votre site pour classer votre boutique plus haut dans les résultats de recherche.",
    "Google Page Speed Optimization": "Optimisation de la vitesse des pages Google",
    "Activate Google Page Speed": "Activer la vitesse des pages Google",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Activez l'outil Google Page Speed pour évaluer les performances de votre site et identifier les opportunités d'amélioration de la vitesse.",
    "Enable Speed Analysis": "Activer l'analyse de la vitesse",
    "Review Speed Analysis Report": "Examiner le rapport d'analyse de la vitesse",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Examinez le rapport détaillé d'analyse de la vitesse pour comprendre les mesures de vitesse actuelles de votre site et identifier les domaines à améliorer.",
    "Go to Reports": "Aller aux rapports",
    Hello: "Bonjour",
    "Let's get your store ready for success": "Préparons votre magasin au succès",
    "Finish later": "Terminer plus tard",
    "Continue onboarding": "Continuer l'intégration",
    "Check image optimization features": "Vérifier les fonctionnalités d'optimisation d'image",
    "Explore Optimization Features": "Explorer les fonctionnalités d'optimisation",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Familiarisez-vous avec la gamme d’outils d’optimisation d’image disponibles. Découvrez comment vous pouvez améliorer les vitesses de chargement des pages et le référencement en optimisant la taille et les formats des images.",
    "Go to Image Optimization": "Accédez à Optimisation d'image",
    "Automate Your Image Workflow": "Automatisez votre flux de travail d'images",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Configurez l'automatisation pour optimiser de manière transparente les nouvelles images au fur et à mesure de leur téléchargement, garantissant ainsi des performances cohérentes sur l'ensemble de votre site.",
    "Go to Automation": "Aller à l'automatisation",
    "Execute a Bulk Optimization": "Exécuter une optimisation groupée",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Effectuez une optimisation groupée pour améliorer efficacement plusieurs images à la fois, ce qui peut augmenter considérablement le temps de chargement de votre site.",
    "Go to bulk operations": "Accéder aux opérations groupées",
    "Broken Links Management": "Gestion des liens brisés",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatisez la détection et la réparation des liens brisés pour améliorer l'expérience utilisateur et les classements SEO.",
    "Review Detected Broken Links": "Examiner les liens brisés détectés",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Examinez la liste des liens rompus identifiés automatiquement par notre système pour comprendre leur impact sur la navigation de votre site.",
    "View Broken Links": "Afficher les liens brisés",
    "Address Broken Links": "Résoudre les liens brisés",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Utilisez nos outils pour réparer ou rediriger rapidement les liens brisés, améliorant ainsi l'intégrité de votre site et la satisfaction des utilisateurs.",
    "Resolve Broken Links": "Résoudre les liens brisés",
    "Automate for Efficiency": "Automatisez pour plus d'efficacité",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Configurez un correctif automatisé pour garder une longueur d'avance sur tout futur lien rompu, garantissant ainsi la santé continue du site.",
    "Enable Automation": "Activer l'automatisation",
    "Meta Tags Management": "Gestion des balises méta",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Optimisez la visibilité de votre site et le classement dans les moteurs de recherche grâce à notre fonctionnalité conviviale de balises méta.",
    "Explore Meta Tag Options": "Explorez les options de balises méta",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Familiarisez-vous avec les différentes options d'édition et d'automatisation des balises méta disponibles pour les produits et les pages individuels.",
    "Explore Meta Tags": "Explorer les balises méta",
    "Edit and Optimize": "Modifier et optimiser",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Plongez dans l'édition de méta-titres, de descriptions et de textes alternatifs d'images pour améliorer le référencement de votre site et l'accessibilité des utilisateurs.",
    "Start Editing": "Commencer l'édition",
    "Automate for Consistency": "Automatiser pour plus de cohérence",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Configurez des règles d'automatisation pour vos balises méta afin de maintenir la cohérence et l'efficacité sur vos pages de produits.",
    "Set Automation": "Définir l'automatisation",
    "Schema Markup": "Balisage de schéma",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Utilisez le balisage Schema pour améliorer la représentation de votre contenu dans les résultats de recherche et attirer plus de clics.",
    "Learn About Schema Options": "En savoir plus sur les options de schéma",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Familiarisez-vous avec les différents types de balises de schéma disponibles, telles que Produit, Entreprise locale, FAQ, etc., pour comprendre leurs avantages.",
    "Explore Schema Types": "Explorer les types de schémas",
    "Activate Key Schemas": "Activer les schémas de clés",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Choisissez et activez des schémas cruciaux pour votre site, comme le schéma de produit pour le commerce électronique ou le schéma d'entreprise local pour les magasins physiques.",
    "Go to Schemas": "Aller aux schémas",
    "Customize Schema Details": "Personnaliser les détails du schéma",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Personnalisez les paramètres de chaque type de schéma pour représenter avec précision votre entreprise ou vos produits dans les résultats de recherche.",
    "Test and Validate Schemas": "Tester et valider les schémas",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Testez vos schémas à l'aide d'outils tels que l'outil de test de données structurées de Google pour vous assurer qu'ils sont correctement implémentés.",
    "Test Schemas": "Schémas de test",
    "Add Breadcrumbs": "Ajouter de la chapelure",
    "Add Breadcrumbs to your store": "Ajoutez du fil d'Ariane à votre boutique",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Pour obtenir une meilleure expérience utilisateur, vous devez ajouter un fil d'Ariane à votre boutique.",
    "How to add breadcrumbs": "Comment ajouter de la chapelure",
    "Understand how to add and configure breadcrumbs in your store.":
      "Comprenez comment ajouter et configurer le fil d'Ariane dans votre boutique.",
    "Google search console": "Console de recherche Google",
    "Connect google search console to sync it with our app.":
      "Connectez la console de recherche Google pour la synchroniser avec notre application.",
    "How to connect GSC.": "Comment connecter GSC.",
    "Understand how to connect and use google search console in our app.":
      "Comprenez comment vous connecter et utiliser la console de recherche Google dans notre application.",
    "Go to GSC": "Aller à GSC",
    "Go to Breadcrumbs Design": "Aller à la conception du fil d'Ariane",
    "Start Onboarding": "Commencer l'intégration",
    "Go to Homepage": "Aller à la page d'accueil",
    "Go to Onboarding": "Aller à l'intégration",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Explorez notre guide d'application convivial conçu pour améliorer votre compréhension. Cliquez sur « Démarrer l'intégration » pour commencer et vous pourrez revenir à la page d'accueil à tout moment.",
    "Please enable our app extension.": "Veuillez activer notre extension d'application.",
    "Generate Meta tags": "Générer des balises Meta",
    "Test description a litle bit longer that title": "Description du test un peu plus longue que le titre",
    "Suggested for you": "suggéré pour vous",
    "Enable Google page speed": "Activer la vitesse des pages Google",
    "Connect GSC": "Connecter GSC",
    "Enable Image Optimize Automation": "Activer l'automatisation de l'optimisation des images",
    "Automate Meta tags": "Automatiser les balises Meta",
    "Automate Broken Links": "Automatisez les liens brisés",
    "Enhance SEO with automatically generated meta tags.":
      "Améliorez le référencement avec des balises méta générées automatiquement.",
    "Improve website performance by optimizing images.":
      "Améliorez les performances du site Web en optimisant les images.",
    "Boost website speed by enabling Google Page Speed.":
      "Augmentez la vitesse du site Web en activant Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Améliorez la visibilité de la recherche en vous connectant à Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Rationalisez l’optimisation des images avec des processus automatisés.",
    "Improve SEO by automating the generation of meta tags.":
      "Améliorez le référencement en automatisant la génération de balises méta.",
    "Improve UX with automated detect and handle, broken links.":
      "Améliorez l’UX grâce à la détection et à la gestion automatisées des liens rompus.",
    "Learn About Add Announcement": "En savoir plus sur l'ajout d'une annonce",
    "Skip And Add Announcement": "Passer et ajouter une annonce",
    "Learn more about": "En savoir plus sur",
    "Add Announcement": "Ajouter une annonce",
    "Announcement Bar": "Barre d'annonce",
    "Rate us!": "Évaluez nous!",
    "How would you Love this app?": "Comment aimeriez-vous cette application ?",
    "Enter Your Feedback Here": "Entrez vos commentaires ici",
    "Leave Us a Review !!": "Laissez-nous un commentaire !!",
    "If you like our app features then please leave us a review !!":
      "Si vous aimez les fonctionnalités de notre application, laissez-nous un commentaire !!",
    "If you like our free features then please leave us a review !!":
      "Si vous aimez nos fonctionnalités gratuites, laissez-nous un commentaire !!",
    "Update Successfully": "Mise à jour réussie",
    "Uninstall App": "Désinstaller l'application",
    "Contact Our Support": "Contactez notre assistance",
    "Leave a message": "Laisser un message",
    "Please Choose a UnInstallation Reason": "Veuillez choisir une raison de désinstallation",
    "Are you facing any issues understanding the features of our app?":
      "Rencontrez-vous des problèmes pour comprendre les fonctionnalités de notre application ?",
    "Please Choose at least one reason": "Veuillez choisir au moins une raison",
    "Thank You For Reaching Out": "Merci d'avoir tendu la main",
    "Contact Support": "Contactez le support",
    "Get Help from Our Support Team": "Obtenez de l'aide de notre équipe d'assistance",
    "Select a reason": "Sélectionnez une raison",
    "Not getting how to use or setup": "Je ne comprends pas comment utiliser ou configurer",
    "Poor customer support": "Mauvais support client",
    "Performance issues": "Les problèmes de performance",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Notre équipe d'assistance est actuellement indisponible le week-end et sera disponible en semaine selon votre fuseau horaire à partir de ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " car nous opérons depuis l’Inde. Vous pouvez toujours laisser un message. Veuillez vous attendre à un certain retard dans notre réponse. Merci pour votre patience.",
    "Our support team is partially available according to your time zone from ":
      "Notre équipe d'assistance est partiellement disponible en fonction de votre fuseau horaire à partir de ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " car nous opérons depuis l’Inde. Les réponses peuvent prendre de 30 minutes à une heure pendant cette période. Veuillez laisser un message et nous vous répondrons dans les plus brefs délais. Merci pour votre patience.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Notre équipe d'assistance est actuellement indisponible et sera disponible en fonction de votre fuseau horaire à partir de ",
    to: "à",
    "Did not meet my expectations": "N'a pas répondu à mes attentes",
    "Feature Limitations": "Limites des fonctionnalités",
    "Banner doesn't set in my app": "La bannière ne s'installe pas dans mon application",
    "Banner is not show properly": "La bannière ne s'affiche pas correctement",
    "Confusing Set Multi Position and Multi Animation":
      "Ensemble confus de positions multiples et d'animations multiples",
    "Sync Profile": "Synchroniser le profil",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
