import modifyData from "../Language/hi.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "सक्रिय",
    Disabled: "अक्षम",
    "Embed is currently disabled": "एंबेड वर्तमान में अक्षम है",
    "Enable App": "ऐप सक्षम करें",
    "1. Click on Enable App.": "1. इनेबल ऐप पर क्लिक करें।",
    "Well done!! you have successfully enable our app.":
      "बहुत अच्छा!! आपने हमारे ऐप को सफलतापूर्वक सक्षम कर दिया है।",
    "2. Enable": "2. सक्षम करें",
    "App Embed as shown in image and save setting.": "छवि में दिखाए अनुसार ऐप एम्बेड करें और सेटिंग सहेजें।",
    "Multi Announcement Bar": "मल्टी अनाउंसमेंट बार",
    "Click on the Enable Now button to enable it.": "इसे सक्षम करने के लिए Enable Now बटन पर क्लिक करें।",
    "Enable Announcement Bar to get started": "आरंभ करने के लिए घोषणा बार सक्षम करें",
    "Enable Now": "अभी सक्षम करें",
    "Sync Status": "सिंक स्थिति",
    Done: "हो गया",
    No: "नहीं",
    Found: "मिला",
    Add: "जोड़ना",
    Search: "खोज",
    Showing: "दिखा",
    of: "का",
    "results, at most": "परिणाम, अधिकतम",
    "per page": "प्रति पृष्ठ",
    "Oops! Something went wrong.": "उफ़! कुछ गलत हो गया।",
    "Let's try that again, please refresh the page.": "आइए फिर से प्रयास करें, कृपया पृष्ठ को ताज़ा करें।",
    "If you're still stuck, contact us by chat support or":
      "यदि आप अभी भी फंसे हुए हैं, तो चैट समर्थन या द्वारा हमसे संपर्क करें",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "तो हम मदद कर सकते हैं!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "कोई भी 3 सुविधा चुनें जिसे आप उच्च प्राथमिकता या सर्वाधिक रुचि के आधार पर सेटअप करना चाहते हैं",
    "Add ": "जोड़ना ",
    "These is premium feature": "ये प्रीमियम फीचर है",
    "Go to pricing": "मूल्य निर्धारण पर जाएँ",
    Save: "बचाना",
    Minimum: "न्यूनतम",
    Maximum: "अधिकतम",
    "images are required": "छवियाँ आवश्यक हैं",
    and: "और",
    "images are allowed": "छवियों की अनुमति है",
    Disconnect: "डिस्कनेक्ट",
    "Sign In with Google": "Google से साइन इन करें",
    "Oops! Something went wrong. Admin token is malformed": "उफ़! कुछ गलत हो गया। एडमिन टोकन ख़राब है",
    "If you're still stuck, contact": "यदि आप अभी भी फंसे हैं तो संपर्क करें",
    Premium: "अधिमूल्य",
    Unlock: "अनलॉक",
    "Unlock advanced features!": "उन्नत सुविधाएँ अनलॉक करें!",
    "© 2021 Webrex. All rights reserved.": "© 2021 वेबरेक्स। सर्वाधिकार सुरक्षित।",
    "Privacy Policy": "गोपनीयता नीति",
    "Terms of Service": "सेवा की शर्तें",
    "Go to Shopify App": "शॉपिफाई ऐप पर जाएं",
    "Review Us": "हमारी समीक्षा करें",
    Cancel: "रद्द करना",
    "Review Popup Show": "पॉपअप शो की समीक्षा करें",
    "click on review us": "हमारी समीक्षा करें पर क्लिक करें",
    "Note: Feel free to leave a star rating without writing a review!":
      "नोट: समीक्षा लिखे बिना बेझिझक स्टार रेटिंग छोड़ें!",
    Help: "मदद",
    "Help Button Click": "सहायता बटन क्लिक करें",
    Confirm: "पुष्टि करना",
    On: "पर",
    Off: "बंद",
    Price: "कीमत",
    Settings: "समायोजन",
    Animation: "एनिमेशन",
    "My Profile": "मेरी प्रोफाइल",
    "My Subscription": "मेरी सदस्यता",
    "Store Name": "स्टोर नाम",
    "Store URL": "स्टोर यूआरएल",
    "Email ID": "ईमेल आईडी",
    "Phone Number": "फ़ोन नंबर",
    Country: "देश",
    Currency: "मुद्रा",
    "Subscription Name": "सदस्यता का नाम",
    "Select language": "भाषा चुने",
    "Announcement setting": "घोषणा सेटिंग",
    "Animation setting": "एनिमेशन सेटिंग",
    Selector: "चयनकर्ता",
    "Save Setting": "सेटिंग को बचाएं",
    "My Announcements": "मेरी घोषणाएँ",
    "Add bar": "बार जोड़ें",
    Number: "संख्या",
    Title: "शीर्षक",
    "Create At": "यहां बनाएं",
    "Slide Activation": "स्लाइड सक्रियण",
    Status: "स्थिति",
    Actions: "कार्रवाई",
    "Save order": "ऑर्डर सहेजें",
    "Reorder Slides": "स्लाइडों को पुन: व्यवस्थित करें",
    position: "पद",
    Top: "शीर्ष",
    "Sticky Top": "चिपचिपा शीर्ष",
    "Bottom Fix": "निचला भाग ठीक करें",
    "Custom Position": "कस्टम स्थिति",
    "Custom Position *Add Class or id of Selected Element.": "कस्टम स्थिति *चयनित तत्व की कक्षा या आईडी जोड़ें।",
    "Bar Padding (px)": "बार पैडिंग (पीएक्स)",
    "Add Remove Button": "निकालें बटन जोड़ें",
    "Choose icon color": "आइकन का रंग चुनें",
    "Custom css": "कस्टम सीएसएस",
    fadeIn: "फीका होना",
    fadeInDown: "फ़ेडइनडाउन",
    fadeInDownBig: "फ़ेडइनडाउनबिग",
    fadeInLeft: "फ़ेडइनलेफ़्ट",
    fadeInLeftBig: "फ़ेडइनलेफ़्टबिग",
    fadeInUp: "फ़ेडइनअप",
    bounceInDown: "बाउंसइनडाउन",
    bounceInLeft: "बाउंसइनलेफ्ट",
    bounceInUp: "बाउंसइनअप",
    zoomIn: "ज़ूम इन",
    zoomInDown: "ज़ूमइनडाउन",
    zoomInLeft: "ज़ूमइनलेफ्ट",
    slideInLeft: "स्लाइडइनलेफ्ट",
    slideInUp: "स्लाइडइनअप",
    slideInDown: "स्लाइडइनडाउन",
    lightSpeedIn: "लाइटस्पीडइन",
    rollIn: "रोलिंग",
    flash: "चमक",
    shake: "हिलाना",
    flip: "पलटना",
    flipInX: "फ्लिपइनएक्स",
    flipOutX: "फ्लिपआउटएक्स",
    fadeOut: "फेड आउट",
    fadeOutDown: "फ़ेडआउटडाउन",
    fadeOutDownBig: "फ़ेडऑउटडाउनबिग",
    fadeOutRight: "फ़ेडऑउटराइट",
    fadeOutRightBig: "फ़ेडऑउटराइटबिग",
    fadeOutUp: "फ़ेडआउटअप",
    bounceOutDown: "बाउंसआउटडाउन",
    bounceOutRight: "बाउंसआउटराइट",
    bounceOutUp: "बाउंसआउटअप",
    zoomOut: "ज़ूम आउट",
    zoomOutDown: "ज़ूमआउटडाउन",
    zoomOutRight: "ज़ूमऑउटराइट",
    slideOutRight: "स्लाइडआउटराइट",
    slideOutUp: "स्लाइडआउटअप",
    slideOutDown: "स्लाइडआउटडाउन",
    lightSpeedOut: "लाइटस्पीडआउट",
    rollOut: "रोल आउट",
    flipInY: "फ्लिपइनवाई",
    "Text Animation": "पाठ एनीमेशन",
    "Animation In": "एनीमेशन इन",
    "Animation Out": "एनिमेशन आउट",
    "Auto play time (time in MS)": "ऑटो प्ले टाइम (एमएस में समय)",
    "Animation time (time in MS)": "एनिमेशन समय (एमएस में समय)",
    "Auto play time (time in Second)": "ऑटो प्ले टाइम (सेकंड में समय)",
    "Background Color": "पृष्ठभूमि का रंग",
    "Space between slide(px)": "स्लाइड के बीच का स्थान(px)",
    visible: "दृश्यमान",
    invisible: "अदृश्य",
    "Promotional & Countdown Bar": "प्रमोशनल एवं काउंटडाउन बार",
    "Free Shipping Bar": "मुफ़्त शिपिंग बार",
    "Add Slide": "स्लाइड जोड़ें",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "निःशुल्क योजना के लिए केवल 1 स्लाइड दिखाई देती है। सभी स्लाइड्स को सक्रिय करने के लिए प्रीमियम प्लान की सदस्यता लें।",
    Pricing: "मूल्य निर्धारण",
    "No Animation Found": "कोई एनीमेशन नहीं मिला",
    "No Preview, Add announcement Bar": "कोई पूर्वावलोकन नहीं, घोषणा बार जोड़ें",
    "Update successfully": "सफलतापूर्वक अद्यतन करें",
    Enable: "सक्षम",
    Disable: "अक्षम करना",
    successfully: "सफलतापूर्वक",
    "Delete successfully": "सफलतापूर्वक हटाएं",
    "Copy successfully": "सफलतापूर्वक कॉपी करें",
    "Reorder successfully": "सफलतापूर्वक पुन: व्यवस्थित करें",
    "Announcement Message": "घोषणा संदेश",
    "Call to Action": "कार्यवाई के लिए बुलावा",
    Timer: "घड़ी",
    Style: "शैली",
    "Background Type": "पृष्ठभूमि प्रकार",
    "Mobile Style": "मोबाइल स्टाइल",
    "Schedule Display": "शेड्यूल प्रदर्शन",
    Update: "अद्यतन",
    "Change Font": "फ़ॉन्ट बदलें",
    "Font Family": "फुहारा परिवार",
    "Font Style": "लिपि शैली",
    Normal: "सामान्य",
    Italic: "तिरछा",
    Oblique: "परोक्ष",
    Unset: "अनसेट",
    "Font Weight": "फ़ॉन्ट वजन",
    Bold: "बोल्ड",
    "Message Font Size": "संदेश फ़ॉन्ट आकार",
    "Message Text color": "संदेश पाठ का रंग",
    Type: "प्रकार",
    None: "कोई नहीं",
    Button: "बटन",
    "Entire clickable bar": "संपूर्ण क्लिक करने योग्य बार",
    "Add a simple link": "एक सरल लिंक जोड़ें",
    "Add coupon placement": "कूपन प्लेसमेंट जोड़ें",
    "Linked Url": "लिंक किया गया यूआरएल",
    "Background Hover Color": "पृष्ठभूमि होवर रंग",
    "Text Hover Color": "टेक्स्ट होवर रंग",
    "Button Text": "टेक्स्ट बटन",
    "Copied Text": "कॉपी किया गया पाठ",
    "Open in the new tab": "नए टैब में खोलें",
    URL: "यूआरएल",
    "Font Size": "फ़ॉन्ट आकार",
    "Button Radius": "बटन त्रिज्या",
    "Button color": "बटन का रंग",
    "Button Text color": "बटन पाठ का रंग",
    "Button Hover Color": "बटन होवर रंग",
    "button Text HoverColor": "बटन टेक्स्ट होवर कलर",
    "Timer Setting": "टाइमर सेटिंग",
    "Timer Type": "टाइमर प्रकार",
    Date: "तारीख",
    "Select Reapt Time": "रिएप्ट टाइम का चयन करें",
    "repeated Hours": "बार-बार घंटे",
    "Normal Timer": "सामान्य टाइमर",
    "Auto repeat timer": "ऑटो रिपीट टाइमर",
    Minute: "मिनट",
    Hour: "घंटा",
    Day: "दिन",
    "Remove Timer When Time End": "समय समाप्त होने पर टाइमर हटा दें",
    "Timer Separator": "टाइमर सेपरेटर",
    "Countdown Timer color": "उलटी गिनती घड़ी का रंग",
    "Timer Text Size": "टाइमर पाठ का आकार",
    "Timer Text Setting": "टाइमर टेक्स्ट सेटिंग",
    "Day Text": "दिन का पाठ",
    "Hour Text": "घंटा पाठ",
    "Minute Text": "मिनट पाठ",
    "Second Text": "दूसरा पाठ",
    "Background Image": "पृष्ठभूमि छवि",
    "Gradient Background": "ग्रेडियेंट पृष्ठभूमि",
    "Style & Color For Mobile": "मोबाइल के लिए शैली और रंग",
    "Timer Background": "टाइमर पृष्ठभूमि",
    "Timer Text Color": "टाइमर टेक्स्ट का रंग",
    "Button Color": "बटन का रंग",
    "Button Text Color": "बटन पाठ का रंग",
    "Button Text Hover Color": "बटन टेक्स्ट होवर रंग",
    "Button Text Size": "बटन टेक्स्ट का आकार",
    "Always Display": "हमेशा प्रदर्शित करें",
    "Only Display Within The Following Period Of Time": "केवल निम्नलिखित समय अवधि के भीतर प्रदर्शित करें",
    "Start Time": "समय शुरू",
    "End Time": "अंत समय",
    "Advance Setting": "अग्रिम सेटिंग",
    "Country Filter": "देश फ़िल्टर",
    Visibility: "दृश्यता",
    "Desktop and Mobile": "डेस्कटॉप और मोबाइल",
    "Only Desktop": "केवल डेस्कटॉप",
    "Only Mobile": "केवल मोबाइल",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "उपयोगकर्ता स्रोत लक्ष्यीकरण (इस निम्नलिखित UTM कोड सहित एक लिंक से आने वाले विज़िटर, उदाहरण के लिए Ref=Facebook, Ref=Web,utm_source=Google...)",
    "Select Page": "पेज चुनें",
    Include: "शामिल करना",
    Exclude: "निकालना",
    "Currency Configuration": "मुद्रा विन्यास",
    Message: "संदेश",
    "Currency Symbol": "मुद्रा चिन्ह",
    "Currency Position": "मुद्रा स्थिति",
    Before: "पहले",
    After: "बाद",
    "money Class": "धन वर्ग",
    "Initial Message": "प्रारंभिक संदेश",
    "Shipping Goal": "शिपिंग लक्ष्य",
    "Progress Message": "प्रगति संदेश",
    "Progress goal": "प्रगति लक्ष्य",
    "Goal Message": "लक्ष्य संदेश",
    "Shipping Price Color": "शिपिंग मूल्य रंग",
    "Shipping Price Size": "शिपिंग मूल्य का आकार",
    "Shipping Font Weight": "शिपिंग फ़ॉन्ट वजन",
    "* When user first time visit": "* जब उपयोगकर्ता पहली बार विज़िट करता है",
    "* When user add item to the cart e.g": "* जब उपयोगकर्ता कार्ट में आइटम जोड़ता है जैसे:",
    "* When cart value is greater than": "* जब कार्ट का मूल्य इससे अधिक हो",
    "Show On Selected Countries": "चयनित देशों पर दिखाएँ",
    "Show On Selected Pages": "चयनित पृष्ठों पर दिखाएँ",
    All: "सभी",
    Home: "घर",
    Cart: "कार्ट",
    Collection: "संग्रह",
    Product: "उत्पाद",
    Custom: "रिवाज़",
    Page: "पृष्ठ",
    Blog: "ब्लॉग",
    "Url is required": "यूआरएल आवश्यक है",
    "Day Text is required": "दिन का पाठ आवश्यक है",
    "Hour Text is required": "घंटा पाठ आवश्यक है",
    "Minute Text is required": "मिनट पाठ आवश्यक है",
    "Second Text is required": "दूसरा पाठ आवश्यक है",
    "Start Time is required": "प्रारंभ समय आवश्यक है",
    "End Time is required": "समाप्ति समय आवश्यक है",
    "Created successfully": "सफलतापूर्वक बनाया गया",
    "United States": "संयुक्त राज्य अमेरिका",
    Canada: "कनाडा",
    Australia: "ऑस्ट्रेलिया",
    "New Zealand": "न्यूज़ीलैंड",
    Germany: "जर्मनी",
    India: "भारत",
    Afghanistan: "अफ़ग़ानिस्तान",
    "land Islands": "भूमि द्वीप",
    Albania: "अल्बानिया",
    Algeria: "एलजीरिया",
    "American Samoa": "अमेरिकी समोआ",
    AndorrA: "एंडोरा",
    Angola: "अंगोला",
    Anguilla: "एंगुइला",
    Antarctica: "अंटार्कटिका",
    "Antigua and Barbuda": "अण्टीगुआ और बारबूडा",
    Argentina: "अर्जेंटीना",
    Armenia: "आर्मीनिया",
    Aruba: "अरूबा",
    Austria: "ऑस्ट्रिया",
    Azerbaijan: "आज़रबाइजान",
    Bahamas: "बहामा",
    Bahrain: "बहरीन",
    Bangladesh: "बांग्लादेश",
    Barbados: "बारबाडोस",
    Belarus: "बेलोरूस",
    Belgium: "बेल्जियम",
    Belize: "बेलीज़",
    Benin: "बेनिन",
    Bermuda: "बरमूडा",
    Bhutan: "भूटान",
    Bolivia: "बोलीविया",
    "Bosnia and Herzegovina": "बोस्निया और हर्जेगोविना",
    Botswana: "बोत्सवाना",
    "Bouvet Island": "बाउवेट द्वीप",
    Brazil: "ब्राज़िल",
    "British Indian Ocean Territory": "ब्रिटेन और भारतीय समुद्री क्षेत्र",
    "Brunei Darussalam": "ब्रूनेइ्र दारएस्सलाम",
    Bulgaria: "बुल्गारिया",
    "Burkina Faso": "बुर्किना फासो",
    Burundi: "बुस्र्न्दी",
    Cambodia: "कंबोडिया",
    Cameroon: "कैमरून",
    "Cape Verde": "केप वर्ड",
    "Cayman Islands": "केमन द्वीपसमूह",
    "Central African Republic": "केन्द्रीय अफ़्रीकी गणराज्य",
    Chad: "काग़ज़ का टुकड़ा",
    Chile: "चिली",
    China: "चीन",
    "Christmas Island": "क्रिसमस द्वीप",
    "Cocos (Keeling) Islands": "कोकोस (कीलिंग) द्वीप समूह",
    Colombia: "कोलंबिया",
    Comoros: "कोमोरोस",
    Congo: "कांगो",
    "Congo, The Democratic Republic of the": "कांगो, लोकतांत्रिक गणराज्य",
    "Cook Islands": "कुक द्वीपसमूह",
    "Costa Rica": "कोस्टा रिका",
    "Cote D'Ivoire": "कोटे डी आइवर",
    Croatia: "क्रोएशिया",
    Cuba: "क्यूबा",
    Cyprus: "साइप्रस",
    "Czech Republic": "चेक रिपब्लिक",
    Denmark: "डेनमार्क",
    Djibouti: "ज़िबूटी",
    Dominica: "डोमिनिका",
    "Dominican Republic": "डोमिनिकन गणराज्य",
    Ecuador: "इक्वेडोर",
    Egypt: "मिस्र",
    "El Salvador": "अल साल्वाडोर",
    "Equatorial Guinea": "भूमध्यवर्ती गिनी",
    Eritrea: "इरिट्रिया",
    Estonia: "एस्तोनिया",
    Ethiopia: "इथियोपिया",
    "Falkland Islands (Malvinas)": "फ़ॉकलैंड द्वीप समूह (माल्विनास)",
    "Faroe Islands": "फ़ैरो द्वीप",
    Fiji: "फ़िजी",
    Finland: "फिनलैंड",
    France: "फ्रांस",
    "French Guiana": "फ्रेंच गयाना",
    "French Polynesia": "फ़्रेंच पोलिनेशिया",
    "French Southern Territories": "दक्षिणी फ्राँसिसी क्षेत्र",
    Gabon: "गैबॉन",
    Gambia: "गाम्बिया",
    Georgia: "जॉर्जिया",
    Ghana: "घाना",
    Gibraltar: "जिब्राल्टर",
    Greece: "यूनान",
    Greenland: "ग्रीनलैंड",
    Grenada: "ग्रेनेडा",
    Guadeloupe: "ग्वाडेलोप",
    Guam: "गुआम",
    Guatemala: "ग्वाटेमाला",
    Guernsey: "ग्वेर्नसे",
    Guinea: "गिनी",
    "Guinea-Bissau": "गिनी-बिसाऊ",
    Guyana: "गुयाना",
    Haiti: "हैती",
    "Heard Island and Mcdonald Islands": "हर्ड द्वीप और मैकडोनाल्ड द्वीप समूह",
    "Holy See (Vatican City State)": "होली सी (वेटिकन सिटी राज्य)",
    Honduras: "होंडुरस",
    "Hong Kong": "हांगकांग",
    Hungary: "हंगरी",
    Iceland: "आइसलैंड",
    Indonesia: "इंडोनेशिया",
    "Iran, Islamic Republic Of": "ईरान (इस्लामिक रिपब्लिक ऑफ",
    Iraq: "इराक",
    Ireland: "आयरलैंड",
    "Isle of Man": "मैन द्वीप",
    Israel: "इजराइल",
    Italy: "इटली",
    Jamaica: "जमैका",
    Japan: "जापान",
    Jersey: "जर्सी",
    Jordan: "जॉर्डन",
    Kazakhstan: "कजाखस्तान",
    Kenya: "केन्या",
    Kiribati: "किरिबाती",
    "Korea, Democratic People'S Republic of": "कोरिया प्रजातात्रिक जनवादी गणतंत्र",
    "Korea, Republic of": "कोरिया गणराज्य",
    Kuwait: "कुवैट",
    Kyrgyzstan: "किर्गिज़स्तान",
    "Lao People'S Democratic Republic": "लाओ पीपुल्स डेमोक्रेटिक रिपब्लिक",
    Latvia: "लातविया",
    Lebanon: "लेबनान",
    Lesotho: "लिसोटो",
    Liberia: "लाइबेरिया",
    "Libyan Arab Jamahiriya": "लीबिया का अरब जमहिरिया",
    Liechtenstein: "लिकटेंस्टाइन",
    Lithuania: "लिथुआनिया",
    Luxembourg: "लक्समबर्ग",
    Macao: "मकाओ",
    "Macedonia, The Former Yugoslav Republic of": "मैसेडोनिया, पूर्व यूगोस्लाव गणराज्य",
    Madagascar: "मेडागास्कर",
    Malawi: "मलावी",
    Malaysia: "मलेशिया",
    Maldives: "मालदीव",
    Mali: "माली",
    Malta: "माल्टा",
    "Marshall Islands": "मार्शल द्वीपसमूह",
    Martinique: "मार्टीनिक",
    Mauritania: "मॉरिटानिया",
    Mauritius: "मॉरीशस",
    Mayotte: "मैयट",
    Mexico: "मेक्सिको",
    "Micronesia, Federated States of": "माइक्रोनेशिया, संघीय राज्य",
    "Moldova, Republic of": "मोल्दोवा, गणराज्य",
    Monaco: "मोनाको",
    Mongolia: "मंगोलिया",
    Montenegro: "मोंटेनेग्रो",
    Montserrat: "मोंटेसेराट",
    Morocco: "मोरक्को",
    Mozambique: "मोज़ाम्बिक",
    Myanmar: "म्यांमार",
    Namibia: "नामिबिया",
    Nauru: "नाउरू",
    Nepal: "नेपाल",
    Netherlands: "नीदरलैंड",
    "Netherlands Antilles": "नीदरलैंड्स एंटाइल्स",
    "New Caledonia": "नया केलडोनिया",
    Nicaragua: "निकारागुआ",
    Niger: "नाइजर",
    Nigeria: "नाइजीरिया",
    Niue: "नियू",
    "Norfolk Island": "नॉरफ़ॉक द्वीप",
    "Northern Mariana Islands": "उत्तरी मरीयाना द्वीप समूह",
    Norway: "नॉर्वे",
    Oman: "ओमान",
    Pakistan: "पाकिस्तान",
    Palau: "पलाउ",
    "Palestinian Territory, Occupied": "अधिकृत फ़िलिस्तीन क्षेत्र",
    Panama: "पनामा",
    "Papua New Guinea": "पापुआ न्यू गिनी",
    Paraguay: "परागुआ",
    Peru: "पेरू",
    Philippines: "फिलिपींस",
    Pitcairn: "पिटकेर्न",
    Poland: "पोलैंड",
    Portugal: "पुर्तगाल",
    "Puerto Rico": "प्यूर्टो रिको",
    Qatar: "कतर",
    Reunion: "रीयूनियन",
    Romania: "रोमानिया",
    "Russian Federation": "रूसी संघ",
    RWANDA: "रवांडा",
    "Saint Helena": "सेंट हेलेना",
    "Saint Kitts and Nevis": "संत किट्ट्स और नेविस",
    "Saint Lucia": "सेंट लूसिया",
    "Saint Pierre and Miquelon": "सेंट पियरे और मिकेलॉन",
    "Saint Vincent and the Grenadines": "संत विंसेंट अँड थे ग्रेनडीनेस",
    Samoa: "समोआ",
    "San Marino": "सैन मारिनो",
    "Sao Tome and Principe": "साओ टोमे और प्रिंसिपे",
    "Saudi Arabia": "सऊदी अरब",
    Senegal: "सेनेगल",
    Serbia: "सर्बिया",
    Seychelles: "सेशल्स",
    "Sierra Leone": "सेरा लिओन",
    Singapore: "सिंगापुर",
    Slovakia: "स्लोवाकिया",
    Slovenia: "स्लोवेनिया",
    "Solomon Islands": "सोलोमन इस्लैंडस",
    Somalia: "सोमालिया",
    "South Africa": "दक्षिण अफ्रीका",
    "South Georgia and the South Sandwich Islands": "दक्षिण जॉर्जिया और दक्षिण सैंडविच द्वीप समूह",
    Spain: "स्पेन",
    "Sri Lanka": "श्रीलंका",
    Sudan: "सूडान",
    Surilabel: "सुरिलाबेल",
    "Svalbard and Jan Mayen": "स्वालबार्ड और जान मायेन",
    Swaziland: "स्वाजीलैंड",
    Sweden: "स्वीडन",
    Switzerland: "स्विट्ज़रलैंड",
    "Syrian Arab Republic": "सीरियाई अरब गणराज्य",
    "Taiwan, Province of China": "ताइवान, चीन प्रांत",
    Tajikistan: "तजाकिस्तान",
    "Tanzania, United Republic of": "तंजानिया, संयुक्त गणराज्य",
    Thailand: "थाईलैंड",
    "Timor-Leste": "तिमोर-लेस्ते",
    Togo: "चल देना",
    Tokelau: "टोकेलाऊ",
    Tonga: "टोंगा",
    "Triidd and Tobago": "ट्राइड और टोबैगो",
    Tunisia: "ट्यूनीशिया",
    Turkey: "टर्की",
    Turkmenistan: "तुर्कमेनिस्तान",
    "Turks and Caicos Islands": "तुर्क और कैकोस द्वीप समूह",
    Tuvalu: "तुवालू",
    Uganda: "युगांडा",
    Ukraine: "यूक्रेन",
    "United Arab Emirates": "संयुक्त अरब अमीरात",
    "United Kingdom": "यूनाइटेड किंगडम",
    "United States Minor Outlying Islands": "संयुक्त राज्य अमेरिका के छोटे दूरस्थ द्वीपसमूह",
    Uruguay: "उरुग्वे",
    Uzbekistan: "उज़्बेकिस्तान",
    Vanuatu: "वानुअतु",
    Venezuela: "वेनेज़ुएला",
    "Viet Nam": "वियतनाम",
    "Virgin Islands, British": "वर्जिन द्वीप समूह, ब्रिटिश",
    "Virgin Islands, U.S.": "वर्जिन द्वीपसमूह, यू.एस",
    "Wallis and Futuna": "वाली और फ़्युटुना",
    "Western Sahara": "पश्चिमी सहारा",
    Yemen: "यमन",
    Zambia: "जाम्बिया",
    Zimbabwe: "ज़िम्बाब्वे",
    "Unlock All Schema with our Premium Plan": "हमारे प्रीमियम प्लान के साथ सभी स्कीम अनलॉक करें",
    "Billed Monthly": "मासिक बिल भेजा गया",
    "Billed Annually": "सालाना बिल किया",
    "Save 30%": "30% बचाएं",
    Premium100Title:
      "एक शुरुआती उपयोगकर्ता के रूप में, हम आपको आश्वस्त करते हैं कि आप हमारी सभी प्रीमियम सुविधाओं का आनंद बिना किसी कीमत के उठाएंगे। मूल्य निर्धारण पृष्ठ के बारे में चिंतित होने की कोई आवश्यकता नहीं है क्योंकि आप बिना किसी शुल्क के हमारी सभी प्रीमियम सुविधाओं तक स्वतंत्र रूप से पहुंच सकते हैं। कृपया हमारी सेवा का आनंद लेना जारी रखने के लिए हमारे ऐप को अनइंस्टॉल न करें।",
    Premium100ReviewLine:
      " यदि आपको हमारा ऐप पसंद है तो कृपया हमें समीक्षा छोड़ें। इससे हमें नई सुविधाएँ विकसित करने के लिए प्रेरित होने में मदद मिलती है।",
    "Check Our Current Pricing": "हमारी वर्तमान कीमत जांचें",
    "Leave Review": "समीक्षा छोड़ें",
    "We're sorry to see you go!": "हमें खेद है कि आप जा रहे हैं!",
    "Cancel Plan": "योजना रद्द करें",
    "Sync Plan": "सिंक योजना",
    "Disccount applied": "छूट लागू",
    Apply: "आवेदन करना",
    "Your code(s)": "आपका कोड",
    "and discount have been applied successfully": "और छूट सफलतापूर्वक लागू कर दी गई है",
    "Your entered promocode is not correct, Enter a valid code":
      "आपका दर्ज किया गया प्रोमोकोड सही नहीं है, एक वैध कोड दर्ज करें",
    "days trial left": "कुछ दिन का ट्रायल बाकी है",
    Upgrade: "उन्नत करना",
    "days free trial, No Credit card required": "दिनों का निःशुल्क परीक्षण, किसी क्रेडिट कार्ड की आवश्यकता नहीं",
    Month: "महीना",
    Year: "वर्ष",
    Unlimited: "असीमित",
    "Enter Promocode": "प्रचार कि नियमावली दर्ज करो",
    "Please Choose a Cancellation Reason": "कृपया रद्दीकरण का कारण चुनें",
    "No Longer Needed?": "अब जरूरत नहीं?",
    "Didn't Meet Expectations": "उम्मीदों पर खरा नहीं उतरा",
    "Cost Concerns": "लागत संबंधी चिंताएँ",
    "Technical Issues": "तकनीकी मुद्दें",
    "Found an Alternative": "एक विकल्प मिला",
    Complexity: "जटिलता",
    "Lack of Features": "सुविधाओं का अभाव",
    "Poor Customer Support": "ख़राब ग्राहक सहायता",
    "Business Closure or Change": "व्यवसाय बंद होना या बदलना",
    "Temporary Pause": "अस्थायी विराम",
    "Performance Issues": "निष्पादन मुद्दे",
    Other: "अन्य",
    "Mention Your Specific Reason Here": "अपना विशिष्ट कारण यहां बताएं",
    Start: "शुरू",
    "Day Free Trial": "दिन का निःशुल्क परीक्षण",
    "Please Select One Option": "कृपया एक विकल्प चुनें",
    "Plan cancelled successfully": "योजना सफलतापूर्वक रद्द कर दी गई",
    "7 days free trial, No Credit card required": "7 दिन का निःशुल्क परीक्षण, किसी क्रेडिट कार्ड की आवश्यकता नहीं",
    "Your remaining trial days are": "आपके परीक्षण के शेष दिन हैं",
    "You have used": "आपने प्रयोग किया है",
    "days.": "दिन.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "कोई परीक्षण दिवस शेष नहीं है. आप पहले ही 7-दिवसीय निःशुल्क परीक्षण का उपयोग कर चुके हैं।",
    "Upgrade your plan now": "अभी अपना प्लान अपग्रेड करें",
    "Unlimited Slides": "असीमित स्लाइड",
    "20+ Animation In & Out": "20+ एनीमेशन अंदर और बाहर",
    "Live Chat Support": "लाइव चैट समर्थन",
    "Priority, 24*7 Urgent setup and support": "प्राथमिकता, 24*7 तत्काल सेटअप और समर्थन",
    "Rich Text Editor": "रिच टेक्स्ट एडिटर",
    "One Slide(banner)": "एक स्लाइड(बैनर)",
    "Repeated Countdown timer": "बार-बार उलटी गिनती घड़ी",
    "Fully Customisable": "पूरी तरह से अनुकूलन योग्य",
    "Background-image": "पृष्ठभूमि छवि",
    "Custom Css": "कस्टम सीएसएस",
    "Enable Our App": "हमारा ऐप सक्षम करें",
    "Book Onboarding Demo": "बुक ऑनबोर्डिंग डेमो",
    Next: "अगला",
    Finish: "खत्म करना",
    Prev: "पिछला",
    "App is not enable please click on the Enable App button to enable it.":
      "ऐप सक्षम नहीं है कृपया इसे सक्षम करने के लिए ऐप सक्षम करें बटन पर क्लिक करें।",
    "This field is required": "यह फ़ील्ड आवश्यक है",
    disableButtonTooltip: "आप मासिक योजना को अपग्रेड नहीं कर सकते क्योंकि आप वार्षिक योजना पर हैं!",
    "Choose plan": "योजना चुनें",
    "Purchase Plan": "खरीद योजना",
    Continue: "जारी रखना",
    "Image Optimization": "छवि अनुकूलन",
    "AI Metatags": "एआई मेटाटैग",
    "Grand Total": "कुल योग",
    "Metatags Edit": "मेटाटैग संपादित करें",
    Products: "उत्पादों",
    "Upgrade plan": "उन्नयन योजना",
    "Your product count is": "आपकी उत्पाद संख्या है",
    "so your suitable plan is": "तो आपकी उपयुक्त योजना है",
    "Enjoy a": "आनंद लें ए",
    "lifetime discount": "आजीवन छूट",
    discountBanner:
      " आजीवन छूट प्राप्त करें, सतत बचत सुनिश्चित करें और हमारे प्रीमियम उत्पादों और सेवाओं के साथ अपने अनुभव को बढ़ाएं।",
    "Images for Optimization every year after trial period end":
      "परीक्षण अवधि समाप्त होने के बाद हर साल अनुकूलन के लिए छवियां",
    "AI Meta Tags Credit for every year after trial period end":
      "परीक्षण अवधि समाप्त होने के बाद प्रत्येक वर्ष के लिए एआई मेटा टैग क्रेडिट",
    "Images for Optimization every month after trial period end":
      "परीक्षण अवधि समाप्त होने के बाद हर महीने अनुकूलन के लिए छवियां",
    "AI Meta Tags Credit for every Month after trial period end":
      "परीक्षण अवधि समाप्त होने के बाद हर महीने के लिए एआई मेटा टैग क्रेडिट",
    "Optimize your google page speed": "अपने Google पृष्ठ की गति को अनुकूलित करें",
    "50 Product Meta tags Optimize, Image alt": "50 उत्पाद मेटा टैग ऑप्टिमाइज़, छवि वैकल्पिक",
    "Product Meta tags Optimize, Image alt": "उत्पाद मेटा टैग ऑप्टिमाइज़, छवि वैकल्पिक",
    "AI ImageAltText Credit for every year after trial period end":
      "परीक्षण अवधि समाप्त होने के बाद प्रत्येक वर्ष के लिए AI ImageAltText क्रेडिट",
    "25 AI ImageAltText Credit": "25 AI ImageAltText क्रेडिट",
    "AI ImageAltText Credit for every Month after trial period end":
      "परीक्षण अवधि समाप्त होने के बाद हर महीने के लिए AI ImageAltText क्रेडिट",
    "Contact Bar": "संपर्क बार",
    "Add To Cart Bar": "कार्ट बार में जोड़ें",
    "Multiple Position": "एकाधिक स्थिति",
    lowMsgStart:
      "यह ऑफ़र विशेष रूप से आपके लिए डिज़ाइन किया गया है, क्योंकि आपने अभी-अभी अपना Shopify स्टोर शुरू किया है",
    lowMsgMiddle: "हमारा",
    lowMsgEnd: "डिस्काउंट इस चुनौतीपूर्ण लेकिन रोमांचक समय के दौरान आपका समर्थन करने का हमारा तरीका है।",
    mediumMsgStart:
      "यह ऑफ़र विशेष रूप से आपके लिए डिज़ाइन किया गया है, क्योंकि आपने अपना Shopify स्टोर शुरू कर दिया है",
    mediumMsgMiddle: "हमारा",
    mediumMsgEnd: "डिस्काउंट इस चुनौतीपूर्ण लेकिन रोमांचक समय के दौरान आपका समर्थन करने का हमारा तरीका है।",
    importantMsgStart:
      "यह ऑफ़र विशेष रूप से आपके लिए डिज़ाइन किया गया है, क्योंकि आपने अपना Shopify स्टोर शुरू कर दिया है",
    importantMsgMiddle: "हमारा",
    importantMsgEnd: "डिस्काउंट इस चुनौतीपूर्ण लेकिन रोमांचक समय के दौरान आपका समर्थन करने का हमारा तरीका है।",
    veryImportantMsgStart:
      "यह ऑफ़र विशेष रूप से आपके लिए डिज़ाइन किया गया है, क्योंकि आपने अपना Shopify स्टोर खोला है",
    veryImportantMsgMiddle: "आप हमारे लिए बहुत महत्वपूर्ण और परिपक्व व्यापारी हैं। हमारा",
    veryImportantMsgEnd: "छूट यह दिखाने के लिए है कि आप हमारे लिए कितना मायने रखते हैं।",
    generalMsg:
      "हमारा Shopify ऐप आपके जैसे स्थापित व्यवसायों की ज़रूरतों को पूरा करने के लिए तैयार किया गया है। इसे उच्च मात्रा और जटिल परिचालनों को निर्बाध रूप से संभालने के लिए डिज़ाइन किया गया है। ",
    lowTitleStart: "नये उद्यमियों के लिए विशेष सहायता:",
    lowTitleEnd: "छूट जैसा कि आपने अभी शुरू किया है",
    mediumTitleStart: "उद्यमियों के लिए विशेष सहायता:",
    mediumTitleEnd: "जैसे ही आपने शुरुआत की छूट",
    importantTitleStart: "उद्यमियों के लिए विशेष सहायता:",
    importantTitleEnd: "जैसे ही आपने शुरुआत की छूट",
    veryImportantTitleStart: "होने पर बधाई",
    veryImportantTitleEnd: "शॉपिफाई में",
    month: "महीना",
    "year and": "वर्ष और",
    ago: "पहले",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "एआई क्रेडिट जोड़ें (1 एआई क्रेडिट/10¢) (10 एआई क्रेडिट/$1)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "छवि जोड़ें altText AI क्रेडिट (1 AI क्रेडिट/4¢) (25 AI क्रेडिट/$1)",
    "Monthly AI AltText Credit": "मासिक एआई AltText क्रेडिट",
    "Yearly AI AltText Credit": "वार्षिक एआई AltText क्रेडिट",
    "Purchase AI AltText Credit": "AI AltText क्रेडिट खरीदें",
    "ImageAltText Credit": "ImageAltText क्रेडिट",
    "Your credits are finished; please upgrade your plan.":
      "आपके क्रेडिट समाप्त हो गए हैं; कृपया अपनी योजना को अपग्रेड करें.",
    "Your credits are finished; you can buy more credits from here.":
      "आपके क्रेडिट समाप्त हो गए हैं; आप यहां से अधिक क्रेडिट खरीद सकते हैं.",
    "This offer expire in": "यह ऑफर समाप्त हो रहा है",
    "Hurry Up!": "जल्दी करो!",
    Current: "मौजूदा",
    "Discount applied": "छूट लागू",
    "trial left": "परीक्षण बाकी",
    "info banner":
      "जब आप स्कैन होमपेज इमेज बटन पर क्लिक करते हैं, तो हमारा ऐप केवल होमपेज इमेज को स्कैन करेगा। इस छवि को अनुकूलित करने के लिए, कृपया मैन्युअल रूप से ऑप्टिमाइज़ बटन पर क्लिक करें।",
    "Optimize Images": "छवियाँ अनुकूलित करें",
    image: "छवि",
    images: "इमेजिस",
    Filename: "फ़ाइल का नाम",
    Images: "इमेजिस",
    Setting: "सेटिंग",
    "Saved(in %)": "सहेजा गया(% में)",
    Action: "कार्रवाई",
    "Product Image": "उत्पाद का चित्र",
    "product image": "उत्पाद का चित्र",
    gif: "gif",
    Homepage: "मुखपृष्ठ",
    "Manage Announcement": "घोषणा प्रबंधित करें",
    "No Announcements Found": "कोई घोषणा नहीं मिली",
    Position: "पद",
    "Campaign Title": "अभियान शीर्षक",
    Visible: "दृश्यमान",
    Invisible: "अदृश्य",
    Views: "दृश्य",
    Clicks: "क्लिक्स",
    Submits: "प्रस्तुत",
    "Above Add to cart Button": "ऊपर कार्ट में जोड़ें बटन",
    "Below Add to cart Button": "नीचे कार्ट में जोड़ें बटन",
    Targeting: "लक्ष्य निर्धारण",
    "Rotating Animation Setting": "घूर्णन एनीमेशन सेटिंग",
    "Marquee Animation Setting": "मार्की एनीमेशन सेटिंग",
    "Show to visitors coming form then specific website": "आने वाले आगंतुकों को विशिष्ट वेबसाइट दिखाएं",
    "Add your website URL": "अपनी वेबसाइट का यूआरएल जोड़ें",
    "Banner Display Start Time": "बैनर प्रदर्शन प्रारंभ समय",
    "Banner Display End Time": "बैनर प्रदर्शन समाप्ति समय",
    "Create Campaign": "अभियान बनाएं",
    "Select Announcement Bar": "घोषणा बार चुनें",
    "Please select template.": "कृपया टेम्पलेट का चयन करें.",
    Previous: "पहले का",
    "Promotion bar": "प्रमोशन बार",
    "Add To Cart": "कार्ट में जोड़ें",
    Embeded: "एम्बेडेड",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "ग्राहकों को आगामी बिक्री, ऑफर के बारे में सचेत करें या इन्वेंट्री अलर्ट सेट करें।",
    "Increase your order value by using or Free Shipping Bar.":
      "या निःशुल्क शिपिंग बार का उपयोग करके अपने ऑर्डर का मूल्य बढ़ाएँ।",
    "Conveniently add items to your cart with a single click!": "एक क्लिक से आसानी से अपने कार्ट में आइटम जोड़ें!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "सदस्यता लेने के लिए चयन करें और विशेष छूट सीधे अपने इनबॉक्स में प्राप्त करें",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "अपने विशेष ऑफर को एक एम्बेडेड बार के साथ हाइलाइट करें, जो कार्ट में जोड़ें बटन के पहले और बाद में प्रदर्शित होता है।",
    Select: "चुनना",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "बैनर छिपाने के लिए UTM कोड जोड़ें (उदाहरण: संदर्भ=Facebook, संदर्भ=Web, Utm_source=Google...)",
    "Include Utm": "Utm शामिल करें",
    "Exclude Utm": "Utm को बाहर करें",
    "Campaign Design": "अभियान डिजाइन",
    "Background Setting": "पृष्ठभूमि सेटिंग",
    "Target Setting": "लक्ष्य तय करना",
    Scheduling: "निर्धारण",
    Rotating: "घूर्णन",
    Marquee: "मार्की",
    "Repeat Timer Date": "दोहराएँ टाइमर दिनांक",
    "Select Repeat Time": "दोहराएँ समय चुनें",
    "Repeated Hours": "दोहराए गए घंटे",
    Border: "सीमा",
    Bashed: "कोसते",
    "Multi Rotating": "बहु घूर्णन",
    Contacts: "संपर्क",
    Email: "ईमेल",
    "First Name": "पहला नाम",
    "Last Name": "उपनाम",
    Phone: "फ़ोन",
    "You have unsaved changes": "आपके पास सहेजे नहीं गए परिवर्तन हैं",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "आपके अभियान में सहेजे नहीं गए परिवर्तन हैं। यदि आप सहेजे बिना छोड़ देते हैं तो परिवर्तन खो जाएंगे।",
    "Leave widthout saving": "चौड़ाई बचत छोड़ें",
    "Save Changes": "परिवर्तनों को सुरक्षित करें",
    Announcement: "घोषणा",
    Feedback: "प्रतिक्रिया",
    "Recipe Instructions": "रेसिपी निर्देश",
    "Visit Help Center": "सहायता केंद्र पर जाएँ",
    "Schedule Meeting": "सुनियोजित बैठक",
    "Setup guide": "सेटअप गाइड",
    "Use this personalized guide to get your store up and running":
      "अपने स्टोर को चालू रखने के लिए इस वैयक्तिकृत मार्गदर्शिका का उपयोग करें",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "कार्रवाई शुरू करने के लिए आपको हमारे ऐप को सक्षम करना होगा, बटन पर क्लिक करने से आप एक्सटेंशन पेज पर पहुंच जाएंगे, फिर आपको बस वहां सेव पर क्लिक करना होगा और यहां वापस आना होगा",
    "Enable our app": "हमारा ऐप सक्षम करें",
    "Learn more": "और अधिक जानें",
    "Skip it": "इसे छोड़ दें",
    steps: "कदम",
    minutes: "मिनट",
    "Mark as done": "पूर्ण हुआ चिह्नित करें",
    "Mark as not done": "'नहीं हुआ' के रूप में चिह्नित करें",
    "You have completed all the steps": "आपने सभी चरण पूरे कर लिए हैं",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "खोज परिणामों पर अपने स्टोर को उच्च रैंक देने के लिए, अपनी साइट की गति को सक्रिय करें और उसका विश्लेषण करें।",
    "Google Page Speed Optimization": "Google पेज स्पीड अनुकूलन",
    "Activate Google Page Speed": "Google पेज स्पीड सक्रिय करें",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "अपनी साइट के प्रदर्शन का आकलन करने और गति बढ़ाने के अवसरों की पहचान करने के लिए Google पेज स्पीड टूल सक्षम करें",
    "Enable Speed Analysis": "गति विश्लेषण सक्षम करें",
    "Review Speed Analysis Report": "गति विश्लेषण रिपोर्ट की समीक्षा करें",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "अपनी साइट की वर्तमान गति मेट्रिक्स और सुधार के लिए सटीक क्षेत्रों को समझने के लिए विस्तृत गति विश्लेषण रिपोर्ट की जांच करें।",
    "Go to Reports": "रिपोर्ट पर जाएँ",
    Hello: "नमस्ते",
    "Let's get your store ready for success": "आइए अपने स्टोर को सफलता के लिए तैयार करें",
    "Finish later": "बाद में समाप्त करें",
    "Continue onboarding": "ऑनबोर्डिंग जारी रखें",
    "Check image optimization features": "छवि अनुकूलन सुविधाओं की जाँच करें",
    "Explore Optimization Features": "अनुकूलन सुविधाओं का अन्वेषण करें",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "उपलब्ध छवि अनुकूलन उपकरणों की श्रृंखला से स्वयं को परिचित करें। देखें कि आप छवि आकार और प्रारूपों को अनुकूलित करके पेज लोड गति और एसईओ को कैसे सुधार सकते हैं।",
    "Go to Image Optimization": "छवि अनुकूलन पर जाएँ",
    "Automate Your Image Workflow": "अपनी छवि वर्कफ़्लो को स्वचालित करें",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "नई छवियों को अपलोड करते समय उन्हें सहजता से अनुकूलित करने के लिए स्वचालन सेट करें, जिससे आपकी साइट पर लगातार प्रदर्शन सुनिश्चित हो सके।",
    "Go to Automation": "स्वचालन पर जाएँ",
    "Execute a Bulk Optimization": "एक थोक अनुकूलन निष्पादित करें",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "एक साथ कई छवियों को कुशलतापूर्वक बढ़ाने के लिए एक बड़ा अनुकूलन करें, जो आपकी साइट के लोडिंग समय को महत्वपूर्ण रूप से बढ़ा सकता है।",
    "Go to bulk operations": "थोक परिचालन पर जाएँ",
    "Broken Links Management": "टूटे हुए लिंक प्रबंधन",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "उपयोगकर्ता अनुभव और एसईओ रैंकिंग को बढ़ाने के लिए टूटे हुए लिंक का पता लगाने और मरम्मत को स्वचालित करें।",
    "Review Detected Broken Links": "पता लगाए गए टूटे हुए लिंक की समीक्षा करें",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "आपकी साइट के नेविगेशन पर उनके प्रभाव को समझने के लिए हमारे सिस्टम द्वारा स्वचालित रूप से पहचाने गए टूटे हुए लिंक की सूची की जांच करें।",
    "View Broken Links": "टूटे हुए लिंक देखें",
    "Address Broken Links": "टूटे हुए लिंक का पता",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "टूटे हुए लिंक को तुरंत ठीक करने या पुनर्निर्देशित करने, अपनी साइट की अखंडता और उपयोगकर्ता संतुष्टि में सुधार करने के लिए हमारे टूल का उपयोग करें।",
    "Resolve Broken Links": "टूटी कड़ियों का समाधान करें",
    "Automate for Efficiency": "दक्षता के लिए स्वचालित करें",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "निरंतर साइट स्वास्थ्य सुनिश्चित करते हुए, भविष्य में किसी भी टूटे हुए लिंक से बचने के लिए स्वचालित सुधार सेट करें।",
    "Enable Automation": "स्वचालन सक्षम करें",
    "Meta Tags Management": "मेटा टैग प्रबंधन",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "हमारी उपयोगकर्ता-अनुकूल मेटा टैग सुविधा के साथ अपनी साइट की दृश्यता और खोज इंजन रैंकिंग को अनुकूलित करें।",
    "Explore Meta Tag Options": "मेटा टैग विकल्पों का अन्वेषण करें",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "व्यक्तिगत उत्पादों और पृष्ठों के लिए उपलब्ध विभिन्न मेटा टैग संपादन और स्वचालन विकल्पों से परिचित हों।",
    "Explore Meta Tags": "मेटा टैग का अन्वेषण करें",
    "Edit and Optimize": "संपादित करें और अनुकूलित करें",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "अपनी साइट के एसईओ और उपयोगकर्ता पहुंच को बढ़ाने के लिए मेटा शीर्षक, विवरण और छवि ऑल्ट टेक्स्ट को संपादित करने में लग जाएं।",
    "Start Editing": "संपादन प्रारंभ करें",
    "Automate for Consistency": "संगति के लिए स्वचालित करें",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "अपने उत्पाद पृष्ठों पर स्थिरता और दक्षता बनाए रखने के लिए अपने मेटा टैग के लिए स्वचालन नियम सेट करें।",
    "Set Automation": "स्वचालन सेट करें",
    "Schema Markup": "स्कीमा मार्कअप",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "खोज परिणामों में अपनी सामग्री का प्रतिनिधित्व बढ़ाने और अधिक क्लिक आकर्षित करने के लिए स्कीमा मार्कअप का उपयोग करें।",
    "Learn About Schema Options": "स्कीमा विकल्पों के बारे में जानें",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "उनके लाभों को समझने के लिए उपलब्ध विभिन्न प्रकार के स्कीमा मार्कअप, जैसे उत्पाद, स्थानीय व्यवसाय, अक्सर पूछे जाने वाले प्रश्न और बहुत कुछ से खुद को परिचित करें।",
    "Explore Schema Types": "स्कीमा प्रकारों का अन्वेषण करें",
    "Activate Key Schemas": "मुख्य स्कीमा सक्रिय करें",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "अपनी साइट के लिए महत्वपूर्ण स्कीमा चुनें और सक्षम करें, जैसे ई-कॉमर्स के लिए उत्पाद स्कीमा या भौतिक दुकानों के लिए स्थानीय व्यापार स्कीमा।",
    "Go to Schemas": "स्कीमास पर जाएं",
    "Customize Schema Details": "स्कीमा विवरण अनुकूलित करें",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "खोज परिणामों में अपने व्यवसाय या उत्पादों को सटीक रूप से प्रस्तुत करने के लिए प्रत्येक स्कीमा प्रकार की सेटिंग्स को अनुकूलित करें।",
    "Test and Validate Schemas": "स्कीमा का परीक्षण और सत्यापन करें",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "यह सुनिश्चित करने के लिए कि वे सही ढंग से कार्यान्वित हैं, Google के संरचित डेटा परीक्षण टूल जैसे टूल का उपयोग करके अपने स्कीमा का परीक्षण करें।",
    "Test Schemas": "परीक्षण स्कीमा",
    "Add Breadcrumbs": "ब्रेडक्रम्ब्स डालें",
    "Add Breadcrumbs to your store": "अपने स्टोर में ब्रेडक्रंब जोड़ें",
    "To get better user experience you need to add breadcrumbs to your store.":
      "बेहतर उपयोगकर्ता अनुभव प्राप्त करने के लिए आपको अपने स्टोर में ब्रेडक्रंब जोड़ना होगा।",
    "How to add breadcrumbs": "ब्रेडक्रम्ब्स कैसे डालें",
    "Understand how to add and configure breadcrumbs in your store.":
      "समझें कि अपने स्टोर में ब्रेडक्रंब कैसे जोड़ें और कॉन्फ़िगर करें।",
    "Google search console": "गूगल सर्च कंसोल",
    "Connect google search console to sync it with our app.":
      "इसे हमारे ऐप के साथ सिंक करने के लिए Google सर्च कंसोल से कनेक्ट करें।",
    "How to connect GSC.": "जीएससी कैसे कनेक्ट करें.",
    "Understand how to connect and use google search console in our app.":
      "समझें कि हमारे ऐप में Google सर्च कंसोल को कैसे कनेक्ट करें और उसका उपयोग कैसे करें।",
    "Go to GSC": "जीएससी पर जाएं",
    "Go to Breadcrumbs Design": "ब्रेडक्रम्ब्स डिज़ाइन पर जाएँ",
    "Start Onboarding": "ऑनबोर्डिंग प्रारंभ करें",
    "Go to Homepage": "मुखपृष्ठ प्र जाएं",
    "Go to Onboarding": "ऑनबोर्डिंग पर जाएं",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "आपकी समझ को बढ़ाने के लिए डिज़ाइन की गई हमारी उपयोगकर्ता-अनुकूल ऐप मार्गदर्शिका का अन्वेषण करें। शुरू करने के लिए 'स्टार्ट ऑनबोर्डिंग' पर क्लिक करें, और आप किसी भी समय फिर से होमपेज पर आ सकते हैं।",
    "Please enable our app extension.": "कृपया हमारा ऐप एक्सटेंशन सक्षम करें।",
    "Generate Meta tags": "मेटा टैग जनरेट करें",
    "Test description a litle bit longer that title": "परीक्षण विवरण शीर्षक से थोड़ा लंबा है",
    "Suggested for you": "आपके लिए सुझाव दिया गया है",
    "Enable Google page speed": "Google पृष्ठ गति सक्षम करें",
    "Connect GSC": "जीएससी कनेक्ट करें",
    "Enable Image Optimize Automation": "छवि अनुकूलन स्वचालन सक्षम करें",
    "Automate Meta tags": "मेटा टैग स्वचालित करें",
    "Automate Broken Links": "टूटे हुए लिंक को स्वचालित करें",
    "Enhance SEO with automatically generated meta tags.":
      "स्वचालित रूप से जेनरेट किए गए मेटा टैग के साथ SEO को बेहतर बनाएं।",
    "Improve website performance by optimizing images.":
      "छवियों को अनुकूलित करके वेबसाइट के प्रदर्शन में सुधार करें।",
    "Boost website speed by enabling Google Page Speed.": "Google पेज स्पीड सक्षम करके वेबसाइट की गति बढ़ाएँ।",
    "Enhance search visibility by connecting to Google Search Console.":
      "Google खोज कंसोल से कनेक्ट करके खोज दृश्यता बढ़ाएँ।",
    "Streamline image optimization with automated processes.":
      "स्वचालित प्रक्रियाओं के साथ छवि अनुकूलन को सुव्यवस्थित करें।",
    "Improve SEO by automating the generation of meta tags.":
      "मेटा टैग की पीढ़ी को स्वचालित करके SEO में सुधार करें।",
    "Improve UX with automated detect and handle, broken links.":
      "स्वचालित पहचान और हैंडल, टूटे हुए लिंक के साथ यूएक्स में सुधार करें।",
    "Learn About Add Announcement": "घोषणा जोड़ने के बारे में जानें",
    "Skip And Add Announcement": "छोड़ें और घोषणा जोड़ें",
    "Learn more about": "बारे में और सीखो",
    "Add Announcement": "घोषणा जोड़ें",
    "Announcement Bar": "घोषणा पट्टी",
    "Rate us!": "हमें रेटिंग दें!",
    "How would you Love this app?": "आप इस ऐप को कैसे पसंद करेंगे?",
    "Enter Your Feedback Here": "अपना फीडबैक यहां दर्ज करें",
    "Leave Us a Review !!": "हमें एक समीक्षा छोड़ दो !!",
    "If you like our app features then please leave us a review !!":
      "यदि आपको हमारी ऐप विशेषताएं पसंद हैं तो कृपया हमें एक समीक्षा छोड़ दें !!",
    "If you like our free features then please leave us a review !!":
      "यदि आपको हमारी निःशुल्क सुविधाएं पसंद हैं तो कृपया हमें एक समीक्षा दें !!",
    "Update Successfully": "सफलतापूर्वक अपडेट करें",
    "Uninstall App": "ऐप अनइंस्टॉल करें",
    "Contact Our Support": "हमारे समर्थन से संपर्क करें",
    "Leave a message": "एक संदेश छोड़ें",
    "Please Choose a UnInstallation Reason": "कृपया अनइंस्टॉलेशन का कारण चुनें",
    "Are you facing any issues understanding the features of our app?":
      "क्या आपको हमारे ऐप की विशेषताओं को समझने में कोई समस्या आ रही है?",
    "Please Choose at least one reason": "कृपया कम से कम एक कारण चुनें",
    "Thank You For Reaching Out": "हमसे संपर्क करने के लिए धन्यवाद",
    "Contact Support": "समर्थन से संपर्क करें",
    "Get Help from Our Support Team": "हमारी सहायता टीम से सहायता प्राप्त करें",
    "Select a reason": "कोई कारण चुनें",
    "Not getting how to use or setup": "उपयोग या सेटअप करने का तरीका नहीं समझ में आ रहा",
    "Poor customer support": "खराब ग्राहक सहायता",
    "Performance issues": "निष्पादन मुद्दे",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "हमारी सहायता टीम वर्तमान में सप्ताहांत पर उपलब्ध नहीं है और आपके समय क्षेत्र के अनुसार सप्ताह के दिनों में उपलब्ध होगी ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " चूंकि हम भारत से काम करते हैं। आप अभी भी संदेश छोड़ सकते हैं। कृपया हमारे जवाब में कुछ देरी की अपेक्षा करें। आपके धैर्य के लिए धन्यवाद।",
    "Our support team is partially available according to your time zone from ":
      "हमारी सहायता टीम आपके समय क्षेत्र के अनुसार आंशिक रूप से उपलब्ध है ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " चूंकि हम भारत से काम करते हैं। इस दौरान जवाब मिलने में 30 मिनट से एक घंटे तक का समय लग सकता है। कृपया एक संदेश छोड़ें, और हम जल्द से जल्द जवाब देंगे। आपके धैर्य के लिए धन्यवाद।",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "हमारी सहायता टीम वर्तमान में अनुपलब्ध है और आपके समय क्षेत्र के अनुसार उपलब्ध होगी ",
    to: "को",
    "Did not meet my expectations": "मेरी उम्मीदें पूरी नहीं हुईं",
    "Feature Limitations": "सुविधा की सीमाएँ",
    "Banner doesn't set in my app": "मेरे ऐप में बैनर सेट नहीं हो रहा है",
    "Banner is not show properly": "बैनर ठीक से नहीं दिख रहा है",
    "Confusing Set Multi Position and Multi Animation": "भ्रमित करने वाला सेट मल्टी पोजीशन और मल्टी एनिमेशन",
    "Sync Profile": "प्रोफ़ाइल सिंक करें",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
