import modifyData from "../Language/it.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Abilitato",
    Disabled: "Disabilitato",
    "Embed is currently disabled": "L'incorporamento è attualmente disabilitato",
    "Enable App": "Abilita app",
    "1. Click on Enable App.": "1. Fare clic su Abilita app.",
    "Well done!! you have successfully enable our app.": "Ben fatto!! hai abilitato con successo la nostra app.",
    "2. Enable": "2. Abilita",
    "App Embed as shown in image and save setting.":
      "Incorpora l'app come mostrato nell'immagine e salva le impostazioni.",
    "Multi Announcement Bar": "Barra annunci multipli",
    "Click on the Enable Now button to enable it.": "Fare clic sul pulsante Abilita ora per abilitarlo.",
    "Enable Announcement Bar to get started": "Abilita la barra degli annunci per iniziare",
    "Enable Now": "Abilita ora",
    "Sync Status": "Stato di sincronizzazione",
    Done: "Fatto",
    No: "NO",
    Found: "Trovato",
    Add: "Aggiungere",
    Search: "Ricerca",
    Showing: "Mostrando",
    of: "Di",
    "results, at most": "risultati, al massimo",
    "per page": "per pagina",
    "Oops! Something went wrong.": "Ops! Qualcosa è andato storto.",
    "Let's try that again, please refresh the page.": "Proviamo di nuovo, aggiorna la pagina.",
    "If you're still stuck, contact us by chat support or":
      "Se sei ancora bloccato, contattaci tramite il supporto chat o",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "così possiamo aiutarti!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Seleziona le 3 funzionalità che desideri impostare con priorità alta o più interessate",
    "Add ": "Aggiungere ",
    "These is premium feature": "Queste sono funzionalità premium",
    "Go to pricing": "Vai ai prezzi",
    Save: "Salva",
    Minimum: "Minimo",
    Maximum: "Massimo",
    "images are required": "le immagini sono obbligatorie",
    and: "E",
    "images are allowed": "sono ammesse immagini",
    Disconnect: "Disconnetti",
    "Sign In with Google": "Accedi con Google",
    "Oops! Something went wrong. Admin token is malformed":
      "Ops! Qualcosa è andato storto. Il token di amministrazione non ha un formato corretto",
    "If you're still stuck, contact": "Se sei ancora bloccato, contatta",
    Premium: "Premio",
    Unlock: "Sbloccare",
    "Unlock advanced features!": "Sblocca funzionalità avanzate!",
    "© 2021 Webrex. All rights reserved.": "© 2021Webrex. Tutti i diritti riservati.",
    "Privacy Policy": "politica sulla riservatezza",
    "Terms of Service": "Termini di servizio",
    "Go to Shopify App": "Vai all'app Shopify",
    "Review Us": "Recensiscici",
    Cancel: "Annulla",
    "Review Popup Show": "Esamina lo spettacolo popup",
    "click on review us": "clicca su esaminaci",
    "Note: Feel free to leave a star rating without writing a review!":
      "Nota: sentiti libero di lasciare una valutazione in stelle senza scrivere una recensione!",
    Help: "Aiuto",
    "Help Button Click": "Fare clic sul pulsante Guida",
    Confirm: "Confermare",
    On: "SU",
    Off: "Spento",
    Price: "Prezzo",
    Settings: "Impostazioni",
    Animation: "Animazione",
    "My Profile": "Il mio profilo",
    "My Subscription": "Il mio abbonamento",
    "Store Name": "Nome del negozio",
    "Store URL": "URL del negozio",
    "Email ID": "E-mail identificativo utente",
    "Phone Number": "Numero di telefono",
    Country: "Paese",
    Currency: "Valuta",
    "Subscription Name": "Nome dell'abbonamento",
    "Select language": "Seleziona la lingua",
    "Announcement setting": "Impostazione dell'annuncio",
    "Animation setting": "Impostazione dell'animazione",
    Selector: "Selettore",
    "Save Setting": "Salva impostazioni",
    "My Announcements": "I miei annunci",
    "Add bar": "Aggiungi barra",
    Number: "Numero",
    Title: "Titolo",
    "Create At": "Crea a",
    "Slide Activation": "Attivazione della diapositiva",
    Status: "Stato",
    Actions: "Azioni",
    "Save order": "Salva ordine",
    "Reorder Slides": "Riordina le diapositive",
    position: "posizione",
    Top: "Superiore",
    "Sticky Top": "Parte superiore appiccicosa",
    "Bottom Fix": "Correzione inferiore",
    "Custom Position": "Posizione personalizzata",
    "Custom Position *Add Class or id of Selected Element.":
      "Posizione personalizzata *Aggiungi classe o ID dell'elemento selezionato.",
    "Bar Padding (px)": "Imbottitura barra (px)",
    "Add Remove Button": "Aggiungi pulsante Rimuovi",
    "Choose icon color": "Scegli il colore dell'icona",
    "Custom css": "CSS personalizzato",
    fadeIn: "dissolvenza",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "dissolvenzaInUp",
    bounceInDown: "rimbalzareInDown",
    bounceInLeft: "rimbalzo a sinistra",
    bounceInUp: "rimbalzoInUp",
    zoomIn: "ingrandire",
    zoomInDown: "zoomInGiù",
    zoomInLeft: "zoom avanti a sinistra",
    slideInLeft: "slideInLeft",
    slideInUp: "slideInUp",
    slideInDown: "slideInDown",
    lightSpeedIn: "lightSpeedIn",
    rollIn: "rollIn",
    flash: "veloce",
    shake: "scuotere",
    flip: "Flip",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "dissolvenza",
    fadeOutDown: "fadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fadeOutUp",
    bounceOutDown: "rimbalzareOutDown",
    bounceOutRight: "rimbalzareOutRight",
    bounceOutUp: "rimbalzareOutUp",
    zoomOut: "zoom indietro",
    zoomOutDown: "zoomOutDown",
    zoomOutRight: "zoomOutRight",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "srotolare",
    flipInY: "flipInY",
    "Text Animation": "Animazione del testo",
    "Animation In": "Animazione dentro",
    "Animation Out": "Animazione fuori",
    "Auto play time (time in MS)": "Tempo di riproduzione automatica (tempo in MS)",
    "Animation time (time in MS)": "Tempo di animazione (tempo in MS)",
    "Auto play time (time in Second)": "Tempo di riproduzione automatica (tempo in secondi)",
    "Background Color": "Colore di sfondo",
    "Space between slide(px)": "Spazio tra la diapositiva (px)",
    visible: "visibile",
    invisible: "invisibile",
    "Promotional & Countdown Bar": "Barra promozionale e per il conto alla rovescia",
    "Free Shipping Bar": "Barra di spedizione gratuita",
    "Add Slide": "Aggiungi diapositiva",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Per il piano GRATUITO è visibile solo 1 diapositiva. Per attivare Tutte le diapositive abbonati al Piano Premium.",
    Pricing: "Prezzi",
    "No Animation Found": "Nessuna animazione trovata",
    "No Preview, Add announcement Bar": "Nessuna anteprima, aggiungi barra degli annunci",
    "Update successfully": "Aggiornamento riuscito",
    Enable: "Abilitare",
    Disable: "disattivare",
    successfully: "con successo",
    "Delete successfully": "Elimina con successo",
    "Copy successfully": "Copia con successo",
    "Reorder successfully": "Riordina con successo",
    "Announcement Message": "Messaggio di annuncio",
    "Call to Action": "Chiamare all'azione",
    Timer: "Timer",
    Style: "Stile",
    "Background Type": "Tipo di sfondo",
    "Mobile Style": "Stile mobile",
    "Schedule Display": "Visualizzazione della pianificazione",
    Update: "Aggiornamento",
    "Change Font": "Cambia carattere",
    "Font Family": "Famiglia di font",
    "Font Style": "Stile carattere",
    Normal: "Normale",
    Italic: "Corsivo",
    Oblique: "Obliquo",
    Unset: "Non settato",
    "Font Weight": "Peso del carattere",
    Bold: "Grassetto",
    "Message Font Size": "Dimensione carattere messaggio",
    "Message Text color": "Colore del testo del messaggio",
    Type: "Tipo",
    None: "Nessuno",
    Button: "Pulsante",
    "Entire clickable bar": "Intera barra cliccabile",
    "Add a simple link": "Aggiungi un collegamento semplice",
    "Add coupon placement": "Aggiungi il posizionamento del coupon",
    "Linked Url": "URL collegato",
    "Background Hover Color": "Colore dello sfondo al passaggio del mouse",
    "Text Hover Color": "Colore del testo al passaggio del mouse",
    "Button Text": "Testo del pulsante",
    "Copied Text": "Testo copiato",
    "Open in the new tab": "Apri nella nuova scheda",
    URL: "URL",
    "Font Size": "Dimensione del font",
    "Button Radius": "Raggio del pulsante",
    "Button color": "Colore del pulsante",
    "Button Text color": "Colore del testo del pulsante",
    "Button Hover Color": "Colore del pulsante al passaggio del mouse",
    "button Text HoverColor": "pulsante Testo HoverColor",
    "Timer Setting": "Impostazione del timer",
    "Timer Type": "Tipo di timer",
    Date: "Data",
    "Select Reapt Time": "Seleziona Tempo di raccolta",
    "repeated Hours": "Ore ripetute",
    "Normal Timer": "Temporizzatore normale",
    "Auto repeat timer": "Temporizzatore a ripetizione automatica",
    Minute: "Minuto",
    Hour: "Ora",
    Day: "Giorno",
    "Remove Timer When Time End": "Rimuovi timer allo scadere del tempo",
    "Timer Separator": "Separatore del temporizzatore",
    "Countdown Timer color": "Colore del timer per il conto alla rovescia",
    "Timer Text Size": "Dimensioni del testo del timer",
    "Timer Text Setting": "Impostazione del testo del timer",
    "Day Text": "Testo del giorno",
    "Hour Text": "Testo dell'ora",
    "Minute Text": "Testo minuto",
    "Second Text": "Secondo testo",
    "Background Image": "Immagine di sfondo",
    "Gradient Background": "Sfondo sfumato",
    "Style & Color For Mobile": "Stile e colore per dispositivi mobili",
    "Timer Background": "Sfondo del timer",
    "Timer Text Color": "Colore del testo del timer",
    "Button Color": "Colore del pulsante",
    "Button Text Color": "Colore del testo del pulsante",
    "Button Text Hover Color": "Colore del testo del pulsante al passaggio del mouse",
    "Button Text Size": "Dimensione del testo del pulsante",
    "Always Display": "Visualizza sempre",
    "Only Display Within The Following Period Of Time": "Visualizza solo entro il seguente periodo di tempo",
    "Start Time": "Ora di inizio",
    "End Time": "Tempo scaduto",
    "Advance Setting": "Impostazione avanzata",
    "Country Filter": "Filtro Paese",
    Visibility: "Visibilità",
    "Desktop and Mobile": "Desktop e dispositivi mobili",
    "Only Desktop": "Solo desktop",
    "Only Mobile": "Solo cellulari",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "TARGETING ORIGINE UTENTE (Visitatori provenienti da un link che include il seguente codice UTM, Es.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Seleziona Pagina",
    Include: "Includere",
    Exclude: "Escludere",
    "Currency Configuration": "Configurazione valuta",
    Message: "Messaggio",
    "Currency Symbol": "Simbolo di valuta",
    "Currency Position": "Posizione valutaria",
    Before: "Prima",
    After: "Dopo",
    "money Class": "Classe monetaria",
    "Initial Message": "Messaggio iniziale",
    "Shipping Goal": "Obiettivo di spedizione",
    "Progress Message": "Messaggio di progresso",
    "Progress goal": "Obiettivo progresso",
    "Goal Message": "Messaggio dell'obiettivo",
    "Shipping Price Color": "Prezzo di spedizione Colore",
    "Shipping Price Size": "Prezzo di spedizione Dimensioni",
    "Shipping Font Weight": "Peso del carattere di spedizione",
    "* When user first time visit": "* Alla prima visita dell'utente",
    "* When user add item to the cart e.g": "* Quando l'utente aggiunge un articolo al carrello, ad esempio:",
    "* When cart value is greater than": "*Quando il valore del carrello è maggiore di",
    "Show On Selected Countries": "Mostra nei paesi selezionati",
    "Show On Selected Pages": "Mostra sulle pagine selezionate",
    All: "Tutto",
    Home: "Casa",
    Cart: "Carrello",
    Collection: "Collezione",
    Product: "Prodotto",
    Custom: "Costume",
    Page: "Pagina",
    Blog: "Blog",
    "Url is required": "L'URL è obbligatorio",
    "Day Text is required": "Giorno Il testo è obbligatorio",
    "Hour Text is required": "Il testo dell'ora è obbligatorio",
    "Minute Text is required": "Il testo minuto è obbligatorio",
    "Second Text is required": "Il secondo testo è obbligatorio",
    "Start Time is required": "L'ora di inizio è obbligatoria",
    "End Time is required": "L'ora di fine è obbligatoria",
    "Created successfully": "Creato con successo",
    "United States": "stati Uniti",
    Canada: "Canada",
    Australia: "Australia",
    "New Zealand": "Nuova Zelanda",
    Germany: "Germania",
    India: "India",
    Afghanistan: "Afghanistan",
    "land Islands": "Isole terrestri",
    Albania: "Albania",
    Algeria: "Algeria",
    "American Samoa": "Samoa americane",
    AndorrA: "Andorra",
    Angola: "L'Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antartide",
    "Antigua and Barbuda": "Antigua e Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Aruba: "Aruba",
    Austria: "Austria",
    Azerbaijan: "Azerbaigian",
    Bahamas: "Bahamas",
    Bahrain: "Bahrein",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Bielorussia",
    Belgium: "Belgio",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermude",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    "Bosnia and Herzegovina": "Bosnia Erzegovina",
    Botswana: "Botswana",
    "Bouvet Island": "Isola Bouvet",
    Brazil: "Brasile",
    "British Indian Ocean Territory": "Territorio britannico dell'Oceano Indiano",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgaria",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Cambogia",
    Cameroon: "Camerun",
    "Cape Verde": "capo Verde",
    "Cayman Islands": "Isole Cayman",
    "Central African Republic": "Repubblica Centrafricana",
    Chad: "Chad",
    Chile: "Chile",
    China: "Cina",
    "Christmas Island": "Isola di Natale",
    "Cocos (Keeling) Islands": "Isole Cocos (Keeling).",
    Colombia: "Colombia",
    Comoros: "Comore",
    Congo: "Congo",
    "Congo, The Democratic Republic of the": "Congo, Repubblica Democratica del",
    "Cook Islands": "Isole Cook",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Costa d'Avorio",
    Croatia: "Croazia",
    Cuba: "Cuba",
    Cyprus: "Cipro",
    "Czech Republic": "Repubblica Ceca",
    Denmark: "Danimarca",
    Djibouti: "Gibuti",
    Dominica: "Dominica",
    "Dominican Republic": "Repubblica Dominicana",
    Ecuador: "Ecuador",
    Egypt: "Egitto",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guinea Equatoriale",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Ethiopia: "Etiopia",
    "Falkland Islands (Malvinas)": "Isole Falkland (Malvine)",
    "Faroe Islands": "Isole Faroe",
    Fiji: "Figi",
    Finland: "Finlandia",
    France: "Francia",
    "French Guiana": "Guiana francese",
    "French Polynesia": "Polinesia francese",
    "French Southern Territories": "Territori della Francia del sud",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Ghana: "Ghana",
    Gibraltar: "Gibilterra",
    Greece: "Grecia",
    Greenland: "Groenlandia",
    Grenada: "Grenada",
    Guadeloupe: "Guadalupa",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Isola Heard e Isole McDonald",
    "Holy See (Vatican City State)": "Santa Sede (Stato della Città del Vaticano)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Ungheria",
    Iceland: "Islanda",
    Indonesia: "Indonesia",
    "Iran, Islamic Republic Of": "Iran (Repubblica Islamica del",
    Iraq: "Iraq",
    Ireland: "Irlanda",
    "Isle of Man": "Isola di Man",
    Israel: "Israele",
    Italy: "Italia",
    Jamaica: "Giamaica",
    Japan: "Giappone",
    Jersey: "Maglia",
    Jordan: "Giordania",
    Kazakhstan: "Kazakistan",
    Kenya: "Kenia",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Corea, Repubblica popolare democratica di",
    "Korea, Republic of": "Corea, Repubblica di",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kirghizistan",
    "Lao People'S Democratic Republic": "Repubblica Democratica Popolare del Laos",
    Latvia: "Lettonia",
    Lebanon: "Libano",
    Lesotho: "Lesoto",
    Liberia: "Liberia",
    "Libyan Arab Jamahiriya": "Giamahiriya araba libica",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lituania",
    Luxembourg: "Lussemburgo",
    Macao: "Macao",
    "Macedonia, The Former Yugoslav Republic of": "Macedonia, ex Repubblica iugoslava di",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldive",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Isole Marshall",
    Martinique: "Martinica",
    Mauritania: "La Mauritania",
    Mauritius: "Maurizio",
    Mayotte: "Mayotte",
    Mexico: "Messico",
    "Micronesia, Federated States of": "Micronesia, Stati Federati di",
    "Moldova, Republic of": "Moldavia, Repubblica di",
    Monaco: "Monaco",
    Mongolia: "Mongolia",
    Montenegro: "Montenegro",
    Montserrat: "Montserrat",
    Morocco: "Marocco",
    Mozambique: "Mozambico",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Olanda",
    "Netherlands Antilles": "Antille Olandesi",
    "New Caledonia": "Nuova Caledonia",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    "Norfolk Island": "Isola Norfolk",
    "Northern Mariana Islands": "Isole Marianne settentrionali",
    Norway: "Norvegia",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Territori palestinesi occupati",
    Panama: "Panama",
    "Papua New Guinea": "Papua Nuova Guinea",
    Paraguay: "Paraguay",
    Peru: "Perù",
    Philippines: "Filippine",
    Pitcairn: "Pitcairn",
    Poland: "Polonia",
    Portugal: "Portogallo",
    "Puerto Rico": "Porto Rico",
    Qatar: "Qatar",
    Reunion: "Riunione",
    Romania: "Romania",
    "Russian Federation": "Federazione Russa",
    RWANDA: "RUANDA",
    "Saint Helena": "Sant'Elena",
    "Saint Kitts and Nevis": "Saint Kitts e Nevis",
    "Saint Lucia": "Santa Lucia",
    "Saint Pierre and Miquelon": "Saint Pierre e Miquelon",
    "Saint Vincent and the Grenadines": "Saint Vincent e Grenadine",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tomé e Principe",
    "Saudi Arabia": "Arabia Saudita",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Seychelles: "Seychelles",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovacchia",
    Slovenia: "Slovenia",
    "Solomon Islands": "Isole Salomone",
    Somalia: "Somalia",
    "South Africa": "Sud Africa",
    "South Georgia and the South Sandwich Islands": "Georgia del Sud e Isole Sandwich Meridionali",
    Spain: "Spagna",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Surilabel: "Surietichetta",
    "Svalbard and Jan Mayen": "Svalbard e Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Svezia",
    Switzerland: "Svizzera",
    "Syrian Arab Republic": "Repubblica Araba Siriana",
    "Taiwan, Province of China": "Taiwan, provincia della Cina",
    Tajikistan: "Tagikistan",
    "Tanzania, United Republic of": "Tanzania, Repubblica Unita di",
    Thailand: "Tailandia",
    "Timor-Leste": "Timor Est",
    Togo: "Andare",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd e Tobago",
    Tunisia: "Tunisia",
    Turkey: "Tacchino",
    Turkmenistan: "Turkmenistan",
    "Turks and Caicos Islands": "Isole Turks e Caicos",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ucraina",
    "United Arab Emirates": "Emirati Arabi Uniti",
    "United Kingdom": "Regno Unito",
    "United States Minor Outlying Islands": "Isole minori esterne degli Stati Uniti",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands, British": "Isole Vergini britanniche",
    "Virgin Islands, U.S.": "Isole Vergini, Stati Uniti",
    "Wallis and Futuna": "Wallis e Futuna",
    "Western Sahara": "Sahara occidentale",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Sblocca tutti gli schemi con il nostro piano Premium",
    "Billed Monthly": "Fatturazione mensile",
    "Billed Annually": "Fatturati ogni anno",
    "Save 30%": "Risparmia il 30%",
    Premium100Title:
      "Come utente iniziale, ti assicuriamo che potrai usufruire di tutte le nostre funzionalità premium senza alcun costo per te. Non è necessario preoccuparsi della pagina dei prezzi poiché puoi accedere liberamente a tutte le nostre funzionalità premium senza alcun costo. Per favore non disinstallare la nostra app per continuare a usufruire del nostro servizio.",
    Premium100ReviewLine:
      " Se ti piace la nostra app, lasciaci una recensione. Questo ci aiuta a rimanere motivati nello sviluppo di nuove funzionalità.",
    "Check Our Current Pricing": "Controlla i nostri prezzi attuali",
    "Leave Review": "Lascia la recensione",
    "We're sorry to see you go!": "Ci dispiace vederti andare!",
    "Cancel Plan": "Annulla piano",
    "Sync Plan": "Sincronizza piano",
    "Disccount applied": "Sconto applicato",
    Apply: "Fare domanda a",
    "Your code(s)": "I tuoi codici",
    "and discount have been applied successfully": "e lo sconto sono stati applicati correttamente",
    "Your entered promocode is not correct, Enter a valid code":
      "Il codice promozionale inserito non è corretto, inserisci un codice valido",
    "days trial left": "giorni di prova rimasti",
    Upgrade: "Aggiornamento",
    "days free trial, No Credit card required": "giorni di prova gratuita, nessuna carta di credito richiesta",
    Month: "Mese",
    Year: "Anno",
    Unlimited: "Illimitato",
    "Enter Promocode": "Inserisci il codice promozionale",
    "Please Choose a Cancellation Reason": "Scegli un motivo di cancellazione",
    "No Longer Needed?": "Non è più necessario?",
    "Didn't Meet Expectations": "Non ha soddisfatto le aspettative",
    "Cost Concerns": "Preoccupazioni sui costi",
    "Technical Issues": "Problemi tecnici",
    "Found an Alternative": "Trovato un'alternativa",
    Complexity: "Complessità",
    "Lack of Features": "Mancanza di funzionalità",
    "Poor Customer Support": "Scarsa assistenza clienti",
    "Business Closure or Change": "Chiusura o modifica dell'attività",
    "Temporary Pause": "Pausa temporanea",
    "Performance Issues": "Problemi di prestazione",
    Other: "Altro",
    "Mention Your Specific Reason Here": "Menziona qui il tuo motivo specifico",
    Start: "Inizio",
    "Day Free Trial": "Prova gratuita di un giorno",
    "Please Select One Option": "Seleziona un'opzione",
    "Plan cancelled successfully": "Piano annullato con successo",
    "7 days free trial, No Credit card required": "Prova gratuita di 7 giorni, nessuna carta di credito richiesta",
    "Your remaining trial days are": "I giorni di prova rimanenti lo sono",
    "You have used": "Hai usato",
    "days.": "giorni.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Nessun giorno di prova rimanente. Hai già utilizzato la prova gratuita di 7 giorni.",
    "Upgrade your plan now": "Aggiorna il tuo piano ora",
    "Unlimited Slides": "Diapositive illimitate",
    "20+ Animation In & Out": "Oltre 20 animazioni in entrata e in uscita",
    "Live Chat Support": "Supporto tramite chat dal vivo",
    "Priority, 24*7 Urgent setup and support":
      "Priorità, configurazione e supporto urgenti 24 ore su 24, 7 giorni su 7",
    "Rich Text Editor": "Editor di testo ricco",
    "One Slide(banner)": "Una diapositiva (banner)",
    "Repeated Countdown timer": "Conto alla rovescia ripetuto",
    "Fully Customisable": "Completamente personalizzabile",
    "Background-image": "Immagine di sfondo",
    "Custom Css": "CSS personalizzato",
    "Enable Our App": "Abilita la nostra app",
    "Book Onboarding Demo": "Prenota demo di onboarding",
    Next: "Prossimo",
    Finish: "Fine",
    Prev: "Prec",
    "App is not enable please click on the Enable App button to enable it.":
      "L'app non è abilitata, fare clic sul pulsante Abilita app per abilitarla.",
    "This field is required": "Questo campo è obbligatorio",
    disableButtonTooltip: "Non puoi aggiornare il piano mensile poiché hai un piano annuale!",
    "Choose plan": "Scegli il piano",
    "Purchase Plan": "Piano di acquisto",
    Continue: "Continua",
    "Image Optimization": "Ottimizzazione delle immagini",
    "AI Metatags": "Metatag AI",
    "Grand Total": "Somma totale",
    "Metatags Edit": "Modifica metatag",
    Products: "Prodotti",
    "Upgrade plan": "Piano di aggiornamento",
    "Your product count is": "Il conteggio dei tuoi prodotti è",
    "so your suitable plan is": "quindi il tuo piano adatto è",
    "Enjoy a": "Godetevi un",
    "lifetime discount": "sconto a vita",
    discountBanner:
      " Abbraccia uno sconto a vita, assicurandoti un risparmio perpetuo e migliorando la tua esperienza con i nostri prodotti e servizi premium.",
    "Images for Optimization every year after trial period end":
      "Immagini per l'ottimizzazione ogni anno al termine del periodo di prova",
    "AI Meta Tags Credit for every year after trial period end":
      "Credito meta tag AI per ogni anno successivo alla fine del periodo di prova",
    "Images for Optimization every month after trial period end":
      "Immagini per l'ottimizzazione ogni mese al termine del periodo di prova",
    "AI Meta Tags Credit for every Month after trial period end":
      "Credito meta tag AI per ogni mese successivo alla fine del periodo di prova",
    "Optimize your google page speed": "Ottimizza la velocità della tua pagina Google",
    "50 Product Meta tags Optimize, Image alt": "50 meta tag del prodotto Ottimizza, Immagine alt",
    "Product Meta tags Optimize, Image alt": "Meta tag del prodotto Ottimizza, Immagine alt",
    "AI ImageAltText Credit for every year after trial period end":
      "Credito AI ImageAltText per ogni anno successivo alla fine del periodo di prova",
    "25 AI ImageAltText Credit": "25 crediti AI ImageAltText",
    "AI ImageAltText Credit for every Month after trial period end":
      "Credito AI ImageAltText per ogni mese successivo alla fine del periodo di prova",
    "Contact Bar": "Barra dei contatti",
    "Add To Cart Bar": "Barra Aggiungi al carrello",
    "Multiple Position": "Posizione multipla",
    lowMsgStart: "Questa offerta è pensata appositamente per te, poiché hai appena avviato il tuo negozio Shopify",
    lowMsgMiddle: "Nostro",
    lowMsgEnd: "discount è il nostro modo di supportarti durante questi tempi difficili ma emozionanti.",
    mediumMsgStart: "Questa offerta è pensata appositamente per te, poiché hai avviato il tuo negozio Shopify",
    mediumMsgMiddle: "Nostro",
    mediumMsgEnd: "discount è il nostro modo di supportarti durante questi tempi difficili ma emozionanti.",
    importantMsgStart: "Questa offerta è pensata appositamente per te, poiché hai avviato il tuo negozio Shopify",
    importantMsgMiddle: "Nostro",
    importantMsgEnd: "discount è il nostro modo di supportarti durante questi tempi difficili ma emozionanti.",
    veryImportantMsgStart:
      "Questa offerta è pensata appositamente per te, poiché hai aperto il tuo negozio Shopify",
    veryImportantMsgMiddle: "Per noi sei un commerciante molto importante e maturo. Nostro",
    veryImportantMsgEnd: "lo sconto è mostrare quanto significhi per noi.",
    generalMsg:
      "La nostra app Shopify è progettata su misura per soddisfare le esigenze di aziende affermate come la tua. È progettato per gestire volumi elevati e operazioni complesse senza problemi. ",
    lowTitleStart: "Supporto speciale per i nuovi imprenditori:",
    lowTitleEnd: "Sconto come hai appena iniziato",
    mediumTitleStart: "Supporto speciale per gli imprenditori:",
    mediumTitleEnd: "Sconto come hai iniziato",
    importantTitleStart: "Supporto speciale per gli imprenditori:",
    importantTitleEnd: "Sconto come hai iniziato",
    veryImportantTitleStart: "Congratulazioni per essere",
    veryImportantTitleEnd: "su Shopify",
    month: "mese",
    "year and": "anno e",
    ago: "fa",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Aggiungi credito AI (1 credito AI/10¢) (10 credito AI/$1)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Aggiungi immagine altCredito AI testo (1 credito AI/4¢) (25 credito AI/$1)",
    "Monthly AI AltText Credit": "Credito AI AltText mensile",
    "Yearly AI AltText Credit": "Credito AI AltText annuale",
    "Purchase AI AltText Credit": "Acquista credito AI AltText",
    "ImageAltText Credit": "Credito ImageAltText",
    "Your credits are finished; please upgrade your plan.":
      "I tuoi crediti sono finiti; per favore aggiorna il tuo piano.",
    "Your credits are finished; you can buy more credits from here.":
      "I tuoi crediti sono finiti; puoi acquistare più crediti da qui.",
    "This offer expire in": "Questa offerta scade tra",
    "Hurry Up!": "Affrettarsi!",
    Current: "Attuale",
    "Discount applied": "Sconto applicato",
    "trial left": "processo rimasto",
    "info banner":
      "Quando fai clic sul pulsante Scansione immagine home page, la nostra app eseguirà la scansione solo dell'immagine della home page. Per ottimizzare questa immagine, fai clic manualmente sul pulsante Ottimizza",
    "Optimize Images": "Ottimizza le immagini",
    image: "Immagine",
    images: "immagini",
    Filename: "Nome del file",
    Images: "immagini",
    Setting: "Collocamento",
    "Saved(in %)": "Salvato(in%)",
    Action: "Azione",
    "Product Image": "Immagine del prodotto",
    "product image": "Immagine del prodotto",
    gif: "gif",
    Homepage: "Home page",
    "Manage Announcement": "Gestisci annuncio",
    "No Announcements Found": "Nessun annuncio trovato",
    Position: "Posizione",
    "Campaign Title": "Titolo della campagna",
    Visible: "Visibile",
    Invisible: "Invisibile",
    Views: "Visualizzazioni",
    Clicks: "Clic",
    Submits: "Invia",
    "Above Add to cart Button": "Sopra il pulsante Aggiungi al carrello",
    "Below Add to cart Button": "Sotto il pulsante Aggiungi al carrello",
    Targeting: "Targeting",
    "Rotating Animation Setting": "Impostazione dell'animazione rotante",
    "Marquee Animation Setting": "Impostazione dell'animazione del riquadro di selezione",
    "Show to visitors coming form then specific website":
      "Mostra ai visitatori provenienti da un sito Web specifico",
    "Add your website URL": "Aggiungi l'URL del tuo sito web",
    "Banner Display Start Time": "Ora di inizio della visualizzazione del banner",
    "Banner Display End Time": "Ora di fine visualizzazione banner",
    "Create Campaign": "Crea campagna",
    "Select Announcement Bar": "Seleziona la barra degli annunci",
    "Please select template.": "Seleziona il modello.",
    Previous: "Precedente",
    "Promotion bar": "Barra delle promozioni",
    "Add To Cart": "Aggiungi al carrello",
    Embeded: "Incorporato",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Informa i clienti delle prossime vendite e offerte oppure imposta avvisi di inventario.",
    "Increase your order value by using or Free Shipping Bar.":
      "Aumenta il valore del tuo ordine utilizzando la barra Spedizione gratuita.",
    "Conveniently add items to your cart with a single click!":
      "Aggiungi comodamente gli articoli al tuo carrello con un solo clic!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Seleziona per iscriverti e ricevere sconti speciali direttamente nella tua casella di posta",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Evidenzia le tue offerte speciali con una barra incorporata, visualizzata prima e dopo il pulsante Aggiungi al carrello.",
    Select: "Selezionare",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Aggiungi il codice UTM Nascondi banner (ad esempio Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Includi UTM",
    "Exclude Utm": "Escludi UTM",
    "Campaign Design": "Progettazione della campagna",
    "Background Setting": "Impostazione dello sfondo",
    "Target Setting": "Impostazione dell'obiettivo",
    Scheduling: "Pianificazione",
    Rotating: "Rotante",
    Marquee: "Tendone",
    "Repeat Timer Date": "Ripeti data timer",
    "Select Repeat Time": "Seleziona Tempo di ripetizione",
    "Repeated Hours": "Ore ripetute",
    Border: "Confine",
    Bashed: "Sconvolto",
    "Multi Rotating": "Multi Rotante",
    Contacts: "Contatti",
    Email: "E-mail",
    "First Name": "Nome di battesimo",
    "Last Name": "Cognome",
    Phone: "Telefono",
    "You have unsaved changes": "Sono presenti modifiche non salvate",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "La tua campagna presenta modifiche non salvate. Se esci senza salvare, le modifiche andranno perse.",
    "Leave widthout saving": "Lascia senza salvare",
    "Save Changes": "Salvare le modifiche",
    Announcement: "Annuncio",
    Feedback: "Feedback",
    "Recipe Instructions": "Istruzioni per la ricetta",
    "Visit Help Center": "Visita il Centro assistenza",
    "Schedule Meeting": "Pianifica riunione",
    "Setup guide": "Guida all'installazione",
    "Use this personalized guide to get your store up and running":
      "Utilizza questa guida personalizzata per rendere operativo il tuo negozio",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Per iniziare a ricevere le azioni devi abilitare la nostra app. Fai clic sul pulsante per accedere alla pagina delle estensioni, quindi devi solo fare clic su Salva lì e tornare qui",
    "Enable our app": "Abilita la nostra app",
    "Learn more": "Saperne di più",
    "Skip it": "Saltalo",
    steps: "passi",
    minutes: "minuti",
    "Mark as done": "segna come fatto",
    "Mark as not done": "Segna come non fatto",
    "You have completed all the steps": "Hai completato tutti i passaggi",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Attiva e analizza la velocità del tuo sito, per posizionare il tuo negozio più in alto nei risultati di ricerca.",
    "Google Page Speed Optimization": "Ottimizzazione della velocità della pagina di Google",
    "Activate Google Page Speed": "Attiva Google Page Speed",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Abilita lo strumento Google Page Speed per valutare le prestazioni del tuo sito e identificare opportunità di miglioramento della velocità",
    "Enable Speed Analysis": "Abilita analisi della velocità",
    "Review Speed Analysis Report": "Esaminare il rapporto sull'analisi della velocità",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Esamina il rapporto dettagliato sull'analisi della velocità per comprendere le attuali metriche di velocità del tuo sito e individuare le aree di miglioramento.",
    "Go to Reports": "Vai a Rapporti",
    Hello: "Ciao",
    "Let's get your store ready for success": "Prepariamo il tuo negozio al successo",
    "Finish later": "Finisci più tardi",
    "Continue onboarding": "Continua l'onboarding",
    "Check image optimization features": "Controlla le funzionalità di ottimizzazione delle immagini",
    "Explore Optimization Features": "Esplora le funzionalità di ottimizzazione",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Acquisisci familiarità con la gamma di strumenti di ottimizzazione delle immagini disponibili. Scopri come puoi migliorare la velocità di caricamento delle pagine e il SEO ottimizzando le dimensioni e i formati delle immagini.",
    "Go to Image Optimization": "Vai a Ottimizzazione dell'immagine",
    "Automate Your Image Workflow": "Automatizza il flusso di lavoro delle immagini",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Configura l'automazione per ottimizzare senza problemi le nuove immagini man mano che vengono caricate, garantendo prestazioni costanti in tutto il tuo sito.",
    "Go to Automation": "Vai a Automazione",
    "Execute a Bulk Optimization": "Eseguire un'ottimizzazione in blocco",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Esegui un'ottimizzazione in blocco per migliorare in modo efficiente più immagini contemporaneamente, il che può aumentare significativamente il tempo di caricamento del tuo sito.",
    "Go to bulk operations": "Vai alle operazioni collettive",
    "Broken Links Management": "Gestione dei collegamenti interrotti",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatizza il rilevamento e la riparazione dei collegamenti interrotti per migliorare l'esperienza dell'utente e il posizionamento SEO.",
    "Review Detected Broken Links": "Esamina i collegamenti interrotti rilevati",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Esamina l'elenco dei collegamenti non funzionanti identificati automaticamente dal nostro sistema per comprenderne l'impatto sulla navigazione del tuo sito.",
    "View Broken Links": "Visualizza collegamenti interrotti",
    "Address Broken Links": "Indirizzo collegamenti interrotti",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Utilizza i nostri strumenti per correggere o reindirizzare rapidamente i collegamenti interrotti, migliorando l'integrità del tuo sito e la soddisfazione degli utenti.",
    "Resolve Broken Links": "Risolvi i collegamenti interrotti",
    "Automate for Efficiency": "Automatizzare per l'efficienza",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Imposta la correzione automatica per stare al passo con eventuali futuri collegamenti interrotti, garantendo la continua integrità del sito.",
    "Enable Automation": "Abilita l'automazione",
    "Meta Tags Management": "Gestione dei meta tag",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Ottimizza la visibilità del tuo sito e il posizionamento nei motori di ricerca con la nostra funzionalità Meta Tag intuitiva.",
    "Explore Meta Tag Options": "Esplora le opzioni dei meta tag",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Scopri le varie opzioni di modifica e automazione dei meta tag disponibili per singoli prodotti e pagine.",
    "Explore Meta Tags": "Esplora i meta tag",
    "Edit and Optimize": "Modifica e ottimizza",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Immergiti nella modifica di meta titoli, descrizioni e testi alternativi delle immagini per migliorare la SEO del tuo sito e l'accessibilità degli utenti.",
    "Start Editing": "Inizia a modificare",
    "Automate for Consistency": "Automatizza per coerenza",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Imposta regole di automazione per i tuoi meta tag per mantenere coerenza ed efficienza nelle pagine dei tuoi prodotti.",
    "Set Automation": "Imposta l'automazione",
    "Schema Markup": "Markup dello schema",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Utilizza il markup dello schema per migliorare la rappresentazione dei tuoi contenuti nei risultati di ricerca e attirare più clic.",
    "Learn About Schema Options": "Informazioni sulle opzioni dello schema",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Acquisisci familiarità con i diversi tipi di markup dello schema disponibili, come Prodotto, Attività locale, Domande frequenti e altro, per comprenderne i vantaggi.",
    "Explore Schema Types": "Esplora i tipi di schema",
    "Activate Key Schemas": "Attiva schemi chiave",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Scegli e abilita schemi cruciali per il tuo sito, come lo schema del prodotto per l'e-commerce o lo schema dell'attività locale per i negozi fisici.",
    "Go to Schemas": "Vai a Schemi",
    "Customize Schema Details": "Personalizza i dettagli dello schema",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Personalizza le impostazioni di ciascun tipo di schema per rappresentare accuratamente la tua attività o i tuoi prodotti nei risultati di ricerca.",
    "Test and Validate Schemas": "Testare e convalidare schemi",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Metti alla prova i tuoi schemi utilizzando strumenti come lo strumento di test dei dati strutturati di Google per assicurarti che siano implementati correttamente.",
    "Test Schemas": "Schemi di prova",
    "Add Breadcrumbs": "Aggiungi il pangrattato",
    "Add Breadcrumbs to your store": "Aggiungi il breadcrumb al tuo negozio",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Per ottenere una migliore esperienza utente devi aggiungere breadcrumb al tuo negozio.",
    "How to add breadcrumbs": "Come aggiungere il pangrattato",
    "Understand how to add and configure breadcrumbs in your store.":
      "Scopri come aggiungere e configurare i breadcrumb nel tuo negozio.",
    "Google search console": "Console di ricerca di Google",
    "Connect google search console to sync it with our app.":
      "Collega Google Search Console per sincronizzarlo con la nostra app.",
    "How to connect GSC.": "Come collegare GSC.",
    "Understand how to connect and use google search console in our app.":
      "Scopri come connetterti e utilizzare Google Search Console nella nostra app.",
    "Go to GSC": "Vai a GSC",
    "Go to Breadcrumbs Design": "Vai a Progettazione breadcrumb",
    "Start Onboarding": "Inizia l'onboarding",
    "Go to Homepage": "Vai alla pagina principale",
    "Go to Onboarding": "Vai a Onboarding",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      'Esplora la nostra guida intuitiva all\'app progettata per migliorare la tua comprensione. Fai clic su "Avvia onboarding" per iniziare e potrai tornare alla home page in qualsiasi momento.',
    "Please enable our app extension.": "Abilita la nostra estensione dell'app.",
    "Generate Meta tags": "Genera meta tag",
    "Test description a litle bit longer that title": "La descrizione del test è un po' più lunga del titolo",
    "Suggested for you": "Suggerito per te",
    "Enable Google page speed": "Abilita la velocità della pagina di Google",
    "Connect GSC": "Connetti GSC",
    "Enable Image Optimize Automation": "Abilita l'automazione dell'ottimizzazione delle immagini",
    "Automate Meta tags": "Automatizza i meta tag",
    "Automate Broken Links": "Automatizza i collegamenti interrotti",
    "Enhance SEO with automatically generated meta tags.":
      "Migliora il SEO con meta tag generati automaticamente.",
    "Improve website performance by optimizing images.":
      "Migliora le prestazioni del sito web ottimizzando le immagini.",
    "Boost website speed by enabling Google Page Speed.":
      "Aumenta la velocità del sito web abilitando Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Migliora la visibilità della ricerca collegandoti a Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Semplifica l'ottimizzazione delle immagini con processi automatizzati.",
    "Improve SEO by automating the generation of meta tags.":
      "Migliora il SEO automatizzando la generazione di meta tag.",
    "Improve UX with automated detect and handle, broken links.":
      "Migliora l'esperienza utente con il rilevamento e la gestione automatizzati dei collegamenti interrotti.",
    "Learn About Add Announcement": "Ulteriori informazioni su Aggiungi annuncio",
    "Skip And Add Announcement": "Salta e aggiungi annuncio",
    "Learn more about": "Impara di più riguardo",
    "Add Announcement": "Aggiungi annuncio",
    "Announcement Bar": "Barra degli annunci",
    "Rate us!": "Valutaci!",
    "How would you Love this app?": "Come ameresti questa app?",
    "Enter Your Feedback Here": "Inserisci qui il tuo feedback",
    "Leave Us a Review !!": "Lasciaci una recensione!!",
    "If you like our app features then please leave us a review !!":
      "Se ti piacciono le funzionalità della nostra app, lasciaci una recensione!!",
    "If you like our free features then please leave us a review !!":
      "Se ti piacciono le nostre funzionalità gratuite, lasciaci una recensione!!",
    "Update Successfully": "Aggiornamento riuscito",
    "Uninstall App": "Disinstallare l'app",
    "Contact Our Support": "Contatta il nostro supporto",
    "Leave a message": "Lasciate un messaggio",
    "Please Choose a UnInstallation Reason": "Scegli un motivo per la disinstallazione",
    "Are you facing any issues understanding the features of our app?":
      "Stai riscontrando problemi nel comprendere le funzionalità della nostra app?",
    "Please Choose at least one reason": "Per favore scegli almeno un motivo",
    "Thank You For Reaching Out": "Grazie per avermi contattato",
    "Contact Support": "Contatta il supporto",
    "Get Help from Our Support Team": "Ottieni aiuto dal nostro team di supporto",
    "Select a reason": "Seleziona un motivo",
    "Not getting how to use or setup": "Non capisco come utilizzare o configurare",
    "Poor customer support": "Scarsa assistenza clienti",
    "Performance issues": "Problemi di prestazione",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Il nostro team di supporto non è attualmente disponibile nei fine settimana e sarà disponibile nei giorni feriali in base al fuso orario ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " poiché operiamo dall'India. Puoi ancora lasciare un messaggio. Si prega di prevedere qualche ritardo nella nostra risposta. Grazie per la vostra pazienza.",
    "Our support team is partially available according to your time zone from ":
      "Il nostro team di supporto è parzialmente disponibile in base al fuso orario da ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " poiché operiamo dall'India. Durante questo periodo le risposte potrebbero richiedere da 30 minuti a un'ora. Per favore lascia un messaggio e ti risponderemo il prima possibile. Grazie per la vostra pazienza.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Il nostro team di supporto non è attualmente disponibile e sarà disponibile in base al fuso orario da ",
    to: "A",
    "Did not meet my expectations": "Non ha soddisfatto le mie aspettative",
    "Feature Limitations": "Limitazioni delle funzionalità",
    "Banner doesn't set in my app": "Il banner non è impostato nella mia app",
    "Banner is not show properly": "Il banner non viene visualizzato correttamente",
    "Confusing Set Multi Position and Multi Animation":
      "Confusione tra l'impostazione multiposizione e l'animazione multipla",
    "Sync Profile": "Sincronizzazione del profilo",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
