import modifyData from "../Language/ja.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "有効",
    Disabled: "無効",
    "Embed is currently disabled": "埋め込みは現在無効になっています",
    "Enable App": "アプリを有効にする",
    "1. Click on Enable App.": "1. 「アプリを有効にする」をクリックします。",
    "Well done!! you have successfully enable our app.": "よくやった！！アプリが正常に有効になりました。",
    "2. Enable": "2.有効にする",
    "App Embed as shown in image and save setting.": "画像のようにアプリを埋め込み、設定を保存します。",
    "Multi Announcement Bar": "マルチアナウンスバー",
    "Click on the Enable Now button to enable it.": "[今すぐ有効にする] ボタンをクリックして有効にします。",
    "Enable Announcement Bar to get started": "開始するにはアナウンスバーを有効にしてください",
    "Enable Now": "今すぐ有効にする",
    "Sync Status": "同期ステータス",
    Done: "終わり",
    No: "いいえ",
    Found: "見つかった",
    Add: "追加",
    Search: "検索",
    Showing: "表示中",
    of: "の",
    "results, at most": "せいぜい結果",
    "per page": "1ページあたり",
    "Oops! Something went wrong.": "おっとっと！何か問題が発生しました。",
    "Let's try that again, please refresh the page.": "もう一度試してみましょう。ページを更新してください。",
    "If you're still stuck, contact us by chat support or":
      "それでも問題が解決しない場合は、チャット サポートまたは",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "私たちがお手伝いできます！",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "優先度の高い機能または最も関心のある機能を 3 つ選択します",
    "Add ": "追加 ",
    "These is premium feature": "これらはプレミアム機能です",
    "Go to pricing": "価格設定に移動",
    Save: "保存",
    Minimum: "最小",
    Maximum: "最大",
    "images are required": "画像は必須です",
    and: "そして",
    "images are allowed": "画像は許可されています",
    Disconnect: "切断する",
    "Sign In with Google": "Googleでサインイン",
    "Oops! Something went wrong. Admin token is malformed":
      "おっとっと！何か問題が発生しました。管理者トークンの形式が不正です",
    "If you're still stuck, contact": "それでも解決しない場合は、お問い合わせください",
    Premium: "プレミアム",
    Unlock: "ロックを解除する",
    "Unlock advanced features!": "高度な機能をアンロックしましょう！",
    "© 2021 Webrex. All rights reserved.": "© 2021 ウェブレックス。無断転載を禁じます。",
    "Privacy Policy": "プライバシーポリシー",
    "Terms of Service": "利用規約",
    "Go to Shopify App": "Shopify アプリに移動",
    "Review Us": "レビューしてください",
    Cancel: "キャンセル",
    "Review Popup Show": "レビューポップアップショー",
    "click on review us": "レビューをクリックしてください",
    "Note: Feel free to leave a star rating without writing a review!":
      "注: レビューを書かずに、お気軽に星評価を残してください。",
    Help: "ヘルプ",
    "Help Button Click": "ヘルプボタンのクリック",
    Confirm: "確認する",
    On: "の上",
    Off: "オフ",
    Price: "価格",
    Settings: "設定",
    Animation: "アニメーション",
    "My Profile": "私のプロフィール",
    "My Subscription": "私のサブスクリプション",
    "Store Name": "店名",
    "Store URL": "ストアURL",
    "Email ID": "電子メールID",
    "Phone Number": "電話番号",
    Country: "国",
    Currency: "通貨",
    "Subscription Name": "サブスクリプション名",
    "Select language": "言語を選択する",
    "Announcement setting": "アナウンス設定",
    "Animation setting": "アニメーション設定",
    Selector: "セレクタ",
    "Save Setting": "設定の保存",
    "My Announcements": "私のお知らせ",
    "Add bar": "バーを追加",
    Number: "番号",
    Title: "タイトル",
    "Create At": "作成場所",
    "Slide Activation": "スライドアクティベーション",
    Status: "状態",
    Actions: "行動",
    "Save order": "順序を保存する",
    "Reorder Slides": "スライドの並べ替え",
    position: "位置",
    Top: "上",
    "Sticky Top": "スティッキートップ",
    "Bottom Fix": "ボトムフィックス",
    "Custom Position": "カスタム位置",
    "Custom Position *Add Class or id of Selected Element.":
      "カスタム位置 *選択した要素のクラスまたは ID を追加します。",
    "Bar Padding (px)": "バーのパディング (ピクセル)",
    "Add Remove Button": "追加削除ボタン",
    "Choose icon color": "アイコンの色を選択してください",
    "Custom css": "カスタムCSS",
    fadeIn: "フェードイン",
    fadeInDown: "フェードインダウン",
    fadeInDownBig: "フェードインダウンビッグ",
    fadeInLeft: "フェードイン左",
    fadeInLeftBig: "フェードイン左ビッグ",
    fadeInUp: "フェードインアップ",
    bounceInDown: "バウンスインダウン",
    bounceInLeft: "左にバウンス",
    bounceInUp: "バウンスインアップ",
    zoomIn: "ズームイン",
    zoomInDown: "ズームインダウン",
    zoomInLeft: "左にズーム",
    slideInLeft: "左にスライド",
    slideInUp: "スライドインアップ",
    slideInDown: "スライドインダウン",
    lightSpeedIn: "ライトスピードイン",
    rollIn: "ロールイン",
    flash: "閃光",
    shake: "振る",
    flip: "フリップ",
    flipInX: "フリップインX",
    flipOutX: "フリップアウトX",
    fadeOut: "フェードアウト",
    fadeOutDown: "フェードアウトダウン",
    fadeOutDownBig: "フェードアウトダウンビッグ",
    fadeOutRight: "フェードアウト右",
    fadeOutRightBig: "フェードアウト右ビッグ",
    fadeOutUp: "フェードアウトアップ",
    bounceOutDown: "バウンスアウトダウン",
    bounceOutRight: "バウンスアウトライト",
    bounceOutUp: "バウンスアウトアップ",
    zoomOut: "ズームアウトする",
    zoomOutDown: "ズームアウトダウン",
    zoomOutRight: "ズームアウト右",
    slideOutRight: "スライドアウト右",
    slideOutUp: "スライドアウトアップ",
    slideOutDown: "スライドアウトダウン",
    lightSpeedOut: "ライトスピードアウト",
    rollOut: "ロールアウトする",
    flipInY: "フリップインY",
    "Text Animation": "テキストアニメーション",
    "Animation In": "アニメーションイン",
    "Animation Out": "アニメーションアウト",
    "Auto play time (time in MS)": "自動再生時間（MS単位の時間）",
    "Animation time (time in MS)": "アニメーション時間 (MS 単位の時間)",
    "Auto play time (time in Second)": "自動再生時間 (秒単位の時間)",
    "Background Color": "背景色",
    "Space between slide(px)": "スライド間のスペース(px)",
    visible: "見える",
    invisible: "見えない",
    "Promotional & Countdown Bar": "プロモーション&カウントダウンバー",
    "Free Shipping Bar": "送料無料バー",
    "Add Slide": "スライドの追加",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "無料プランでは 1 つのスライドのみが表示されます。すべてのスライドを有効にするには、プレミアム プランに登録してください。",
    Pricing: "価格設定",
    "No Animation Found": "アニメーションが見つかりませんでした",
    "No Preview, Add announcement Bar": "プレビューなし、アナウンスバーを追加",
    "Update successfully": "正常に更新されました",
    Enable: "有効にする",
    Disable: "無効にする",
    successfully: "無事に",
    "Delete successfully": "正常に削除されました",
    "Copy successfully": "コピーに成功しました",
    "Reorder successfully": "再注文が成功しました",
    "Announcement Message": "お知らせメッセージ",
    "Call to Action": "アクションの呼び出し",
    Timer: "タイマー",
    Style: "スタイル",
    "Background Type": "背景の種類",
    "Mobile Style": "モバイルスタイル",
    "Schedule Display": "スケジュール表示",
    Update: "アップデート",
    "Change Font": "フォントの変更",
    "Font Family": "フォントファミリー",
    "Font Style": "フォントスタイル",
    Normal: "普通",
    Italic: "イタリック",
    Oblique: "斜め",
    Unset: "設定を解除する",
    "Font Weight": "フォントの太さ",
    Bold: "大胆な",
    "Message Font Size": "メッセージのフォントサイズ",
    "Message Text color": "メッセージの文字色",
    Type: "タイプ",
    None: "なし",
    Button: "ボタン",
    "Entire clickable bar": "クリック可能なバー全体",
    "Add a simple link": "簡単なリンクを追加する",
    "Add coupon placement": "クーポンの配置を追加する",
    "Linked Url": "リンクされた URL",
    "Background Hover Color": "背景のホバー色",
    "Text Hover Color": "テキストホバーの色",
    "Button Text": "ボタンのテキスト",
    "Copied Text": "コピーされたテキスト",
    "Open in the new tab": "新しいタブで開く",
    URL: "URL",
    "Font Size": "フォントサイズ",
    "Button Radius": "ボタンの半径",
    "Button color": "ボタンの色",
    "Button Text color": "ボタンの文字色",
    "Button Hover Color": "ボタンのホバー色",
    "button Text HoverColor": "ボタンのテキストのホバーカラー",
    "Timer Setting": "タイマー設定",
    "Timer Type": "タイマーの種類",
    Date: "日付",
    "Select Reapt Time": "受信時間を選択してください",
    "repeated Hours": "繰り返しの時間",
    "Normal Timer": "ノーマルタイマー",
    "Auto repeat timer": "オートリピートタイマー",
    Minute: "分",
    Hour: "時間",
    Day: "日",
    "Remove Timer When Time End": "時間が終了したらタイマーを削除する",
    "Timer Separator": "タイマーセパレータ",
    "Countdown Timer color": "カウントダウンタイマーの色",
    "Timer Text Size": "タイマーの文字サイズ",
    "Timer Text Setting": "タイマーテキスト設定",
    "Day Text": "曜日のテキスト",
    "Hour Text": "時間のテキスト",
    "Minute Text": "議事録テキスト",
    "Second Text": "2 番目のテキスト",
    "Background Image": "背景画像",
    "Gradient Background": "グラデーションの背景",
    "Style & Color For Mobile": "モバイル用のスタイルとカラー",
    "Timer Background": "タイマーの背景",
    "Timer Text Color": "タイマーの文字の色",
    "Button Color": "ボタンの色",
    "Button Text Color": "ボタンのテキストの色",
    "Button Text Hover Color": "ボタンのテキストのホバー色",
    "Button Text Size": "ボタンの文字サイズ",
    "Always Display": "常に表示",
    "Only Display Within The Following Period Of Time": "以下の期間内のみ表示",
    "Start Time": "始まる時間",
    "End Time": "終了時間",
    "Advance Setting": "詳細設定",
    "Country Filter": "国フィルター",
    Visibility: "可視性",
    "Desktop and Mobile": "デスクトップとモバイル",
    "Only Desktop": "デスクトップのみ",
    "Only Mobile": "モバイルのみ",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "ユーザーソースターゲティング (次の UTM コードを含むリンクからの訪問者、例:Ref=Facebook、Ref=Web、Utm_source=Google...)",
    "Select Page": "ページを選択",
    Include: "含む",
    Exclude: "除外する",
    "Currency Configuration": "通貨構成",
    Message: "メッセージ",
    "Currency Symbol": "通貨記号",
    "Currency Position": "通貨ポジション",
    Before: "前に",
    After: "後",
    "money Class": "お金のクラス",
    "Initial Message": "最初のメッセージ",
    "Shipping Goal": "出荷目標",
    "Progress Message": "進捗メッセージ",
    "Progress goal": "進捗目標",
    "Goal Message": "目標メッセージ",
    "Shipping Price Color": "送料価格 カラー",
    "Shipping Price Size": "送料サイズ",
    "Shipping Font Weight": "出荷時のフォントウェイト",
    "* When user first time visit": "※初回訪問時",
    "* When user add item to the cart e.g": "* ユーザーがカートに商品を追加するとき、例:",
    "* When cart value is greater than": "※カート金額が以上の場合",
    "Show On Selected Countries": "選択した国で表示",
    "Show On Selected Pages": "選択したページに表示",
    All: "全て",
    Home: "家",
    Cart: "カート",
    Collection: "コレクション",
    Product: "製品",
    Custom: "カスタム",
    Page: "ページ",
    Blog: "ブログ",
    "Url is required": "URLは必須です",
    "Day Text is required": "曜日テキストは必須です",
    "Hour Text is required": "時間テキストは必須です",
    "Minute Text is required": "議事録テキストは必須です",
    "Second Text is required": "2 番目のテキストは必須です",
    "Start Time is required": "開始時間は必須です",
    "End Time is required": "終了時刻は必須です",
    "Created successfully": "正常に作成されました",
    "United States": "アメリカ",
    Canada: "カナダ",
    Australia: "オーストラリア",
    "New Zealand": "ニュージーランド",
    Germany: "ドイツ",
    India: "インド",
    Afghanistan: "アフガニスタン",
    "land Islands": "陸の島々",
    Albania: "アルバニア",
    Algeria: "アルジェリア",
    "American Samoa": "アメリカ領サモア",
    AndorrA: "アンドラ",
    Angola: "アンゴラ",
    Anguilla: "アンギラ",
    Antarctica: "南極大陸",
    "Antigua and Barbuda": "アンティグア・バーブーダ",
    Argentina: "アルゼンチン",
    Armenia: "アルメニア",
    Aruba: "アルバ",
    Austria: "オーストリア",
    Azerbaijan: "アゼルバイジャン",
    Bahamas: "バハマ",
    Bahrain: "バーレーン",
    Bangladesh: "バングラデシュ",
    Barbados: "バルバドス",
    Belarus: "ベラルーシ",
    Belgium: "ベルギー",
    Belize: "ベリーズ",
    Benin: "ベナン",
    Bermuda: "バミューダ",
    Bhutan: "ブータン",
    Bolivia: "ボリビア",
    "Bosnia and Herzegovina": "ボスニア・ヘルツェゴビナ",
    Botswana: "ボツワナ",
    "Bouvet Island": "ブーベ島",
    Brazil: "ブラジル",
    "British Indian Ocean Territory": "英領インド洋領土",
    "Brunei Darussalam": "ブルネイ ダルサラーム",
    Bulgaria: "ブルガリア",
    "Burkina Faso": "ブルキナファソ",
    Burundi: "ブルンジ",
    Cambodia: "カンボジア",
    Cameroon: "カメルーン",
    "Cape Verde": "カーボベルデ",
    "Cayman Islands": "ケイマン諸島",
    "Central African Republic": "中央アフリカ共和国",
    Chad: "チャド",
    Chile: "チリ",
    China: "中国",
    "Christmas Island": "クリスマス島",
    "Cocos (Keeling) Islands": "ココス (キーリング) 諸島",
    Colombia: "コロンビア",
    Comoros: "コモロ",
    Congo: "コンゴ",
    "Congo, The Democratic Republic of the": "コンゴ民主共和国",
    "Cook Islands": "クック諸島",
    "Costa Rica": "コスタリカ",
    "Cote D'Ivoire": "コートジボワール",
    Croatia: "クロアチア",
    Cuba: "キューバ",
    Cyprus: "キプロス",
    "Czech Republic": "チェコ共和国",
    Denmark: "デンマーク",
    Djibouti: "ジブチ",
    Dominica: "ドミニカ",
    "Dominican Republic": "ドミニカ共和国",
    Ecuador: "エクアドル",
    Egypt: "エジプト",
    "El Salvador": "エルサルバドル",
    "Equatorial Guinea": "赤道ギニア",
    Eritrea: "エリトリア",
    Estonia: "エストニア",
    Ethiopia: "エチオピア",
    "Falkland Islands (Malvinas)": "フォークランド諸島 (マルビナス)",
    "Faroe Islands": "フェロー諸島",
    Fiji: "フィジー",
    Finland: "フィンランド",
    France: "フランス",
    "French Guiana": "フランス領ギアナ",
    "French Polynesia": "フランス領ポリネシア",
    "French Southern Territories": "フランス領南方領土",
    Gabon: "ガボン",
    Gambia: "ガンビア",
    Georgia: "ジョージア",
    Ghana: "ガーナ",
    Gibraltar: "ジブラルタル",
    Greece: "ギリシャ",
    Greenland: "グリーンランド",
    Grenada: "グレナダ",
    Guadeloupe: "グアドループ",
    Guam: "グアム",
    Guatemala: "グアテマラ",
    Guernsey: "ガーンジー島",
    Guinea: "ギニア",
    "Guinea-Bissau": "ギニアビサウ",
    Guyana: "ガイアナ",
    Haiti: "ハイチ",
    "Heard Island and Mcdonald Islands": "ハード島とマクドナルド諸島",
    "Holy See (Vatican City State)": "ローマ法王庁 (バチカン市国)",
    Honduras: "ホンジュラス",
    "Hong Kong": "香港",
    Hungary: "ハンガリー",
    Iceland: "アイスランド",
    Indonesia: "インドネシア",
    "Iran, Islamic Republic Of": "イラン、イスラム共和国",
    Iraq: "イラク",
    Ireland: "アイルランド",
    "Isle of Man": "マン島",
    Israel: "イスラエル",
    Italy: "イタリア",
    Jamaica: "ジャマイカ",
    Japan: "日本",
    Jersey: "ジャージー",
    Jordan: "ヨルダン",
    Kazakhstan: "カザフスタン",
    Kenya: "ケニア",
    Kiribati: "キリバス",
    "Korea, Democratic People'S Republic of": "韓国、民主人民共和国",
    "Korea, Republic of": "大韓民国",
    Kuwait: "クウェート",
    Kyrgyzstan: "キルギス",
    "Lao People'S Democratic Republic": "ラオス人民民主共和国",
    Latvia: "ラトビア",
    Lebanon: "レバノン",
    Lesotho: "レソト",
    Liberia: "リベリア",
    "Libyan Arab Jamahiriya": "リビア・アラブ・ジャマヒリヤ",
    Liechtenstein: "リヒテンシュタイン",
    Lithuania: "リトアニア",
    Luxembourg: "ルクセンブルク",
    Macao: "マカオ",
    "Macedonia, The Former Yugoslav Republic of": "マケドニア、旧ユーゴスラビア共和国",
    Madagascar: "マダガスカル",
    Malawi: "マラウイ",
    Malaysia: "マレーシア",
    Maldives: "モルディブ",
    Mali: "マリ",
    Malta: "マルタ",
    "Marshall Islands": "マーシャル諸島",
    Martinique: "マルティニーク",
    Mauritania: "モーリタニア",
    Mauritius: "モーリシャス",
    Mayotte: "マヨット",
    Mexico: "メキシコ",
    "Micronesia, Federated States of": "ミクロネシア連邦",
    "Moldova, Republic of": "モルドバ共和国",
    Monaco: "モナコ",
    Mongolia: "モンゴル",
    Montenegro: "モンテネグロ",
    Montserrat: "モントセラト",
    Morocco: "モロッコ",
    Mozambique: "モザンビーク",
    Myanmar: "ミャンマー",
    Namibia: "ナミビア",
    Nauru: "ナウル",
    Nepal: "ネパール",
    Netherlands: "オランダ",
    "Netherlands Antilles": "オランダ領アンティル",
    "New Caledonia": "ニューカレドニア",
    Nicaragua: "ニカラグア",
    Niger: "ニジェール",
    Nigeria: "ナイジェリア",
    Niue: "ニウエ",
    "Norfolk Island": "ノーフォーク島",
    "Northern Mariana Islands": "北マリアナ諸島",
    Norway: "ノルウェー",
    Oman: "オマーン",
    Pakistan: "パキスタン",
    Palau: "パラオ",
    "Palestinian Territory, Occupied": "パレスチナ領土、占領",
    Panama: "パナマ",
    "Papua New Guinea": "パプアニューギニア",
    Paraguay: "パラグアイ",
    Peru: "ペルー",
    Philippines: "フィリピン",
    Pitcairn: "ピトケアン",
    Poland: "ポーランド",
    Portugal: "ポルトガル",
    "Puerto Rico": "プエルトリコ",
    Qatar: "カタール",
    Reunion: "再会",
    Romania: "ルーマニア",
    "Russian Federation": "ロシア連邦",
    RWANDA: "ルワンダ",
    "Saint Helena": "セントヘレナ",
    "Saint Kitts and Nevis": "セントクリストファー・ネイビス",
    "Saint Lucia": "セントルシア",
    "Saint Pierre and Miquelon": "サンピエール島ミクロン島",
    "Saint Vincent and the Grenadines": "セントビンセントおよびグレナディーン諸島",
    Samoa: "サモア",
    "San Marino": "サンマリノ",
    "Sao Tome and Principe": "サントメ・プリンシペ",
    "Saudi Arabia": "サウジアラビア",
    Senegal: "セネガル",
    Serbia: "セルビア",
    Seychelles: "セーシェル",
    "Sierra Leone": "シエラレオネ",
    Singapore: "シンガポール",
    Slovakia: "スロバキア",
    Slovenia: "スロベニア",
    "Solomon Islands": "ソロモン諸島",
    Somalia: "ソマリア",
    "South Africa": "南アフリカ",
    "South Georgia and the South Sandwich Islands": "サウスジョージア島とサウスサンドイッチ諸島",
    Spain: "スペイン",
    "Sri Lanka": "スリランカ",
    Sudan: "スーダン",
    Surilabel: "スリラベル",
    "Svalbard and Jan Mayen": "スバールバル諸島とヤンマイエン島",
    Swaziland: "スワジランド",
    Sweden: "スウェーデン",
    Switzerland: "スイス",
    "Syrian Arab Republic": "シリア・アラブ共和国",
    "Taiwan, Province of China": "台湾、中国省",
    Tajikistan: "タジキスタン",
    "Tanzania, United Republic of": "タンザニア連合共和国",
    Thailand: "タイ",
    "Timor-Leste": "東ティモール",
    Togo: "持ち帰り",
    Tokelau: "トケラウ",
    Tonga: "トンガ",
    "Triidd and Tobago": "トリイド・トバゴ",
    Tunisia: "チュニジア",
    Turkey: "七面鳥",
    Turkmenistan: "トルクメニスタン",
    "Turks and Caicos Islands": "タークス・カイコス諸島",
    Tuvalu: "ツバル",
    Uganda: "ウガンダ",
    Ukraine: "ウクライナ",
    "United Arab Emirates": "アラブ首長国連邦",
    "United Kingdom": "イギリス",
    "United States Minor Outlying Islands": "米国小離島",
    Uruguay: "ウルグアイ",
    Uzbekistan: "ウズベキスタン",
    Vanuatu: "バヌアツ",
    Venezuela: "ベネズエラ",
    "Viet Nam": "ベトナム",
    "Virgin Islands, British": "バージン諸島、イギリス",
    "Virgin Islands, U.S.": "バージン諸島、米国",
    "Wallis and Futuna": "ウォリス・フツナ",
    "Western Sahara": "西サハラ",
    Yemen: "イエメン",
    Zambia: "ザンビア",
    Zimbabwe: "ジンバブエ",
    "Unlock All Schema with our Premium Plan": "プレミアム プランですべてのスキーマのロックを解除する",
    "Billed Monthly": "毎月請求",
    "Billed Annually": "毎年請求される",
    "Save 30%": "30% 割引",
    Premium100Title:
      "初期ユーザーの皆様には、すべてのプレミアム機能を無料でお楽しみいただけることをお約束します。すべてのプレミアム機能に無料で自由にアクセスできるため、価格ページについて心配する必要はありません。サービスを引き続きお楽しみいただくために、アプリをアンインストールしないでください。",
    Premium100ReviewLine:
      " 私たちのアプリが気に入っていただけましたら、レビューを残してください。これは、新しい機能を開発するモチベーションを高めるのに役立ちます。",
    "Check Our Current Pricing": "現在の価格を確認する",
    "Leave Review": "レビューを残す",
    "We're sorry to see you go!": "残念です。",
    "Cancel Plan": "プランをキャンセルする",
    "Sync Plan": "同期計画",
    "Disccount applied": "割引が適用されました",
    Apply: "適用する",
    "Your code(s)": "あなたのコード",
    "and discount have been applied successfully": "割引が正常に適用されました",
    "Your entered promocode is not correct, Enter a valid code":
      "入力したプロモーションコードが正しくありません。有効なコードを入力してください",
    "days trial left": "トライアル残り日数",
    Upgrade: "アップグレード",
    "days free trial, No Credit card required": "数日間の無料トライアル、クレジット カードは不要",
    Month: "月",
    Year: "年",
    Unlimited: "無制限",
    "Enter Promocode": "プロモーションコードを入力",
    "Please Choose a Cancellation Reason": "キャンセル理由を選択してください",
    "No Longer Needed?": "不要になりました？",
    "Didn't Meet Expectations": "期待に応えられなかった",
    "Cost Concerns": "コストの問題",
    "Technical Issues": "技術的な問題",
    "Found an Alternative": "代替品を見つけました",
    Complexity: "複雑",
    "Lack of Features": "機能の欠如",
    "Poor Customer Support": "貧弱な顧客サポート",
    "Business Closure or Change": "事業の閉鎖または変更",
    "Temporary Pause": "一時停止",
    "Performance Issues": "パフォーマンスの問題",
    Other: "他の",
    "Mention Your Specific Reason Here": "具体的な理由をここに記入してください",
    Start: "始める",
    "Day Free Trial": "一日無料トライアル",
    "Please Select One Option": "オプションを 1 つ選択してください",
    "Plan cancelled successfully": "計画は正常にキャンセルされました",
    "7 days free trial, No Credit card required": "7 日間の無料トライアル、クレジット カードは不要",
    "Your remaining trial days are": "残りのトライアル日数は",
    "You have used": "あなたが使用した",
    "days.": "日々。",
    "No trial days remaining. You have already used the 7-day free trial.":
      "トライアル日数は残りません。すでに 7 日間の無料トライアルを使用しています。",
    "Upgrade your plan now": "今すぐプランをアップグレードしてください",
    "Unlimited Slides": "無制限のスライド",
    "20+ Animation In & Out": "20 以上のアニメーションの入出力",
    "Live Chat Support": "ライブチャットサポート",
    "Priority, 24*7 Urgent setup and support": "優先、24 時間 365 日の緊急セットアップとサポート",
    "Rich Text Editor": "リッチテキストエディター",
    "One Slide(banner)": "1 つのスライド (バナー)",
    "Repeated Countdown timer": "繰り返しカウントダウンタイマー",
    "Fully Customisable": "完全にカスタマイズ可能",
    "Background-image": "背景画像",
    "Custom Css": "カスタム CSS",
    "Enable Our App": "アプリを有効にする",
    "Book Onboarding Demo": "オンボーディングデモを予約する",
    Next: "次",
    Finish: "仕上げる",
    Prev: "前へ",
    "App is not enable please click on the Enable App button to enable it.":
      "アプリが有効になっていません。「アプリを有効にする」ボタンをクリックして有効にしてください。",
    "This field is required": "この項目は必須です",
    disableButtonTooltip: "年間プランを利用しているため、月額プランにアップグレードすることはできません。",
    "Choose plan": "プランを選ぶ",
    "Purchase Plan": "購入プラン",
    Continue: "続く",
    "Image Optimization": "画像の最適化",
    "AI Metatags": "AI メタタグ",
    "Grand Total": "総計",
    "Metatags Edit": "メタタグの編集",
    Products: "製品",
    "Upgrade plan": "アップグレードプラン",
    "Your product count is": "あなたの商品数は",
    "so your suitable plan is": "したがって、あなたの適切なプランは",
    "Enjoy a": "楽しんでください",
    "lifetime discount": "生涯割引",
    discountBanner:
      " 生涯割引を活用して、永続的な節約を確保し、当社のプレミアム製品とサービスのエクスペリエンスを向上させましょう。",
    "Images for Optimization every year after trial period end": "試用期間終了後、毎年最適化用のイメージを提供",
    "AI Meta Tags Credit for every year after trial period end":
      "試用期間終了後、毎年 AI メタ タグ クレジットが付与されます",
    "Images for Optimization every month after trial period end": "試用期間終了後、毎月の最適化用イメージ",
    "AI Meta Tags Credit for every Month after trial period end": "試用期間終了後、毎月の AI メタタグ クレジット",
    "Optimize your google page speed": "Google ページの速度を最適化する",
    "50 Product Meta tags Optimize, Image alt": "50 個の製品メタ タグ 最適化、画像 alt",
    "Product Meta tags Optimize, Image alt": "製品メタタグ 最適化、画像代替",
    "AI ImageAltText Credit for every year after trial period end":
      "試用期間終了後、毎年 AI ImageAltText クレジットが付与されます",
    "25 AI ImageAltText Credit": "25 AI ImageAltText クレジット",
    "AI ImageAltText Credit for every Month after trial period end":
      "試用期間終了後、毎月の AI ImageAltText クレジット",
    "Contact Bar": "コンタクトバー",
    "Add To Cart Bar": "カートに追加バー",
    "Multiple Position": "複数のポジション",
    lowMsgStart: "このオファーは、Shopify ストアを始めたばかりのあなた向けに特別に設計されています。",
    lowMsgMiddle: "私たちの",
    lowMsgEnd: "割引は、この困難ではあるがエキサイティングな時期にお客様をサポートするための私たちの方法です。",
    mediumMsgStart: "このオファーは、Shopify ストアを始めたあなた向けに特別に設計されています。",
    mediumMsgMiddle: "私たちの",
    mediumMsgEnd: "割引は、この困難ではあるがエキサイティングな時期にお客様をサポートするための私たちの方法です。",
    importantMsgStart: "このオファーは、Shopify ストアを始めたあなた向けに特別に設計されています。",
    importantMsgMiddle: "私たちの",
    importantMsgEnd:
      "割引は、この困難ではあるがエキサイティングな時期にお客様をサポートするための私たちの方法です。",
    veryImportantMsgStart: "このオファーは、Shopify ストアをオープンしたあなた向けに特別に設計されています。",
    veryImportantMsgMiddle: "あなたは私たちにとって非常に重要で成熟した商人です。私たちの",
    veryImportantMsgEnd: "割引は、あなたが私たちにとってどれだけ意味があるかを示すことです。",
    generalMsg:
      "当社の Shopify アプリは、貴社のような確立されたビジネスのニーズを満たすように調整されています。大量の操作や複雑な操作をシームレスに処理できるように設計されています。 ",
    lowTitleStart: "新規起業家への特別サポート:",
    lowTitleEnd: "始めたばかりなので割引",
    mediumTitleStart: "起業家向けの特別サポート:",
    mediumTitleEnd: "開始時の割引",
    importantTitleStart: "起業家向けの特別サポート:",
    importantTitleEnd: "開始時の割引",
    veryImportantTitleStart: "おめでとうございます",
    veryImportantTitleEnd: "Shopifyで",
    month: "月",
    "year and": "年と",
    ago: "前",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "AI クレジットを追加 (1 AI クレジット/10¢) (10 AI クレジット/$1 )",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "画像の altText を追加 AI クレジット (1 AI クレジット/4¢) (25 AI クレジット/$1 )",
    "Monthly AI AltText Credit": "毎月の AI AltText クレジット",
    "Yearly AI AltText Credit": "年間 AI AltText クレジット",
    "Purchase AI AltText Credit": "AI AltText クレジットを購入する",
    "ImageAltText Credit": "ImageAltTextクレジット",
    "Your credits are finished; please upgrade your plan.":
      "クレジットは終了です。プランをアップグレードしてください。",
    "Your credits are finished; you can buy more credits from here.":
      "クレジットは終了です。ここからさらにクレジットを購入できます。",
    "This offer expire in": "このオファーの有効期限は次のとおりです",
    "Hurry Up!": "急いで！",
    Current: "現在",
    "Discount applied": "割引が適用されました",
    "trial left": "裁判は終了",
    "info banner":
      "「ホームページ画像をスキャン」ボタンをクリックすると、アプリはホームページ画像のみをスキャンします。この画像を最適化するには、「最適化」ボタンを手動でクリックしてください。",
    "Optimize Images": "画像の最適化",
    image: "画像",
    images: "画像",
    Filename: "ファイル名",
    Images: "画像",
    Setting: "設定",
    "Saved(in %)": "保存済み(%)",
    Action: "アクション",
    "Product Image": "製品イメージ",
    "product image": "製品画像",
    gif: "gif",
    Homepage: "ホームページ",
    "Manage Announcement": "お知らせの管理",
    "No Announcements Found": "お知らせが見つかりませんでした",
    Position: "位置",
    "Campaign Title": "キャンペーンタイトル",
    Visible: "見える",
    Invisible: "見えない",
    Views: "ビュー",
    Clicks: "クリック数",
    Submits: "提出",
    "Above Add to cart Button": "上のカートに追加ボタン",
    "Below Add to cart Button": "下の「カートに追加」ボタン",
    Targeting: "ターゲティング",
    "Rotating Animation Setting": "回転アニメーション設定",
    "Marquee Animation Setting": "マーキーアニメーション設定",
    "Show to visitors coming form then specific website": "特定のウェブサイトからアクセスした訪問者に表示する",
    "Add your website URL": "ウェブサイトのURLを追加する",
    "Banner Display Start Time": "バナー表示開始時間",
    "Banner Display End Time": "バナー表示終了時間",
    "Create Campaign": "キャンペーンを作成",
    "Select Announcement Bar": "アナウンスバーを選択",
    "Please select template.": "テンプレートを選択してください。",
    Previous: "前の",
    "Promotion bar": "プロモーションバー",
    "Add To Cart": "カートに追加",
    Embeded: "埋め込み",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "今後のセールやオファーについて顧客に通知したり、在庫アラートを設定したりできます。",
    "Increase your order value by using or Free Shipping Bar.": "または無料配送バーを使用して注文額を増やします。",
    "Conveniently add items to your cart with a single click!": "ワンクリックで商品をカートに便利に追加できます。",
    "Select to subscribe and receive special discounts directly to your inbox":
      "購読を選択すると、特別割引が直接受信トレイに届きます",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "「カートに追加」ボタンの前後に表示される埋め込みバーで特別オファーを強調表示します。",
    Select: "選択",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "バナー非表示 UTM コードを追加します (例:Ref=Facebook、Ref=Web、Utm_source=Google...)",
    "Include Utm": "Utmを含める",
    "Exclude Utm": "Utmを除外",
    "Campaign Design": "キャンペーンデザイン",
    "Background Setting": "背景設定",
    "Target Setting": "目標設定",
    Scheduling: "スケジュール",
    Rotating: "回転",
    Marquee: "マーキー",
    "Repeat Timer Date": "繰り返しタイマー日付",
    "Select Repeat Time": "繰り返し時間を選択",
    "Repeated Hours": "繰り返しの時間",
    Border: "国境",
    Bashed: "殴られた",
    "Multi Rotating": "マルチ回転",
    Contacts: "連絡先",
    Email: "Eメール",
    "First Name": "ファーストネーム",
    "Last Name": "苗字",
    Phone: "電話",
    "You have unsaved changes": "保存されていない変更があります",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "キャンペーンには保存されていない変更があります。保存せずに終了すると変更は失われます。",
    "Leave widthout saving": "幅外保存を残す",
    "Save Changes": "変更内容を保存",
    Announcement: "発表",
    Feedback: "フィードバック",
    "Recipe Instructions": "レシピの説明",
    "Visit Help Center": "ヘルプセンターにアクセス",
    "Schedule Meeting": "会議のスケジュール",
    "Setup guide": "セットアップガイド",
    "Use this personalized guide to get your store up and running":
      "このパーソナライズされたガイドを使用して、ストアを立ち上げて運営してください",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "アクションの取得を開始するには、アプリを有効にする必要があります。ボタンをクリックすると拡張機能ページに移動します。そこで保存をクリックして、ここに戻るだけです。",
    "Enable our app": "アプリを有効にする",
    "Learn more": "もっと詳しく知る",
    "Skip it": "スキップしてください",
    steps: "ステップ",
    minutes: "分",
    "Mark as done": "完了としてマークする",
    "Mark as not done": "未完了としてマークする",
    "You have completed all the steps": "すべての手順が完了しました",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "サイトの速度をアクティブにして分析し、検索結果でストアを上位にランク付けします。",
    "Google Page Speed Optimization": "Google ページ速度の最適化",
    "Activate Google Page Speed": "Google ページ速度を有効にする",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Google Page Speed ツールを有効にしてサイトのパフォーマンスを評価し、速度向上の機会を特定します。",
    "Enable Speed Analysis": "速度分析を有効にする",
    "Review Speed Analysis Report": "レビュー速度分析レポート",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "詳細な速度分析レポートを調べて、サイトの現在の速度指標を理解し、改善すべき領域を特定します。",
    "Go to Reports": "レポートに移動",
    Hello: "こんにちは",
    "Let's get your store ready for success": "あなたのストアを成功に向けて準備しましょう",
    "Finish later": "後で終了",
    "Continue onboarding": "オンボーディングを続ける",
    "Check image optimization features": "画像の最適化機能を確認する",
    "Explore Optimization Features": "最適化機能を調べる",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "利用可能なさまざまな画像最適化ツールについてよく理解してください。画像のサイズと形式を最適化することで、ページの読み込み速度と SEO を向上させる方法をご覧ください。",
    "Go to Image Optimization": "画像の最適化に移動",
    "Automate Your Image Workflow": "画像ワークフローを自動化する",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "新しい画像がアップロードされるときにシームレスに最適化する自動化を設定し、サイト全体で一貫したパフォーマンスを確保します。",
    "Go to Automation": "自動化に移動",
    "Execute a Bulk Optimization": "一括最適化を実行する",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "一括最適化を実行すると、複数の画像を一度に効率的に強化でき、サイトの読み込み時間を大幅に短縮できます。",
    "Go to bulk operations": "一括操作に移動",
    "Broken Links Management": "リンク切れの管理",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "壊れたリンクの検出と修復を自動化して、ユーザー エクスペリエンスと SEO ランキングを強化します。",
    "Review Detected Broken Links": "検出されたリンク切れを確認する",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "システムによって自動的に識別された壊れたリンクのリストを調べて、サイトのナビゲーションへの影響を理解してください。",
    "View Broken Links": "壊れたリンクを表示する",
    "Address Broken Links": "壊れたリンクに対処する",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "当社のツールを利用して壊れたリンクを迅速に修正またはリダイレクトし、サイトの完全性とユーザー満足度を向上させます。",
    "Resolve Broken Links": "壊れたリンクを解決する",
    "Automate for Efficiency": "自動化して効率化",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "自動修正を設定して、将来のリンク切れに先んじてサイトの継続的な健全性を確保します。",
    "Enable Automation": "自動化を有効にする",
    "Meta Tags Management": "メタタグ管理",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "ユーザーフレンドリーなメタタグ機能を使用して、サイトの可視性と検索エンジンのランキングを最適化します。",
    "Explore Meta Tag Options": "メタタグのオプションを調べる",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "個々の製品やページで利用できるさまざまなメタ タグの編集および自動化オプションについて理解します。",
    "Explore Meta Tags": "メタタグを調べる",
    "Edit and Optimize": "編集と最適化",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "メタ タイトル、説明、画像の代替テキストを編集して、サイトの SEO とユーザーのアクセシビリティを強化します。",
    "Start Editing": "編集を開始する",
    "Automate for Consistency": "一貫性を保つために自動化する",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "メタタグの自動化ルールを設定して、商品ページ全体で一貫性と効率を維持します。",
    "Set Automation": "オートメーションの設定",
    "Schema Markup": "スキーマのマークアップ",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "スキーマ マークアップを利用して、検索結果におけるコンテンツの表現を強化し、より多くのクリックを呼び込みます。",
    "Learn About Schema Options": "スキーマオプションについて学ぶ",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "製品、ローカル ビジネス、FAQ など、利用可能なさまざまな種類のスキーマ マークアップをよく理解し、その利点を理解してください。",
    "Explore Schema Types": "スキーマの種類を調べる",
    "Activate Key Schemas": "キースキーマのアクティブ化",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "電子商取引の製品スキーマや実店舗のローカル ビジネス スキーマなど、サイトにとって重要なスキーマを選択して有効にします。",
    "Go to Schemas": "スキーマに移動",
    "Customize Schema Details": "スキーマの詳細をカスタマイズする",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "各スキーマ タイプの設定をカスタマイズして、検索結果でビジネスや製品を正確に表現します。",
    "Test and Validate Schemas": "スキーマのテストと検証",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Google の構造化データ テスト ツールなどのツールを使用してスキーマをテストし、スキーマが正しく実装されていることを確認します。",
    "Test Schemas": "テストスキーマ",
    "Add Breadcrumbs": "ブレッドクラムの追加",
    "Add Breadcrumbs to your store": "ストアにブレッドクラムを追加する",
    "To get better user experience you need to add breadcrumbs to your store.":
      "ユーザーエクスペリエンスを向上させるには、ストアにブレッドクラムを追加する必要があります。",
    "How to add breadcrumbs": "パンくずリストの追加方法",
    "Understand how to add and configure breadcrumbs in your store.":
      "ストアにブレッドクラムを追加および構成する方法を理解します。",
    "Google search console": "Googleサーチコンソール",
    "Connect google search console to sync it with our app.":
      "Google Search Console に接続してアプリと同期します。",
    "How to connect GSC.": "GSCの接続方法です。",
    "Understand how to connect and use google search console in our app.":
      "アプリで Google Search Console に接続して使用する方法を理解します。",
    "Go to GSC": "GSCへ行く",
    "Go to Breadcrumbs Design": "ブレッドクラムのデザインに移動",
    "Start Onboarding": "オンボーディングを開始する",
    "Go to Homepage": "ホームページへ",
    "Go to Onboarding": "オンボーディングに移動",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "理解を深めるために設計されたユーザーフレンドリーなアプリガイドをご覧ください。 [オンボーディングを開始] をクリックして開始すると、いつでも再びホームページにアクセスできます。",
    "Please enable our app extension.": "アプリ拡張機能を有効にしてください。",
    "Generate Meta tags": "メタタグを生成する",
    "Test description a litle bit longer that title": "テストの説明を少し長くして、そのタイトルを",
    "Suggested for you": "あなたにおすすめ",
    "Enable Google page speed": "Googleのページ速度を有効にする",
    "Connect GSC": "GSCを接続する",
    "Enable Image Optimize Automation": "画像最適化の自動化を有効にする",
    "Automate Meta tags": "メタタグを自動化する",
    "Automate Broken Links": "壊れたリンクを自動化する",
    "Enhance SEO with automatically generated meta tags.": "自動生成されたメタタグで SEO を強化します。",
    "Improve website performance by optimizing images.":
      "画像を最適化することでウェブサイトのパフォーマンスを向上させます。",
    "Boost website speed by enabling Google Page Speed.":
      "Google Page Speed を有効にしてウェブサイトの速度を向上させます。",
    "Enhance search visibility by connecting to Google Search Console.":
      "Google Search Consoleに接続して検索の可視性を高めます。",
    "Streamline image optimization with automated processes.": "自動プロセスにより画像の最適化を合理化します。",
    "Improve SEO by automating the generation of meta tags.":
      "メタタグの生成を自動化することで SEO を改善します。",
    "Improve UX with automated detect and handle, broken links.":
      "壊れたリンクを自動検出して処理することで UX を向上させます。",
    "Learn About Add Announcement": "アナウンスの追加について学ぶ",
    "Skip And Add Announcement": "スキップしてアナウンスを追加",
    "Learn more about": "詳細はこちら",
    "Add Announcement": "お知らせを追加",
    "Announcement Bar": "アナウンスバー",
    "Rate us!": "私たちを評価してください！",
    "How would you Love this app?": "このアプリを気に入っていただけましたか?",
    "Enter Your Feedback Here": "ここにフィードバックを入力してください",
    "Leave Us a Review !!": "レビューを残してください!!",
    "If you like our app features then please leave us a review !!":
      "当アプリの機能が気に入ったら、ぜひレビューを残してください!!",
    "If you like our free features then please leave us a review !!":
      "当社の無料機能が気に入ったら、ぜひレビューを残してください!!",
    "Update Successfully": "更新に成功しました",
    "Uninstall App": "アプリをアンインストールする",
    "Contact Our Support": "サポートへのお問い合わせ",
    "Leave a message": "伝言を残す",
    "Please Choose a UnInstallation Reason": "アンインストールの理由を選択してください",
    "Are you facing any issues understanding the features of our app?":
      "当社のアプリの機能を理解する上で問題に直面していますか?",
    "Please Choose at least one reason": "少なくとも1つの理由を選択してください",
    "Thank You For Reaching Out": "ご連絡いただきありがとうございます",
    "Contact Support": "サポート問い合わせ先",
    "Get Help from Our Support Team": "サポートチームからのサポートを受ける",
    "Select a reason": "理由を選択してください",
    "Not getting how to use or setup": "使い方や設定方法が分からない",
    "Poor customer support": "顧客サポートが不十分",
    "Performance issues": "パフォーマンスの問題",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "当社のサポートチームは現在週末は対応しておりませんが、お客様のタイムゾーンに応じて平日にご利用いただけます。 ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " 当社はインドから運営しているため、メッセージを残すことは可能です。返答には多少の遅れが生じる可能性がありますのでご了承ください。しばらくお待ちください。",
    "Our support team is partially available according to your time zone from ":
      "当社のサポートチームは、お客様のタイムゾーンに応じて部分的に対応可能です。 ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " 当社はインドから運営しているため、対応に30分から1時間かかる場合があります。メッセージを残していただければ、できるだけ早く対応いたします。しばらくお待ちください。",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "当社のサポートチームは現在利用できません。お客様のタイムゾーンに応じて、 ",
    to: "に",
    "Did not meet my expectations": "期待に応えられなかった",
    "Feature Limitations": "機能の制限",
    "Banner doesn't set in my app": "アプリにバナーが設定されません",
    "Banner is not show properly": "バナーが正しく表示されません",
    "Confusing Set Multi Position and Multi Animation": "紛らわしいセットマルチポジションとマルチアニメーション",
    "Sync Profile": "プロファイルを同期",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
