import modifyData from "../Language/ko.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "활성화됨",
    Disabled: "장애가 있는",
    "Embed is currently disabled": "삽입이 현재 비활성화되어 있습니다.",
    "Enable App": "앱 활성화",
    "1. Click on Enable App.": "1. 앱 활성화를 클릭하세요.",
    "Well done!! you have successfully enable our app.": "잘하셨어요!! 우리 앱을 성공적으로 활성화했습니다.",
    "2. Enable": "2. 활성화",
    "App Embed as shown in image and save setting.": "이미지에 표시된 대로 앱을 삽입하고 설정을 저장합니다.",
    "Multi Announcement Bar": "다중 공지사항 바",
    "Click on the Enable Now button to enable it.": "활성화하려면 지금 활성화 버튼을 클릭하세요.",
    "Enable Announcement Bar to get started": "시작하려면 알림 표시줄을 활성화하세요.",
    "Enable Now": "지금 활성화",
    "Sync Status": "동기화 상태",
    Done: "완료",
    No: "아니요",
    Found: "설립하다",
    Add: "추가하다",
    Search: "찾다",
    Showing: "전시",
    of: "~의",
    "results, at most": "결과는 기껏해야",
    "per page": "페이지 당",
    "Oops! Something went wrong.": "이런! 문제가 발생했습니다.",
    "Let's try that again, please refresh the page.": "다시 시도해 보세요. 페이지를 새로고침해 주세요.",
    "If you're still stuck, contact us by chat support or":
      "여전히 문제가 해결되지 않으면 채팅 지원으로 문의하거나",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "그래서 우리가 도와드릴 수 있어요!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "높은 우선순위 또는 가장 관심 있는 기능으로 설정하려는 기능 3개를 선택하세요.",
    "Add ": "추가하다 ",
    "These is premium feature": "이것은 프리미엄 기능입니다",
    "Go to pricing": "가격으로 이동",
    Save: "구하다",
    Minimum: "최저한의",
    Maximum: "최고",
    "images are required": "이미지가 필요합니다",
    and: "그리고",
    "images are allowed": "이미지는 허용됩니다",
    Disconnect: "연결 끊기",
    "Sign In with Google": "Google로 로그인",
    "Oops! Something went wrong. Admin token is malformed":
      "이런! 문제가 발생했습니다. 관리 토큰의 형식이 잘못되었습니다.",
    "If you're still stuck, contact": "그래도 막히면 연락하세요",
    Premium: "프리미엄",
    Unlock: "터놓다",
    "Unlock advanced features!": "고급 기능을 잠금 해제하세요!",
    "© 2021 Webrex. All rights reserved.": "© 2021 웹렉스. 판권 소유.",
    "Privacy Policy": "개인 정보 정책",
    "Terms of Service": "서비스 약관",
    "Go to Shopify App": "Shopify 앱으로 이동",
    "Review Us": "우리를 검토",
    Cancel: "취소",
    "Review Popup Show": "팝업 쇼 검토",
    "click on review us": "리뷰를 클릭하세요",
    "Note: Feel free to leave a star rating without writing a review!":
      "참고: 리뷰를 작성하지 않고 자유롭게 별점을 남겨주세요!",
    Help: "돕다",
    "Help Button Click": "도움말 버튼 클릭",
    Confirm: "확인하다",
    On: "~에",
    Off: "끄다",
    Price: "가격",
    Settings: "설정",
    Animation: "생기",
    "My Profile": "내 프로필",
    "My Subscription": "내 구독",
    "Store Name": "가게 이름",
    "Store URL": "매장 URL",
    "Email ID": "이메일 주소",
    "Phone Number": "전화 번호",
    Country: "국가",
    Currency: "통화",
    "Subscription Name": "구독 이름",
    "Select language": "언어 선택",
    "Announcement setting": "공지사항 설정",
    "Animation setting": "애니메이션 설정",
    Selector: "선택자",
    "Save Setting": "설정 저장",
    "My Announcements": "내 공지사항",
    "Add bar": "바 추가",
    Number: "숫자",
    Title: "제목",
    "Create At": "생성 시간",
    "Slide Activation": "슬라이드 활성화",
    Status: "상태",
    Actions: "행위",
    "Save order": "주문 저장",
    "Reorder Slides": "슬라이드 재정렬",
    position: "위치",
    Top: "맨 위",
    "Sticky Top": "끈적끈적한 탑",
    "Bottom Fix": "하단 수정",
    "Custom Position": "맞춤 위치",
    "Custom Position *Add Class or id of Selected Element.":
      "사용자 정의 위치 *선택한 요소의 클래스 또는 ID를 추가합니다.",
    "Bar Padding (px)": "막대 패딩(px)",
    "Add Remove Button": "제거 버튼 추가",
    "Choose icon color": "아이콘 색상 선택",
    "Custom css": "맞춤 CSS",
    fadeIn: "점점 뚜렷해지다",
    fadeInDown: "페이드인다운",
    fadeInDownBig: "페이드인다운빅",
    fadeInLeft: "페이드인왼쪽",
    fadeInLeftBig: "페이드인왼쪽큰",
    fadeInUp: "페이드인업",
    bounceInDown: "바운스인다운",
    bounceInLeft: "왼쪽으로 바운스",
    bounceInUp: "바운스인업",
    zoomIn: "확대",
    zoomInDown: "확대/축소",
    zoomInLeft: "확대왼쪽",
    slideInLeft: "슬라이드인왼쪽",
    slideInUp: "슬라이드인업",
    slideInDown: "슬라이드인다운",
    lightSpeedIn: "라이트스피드인",
    rollIn: "롤인",
    flash: "플래시",
    shake: "떨림",
    flip: "튀기다",
    flipInX: "플립인X",
    flipOutX: "플립아웃X",
    fadeOut: "사라지다",
    fadeOutDown: "페이드아웃다운",
    fadeOutDownBig: "fadeOut아래로큰",
    fadeOutRight: "페이드아웃오른쪽",
    fadeOutRightBig: "fadeOut오른쪽큰",
    fadeOutUp: "페이드아웃업",
    bounceOutDown: "바운스아웃다운",
    bounceOutRight: "바운스아웃오른쪽",
    bounceOutUp: "바운스아웃업",
    zoomOut: "축소",
    zoomOutDown: "축소 축소",
    zoomOutRight: "확대/축소오른쪽",
    slideOutRight: "슬라이드아웃오른쪽",
    slideOutUp: "슬라이드아웃업",
    slideOutDown: "슬라이드아웃다운",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "발표",
    flipInY: "플립인Y",
    "Text Animation": "텍스트 애니메이션",
    "Animation In": "애니메이션 인",
    "Animation Out": "애니메이션 출력",
    "Auto play time (time in MS)": "자동 재생 시간(MS 단위의 시간)",
    "Animation time (time in MS)": "애니메이션 시간(MS 단위의 시간)",
    "Auto play time (time in Second)": "자동 재생 시간(초 단위 시간)",
    "Background Color": "배경색",
    "Space between slide(px)": "슬라이드 사이의 간격(px)",
    visible: "보이는",
    invisible: "보이지 않는",
    "Promotional & Countdown Bar": "프로모션 및 카운트다운 바",
    "Free Shipping Bar": "무료 배송 바",
    "Add Slide": "슬라이드 추가",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "무료 플랜에는 슬라이드 1개만 표시됩니다. 모든 슬라이드를 활성화하려면 프리미엄 플랜을 구독하세요.",
    Pricing: "가격",
    "No Animation Found": "애니메이션을 찾을 수 없습니다",
    "No Preview, Add announcement Bar": "미리보기 없음, 공지사항 표시줄 추가",
    "Update successfully": "업데이트가 성공적으로 완료되었습니다.",
    Enable: "할 수 있게 하다",
    Disable: "장애를 입히다",
    successfully: "성공적으로",
    "Delete successfully": "성공적으로 삭제되었습니다",
    "Copy successfully": "성공적으로 복사되었습니다.",
    "Reorder successfully": "성공적으로 재주문했습니다",
    "Announcement Message": "공지사항 메시지",
    "Call to Action": "행동을 요구하다",
    Timer: "시간제 노동자",
    Style: "스타일",
    "Background Type": "배경 유형",
    "Mobile Style": "모바일 스타일",
    "Schedule Display": "일정 표시",
    Update: "업데이트",
    "Change Font": "글꼴 변경",
    "Font Family": "글꼴군",
    "Font Style": "글꼴 스타일",
    Normal: "정상",
    Italic: "이탤릭체",
    Oblique: "비스듬한",
    Unset: "설정되지 않음",
    "Font Weight": "글꼴 두께",
    Bold: "용감한",
    "Message Font Size": "메시지 글꼴 크기",
    "Message Text color": "메시지 텍스트 색상",
    Type: "유형",
    None: "없음",
    Button: "단추",
    "Entire clickable bar": "클릭 가능한 막대 전체",
    "Add a simple link": "간단한 링크 추가",
    "Add coupon placement": "쿠폰 배치 추가",
    "Linked Url": "연결된 URL",
    "Background Hover Color": "배경 호버 색상",
    "Text Hover Color": "텍스트 호버 색상",
    "Button Text": "버튼 텍스트",
    "Copied Text": "복사된 텍스트",
    "Open in the new tab": "새 탭에서 열기",
    URL: "URL",
    "Font Size": "글꼴 크기",
    "Button Radius": "버튼 반경",
    "Button color": "버튼 색상",
    "Button Text color": "버튼 텍스트 색상",
    "Button Hover Color": "버튼 호버 색상",
    "button Text HoverColor": "버튼 텍스트 HoverColor",
    "Timer Setting": "타이머 설정",
    "Timer Type": "타이머 유형",
    Date: "날짜",
    "Select Reapt Time": "반복 시간 선택",
    "repeated Hours": "반복되는 시간",
    "Normal Timer": "일반 타이머",
    "Auto repeat timer": "자동 반복 타이머",
    Minute: "분",
    Hour: "시간",
    Day: "낮",
    "Remove Timer When Time End": "시간이 끝나면 타이머 제거",
    "Timer Separator": "타이머 분리기",
    "Countdown Timer color": "카운트다운 타이머 색상",
    "Timer Text Size": "타이머 텍스트 크기",
    "Timer Text Setting": "타이머 텍스트 설정",
    "Day Text": "요일 텍스트",
    "Hour Text": "시간 텍스트",
    "Minute Text": "분 텍스트",
    "Second Text": "두 번째 텍스트",
    "Background Image": "배경 이미지",
    "Gradient Background": "그라데이션 배경",
    "Style & Color For Mobile": "모바일용 스타일 및 색상",
    "Timer Background": "타이머 배경",
    "Timer Text Color": "타이머 텍스트 색상",
    "Button Color": "버튼 색상",
    "Button Text Color": "버튼 텍스트 색상",
    "Button Text Hover Color": "버튼 텍스트 호버 색상",
    "Button Text Size": "버튼 텍스트 크기",
    "Always Display": "항상 표시",
    "Only Display Within The Following Period Of Time": "다음 기간 내에만 표시",
    "Start Time": "시작 시간",
    "End Time": "종료 시간",
    "Advance Setting": "고급 설정",
    "Country Filter": "국가 필터",
    Visibility: "시계",
    "Desktop and Mobile": "데스크톱 및 모바일",
    "Only Desktop": "데스크톱만",
    "Only Mobile": "모바일 전용",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "사용자 소스 타겟팅(다음 UTM 코드를 포함하는 링크에서 들어오는 방문자, 예:Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "페이지 선택",
    Include: "포함하다",
    Exclude: "들어오지 못하게 하다",
    "Currency Configuration": "통화 구성",
    Message: "메시지",
    "Currency Symbol": "통화 기호",
    "Currency Position": "통화 포지션",
    Before: "전에",
    After: "후에",
    "money Class": "돈 수업",
    "Initial Message": "초기 메시지",
    "Shipping Goal": "배송 목표",
    "Progress Message": "진행 메시지",
    "Progress goal": "진행목표",
    "Goal Message": "목표 메시지",
    "Shipping Price Color": "배송비 색상",
    "Shipping Price Size": "배송비 사이즈",
    "Shipping Font Weight": "배송 글꼴 무게",
    "* When user first time visit": "* 사용자가 처음 방문하는 경우",
    "* When user add item to the cart e.g": "* 사용자가 장바구니에 품목을 추가하는 경우 예:",
    "* When cart value is greater than": "* 장바구니 금액이 다음보다 큰 경우",
    "Show On Selected Countries": "선택한 국가에 표시",
    "Show On Selected Pages": "선택한 페이지에 표시",
    All: "모두",
    Home: "집",
    Cart: "카트",
    Collection: "수집",
    Product: "제품",
    Custom: "관습",
    Page: "페이지",
    Blog: "블로그",
    "Url is required": "URL이 필요합니다",
    "Day Text is required": "요일 텍스트가 필요합니다",
    "Hour Text is required": "시간 텍스트가 필요합니다.",
    "Minute Text is required": "회의록 텍스트가 필요합니다.",
    "Second Text is required": "두 번째 텍스트가 필요합니다",
    "Start Time is required": "시작 시간은 필수 항목입니다.",
    "End Time is required": "종료 시간은 필수 항목입니다.",
    "Created successfully": "성공적으로 생성되었습니다",
    "United States": "미국",
    Canada: "캐나다",
    Australia: "호주",
    "New Zealand": "뉴질랜드",
    Germany: "독일",
    India: "인도",
    Afghanistan: "아프가니스탄",
    "land Islands": "육지 제도",
    Albania: "알바니아",
    Algeria: "알제리",
    "American Samoa": "아메리칸사모아",
    AndorrA: "안도라A",
    Angola: "앙골라",
    Anguilla: "앵귈라",
    Antarctica: "남극 대륙",
    "Antigua and Barbuda": "앤티가 바부다",
    Argentina: "아르헨티나",
    Armenia: "아르메니아",
    Aruba: "아루바",
    Austria: "오스트리아",
    Azerbaijan: "아제르바이잔",
    Bahamas: "바하마",
    Bahrain: "바레인",
    Bangladesh: "방글라데시",
    Barbados: "바베이도스",
    Belarus: "벨라루스",
    Belgium: "벨기에",
    Belize: "벨리즈",
    Benin: "베냉",
    Bermuda: "버뮤다",
    Bhutan: "부탄",
    Bolivia: "볼리비아",
    "Bosnia and Herzegovina": "보스니아 헤르체고비나",
    Botswana: "보츠와나",
    "Bouvet Island": "부베섬",
    Brazil: "브라질",
    "British Indian Ocean Territory": "영국령 인도양 지역",
    "Brunei Darussalam": "브루나이 다루살람",
    Bulgaria: "불가리아",
    "Burkina Faso": "부키 나 파소",
    Burundi: "부룬디",
    Cambodia: "캄보디아",
    Cameroon: "카메룬",
    "Cape Verde": "카보베르데",
    "Cayman Islands": "케이맨 제도",
    "Central African Republic": "중앙 아프리카 공화국",
    Chad: "차드",
    Chile: "칠레",
    China: "중국",
    "Christmas Island": "크리스마스 섬",
    "Cocos (Keeling) Islands": "코코스(킬링) 제도",
    Colombia: "콜롬비아",
    Comoros: "코모로",
    Congo: "콩고",
    "Congo, The Democratic Republic of the": "콩고민주공화국",
    "Cook Islands": "쿡 제도",
    "Costa Rica": "코스타리카",
    "Cote D'Ivoire": "코트디부아르",
    Croatia: "크로아티아",
    Cuba: "쿠바",
    Cyprus: "키프로스",
    "Czech Republic": "체코 공화국",
    Denmark: "덴마크",
    Djibouti: "지부티",
    Dominica: "도미니카",
    "Dominican Republic": "도미니카 공화국",
    Ecuador: "에콰도르",
    Egypt: "이집트",
    "El Salvador": "엘살바도르",
    "Equatorial Guinea": "적도기니",
    Eritrea: "에리트레아",
    Estonia: "에스토니아",
    Ethiopia: "에티오피아",
    "Falkland Islands (Malvinas)": "포클랜드 제도(말비나스)",
    "Faroe Islands": "페로 제도",
    Fiji: "피지",
    Finland: "핀란드",
    France: "프랑스",
    "French Guiana": "프랑스령 기아나",
    "French Polynesia": "프랑스 령 폴리네시아의",
    "French Southern Territories": "프랑스 남부 지역",
    Gabon: "가봉",
    Gambia: "감비아",
    Georgia: "그루지야",
    Ghana: "가나",
    Gibraltar: "지브롤터",
    Greece: "그리스",
    Greenland: "그린란드",
    Grenada: "그레나다",
    Guadeloupe: "과들루프",
    Guam: "괌",
    Guatemala: "과테말라",
    Guernsey: "건지",
    Guinea: "기니",
    "Guinea-Bissau": "기니비사우",
    Guyana: "가이아나",
    Haiti: "아이티",
    "Heard Island and Mcdonald Islands": "허드섬과 맥도날드섬",
    "Holy See (Vatican City State)": "교황청(바티칸 시국)",
    Honduras: "온두라스",
    "Hong Kong": "홍콩",
    Hungary: "헝가리",
    Iceland: "아이슬란드",
    Indonesia: "인도네시아",
    "Iran, Islamic Republic Of": "이란, 이슬람 공화국",
    Iraq: "이라크",
    Ireland: "아일랜드",
    "Isle of Man": "맨 섬",
    Israel: "이스라엘",
    Italy: "이탈리아",
    Jamaica: "자메이카",
    Japan: "일본",
    Jersey: "저지",
    Jordan: "요르단",
    Kazakhstan: "카자흐스탄",
    Kenya: "케냐",
    Kiribati: "키리바시",
    "Korea, Democratic People'S Republic of": "조선민주주의인민공화국",
    "Korea, Republic of": "대한민국",
    Kuwait: "쿠웨이트",
    Kyrgyzstan: "키르기스스탄",
    "Lao People'S Democratic Republic": "라오스 인민민주주의공화국",
    Latvia: "라트비아",
    Lebanon: "레바논",
    Lesotho: "레소토",
    Liberia: "라이베리아",
    "Libyan Arab Jamahiriya": "리비아 아랍 자마히리야",
    Liechtenstein: "리히텐슈타인",
    Lithuania: "리투아니아",
    Luxembourg: "룩셈부르크",
    Macao: "마카오",
    "Macedonia, The Former Yugoslav Republic of": "마케도니아, 구 유고슬라비아 공화국",
    Madagascar: "마다가스카르",
    Malawi: "말라위",
    Malaysia: "말레이시아",
    Maldives: "몰디브",
    Mali: "말리",
    Malta: "몰타",
    "Marshall Islands": "마샬 군도",
    Martinique: "마르티니크",
    Mauritania: "모리타니",
    Mauritius: "모리셔스",
    Mayotte: "마요트",
    Mexico: "멕시코",
    "Micronesia, Federated States of": "미크로네시아",
    "Moldova, Republic of": "몰도바 공화국",
    Monaco: "모나코",
    Mongolia: "몽골리아",
    Montenegro: "몬테네그로",
    Montserrat: "몬세라트",
    Morocco: "모로코",
    Mozambique: "모잠비크",
    Myanmar: "미얀마",
    Namibia: "나미비아",
    Nauru: "나우루",
    Nepal: "네팔",
    Netherlands: "네덜란드",
    "Netherlands Antilles": "네덜란드 령 앤 틸리 스",
    "New Caledonia": "뉴 칼레도니아",
    Nicaragua: "니카라과",
    Niger: "니제르",
    Nigeria: "나이지리아",
    Niue: "니우에",
    "Norfolk Island": "노퍽섬",
    "Northern Mariana Islands": "북마리아나 제도",
    Norway: "노르웨이",
    Oman: "오만",
    Pakistan: "파키스탄",
    Palau: "팔라우",
    "Palestinian Territory, Occupied": "팔레스타인 영토, 점령",
    Panama: "파나마",
    "Papua New Guinea": "파푸아 뉴기니",
    Paraguay: "파라과이",
    Peru: "페루",
    Philippines: "필리핀 제도",
    Pitcairn: "핏케언",
    Poland: "폴란드",
    Portugal: "포르투갈",
    "Puerto Rico": "푸에르토 리코",
    Qatar: "카타르",
    Reunion: "재결합",
    Romania: "루마니아",
    "Russian Federation": "러시아 연방",
    RWANDA: "르완다",
    "Saint Helena": "세인트 헬레나",
    "Saint Kitts and Nevis": "세인트키츠네비스",
    "Saint Lucia": "세인트루시아",
    "Saint Pierre and Miquelon": "생 피에르 앤 미클롱",
    "Saint Vincent and the Grenadines": "세인트 빈센트 그레나딘",
    Samoa: "사모아",
    "San Marino": "산 마리노",
    "Sao Tome and Principe": "상투메 프린시페",
    "Saudi Arabia": "사우디 아라비아",
    Senegal: "세네갈",
    Serbia: "세르비아",
    Seychelles: "세이셸",
    "Sierra Leone": "시에라리온",
    Singapore: "싱가포르",
    Slovakia: "슬로바키아",
    Slovenia: "슬로베니아",
    "Solomon Islands": "솔로몬 제도",
    Somalia: "소말리아",
    "South Africa": "남아프리카",
    "South Georgia and the South Sandwich Islands": "사우스조지아 사우스샌드위치 제도",
    Spain: "스페인",
    "Sri Lanka": "스리랑카",
    Sudan: "수단",
    Surilabel: "수리라벨",
    "Svalbard and Jan Mayen": "스발바르와 얀마옌",
    Swaziland: "스와질란드",
    Sweden: "스웨덴",
    Switzerland: "스위스",
    "Syrian Arab Republic": "시리아 아랍 공화국",
    "Taiwan, Province of China": "대만, 중국",
    Tajikistan: "타지키스탄",
    "Tanzania, United Republic of": "탄자니아, 미국",
    Thailand: "태국",
    "Timor-Leste": "동티모르",
    Togo: "토고",
    Tokelau: "토켈라우",
    Tonga: "통가",
    "Triidd and Tobago": "트리이드 토바고",
    Tunisia: "튀니지",
    Turkey: "칠면조",
    Turkmenistan: "투르크메니스탄",
    "Turks and Caicos Islands": "터크스 케이커스 제도",
    Tuvalu: "투발루",
    Uganda: "우간다",
    Ukraine: "우크라이나",
    "United Arab Emirates": "아랍 에미리트",
    "United Kingdom": "영국",
    "United States Minor Outlying Islands": "미국령 군소 제도",
    Uruguay: "우루과이",
    Uzbekistan: "우즈베키스탄",
    Vanuatu: "바누아투",
    Venezuela: "베네수엘라",
    "Viet Nam": "베트남",
    "Virgin Islands, British": "영국령 버진 아일랜드",
    "Virgin Islands, U.S.": "미국 버진아일랜드",
    "Wallis and Futuna": "월리스푸투나",
    "Western Sahara": "서부 사하라",
    Yemen: "예멘",
    Zambia: "잠비아",
    Zimbabwe: "짐바브웨",
    "Unlock All Schema with our Premium Plan": "프리미엄 플랜으로 모든 스키마 잠금 해제",
    "Billed Monthly": "월별 청구",
    "Billed Annually": "매년 청구됨",
    "Save 30%": "30% 할인",
    Premium100Title:
      "초기 사용자로서 우리는 귀하가 모든 프리미엄 기능을 무료로 즐길 수 있음을 보장합니다. 모든 프리미엄 기능을 무료로 자유롭게 액세스할 수 있으므로 가격 페이지에 대해 걱정할 필요가 없습니다. 계속해서 서비스를 즐기려면 앱을 제거하지 마세요.",
    Premium100ReviewLine:
      " 저희 앱이 마음에 드신다면 리뷰를 남겨주세요. 이는 새로운 기능을 개발하는 데 동기를 부여하는 데 도움이 됩니다.",
    "Check Our Current Pricing": "현재 가격을 확인하세요",
    "Leave Review": "리뷰 남기기",
    "We're sorry to see you go!": "배웅 못 해줘서 미안해!",
    "Cancel Plan": "계획 취소",
    "Sync Plan": "동기화 계획",
    "Disccount applied": "할인이 적용되었습니다",
    Apply: "적용하다",
    "Your code(s)": "귀하의 코드",
    "and discount have been applied successfully": "할인이 성공적으로 적용되었습니다",
    "Your entered promocode is not correct, Enter a valid code":
      "입력한 프로모션 코드가 올바르지 않습니다. 유효한 코드를 입력하세요.",
    "days trial left": "남은 평가판 일수",
    Upgrade: "업그레이드",
    "days free trial, No Credit card required": "일 무료 평가판, 신용 카드 필요 없음",
    Month: "월",
    Year: "년도",
    Unlimited: "제한 없는",
    "Enter Promocode": "프로모션 코드 입력하기",
    "Please Choose a Cancellation Reason": "취소 사유를 선택하세요.",
    "No Longer Needed?": "더 이상 필요 없어요?",
    "Didn't Meet Expectations": "기대에 미치지 못함",
    "Cost Concerns": "비용 문제",
    "Technical Issues": "기술적 문제",
    "Found an Alternative": "대안을 찾았습니다",
    Complexity: "복잡성",
    "Lack of Features": "기능 부족",
    "Poor Customer Support": "열악한 고객 지원",
    "Business Closure or Change": "폐업 또는 변경",
    "Temporary Pause": "임시 정지",
    "Performance Issues": "성능 문제",
    Other: "다른",
    "Mention Your Specific Reason Here": "여기에 구체적인 이유를 언급하세요",
    Start: "시작",
    "Day Free Trial": "일일 무료 평가판",
    "Please Select One Option": "하나의 옵션을 선택하십시오",
    "Plan cancelled successfully": "계획이 성공적으로 취소되었습니다",
    "7 days free trial, No Credit card required": "7일 무료 평가판, 신용카드 필요 없음",
    "Your remaining trial days are": "남은 평가판 일수는 다음과 같습니다.",
    "You have used": "당신은 사용했습니다",
    "days.": "날.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "남은 평가판 일수가 없습니다. 이미 7일 무료 평가판을 사용하셨습니다.",
    "Upgrade your plan now": "지금 플랜을 업그레이드하세요",
    "Unlimited Slides": "무제한 슬라이드",
    "20+ Animation In & Out": "20개 이상의 애니메이션 인앤아웃",
    "Live Chat Support": "라이브 채팅 지원",
    "Priority, 24*7 Urgent setup and support": "우선순위, 24*7 긴급 설정 및 지원",
    "Rich Text Editor": "리치 텍스트 편집기",
    "One Slide(banner)": "슬라이드 1개(배너)",
    "Repeated Countdown timer": "반복 카운트다운 타이머",
    "Fully Customisable": "완전히 맞춤화 가능",
    "Background-image": "배경 이미지",
    "Custom Css": "맞춤 CSS",
    "Enable Our App": "우리 앱 활성화",
    "Book Onboarding Demo": "온보딩 데모 예약",
    Next: "다음",
    Finish: "마치다",
    Prev: "이전",
    "App is not enable please click on the Enable App button to enable it.":
      "앱이 활성화되어 있지 않습니다. 활성화하려면 앱 활성화 버튼을 클릭하세요.",
    "This field is required": "이 필드는 필수입니다",
    disableButtonTooltip: "연간 요금제와 마찬가지로 월간 요금제를 업그레이드할 수 없습니다!",
    "Choose plan": "요금제 선택",
    "Purchase Plan": "구매 계획",
    Continue: "계속하다",
    "Image Optimization": "이미지 최적화",
    "AI Metatags": "AI 메타태그",
    "Grand Total": "총계",
    "Metatags Edit": "메타태그 편집",
    Products: "제품",
    "Upgrade plan": "업그레이드 계획",
    "Your product count is": "귀하의 제품 수는 다음과 같습니다.",
    "so your suitable plan is": "그래서 당신에게 적합한 계획은",
    "Enjoy a": "즐겨보세요",
    "lifetime discount": "평생할인",
    discountBanner: " 평생 할인을 받아 영구 저축을 확보하고 프리미엄 제품과 서비스에 대한 경험을 향상하십시오.",
    "Images for Optimization every year after trial period end": "평가판 기간 종료 후 매년 최적화를 위한 이미지",
    "AI Meta Tags Credit for every year after trial period end": "평가 기간 종료 후 매년 AI 메타 태그 크레딧 제공",
    "Images for Optimization every month after trial period end": "평가판 기간 종료 후 매월 최적화용 이미지",
    "AI Meta Tags Credit for every Month after trial period end":
      "평가판 기간 종료 후 매월 AI 메타 태그 크레딧 제공",
    "Optimize your google page speed": "Google 페이지 속도 최적화",
    "50 Product Meta tags Optimize, Image alt": "제품 메타 태그 50개 최적화, 이미지 대체",
    "Product Meta tags Optimize, Image alt": "제품 메타 태그 최적화, 이미지 대체",
    "AI ImageAltText Credit for every year after trial period end":
      "평가판 기간 종료 후 매년 AI ImageAltText 크레딧",
    "25 AI ImageAltText Credit": "25 AI ImageAltText 크레딧",
    "AI ImageAltText Credit for every Month after trial period end":
      "평가판 기간 종료 후 매월 AI ImageAltText 크레딧",
    "Contact Bar": "연락처 바",
    "Add To Cart Bar": "장바구니 바에 추가",
    "Multiple Position": "다중 위치",
    lowMsgStart: "이 제안은 이제 막 Shopify 스토어를 시작한 귀하를 위해 특별히 고안되었습니다.",
    lowMsgMiddle: "우리의",
    lowMsgEnd: "할인은 이 힘들지만 흥미로운 시기에 귀하를 지원하는 우리의 방법입니다.",
    mediumMsgStart: "이 제안은 Shopify 스토어를 시작한 귀하를 위해 특별히 고안되었습니다.",
    mediumMsgMiddle: "우리의",
    mediumMsgEnd: "할인은 이 힘들지만 흥미로운 시기에 귀하를 지원하는 우리의 방법입니다.",
    importantMsgStart: "이 제안은 Shopify 스토어를 시작한 귀하를 위해 특별히 고안되었습니다.",
    importantMsgMiddle: "우리의",
    importantMsgEnd: "할인은 이 힘들지만 흥미로운 시기에 귀하를 지원하는 우리의 방법입니다.",
    veryImportantMsgStart: "이 제안은 Shopify 스토어를 개설한 귀하를 위해 특별히 고안되었습니다.",
    veryImportantMsgMiddle: "당신은 우리에게 매우 중요하고 성숙한 상인입니다. 우리의",
    veryImportantMsgEnd: "할인은 귀하가 우리에게 얼마나 의미가 있는지를 보여주는 것입니다.",
    generalMsg:
      "Shopify 앱은 귀하와 같은 기존 기업의 요구 사항을 충족하도록 맞춤화되었습니다. 대용량과 복잡한 작업을 원활하게 처리하도록 설계되었습니다. ",
    lowTitleStart: "신규 창업자를 위한 특별 지원:",
    lowTitleEnd: "방금 시작했기 때문에 할인을 받으세요",
    mediumTitleStart: "기업가를 위한 특별 지원:",
    mediumTitleEnd: "시작부터 할인",
    importantTitleStart: "기업가를 위한 특별 지원:",
    importantTitleEnd: "시작부터 할인",
    veryImportantTitleStart: "되신걸 축하드립니다",
    veryImportantTitleEnd: "Shopify에서",
    month: "월",
    "year and": "연도와",
    ago: "~ 전에",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )": "AI 크레딧 추가(1 AI 크레딧/10¢) (10 AI 크레딧/$1 )",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "이미지 추가 altText AI 크레딧(1 AI 크레딧/4¢) (25 AI 크레딧/$1 )",
    "Monthly AI AltText Credit": "월간 AI AltText 크레딧",
    "Yearly AI AltText Credit": "연간 AI AltText 크레딧",
    "Purchase AI AltText Credit": "AI AltText 크레딧 구매",
    "ImageAltText Credit": "ImageAltText 크레딧",
    "Your credits are finished; please upgrade your plan.":
      "귀하의 크레딧이 완료되었습니다. 요금제를 업그레이드해주세요.",
    "Your credits are finished; you can buy more credits from here.":
      "귀하의 크레딧이 완료되었습니다. 여기에서 더 많은 크레딧을 구입할 수 있습니다.",
    "This offer expire in": "이 제안은 다음 날짜에 만료됩니다.",
    "Hurry Up!": "서둘러요!",
    Current: "현재의",
    "Discount applied": "할인이 적용되었습니다",
    "trial left": "남은 재판",
    "info banner":
      "홈페이지 이미지 스캔 버튼을 클릭하면 당사 앱은 홈페이지 이미지만 스캔합니다. 이 이미지를 최적화하려면 최적화 버튼을 수동으로 클릭하세요.",
    "Optimize Images": "이미지 최적화",
    image: "영상",
    images: "이미지",
    Filename: "파일 이름",
    Images: "이미지",
    Setting: "환경",
    "Saved(in %)": "저장됨(%)",
    Action: "행동",
    "Product Image": "제품 이미지",
    "product image": "제품 이미지",
    gif: "gif",
    Homepage: "홈페이지",
    "Manage Announcement": "공지사항 관리",
    "No Announcements Found": "공지사항을 찾을 수 없습니다.",
    Position: "위치",
    "Campaign Title": "캠페인 제목",
    Visible: "보이는",
    Invisible: "보이지 않는",
    Views: "견해",
    Clicks: "클릭수",
    Submits: "제출",
    "Above Add to cart Button": "위 장바구니에 담기 버튼",
    "Below Add to cart Button": "장바구니에 담기 버튼 아래",
    Targeting: "타겟팅",
    "Rotating Animation Setting": "회전 애니메이션 설정",
    "Marquee Animation Setting": "움직이는 애니메이션 설정",
    "Show to visitors coming form then specific website": "방문자에게 특정 웹사이트 양식을 보여줍니다.",
    "Add your website URL": "웹사이트 URL을 추가하세요.",
    "Banner Display Start Time": "배너 표시 시작 시간",
    "Banner Display End Time": "배너 표시 종료 시간",
    "Create Campaign": "캠페인 만들기",
    "Select Announcement Bar": "공지사항 바 선택",
    "Please select template.": "템플릿을 선택해주세요.",
    Previous: "이전의",
    "Promotion bar": "프로모션 바",
    "Add To Cart": "장바구니에 담기",
    Embeded: "내장됨",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "고객에게 다가올 세일이나 특가 정보를 알리거나, 재고 알림을 설정합니다.",
    "Increase your order value by using or Free Shipping Bar.":
      "또는 무료 배송 바를 사용하여 주문 가치를 높이세요.",
    "Conveniently add items to your cart with a single click!":
      "단 한 번의 클릭으로 편리하게 장바구니에 상품을 추가하세요!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "구독을 선택하면 특별 할인 혜택을 이메일로 직접 받으실 수 있습니다.",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "장바구니에 담기 버튼 앞과 뒤에 표시되는 내장형 막대로 특별 할인 혜택을 강조하세요.",
    Select: "선택하다",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "배너 숨기기 UTM 코드를 추가합니다(예: Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Utm 포함",
    "Exclude Utm": "Utm 제외",
    "Campaign Design": "캠페인 디자인",
    "Background Setting": "배경 설정",
    "Target Setting": "타겟 설정",
    Scheduling: "스케줄링",
    Rotating: "회전",
    Marquee: "큰 천막",
    "Repeat Timer Date": "반복 타이머 날짜",
    "Select Repeat Time": "반복 시간 선택",
    "Repeated Hours": "반복되는 시간",
    Border: "국경",
    Bashed: "두들겨 맞다",
    "Multi Rotating": "다중 회전",
    Contacts: "콘택트 렌즈",
    Email: "이메일",
    "First Name": "이름",
    "Last Name": "성",
    Phone: "핸드폰",
    "You have unsaved changes": "저장되지 않은 변경사항이 있습니다.",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "캠페인에 저장되지 않은 변경사항이 있습니다. 저장하지 않고 나가면 변경사항이 손실됩니다.",
    "Leave widthout saving": "너비를 초과하여 저장하지 마십시오.",
    "Save Changes": "변경 사항을 저장하다",
    Announcement: "발표",
    Feedback: "피드백",
    "Recipe Instructions": "레시피 지침",
    "Visit Help Center": "도움말 센터 방문",
    "Schedule Meeting": "회의 예약",
    "Setup guide": "설정 가이드",
    "Use this personalized guide to get your store up and running":
      "이 맞춤형 가이드를 활용하여 매장을 운영하세요.",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "앱을 활성화하는 데 필요한 작업을 시작하려면 버튼을 클릭하면 확장 프로그램 페이지로 이동합니다. 그런 다음 거기에서 저장을 클릭하고 여기로 돌아오면 됩니다.",
    "Enable our app": "우리 앱을 활성화하세요",
    "Learn more": "더 알아보기",
    "Skip it": "그냥 넘어가",
    steps: "단계",
    minutes: "분",
    "Mark as done": "완료로 표시",
    "Mark as not done": "완료되지 않음으로 표시",
    "You have completed all the steps": "모든 단계를 완료했습니다.",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "사이트 속도를 활성화하고 분석하여 검색 결과에서 매장 순위를 높이세요.",
    "Google Page Speed Optimization": "Google 페이지 속도 최적화",
    "Activate Google Page Speed": "Google 페이지 속도 활성화",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Google Page Speed 도구를 활성화하여 사이트 성능을 평가하고 속도 향상 기회를 파악하세요.",
    "Enable Speed Analysis": "속도 분석 활성화",
    "Review Speed Analysis Report": "속도 분석 보고서 검토",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "자세한 속도 분석 보고서를 검토하여 사이트의 현재 속도 지표를 이해하고 개선이 필요한 영역을 찾아보세요.",
    "Go to Reports": "보고서로 이동",
    Hello: "안녕하세요",
    "Let's get your store ready for success": "귀하의 매장이 성공할 수 있도록 준비합시다",
    "Finish later": "나중에 완료",
    "Continue onboarding": "계속해서 온보딩",
    "Check image optimization features": "이미지 최적화 기능 확인",
    "Explore Optimization Features": "최적화 기능 살펴보기",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "사용 가능한 다양한 이미지 최적화 도구를 숙지하세요. 이미지 크기와 형식을 최적화하여 페이지 로드 속도와 SEO를 개선할 수 있는 방법을 알아보세요.",
    "Go to Image Optimization": "이미지 최적화로 이동",
    "Automate Your Image Workflow": "이미지 워크플로우 자동화",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "새로운 이미지가 업로드될 때 원활하게 최적화되도록 자동화를 설정하여 사이트 전체에서 일관된 성능을 보장하세요.",
    "Go to Automation": "자동화로 이동",
    "Execute a Bulk Optimization": "대량 최적화 실행",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "일괄 최적화를 수행하여 한 번에 여러 이미지를 효율적으로 개선하면 사이트 로딩 시간이 크게 늘어날 수 있습니다.",
    "Go to bulk operations": "대량 작업으로 이동",
    "Broken Links Management": "끊어진 링크 관리",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "깨진 링크의 감지 및 복구를 자동화하여 사용자 경험과 SEO 순위를 향상합니다.",
    "Review Detected Broken Links": "감지된 끊어진 링크 검토",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "귀하의 사이트 탐색에 미치는 영향을 이해하려면 당사 시스템에서 자동으로 식별한 끊어진 링크 목록을 검토하십시오.",
    "View Broken Links": "끊어진 링크 보기",
    "Address Broken Links": "끊어진 링크 해결",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "당사의 도구를 활용하여 끊어진 링크를 신속하게 수정하거나 리디렉션하여 사이트의 무결성과 사용자 만족도를 향상시키십시오.",
    "Resolve Broken Links": "끊어진 링크 해결",
    "Automate for Efficiency": "효율성을 위한 자동화",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "향후 끊어진 링크에 앞서 자동 수정을 설정하여 지속적인 사이트 상태를 보장하세요.",
    "Enable Automation": "자동화 활성화",
    "Meta Tags Management": "메타 태그 관리",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "사용자 친화적인 메타 태그 기능으로 사이트의 가시성과 검색 엔진 순위를 최적화하세요.",
    "Explore Meta Tag Options": "메타태그 옵션 살펴보기",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "개별 제품 및 페이지에 사용할 수 있는 다양한 메타 태그 편집 및 자동화 옵션에 대해 알아보세요.",
    "Explore Meta Tags": "메타 태그 살펴보기",
    "Edit and Optimize": "편집 및 최적화",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "사이트의 SEO 및 사용자 접근성을 향상시키기 위해 메타 제목, 설명 및 이미지 대체 텍스트를 편집해 보세요.",
    "Start Editing": "편집 시작",
    "Automate for Consistency": "일관성을 위한 자동화",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "제품 페이지 전체에서 일관성과 효율성을 유지하려면 메타 태그에 대한 자동화 규칙을 설정하세요.",
    "Set Automation": "자동화 설정",
    "Schema Markup": "스키마 마크업",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "스키마 마크업을 활용하여 검색 결과에서 콘텐츠 표현을 향상하고 더 많은 클릭을 유도하세요.",
    "Learn About Schema Options": "스키마 옵션에 대해 알아보기",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "제품, 지역 비즈니스, FAQ 등 사용 가능한 다양한 유형의 스키마 마크업을 숙지하고 그 이점을 이해하세요.",
    "Explore Schema Types": "스키마 유형 살펴보기",
    "Activate Key Schemas": "주요 스키마 활성화",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "전자상거래용 제품 스키마, 실제 매장용 로컬 비즈니스 스키마 등 사이트에 중요한 스키마를 선택하고 활성화하세요.",
    "Go to Schemas": "스키마로 이동",
    "Customize Schema Details": "스키마 세부정보 사용자 정의",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "검색 결과에 귀하의 비즈니스나 제품이 정확하게 나타나도록 각 스키마 유형의 설정을 맞춤화하세요.",
    "Test and Validate Schemas": "스키마 테스트 및 검증",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Google의 구조화된 데이터 테스트 도구와 같은 도구를 사용하여 스키마를 테스트하여 스키마가 올바르게 구현되었는지 확인하세요.",
    "Test Schemas": "테스트 스키마",
    "Add Breadcrumbs": "이동 경로 추가",
    "Add Breadcrumbs to your store": "상점에 탐색경로 추가",
    "To get better user experience you need to add breadcrumbs to your store.":
      "더 나은 사용자 경험을 얻으려면 상점에 탐색경로를 추가해야 합니다.",
    "How to add breadcrumbs": "탐색경로를 추가하는 방법",
    "Understand how to add and configure breadcrumbs in your store.":
      "상점에 탐색경로를 추가하고 구성하는 방법을 이해하십시오.",
    "Google search console": "구글 서치 콘솔",
    "Connect google search console to sync it with our app.": "Google 검색 콘솔을 연결하여 앱과 동기화하세요.",
    "How to connect GSC.": "GSC를 연결하는 방법.",
    "Understand how to connect and use google search console in our app.":
      "앱에서 Google Search Console을 연결하고 사용하는 방법을 알아보세요.",
    "Go to GSC": "GSC로 이동",
    "Go to Breadcrumbs Design": "이동 경로 디자인으로 이동",
    "Start Onboarding": "온보딩 시작",
    "Go to Homepage": "홈페이지로 이동",
    "Go to Onboarding": "온보딩으로 이동",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "이해를 돕기 위해 고안된 사용자 친화적인 앱 가이드를 살펴보세요. 시작하려면 '온보딩 시작'을 클릭하세요. 언제든지 홈페이지로 다시 오실 수 있습니다.",
    "Please enable our app extension.": "앱 확장 기능을 활성화해 주세요.",
    "Generate Meta tags": "메타 태그 생성",
    "Test description a litle bit longer that title": "제목보다 조금 더 긴 테스트 설명",
    "Suggested for you": "당신을 위해 제안",
    "Enable Google page speed": "Google 페이지 속도 활성화",
    "Connect GSC": "GSC 연결",
    "Enable Image Optimize Automation": "이미지 최적화 자동화 활성화",
    "Automate Meta tags": "메타 태그 자동화",
    "Automate Broken Links": "끊어진 링크 자동화",
    "Enhance SEO with automatically generated meta tags.": "자동으로 생성된 메타 태그로 SEO를 강화하세요.",
    "Improve website performance by optimizing images.": "이미지를 최적화하여 웹사이트 성능을 향상하세요.",
    "Boost website speed by enabling Google Page Speed.":
      "Google Page Speed를 활성화하여 웹사이트 속도를 높이세요.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Google Search Console에 연결하여 검색 가시성을 향상하세요.",
    "Streamline image optimization with automated processes.": "자동화된 프로세스로 이미지 최적화를 간소화합니다.",
    "Improve SEO by automating the generation of meta tags.": "메타 태그 생성을 자동화하여 SEO를 개선합니다.",
    "Improve UX with automated detect and handle, broken links.":
      "끊어진 링크를 자동으로 감지하고 처리하여 UX를 개선합니다.",
    "Learn About Add Announcement": "공지 추가에 대해 알아보기",
    "Skip And Add Announcement": "공지 사항 건너뛰기 및 추가",
    "Learn more about": "자세히 알아보기",
    "Add Announcement": "공지사항 추가",
    "Announcement Bar": "공지사항 바",
    "Rate us!": "우리를 평가해 주세요!",
    "How would you Love this app?": "이 앱이 마음에 드시나요?",
    "Enter Your Feedback Here": "여기에 피드백을 입력하세요",
    "Leave Us a Review !!": "리뷰를 남겨주세요!!",
    "If you like our app features then please leave us a review !!":
      "저희 앱 기능이 마음에 드신다면 리뷰를 남겨주세요!!",
    "If you like our free features then please leave us a review !!":
      "무료 기능이 마음에 드신다면 리뷰를 남겨주세요!!",
    "Update Successfully": "업데이트가 성공적으로 완료되었습니다.",
    "Uninstall App": "앱 제거",
    "Contact Our Support": "지원팀에 문의하세요",
    "Leave a message": "메시지를 남겨주세요",
    "Please Choose a UnInstallation Reason": "제거 이유를 선택하십시오",
    "Are you facing any issues understanding the features of our app?":
      "우리 앱의 기능을 이해하는 데 문제가 있습니까?",
    "Please Choose at least one reason": "이유를 하나 이상 선택하세요.",
    "Thank You For Reaching Out": "문의해 주셔서 감사합니다.",
    "Contact Support": "연락처 지원",
    "Get Help from Our Support Team": "지원팀으로부터 도움을 받으세요",
    "Select a reason": "이유를 선택하세요",
    "Not getting how to use or setup": "사용 방법이나 설정 방법을 알 수 없음",
    "Poor customer support": "열악한 고객 지원",
    "Performance issues": "성능 문제",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "우리 지원팀은 현재 주말에 근무하지 않으며 귀하의 시간대에 따라 주중에는 ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " 우리는 인도에서 사업을 하고 있습니다. 메시지를 남길 수는 있습니다. 답변이 다소 지연될 수 있습니다. 양해해 주셔서 감사합니다.",
    "Our support team is partially available according to your time zone from ":
      "우리 지원팀은 귀하의 시간대에 따라 부분적으로 이용 가능합니다. ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " 우리는 인도에서 사업을 하고 있습니다. 이 시간 동안 응답은 30분에서 1시간 정도 걸릴 수 있습니다. 메시지를 남겨주시면 최대한 빨리 답변해드리겠습니다. 양해해 주셔서 감사합니다.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "우리 지원팀은 현재 이용할 수 없으며 귀하의 시간대에 따라 다음 시간부터 이용 가능합니다. ",
    to: "에게",
    "Did not meet my expectations": "내 기대에 미치지 못함",
    "Feature Limitations": "기능 제한",
    "Banner doesn't set in my app": "내 앱에 배너가 설정되지 않습니다",
    "Banner is not show properly": "배너가 제대로 표시되지 않습니다",
    "Confusing Set Multi Position and Multi Animation": "다중 위치 설정과 다중 애니메이션 설정의 혼동",
    "Sync Profile": "동기화 프로필",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
