import modifyData from "../Language/nl.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Ingeschakeld",
    Disabled: "Gehandicapt",
    "Embed is currently disabled": "Insluiten is momenteel uitgeschakeld",
    "Enable App": "App inschakelen",
    "1. Click on Enable App.": "1. Klik op App inschakelen.",
    "Well done!! you have successfully enable our app.": "Goed gedaan!! je hebt onze app succesvol ingeschakeld.",
    "2. Enable": "2. Inschakelen",
    "App Embed as shown in image and save setting.":
      "App insluiten zoals weergegeven in afbeelding en instellingen opslaan.",
    "Multi Announcement Bar": "Balk met meerdere aankondigingen",
    "Click on the Enable Now button to enable it.": "Klik op de knop Nu inschakelen om deze in te schakelen.",
    "Enable Announcement Bar to get started": "Schakel de aankondigingsbalk in om aan de slag te gaan",
    "Enable Now": "Schakel nu in",
    "Sync Status": "Synchronisatiestatus",
    Done: "Klaar",
    No: "Nee",
    Found: "Gevonden",
    Add: "Toevoegen",
    Search: "Zoekopdracht",
    Showing: "Tonen",
    of: "van",
    "results, at most": "resultaten, hoogstens",
    "per page": "per pagina",
    "Oops! Something went wrong.": "Oeps! Er is iets fout gegaan.",
    "Let's try that again, please refresh the page.": "Laten we het nog eens proberen. Vernieuw de pagina.",
    "If you're still stuck, contact us by chat support or":
      "Als je nog steeds vastzit, neem dan contact met ons op via chatondersteuning of",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "dus wij kunnen helpen!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Selecteer een van de drie functies die u met hoge prioriteit of met de meeste interesse wilt instellen",
    "Add ": "Toevoegen ",
    "These is premium feature": "Dit is een premiumfunctie",
    "Go to pricing": "Ga naar prijzen",
    Save: "Redden",
    Minimum: "Minimum",
    Maximum: "Maximaal",
    "images are required": "afbeeldingen zijn vereist",
    and: "En",
    "images are allowed": "afbeeldingen zijn toegestaan",
    Disconnect: "Loskoppelen",
    "Sign In with Google": "Log in met Google",
    "Oops! Something went wrong. Admin token is malformed":
      "Oeps! Er is iets fout gegaan. Beheerdertoken heeft een onjuiste indeling",
    "If you're still stuck, contact": "Als je nog steeds vastzit, neem dan contact op",
    Premium: "Premie",
    Unlock: "Ontgrendelen",
    "Unlock advanced features!": "Ontgrendel geavanceerde functies!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Alle rechten voorbehouden.",
    "Privacy Policy": "Privacybeleid",
    "Terms of Service": "Servicevoorwaarden",
    "Go to Shopify App": "Ga naar Shopify-app",
    "Review Us": "Beoordeel ons",
    Cancel: "Annuleren",
    "Review Popup Show": "Beoordeel pop-upshow",
    "click on review us": "klik op review ons",
    "Note: Feel free to leave a star rating without writing a review!":
      "Let op: Laat gerust een sterbeoordeling achter zonder een recensie te schrijven!",
    Help: "Hulp",
    "Help Button Click": "Help-knop Klik",
    Confirm: "Bevestigen",
    On: "Op",
    Off: "Uit",
    Price: "Prijs",
    Settings: "Instellingen",
    Animation: "Animatie",
    "My Profile": "Mijn profiel",
    "My Subscription": "Mijn abonnement",
    "Store Name": "Winkel naam",
    "Store URL": "Winkel-URL",
    "Email ID": "E-mail identiteit",
    "Phone Number": "Telefoonnummer",
    Country: "Land",
    Currency: "Munteenheid",
    "Subscription Name": "Abonnementsnaam",
    "Select language": "Selecteer taal",
    "Announcement setting": "Aankondiging instelling",
    "Animation setting": "Animatie-instelling",
    Selector: "Selector",
    "Save Setting": "Instelling opslaan",
    "My Announcements": "Mijn aankondigingen",
    "Add bar": "Voeg balk toe",
    Number: "Nummer",
    Title: "Titel",
    "Create At": "Creëer bij",
    "Slide Activation": "Dia-activering",
    Status: "Toestand",
    Actions: "Acties",
    "Save order": "Bestelling opslaan",
    "Reorder Slides": "Dia's opnieuw rangschikken",
    position: "positie",
    Top: "Bovenkant",
    "Sticky Top": "Kleverige bovenkant",
    "Bottom Fix": "Bodemcorrectie",
    "Custom Position": "Aangepaste positie",
    "Custom Position *Add Class or id of Selected Element.":
      "Aangepaste positie *Voeg klasse of ID van geselecteerd element toe.",
    "Bar Padding (px)": "Stangvulling (px)",
    "Add Remove Button": "Knop Verwijderen toevoegen",
    "Choose icon color": "Kies de kleur van het pictogram",
    "Custom css": "Aangepaste CSS",
    fadeIn: "vervagen",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLinks",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "fadeInUp",
    bounceInDown: "stuiterenInDown",
    bounceInLeft: "stuiterenInLinks",
    bounceInUp: "stuiterenInUp",
    zoomIn: "in zoomen",
    zoomInDown: "zoomInOmlaag",
    zoomInLeft: "zoomInLinks",
    slideInLeft: "slideInLinks",
    slideInUp: "slideInUp",
    slideInDown: "slideInDown",
    lightSpeedIn: "lichtSpeedIn",
    rollIn: "rolIn",
    flash: "flash",
    shake: "schudden",
    flip: "omdraaien",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "fade-out",
    fadeOutDown: "fadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fadeOutUp",
    bounceOutDown: "bounceOutDown",
    bounceOutRight: "bounceOutRight",
    bounceOutUp: "bounceOutUp",
    zoomOut: "uitzoomen",
    zoomOutDown: "zoomUitOmlaag",
    zoomOutRight: "zoomOutRechts",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "lichtSpeedOut",
    rollOut: "uitrollen",
    flipInY: "flipInY",
    "Text Animation": "Tekstanimatie",
    "Animation In": "Animatie In",
    "Animation Out": "Animatie uit",
    "Auto play time (time in MS)": "Automatische afspeeltijd (tijd in MS)",
    "Animation time (time in MS)": "Animatietijd (tijd in MS)",
    "Auto play time (time in Second)": "Automatische afspeeltijd (tijd in seconden)",
    "Background Color": "Achtergrond kleur",
    "Space between slide(px)": "Ruimte tussen dia(px)",
    visible: "zichtbaar",
    invisible: "onzichtbaar",
    "Promotional & Countdown Bar": "Promotie- en aftelbalk",
    "Free Shipping Bar": "Gratis verzendingsbalk",
    "Add Slide": "Dia toevoegen",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Bij het GRATIS abonnement is slechts 1 dia zichtbaar. Om Alle dia's te activeren, abonneert u zich op het Premium Plan.",
    Pricing: "Prijzen",
    "No Animation Found": "Geen animatie gevonden",
    "No Preview, Add announcement Bar": "Geen voorbeeld, aankondigingsbalk toevoegen",
    "Update successfully": "Update succesvol",
    Enable: "Inschakelen",
    Disable: "Uitzetten",
    successfully: "met succes",
    "Delete successfully": "Succesvol verwijderen",
    "Copy successfully": "Kopieer succesvol",
    "Reorder successfully": "Opnieuw bestellen",
    "Announcement Message": "Aankondiging bericht",
    "Call to Action": "Oproep tot actie",
    Timer: "Timer",
    Style: "Stijl",
    "Background Type": "Achtergrondtype",
    "Mobile Style": "Mobiele stijl",
    "Schedule Display": "Weergave schema",
    Update: "Update",
    "Change Font": "Wijzig lettertype",
    "Font Family": "Lettertypefamilie",
    "Font Style": "Lettertype",
    Normal: "Normaal",
    Italic: "Cursief",
    Oblique: "Schuin",
    Unset: "Uitgeschakeld",
    "Font Weight": "Lettertype dikte",
    Bold: "Vetgedrukt",
    "Message Font Size": "Lettergrootte bericht",
    "Message Text color": "Bericht Tekstkleur",
    Type: "Type",
    None: "Geen",
    Button: "Knop",
    "Entire clickable bar": "Gehele klikbare balk",
    "Add a simple link": "Voeg een eenvoudige link toe",
    "Add coupon placement": "Voeg couponplaatsing toe",
    "Linked Url": "Gelinkte URL",
    "Background Hover Color": "Achtergrondkleur zweven",
    "Text Hover Color": "Tekstzweefkleur",
    "Button Text": "Knop tekst",
    "Copied Text": "Gekopieerde tekst",
    "Open in the new tab": "Openen in het nieuwe tabblad",
    URL: "URL",
    "Font Size": "Lettertypegrootte",
    "Button Radius": "Knopradius",
    "Button color": "Knop kleur",
    "Button Text color": "Knop Tekstkleur",
    "Button Hover Color": "Knopzweefkleur",
    "button Text HoverColor": "knop Tekst HoverColor",
    "Timer Setting": "Timerinstelling",
    "Timer Type": "Timertype",
    Date: "Datum",
    "Select Reapt Time": "Selecteer Herhalingstijd",
    "repeated Hours": "herhaalde uren",
    "Normal Timer": "Normale timer",
    "Auto repeat timer": "Timer voor automatische herhaling",
    Minute: "Minuut",
    Hour: "Uur",
    Day: "Dag",
    "Remove Timer When Time End": "Verwijder de timer als de tijd voorbij is",
    "Timer Separator": "Timer-scheider",
    "Countdown Timer color": "Kleur afteltimer",
    "Timer Text Size": "Timertekstgrootte",
    "Timer Text Setting": "Timertekstinstelling",
    "Day Text": "Dag tekst",
    "Hour Text": "Uur tekst",
    "Minute Text": "Minuut tekst",
    "Second Text": "Tweede tekst",
    "Background Image": "Achtergrond afbeelding",
    "Gradient Background": "Achtergrond met kleurovergang",
    "Style & Color For Mobile": "Stijl en kleur voor mobiel",
    "Timer Background": "Timerachtergrond",
    "Timer Text Color": "Timertekstkleur",
    "Button Color": "Knop kleur",
    "Button Text Color": "Knoptekstkleur",
    "Button Text Hover Color": "Knoptekst Hoverkleur",
    "Button Text Size": "Tekstgrootte van knop",
    "Always Display": "Altijd weergeven",
    "Only Display Within The Following Period Of Time": "Alleen weergave binnen de volgende tijdsperiode",
    "Start Time": "Starttijd",
    "End Time": "Eindtijd",
    "Advance Setting": "Geavanceerde instelling",
    "Country Filter": "Landfilter",
    Visibility: "Zichtbaarheid",
    "Desktop and Mobile": "Desktop en mobiel",
    "Only Desktop": "Alleen bureaublad",
    "Only Mobile": "Alleen mobiel",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "GEBRUIKERSBRON TARGETING (Bezoekers die afkomstig zijn van een link die deze volgende UTM-code bevat, bijvoorbeeld.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Selecteer Pagina",
    Include: "Erbij betrekken",
    Exclude: "Uitsluiten",
    "Currency Configuration": "Valutaconfiguratie",
    Message: "Bericht",
    "Currency Symbol": "Symbool van munteenheid",
    "Currency Position": "Valutapositie",
    Before: "Voor",
    After: "Na",
    "money Class": "geld klasse",
    "Initial Message": "Eerste bericht",
    "Shipping Goal": "Verzendingsdoel",
    "Progress Message": "Vooruitgangsbericht",
    "Progress goal": "Vooruitgangsdoel",
    "Goal Message": "Doelbericht",
    "Shipping Price Color": "Verzendprijs Kleur",
    "Shipping Price Size": "Verzendprijs Grootte",
    "Shipping Font Weight": "Gewicht verzendlettertype",
    "* When user first time visit": "* Wanneer de gebruiker voor het eerst bezoekt",
    "* When user add item to the cart e.g":
      "* Wanneer de gebruiker een item aan de winkelwagen toevoegt, bijvoorbeeld:",
    "* When cart value is greater than": "* Wanneer de winkelwagenwaarde groter is dan",
    "Show On Selected Countries": "Toon in geselecteerde landen",
    "Show On Selected Pages": "Weergeven op geselecteerde pagina's",
    All: "Alle",
    Home: "Thuis",
    Cart: "Winkelwagen",
    Collection: "Verzameling",
    Product: "Product",
    Custom: "Aangepast",
    Page: "Bladzijde",
    Blog: "Bloggen",
    "Url is required": "URL is vereist",
    "Day Text is required": "Dagtekst is vereist",
    "Hour Text is required": "Uurtekst is vereist",
    "Minute Text is required": "Notulentekst is vereist",
    "Second Text is required": "Tweede tekst is vereist",
    "Start Time is required": "Starttijd is vereist",
    "End Time is required": "Eindtijd is vereist",
    "Created successfully": "Succesvol aangemaakt",
    "United States": "Verenigde Staten",
    Canada: "Canada",
    Australia: "Australië",
    "New Zealand": "Nieuw-Zeeland",
    Germany: "Duitsland",
    India: "Indië",
    Afghanistan: "Afghanistan",
    "land Islands": "land eilanden",
    Albania: "Albanië",
    Algeria: "Algerije",
    "American Samoa": "Amerikaans Samoa",
    AndorrA: "Andorra",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarctica",
    "Antigua and Barbuda": "Antigua en Barbuda",
    Argentina: "Argentinië",
    Armenia: "Armenië",
    Aruba: "Aruba",
    Austria: "Oostenrijk",
    Azerbaijan: "Azerbeidzjan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrein",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Wit-Rusland",
    Belgium: "België",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermuda",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    "Bosnia and Herzegovina": "Bosnië-Herzegovina",
    Botswana: "Botswana",
    "Bouvet Island": "Bouvet-eiland",
    Brazil: "Brazilië",
    "British Indian Ocean Territory": "Brits-Indisch oceaan gebied",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgarije",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Cambodja",
    Cameroon: "Kameroen",
    "Cape Verde": "Kaapverdië",
    "Cayman Islands": "Kaaiman Eilanden",
    "Central African Republic": "Centraal Afrikaanse Republiek",
    Chad: "Tsjaad",
    Chile: "Chili",
    China: "China",
    "Christmas Island": "Kersteiland",
    "Cocos (Keeling) Islands": "Cocoseilanden (Keeling).",
    Colombia: "Colombia",
    Comoros: "Comoren",
    Congo: "Congo",
    "Congo, The Democratic Republic of the": "Congo, de Democratische Republiek van de",
    "Cook Islands": "Cook Eilanden",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Ivoorkust",
    Croatia: "Kroatië",
    Cuba: "Cuba",
    Cyprus: "Cyprus",
    "Czech Republic": "Tsjechische Republiek",
    Denmark: "Denemarken",
    Djibouti: "Djibouti",
    Dominica: "Dominica",
    "Dominican Republic": "Dominicaanse Republiek",
    Ecuador: "Ecuador",
    Egypt: "Egypte",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Equatoriaal-Guinea",
    Eritrea: "Eritrea",
    Estonia: "Estland",
    Ethiopia: "Ethiopië",
    "Falkland Islands (Malvinas)": "Falklandeilanden (Malvinas)",
    "Faroe Islands": "Faeröer eilanden",
    Fiji: "Fiji",
    Finland: "Finland",
    France: "Frankrijk",
    "French Guiana": "Frans-Guyana",
    "French Polynesia": "Frans-Polynesië",
    "French Southern Territories": "Franse zuidelijke gebieden",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgië",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Griekenland",
    Greenland: "Groenland",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinee-Bissau",
    Guyana: "Guyana",
    Haiti: "Haïti",
    "Heard Island and Mcdonald Islands": "Heard-eiland en McDonald-eilanden",
    "Holy See (Vatican City State)": "Heilige Stoel (staat Vaticaanstad)",
    Honduras: "Honduras",
    "Hong Kong": "Hongkong",
    Hungary: "Hongarije",
    Iceland: "IJsland",
    Indonesia: "Indonesië",
    "Iran, Islamic Republic Of": "Iran, Islamitische Republiek",
    Iraq: "Irak",
    Ireland: "Ierland",
    "Isle of Man": "Eiland Man",
    Israel: "Israël",
    Italy: "Italië",
    Jamaica: "Jamaica",
    Japan: "Japan",
    Jersey: "Jersey",
    Jordan: "Jordanië",
    Kazakhstan: "Kazachstan",
    Kenya: "Kenia",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Korea, Democratische Volksrepubliek",
    "Korea, Republic of": "Korea, republiek van",
    Kuwait: "Koeweit",
    Kyrgyzstan: "Kirgizië",
    "Lao People'S Democratic Republic": "Lao Democratische Volksrepubliek",
    Latvia: "Letland",
    Lebanon: "Libanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    "Libyan Arab Jamahiriya": "Libië",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Litouwen",
    Luxembourg: "Luxemburg",
    Macao: "Macau",
    "Macedonia, The Former Yugoslav Republic of": "Macedonië, de Voormalige Joegoslavische Republiek",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Maleisië",
    Maldives: "Maldiven",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Marshall eilanden",
    Martinique: "Martinique",
    Mauritania: "Mauritanië",
    Mauritius: "Mauritius",
    Mayotte: "Mayotte",
    Mexico: "Mexico",
    "Micronesia, Federated States of": "Micronesië, Federale Staten van",
    "Moldova, Republic of": "Moldavië, Republiek",
    Monaco: "Monaco",
    Mongolia: "Mongolië",
    Montenegro: "Montenegro",
    Montserrat: "Montserrat",
    Morocco: "Marokko",
    Mozambique: "Mozambique",
    Myanmar: "Myanmar",
    Namibia: "Namibië",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Nederland",
    "Netherlands Antilles": "Nederlandse Antillen",
    "New Caledonia": "Nieuw-Caledonië",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    "Norfolk Island": "Norfolkeiland",
    "Northern Mariana Islands": "noordelijke Mariana eilanden",
    Norway: "Noorwegen",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Palestijns gebied, bezet",
    Panama: "Panama",
    "Papua New Guinea": "Papoea-Nieuw-Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Filippijnen",
    Pitcairn: "Pitcairn",
    Poland: "Polen",
    Portugal: "Portugal",
    "Puerto Rico": "Puerto Rico",
    Qatar: "Katar",
    Reunion: "Bijeenkomst",
    Romania: "Roemenië",
    "Russian Federation": "Russische Federatie",
    RWANDA: "RWANDA",
    "Saint Helena": "Sint-Helena",
    "Saint Kitts and Nevis": "Saint Kitts en Nevis",
    "Saint Lucia": "Sint Lucia",
    "Saint Pierre and Miquelon": "Saint-Pierre en Miquelon",
    "Saint Vincent and the Grenadines": "Saint Vincent en de Grenadines",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tomé en Principe",
    "Saudi Arabia": "Saoedi-Arabië",
    Senegal: "Senegal",
    Serbia: "Servië",
    Seychelles: "Seychellen",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slowakije",
    Slovenia: "Slovenië",
    "Solomon Islands": "Solomon eilanden",
    Somalia: "Somalië",
    "South Africa": "Zuid-Afrika",
    "South Georgia and the South Sandwich Islands": "Zuid-Georgië en de Zuidelijke Sandwicheilanden",
    Spain: "Spanje",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Soedan",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Spitsbergen en Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Zweden",
    Switzerland: "Zwitserland",
    "Syrian Arab Republic": "Syrische Arabische Republiek",
    "Taiwan, Province of China": "Taiwan, provincie China",
    Tajikistan: "Tadzjikistan",
    "Tanzania, United Republic of": "Tanzania, Verenigde Republiek",
    Thailand: "Thailand",
    "Timor-Leste": "Oost-Timor",
    Togo: "Gaan",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd en Tobago",
    Tunisia: "Tunesië",
    Turkey: "Kalkoen",
    Turkmenistan: "Turkmenistan",
    "Turks and Caicos Islands": "Turks- en Caicoseilanden",
    Tuvalu: "Tuvalu",
    Uganda: "Oeganda",
    Ukraine: "Oekraïne",
    "United Arab Emirates": "Verenigde Arabische Emiraten",
    "United Kingdom": "Verenigd Koninkrijk",
    "United States Minor Outlying Islands": "Kleine afgelegen eilanden van de Verenigde Staten",
    Uruguay: "Uruguay",
    Uzbekistan: "Oezbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands, British": "Maagdeneilanden, Brits",
    "Virgin Islands, U.S.": "Maagdeneilanden, VS",
    "Wallis and Futuna": "Wallis en Futuna",
    "Western Sahara": "Westelijke Sahara",
    Yemen: "Jemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Ontgrendel alle schema's met ons Premium Plan",
    "Billed Monthly": "Maandelijks gefactureerd",
    "Billed Annually": "Jaarlijks gefactureerd",
    "Save 30%": "Bespaar 30%",
    Premium100Title:
      "Als vroege gebruiker verzekeren wij u dat u kosteloos van al onze premiumfuncties zult genieten. U hoeft zich geen zorgen te maken over de prijspagina, aangezien u kosteloos toegang heeft tot al onze premiumfuncties. Verwijder onze app niet om van onze service te blijven genieten.",
    Premium100ReviewLine:
      " Als je onze app leuk vindt, laat ons dan een beoordeling achter. Dat helpt ons gemotiveerd te raken bij het ontwikkelen van nieuwe functies.",
    "Check Our Current Pricing": "Bekijk onze huidige prijzen",
    "Leave Review": "Beoordeling achterlaten",
    "We're sorry to see you go!": "We vinden het jammer dat je weggaat!",
    "Cancel Plan": "Annuleer abonnement",
    "Sync Plan": "Synchronisatieplan",
    "Disccount applied": "Korting toegepast",
    Apply: "Toepassen",
    "Your code(s)": "Jouw code(s)",
    "and discount have been applied successfully": "en korting zijn met succes toegepast",
    "Your entered promocode is not correct, Enter a valid code":
      "Uw ingevoerde promocode is niet correct. Voer een geldige code in",
    "days trial left": "dagen proef nog",
    Upgrade: "Upgrade",
    "days free trial, No Credit card required": "dagen gratis proefperiode, geen creditcard vereist",
    Month: "Maand",
    Year: "Jaar",
    Unlimited: "Onbeperkt",
    "Enter Promocode": "Voer promotiecode in",
    "Please Choose a Cancellation Reason": "Kies een reden voor annulering",
    "No Longer Needed?": "Niet langer nodig?",
    "Didn't Meet Expectations": "Voldeed niet aan de verwachtingen",
    "Cost Concerns": "Kostenproblemen",
    "Technical Issues": "Technische problemen",
    "Found an Alternative": "Een alternatief gevonden",
    Complexity: "Complexiteit",
    "Lack of Features": "Gebrek aan functies",
    "Poor Customer Support": "Slechte klantenondersteuning",
    "Business Closure or Change": "Bedrijfssluiting of verandering",
    "Temporary Pause": "Tijdelijke pauze",
    "Performance Issues": "Prestatieproblemen",
    Other: "Ander",
    "Mention Your Specific Reason Here": "Vermeld hier uw specifieke reden",
    Start: "Begin",
    "Day Free Trial": "Dag gratis proefperiode",
    "Please Select One Option": "Selecteer één optie",
    "Plan cancelled successfully": "Plan geannuleerd",
    "7 days free trial, No Credit card required": "Gratis proefperiode van 7 dagen, geen creditcard vereist",
    "Your remaining trial days are": "Uw resterende proefdagen zijn",
    "You have used": "Je hebt gebruikt",
    "days.": "dagen.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Er zijn geen proefdagen meer. Je hebt al gebruik gemaakt van de gratis proefperiode van 7 dagen.",
    "Upgrade your plan now": "Upgrade nu uw abonnement",
    "Unlimited Slides": "Onbeperkte dia's",
    "20+ Animation In & Out": "20+ animatie in en uit",
    "Live Chat Support": "Livechat-ondersteuning",
    "Priority, 24*7 Urgent setup and support": "Prioriteit, 24*7 Spoedinstallatie en ondersteuning",
    "Rich Text Editor": "Rich Text-editor",
    "One Slide(banner)": "Eén dia (banner)",
    "Repeated Countdown timer": "Herhaalde afteltimer",
    "Fully Customisable": "Volledig aanpasbaar",
    "Background-image": "Achtergrond afbeelding",
    "Custom Css": "Aangepaste CSS",
    "Enable Our App": "Schakel onze app in",
    "Book Onboarding Demo": "Boek een onboarding-demo",
    Next: "Volgende",
    Finish: "Finish",
    Prev: "Vorige",
    "App is not enable please click on the Enable App button to enable it.":
      "App is niet ingeschakeld. Klik op de knop App inschakelen om deze in te schakelen.",
    "This field is required": "dit veld is verplicht",
    disableButtonTooltip: "U kunt het maandabonnement niet upgraden omdat u een jaarabonnement heeft!",
    "Choose plan": "Kies abonnement",
    "Purchase Plan": "Aankoopplan",
    Continue: "Doorgaan",
    "Image Optimization": "Beeldoptimalisatie",
    "AI Metatags": "AI-metatags",
    "Grand Total": "Eindtotaal",
    "Metatags Edit": "Metatags Bewerken",
    Products: "Producten",
    "Upgrade plan": "Upgradeplan",
    "Your product count is": "Uw productaantal is",
    "so your suitable plan is": "dus uw geschikte plan is",
    "Enjoy a": "Geniet van een",
    "lifetime discount": "levenslange korting",
    discountBanner:
      " Omarm een levenslange korting, verzeker u van eeuwigdurende besparingen en verbeter uw ervaring met onze premium producten en diensten.",
    "Images for Optimization every year after trial period end":
      "Afbeeldingen voor optimalisatie elk jaar na afloop van de proefperiode",
    "AI Meta Tags Credit for every year after trial period end":
      "AI-metatagstegoed voor elk jaar na het einde van de proefperiode",
    "Images for Optimization every month after trial period end":
      "Afbeeldingen voor optimalisatie elke maand na afloop van de proefperiode",
    "AI Meta Tags Credit for every Month after trial period end":
      "AI-metatagstegoed voor elke maand na het einde van de proefperiode",
    "Optimize your google page speed": "Optimaliseer de snelheid van uw Google-pagina",
    "50 Product Meta tags Optimize, Image alt": "50 Product-metatags Optimaliseren, Afbeelding alt",
    "Product Meta tags Optimize, Image alt": "Product-metatags Optimaliseren, Afbeelding alt",
    "AI ImageAltText Credit for every year after trial period end":
      "AI ImageAltText Tegoed voor elk jaar na het einde van de proefperiode",
    "25 AI ImageAltText Credit": "25 AI ImageAltText-tegoed",
    "AI ImageAltText Credit for every Month after trial period end":
      "AI ImageAltText-tegoed voor elke maand na het einde van de proefperiode",
    "Contact Bar": "Contactbalk",
    "Add To Cart Bar": "Voeg toe aan winkelwagenbalk",
    "Multiple Position": "Meerdere posities",
    lowMsgStart: "Deze aanbieding is speciaal voor u ontworpen, aangezien u net uw Shopify-winkel bent gestart",
    lowMsgMiddle: "Ons",
    lowMsgEnd: "korting is onze manier om u te ondersteunen tijdens deze uitdagende maar opwindende tijden.",
    mediumMsgStart: "Deze aanbieding is speciaal voor u ontworpen, aangezien u uw Shopify-winkel bent gestart",
    mediumMsgMiddle: "Ons",
    mediumMsgEnd: "korting is onze manier om u te ondersteunen tijdens deze uitdagende maar opwindende tijden.",
    importantMsgStart: "Deze aanbieding is speciaal voor u ontworpen, aangezien u uw Shopify-winkel bent gestart",
    importantMsgMiddle: "Ons",
    importantMsgEnd: "korting is onze manier om u te ondersteunen tijdens deze uitdagende maar opwindende tijden.",
    veryImportantMsgStart:
      "Deze aanbieding is speciaal voor u ontworpen, aangezien u uw Shopify-winkel heeft geopend",
    veryImportantMsgMiddle: "U bent voor ons een zeer belangrijke en volwassen koopman. Ons",
    veryImportantMsgEnd: "korting is om te laten zien hoeveel je voor ons betekent.",
    generalMsg:
      "Onze Shopify-app is afgestemd op de behoeften van gevestigde bedrijven zoals het uwe. Het is ontworpen om grote volumes en complexe bewerkingen naadloos af te handelen. ",
    lowTitleStart: "Speciale steun voor nieuwe ondernemers:",
    lowTitleEnd: "Korting zoals je net bent begonnen",
    mediumTitleStart: "Speciale steun voor ondernemers:",
    mediumTitleEnd: "Korting toen je begon",
    importantTitleStart: "Speciale steun voor ondernemers:",
    importantTitleEnd: "Korting toen je begon",
    veryImportantTitleStart: "Gefeliciteerd met het zijn",
    veryImportantTitleEnd: "in Shopify",
    month: "maand",
    "year and": "jaar en",
    ago: "geleden",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "AI-credit toevoegen (1 AI-credit/10 ¢) (10 AI-credit/$1)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Afbeelding toevoegen altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )",
    "Monthly AI AltText Credit": "Maandelijks AI AltText-tegoed",
    "Yearly AI AltText Credit": "Jaarlijks AI AltText-tegoed",
    "Purchase AI AltText Credit": "Koop AI AltText-tegoed",
    "ImageAltText Credit": "ImageAltText-tegoed",
    "Your credits are finished; please upgrade your plan.":
      "Je tegoeden zijn op; upgrade alstublieft uw abonnement.",
    "Your credits are finished; you can buy more credits from here.":
      "Je tegoeden zijn op; Je kunt hier meer credits kopen.",
    "This offer expire in": "Deze aanbieding vervalt over",
    "Hurry Up!": "Haast je!",
    Current: "Huidig",
    "Discount applied": "Korting toegepast",
    "trial left": "proef links",
    "info banner":
      "Wanneer u op de knop Homepagina-afbeelding scannen klikt, scant onze app alleen de afbeelding van de startpagina. Om deze afbeelding te optimaliseren, klikt u handmatig op de knop Optimaliseren",
    "Optimize Images": "Optimaliseer afbeeldingen",
    image: "afbeelding",
    images: "afbeeldingen",
    Filename: "Bestandsnaam",
    Images: "Afbeeldingen",
    Setting: "Instelling",
    "Saved(in %)": "Opgeslagen(in%)",
    Action: "Actie",
    "Product Image": "product afbeelding",
    "product image": "product afbeelding",
    gif: "GIF",
    Homepage: "Startpagina",
    "Manage Announcement": "Beheer aankondiging",
    "No Announcements Found": "Geen mededelingen gevonden",
    Position: "Positie",
    "Campaign Title": "Campagnetitel",
    Visible: "Zichtbaar",
    Invisible: "Onzichtbaar",
    Views: "Keer bekeken",
    Clicks: "Klikken",
    Submits: "Verzendt",
    "Above Add to cart Button": "Boven de knop Toevoegen aan winkelwagen",
    "Below Add to cart Button": "Hieronder de knop Toevoegen aan winkelwagen",
    Targeting: "Gericht op",
    "Rotating Animation Setting": "Roterende animatie-instelling",
    "Marquee Animation Setting": "Selectie-animatie-instelling",
    "Show to visitors coming form then specific website":
      "Toon aan bezoekers die van een specifieke website komen",
    "Add your website URL": "Voeg uw website-URL toe",
    "Banner Display Start Time": "Starttijd bannerweergave",
    "Banner Display End Time": "Eindtijd bannerweergave",
    "Create Campaign": "Campagne maken",
    "Select Announcement Bar": "Selecteer aankondigingsbalk",
    "Please select template.": "Selecteer een sjabloon.",
    Previous: "Vorig",
    "Promotion bar": "Promotiebalk",
    "Add To Cart": "Toevoegen aan winkelwagen",
    Embeded: "Ingebed",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Waarschuw klanten voor aankomende verkopen, aanbiedingen of stel voorraadwaarschuwingen in.",
    "Increase your order value by using or Free Shipping Bar.":
      "Verhoog de waarde van uw bestelling door gebruik te maken van onze gratis verzendbalk.",
    "Conveniently add items to your cart with a single click!":
      "Voeg eenvoudig artikelen toe aan uw winkelwagen met één klik!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Selecteer om u te abonneren en speciale kortingen rechtstreeks in uw inbox te ontvangen",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Laat uw speciale aanbiedingen opvallen met een ingebouwde balk die voor en na de knop 'Toevoegen aan winkelwagen' wordt weergegeven.",
    Select: "Selecteer",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Voeg UTM-code voor banner verbergen toe (bijv. Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Inclusief Utm",
    "Exclude Utm": "Utm uitsluiten",
    "Campaign Design": "Campagne ontwerp",
    "Background Setting": "Achtergrondinstelling",
    "Target Setting": "Doelstelling instellen",
    Scheduling: "Planning",
    Rotating: "Roterend",
    Marquee: "Markies",
    "Repeat Timer Date": "Herhaal timer datum",
    "Select Repeat Time": "Selecteer Herhaaltijd",
    "Repeated Hours": "Herhaalde uren",
    Border: "Grens",
    Bashed: "Geslagen",
    "Multi Rotating": "Multi Roterend",
    Contacts: "Contacten",
    Email: "E-mail",
    "First Name": "Voornaam",
    "Last Name": "Achternaam",
    Phone: "Telefoon",
    "You have unsaved changes": "U heeft niet-opgeslagen wijzigingen",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Uw campagne bevat niet-opgeslagen wijzigingen. Wijzigingen gaan verloren als u vertrekt zonder op te slaan.",
    "Leave widthout saving": "Laat de breedte-besparing staan",
    "Save Changes": "Wijzigingen opslaan",
    Announcement: "Aankondiging",
    Feedback: "Feedback",
    "Recipe Instructions": "Receptinstructies",
    "Visit Help Center": "Bezoek het Helpcentrum",
    "Schedule Meeting": "Vergadering plannen",
    "Setup guide": "Installatiehandleiding",
    "Use this personalized guide to get your store up and running":
      "Gebruik deze persoonlijke gids om uw winkel operationeel te krijgen",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Om acties te kunnen ontvangen, moet u onze app inschakelen. Als u op de knop klikt, gaat u naar de pagina met extensies. Vervolgens hoeft u alleen maar op 'Opslaan' te klikken en hier terug te komen",
    "Enable our app": "Schakel onze app in",
    "Learn more": "Kom meer te weten",
    "Skip it": "Sla het over",
    steps: "stappen",
    minutes: "minuten",
    "Mark as done": "Markeer als klaar",
    "Mark as not done": "Markeer niet als klaar",
    "You have completed all the steps": "Je hebt alle stappen voltooid",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Activeer en analyseer de snelheid van uw site om uw winkel hoger te rangschikken in de zoekresultaten.",
    "Google Page Speed Optimization": "Optimalisatie van de paginasnelheid van Google",
    "Activate Google Page Speed": "Activeer Google Paginasnelheid",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Schakel de Google Page Speed-tool in om de prestaties van uw site te beoordelen en mogelijkheden voor snelheidsverbetering te identificeren",
    "Enable Speed Analysis": "Snelheidsanalyse inschakelen",
    "Review Speed Analysis Report": "Bekijk het snelheidsanalyserapport",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Bekijk het gedetailleerde snelheidsanalyserapport om inzicht te krijgen in de huidige snelheidsgegevens van uw site en om verbeterpunten aan te wijzen.",
    "Go to Reports": "Ga naar Rapporten",
    Hello: "Hallo",
    "Let's get your store ready for success": "Laten we uw winkel klaarmaken voor succes",
    "Finish later": "Eindig later",
    "Continue onboarding": "Ga door met onboarden",
    "Check image optimization features": "Controleer de functies voor beeldoptimalisatie",
    "Explore Optimization Features": "Ontdek optimalisatiefuncties",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Maak uzelf vertrouwd met het scala aan beschikbare hulpmiddelen voor beeldoptimalisatie. Ontdek hoe u de laadsnelheid van pagina's en SEO kunt verbeteren door de afbeeldingsformaten en -indelingen te optimaliseren.",
    "Go to Image Optimization": "Ga naar Beeldoptimalisatie",
    "Automate Your Image Workflow": "Automatiseer uw beeldworkflow",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Stel automatisering in om nieuwe afbeeldingen naadloos te optimaliseren terwijl ze worden geüpload, zodat consistente prestaties op uw hele site worden gegarandeerd.",
    "Go to Automation": "Ga naar Automatisering",
    "Execute a Bulk Optimization": "Voer een bulkoptimalisatie uit",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Voer een bulkoptimalisatie uit om meerdere afbeeldingen tegelijk efficiënt te verbeteren, waardoor de laadtijd van uw site aanzienlijk kan worden verbeterd.",
    "Go to bulk operations": "Ga naar bulkbewerkingen",
    "Broken Links Management": "Beheer van verbroken links",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatiseer de detectie en reparatie van verbroken links om de gebruikerservaring en SEO-ranglijst te verbeteren.",
    "Review Detected Broken Links": "Controleer gedetecteerde verbroken koppelingen",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Bekijk de lijst met verbroken links die automatisch door ons systeem worden geïdentificeerd om inzicht te krijgen in hun impact op de navigatie op uw site.",
    "View Broken Links": "Bekijk verbroken links",
    "Address Broken Links": "Adres verbroken links",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Gebruik onze tools om verbroken links snel te herstellen of om te leiden, waardoor de integriteit van uw site en de gebruikerstevredenheid worden verbeterd.",
    "Resolve Broken Links": "Los verbroken koppelingen op",
    "Automate for Efficiency": "Automatiseer voor efficiëntie",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Stel een automatische oplossing in om eventuele toekomstige verbroken links voor te blijven en een continue sitegezondheid te garanderen.",
    "Enable Automation": "Automatisering inschakelen",
    "Meta Tags Management": "Beheer van metatags",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Optimaliseer de zichtbaarheid van uw site en de ranking in zoekmachines met onze gebruiksvriendelijke metatagsfunctie.",
    "Explore Meta Tag Options": "Ontdek metatagopties",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Maak kennis met de verschillende bewerkings- en automatiseringsopties voor metatags die beschikbaar zijn voor individuele producten en pagina's.",
    "Explore Meta Tags": "Ontdek metatags",
    "Edit and Optimize": "Bewerken en optimaliseren",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Duik in het bewerken van metatitels, beschrijvingen en alt-teksten voor afbeeldingen om de SEO en gebruikerstoegankelijkheid van uw site te verbeteren.",
    "Start Editing": "Begin met bewerken",
    "Automate for Consistency": "Automatiseer voor consistentie",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Stel automatiseringsregels in voor uw metatags om de consistentie en efficiëntie op uw productpagina's te behouden.",
    "Set Automation": "Automatisering instellen",
    "Schema Markup": "Schema-opmaak",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Gebruik Schema-opmaak om de weergave van uw inhoud in de zoekresultaten te verbeteren en meer klikken te genereren.",
    "Learn About Schema Options": "Meer informatie over schemaopties",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Maak uzelf vertrouwd met de verschillende typen schemamarkeringen die beschikbaar zijn, zoals Product, Lokaal bedrijf, Veelgestelde vragen en meer, om de voordelen ervan te begrijpen.",
    "Explore Schema Types": "Verken schematypen",
    "Activate Key Schemas": "Activeer sleutelschema's",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Kies cruciale schema's voor uw site en schakel deze in, zoals Product Schema voor e-commerce of Lokaal bedrijfsschema voor fysieke winkels.",
    "Go to Schemas": "Ga naar Schema's",
    "Customize Schema Details": "Pas schemadetails aan",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Pas de instellingen van elk schematype aan om uw bedrijf of producten nauwkeurig weer te geven in de zoekresultaten.",
    "Test and Validate Schemas": "Test en valideer schema's",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Test uw schema's met behulp van tools zoals de Structured Data Testing Tool van Google om er zeker van te zijn dat ze correct worden geïmplementeerd.",
    "Test Schemas": "Testschema's",
    "Add Breadcrumbs": "Voeg broodkruimels toe",
    "Add Breadcrumbs to your store": "Voeg broodkruimels toe aan uw winkel",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Om een betere gebruikerservaring te krijgen, moet u broodkruimels aan uw winkel toevoegen.",
    "How to add breadcrumbs": "Hoe broodkruimels toe te voegen",
    "Understand how to add and configure breadcrumbs in your store.":
      "Begrijp hoe u broodkruimels in uw winkel kunt toevoegen en configureren.",
    "Google search console": "Google-zoekconsole",
    "Connect google search console to sync it with our app.":
      "Verbind Google Search Console om het te synchroniseren met onze app.",
    "How to connect GSC.": "Hoe GSC aan te sluiten.",
    "Understand how to connect and use google search console in our app.":
      "Begrijp hoe u verbinding kunt maken en de Google Search Console in onze app kunt gebruiken.",
    "Go to GSC": "Ga naar GSC",
    "Go to Breadcrumbs Design": "Ga naar Broodkruimelsontwerp",
    "Start Onboarding": "Begin met onboarden",
    "Go to Homepage": "Ga naar homepagina",
    "Go to Onboarding": "Ga naar Onboarding",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Ontdek onze gebruiksvriendelijke app-gids die is ontworpen om uw begrip te vergroten. Klik op 'Start Onboarding' om te beginnen en u kunt op elk gewenst moment weer naar de startpagina gaan.",
    "Please enable our app extension.": "Schakel onze app-extensie in.",
    "Generate Meta tags": "Metatags genereren",
    "Test description a litle bit longer that title": "Testbeschrijving iets langer dan de titel",
    "Suggested for you": "Voorgesteld voor jou",
    "Enable Google page speed": "Schakel de paginasnelheid van Google in",
    "Connect GSC": "Sluit GSC aan",
    "Enable Image Optimize Automation": "Schakel Automatisering van beeldoptimalisatie in",
    "Automate Meta tags": "Automatiseer metatags",
    "Automate Broken Links": "Automatiseer verbroken koppelingen",
    "Enhance SEO with automatically generated meta tags.": "Verbeter SEO met automatisch gegenereerde metatags.",
    "Improve website performance by optimizing images.":
      "Verbeter de prestaties van uw website door afbeeldingen te optimaliseren.",
    "Boost website speed by enabling Google Page Speed.":
      "Verhoog de websitesnelheid door Google Page Speed in te schakelen.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Verbeter de zichtbaarheid van zoekopdrachten door verbinding te maken met Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Stroomlijn beeldoptimalisatie met geautomatiseerde processen.",
    "Improve SEO by automating the generation of meta tags.":
      "Verbeter SEO door het genereren van metatags te automatiseren.",
    "Improve UX with automated detect and handle, broken links.":
      "Verbeter de UX met automatische detectie en afhandeling van verbroken links.",
    "Learn About Add Announcement": "Meer informatie over het toevoegen van aankondigingen",
    "Skip And Add Announcement": "Aankondiging overslaan en toevoegen",
    "Learn more about": "Leer meer over",
    "Add Announcement": "Aankondiging toevoegen",
    "Announcement Bar": "Aankondigingsbalk",
    "Rate us!": "Beoordeel ons!",
    "How would you Love this app?": "Wat zou je van deze app vinden?",
    "Enter Your Feedback Here": "Voer hier uw feedback in",
    "Leave Us a Review !!": "Laat ons een recensie achter!!",
    "If you like our app features then please leave us a review !!":
      "Als je onze app-functies leuk vindt, laat dan een beoordeling achter !!",
    "If you like our free features then please leave us a review !!":
      "Als je onze gratis functies leuk vindt, laat dan een beoordeling achter !!",
    "Update Successfully": "Update succesvol",
    "Uninstall App": "App verwijderen",
    "Contact Our Support": "Neem contact op met onze ondersteuning",
    "Leave a message": "Laat een bericht achter",
    "Please Choose a UnInstallation Reason": "Kies een reden voor het verwijderen",
    "Are you facing any issues understanding the features of our app?":
      "Heeft u problemen met het begrijpen van de functies van onze app?",
    "Please Choose at least one reason": "Kies ten minste één reden",
    "Thank You For Reaching Out": "Bedankt dat u contact met ons opneemt",
    "Contact Support": "Contact opnemen met ondersteuning",
    "Get Help from Our Support Team": "Krijg hulp van ons ondersteuningsteam",
    "Select a reason": "Selecteer een reden",
    "Not getting how to use or setup": "Ik begrijp niet hoe ik het moet gebruiken of instellen",
    "Poor customer support": "Slechte klantenondersteuning",
    "Performance issues": "Prestatieproblemen",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Ons ondersteuningsteam is momenteel niet beschikbaar in het weekend en zal op weekdagen beschikbaar zijn, afhankelijk van uw tijdzone ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " aangezien wij vanuit India opereren. U kunt nog steeds een bericht achterlaten. Gelieve enige vertraging in onze reactie te verwachten. Bedankt voor uw geduld.",
    "Our support team is partially available according to your time zone from ":
      "Ons ondersteuningsteam is gedeeltelijk beschikbaar, afhankelijk van uw tijdzone ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " aangezien wij vanuit India opereren. Gedurende deze tijd kan het reageren tussen 30 minuten en een uur duren. Laat dan een bericht achter, wij reageren zo snel mogelijk. Bedankt voor uw geduld.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Ons ondersteuningsteam is momenteel niet beschikbaar en zal beschikbaar zijn volgens uw tijdzone vanaf ",
    to: "naar",
    "Did not meet my expectations": "Voldeed niet aan mijn verwachtingen",
    "Feature Limitations": "Functiebeperkingen",
    "Banner doesn't set in my app": "Banner wordt niet ingesteld in mijn app",
    "Banner is not show properly": "Banner wordt niet goed weergegeven",
    "Confusing Set Multi Position and Multi Animation": "Verwarrende Set Multi-positie en Multi-animatie",
    "Sync Profile": "Synchronisatieprofiel",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
