import modifyData from "../Language/pl.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Włączony",
    Disabled: "Wyłączony",
    "Embed is currently disabled": "Osadzanie jest obecnie wyłączone",
    "Enable App": "Włącz aplikację",
    "1. Click on Enable App.": "1. Kliknij opcję Włącz aplikację.",
    "Well done!! you have successfully enable our app.": "Dobrze zrobiony!! pomyślnie włączyłeś naszą aplikację.",
    "2. Enable": "2. Włącz",
    "App Embed as shown in image and save setting.":
      "Umieść aplikację w sposób pokazany na obrazku i zapisz ustawienia.",
    "Multi Announcement Bar": "Pasek wielu ogłoszeń",
    "Click on the Enable Now button to enable it.": "Kliknij przycisk Włącz teraz, aby go włączyć.",
    "Enable Announcement Bar to get started": "Aby rozpocząć, włącz pasek ogłoszeń",
    "Enable Now": "Włącz teraz",
    "Sync Status": "Stan synchronizacji",
    Done: "Zrobione",
    No: "NIE",
    Found: "Znaleziony",
    Add: "Dodać",
    Search: "Szukaj",
    Showing: "Seans",
    of: "z",
    "results, at most": "co najwyżej rezultaty",
    "per page": "na stronę",
    "Oops! Something went wrong.": "Ups! Coś poszło nie tak.",
    "Let's try that again, please refresh the page.": "Spróbujmy jeszcze raz. Odśwież stronę.",
    "If you're still stuck, contact us by chat support or":
      "Jeśli nadal utkniesz, skontaktuj się z nami za pośrednictwem czatu lub",
    "support@webrexstudio.com": "wsparcie@webrexstudio.com",
    "so we can help!": "więc możemy pomóc!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Wybierz dowolne 3 funkcje, które chcesz ustawić na wysoki priorytet lub które są najbardziej interesujące",
    "Add ": "Dodać ",
    "These is premium feature": "To jest funkcja premium",
    "Go to pricing": "Przejdź do cennika",
    Save: "Ratować",
    Minimum: "Minimum",
    Maximum: "Maksymalny",
    "images are required": "wymagane są obrazy",
    and: "I",
    "images are allowed": "obrazy są dozwolone",
    Disconnect: "Rozłączyć się",
    "Sign In with Google": "Zaloguj się za pomocą Google",
    "Oops! Something went wrong. Admin token is malformed":
      "Ups! Coś poszło nie tak. Token administratora jest uszkodzony",
    "If you're still stuck, contact": "Jeśli nadal utkniesz, skontaktuj się",
    Premium: "Premia",
    Unlock: "Odblokować",
    "Unlock advanced features!": "Odblokuj zaawansowane funkcje!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Wszelkie prawa zastrzeżone.",
    "Privacy Policy": "Polityka prywatności",
    "Terms of Service": "Warunki usługi",
    "Go to Shopify App": "Przejdź do aplikacji Shopify",
    "Review Us": "Oceń nas",
    Cancel: "Anulować",
    "Review Popup Show": "Przejrzyj wyskakujący program",
    "click on review us": "kliknij oceń nas",
    "Note: Feel free to leave a star rating without writing a review!":
      "Uwaga: możesz zostawić ocenę w postaci gwiazdek bez pisania recenzji!",
    Help: "Pomoc",
    "Help Button Click": "Kliknij przycisk Pomoc",
    Confirm: "Potwierdzać",
    On: "NA",
    Off: "Wyłączony",
    Price: "Cena",
    Settings: "Ustawienia",
    Animation: "Animacja",
    "My Profile": "Mój profil",
    "My Subscription": "Moja subskrypcja",
    "Store Name": "Nazwa sklepu",
    "Store URL": "Adres URL sklepu",
    "Email ID": "ID e-mail",
    "Phone Number": "Numer telefonu",
    Country: "Kraj",
    Currency: "Waluta",
    "Subscription Name": "Nazwa subskrypcji",
    "Select language": "Wybierz język",
    "Announcement setting": "Ustawienie ogłoszenia",
    "Animation setting": "Ustawienie animacji",
    Selector: "Selektor",
    "Save Setting": "Zapisz ustawienia",
    "My Announcements": "Moje ogłoszenia",
    "Add bar": "Dodaj pasek",
    Number: "Numer",
    Title: "Tytuł",
    "Create At": "Utwórz w",
    "Slide Activation": "Aktywacja slajdu",
    Status: "Status",
    Actions: "działania",
    "Save order": "Zapisz zamówienie",
    "Reorder Slides": "Zmień kolejność slajdów",
    position: "pozycja",
    Top: "Szczyt",
    "Sticky Top": "Przyklejony wierzchołek",
    "Bottom Fix": "Dolna poprawka",
    "Custom Position": "Pozycja niestandardowa",
    "Custom Position *Add Class or id of Selected Element.":
      "Pozycja niestandardowa *Dodaj klasę lub identyfikator wybranego elementu.",
    "Bar Padding (px)": "Wypełnienie paska (px)",
    "Add Remove Button": "Dodaj przycisk Usuń",
    "Choose icon color": "Wybierz kolor ikony",
    "Custom css": "Niestandardowe CSS",
    fadeIn: "zanikanie",
    fadeInDown: "zanikanie w dół",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "zanikanie w lewo",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "zanikanie w górę",
    bounceInDown: "odbijanie się w dół",
    bounceInLeft: "odbijanie w lewo",
    bounceInUp: "odbijanie się w górę",
    zoomIn: "zbliżenie",
    zoomInDown: "powiększ w dół",
    zoomInLeft: "powiększ w lewo",
    slideInLeft: "przesuń w lewo",
    slideInUp: "slajdInUp",
    slideInDown: "przesuń w dół",
    lightSpeedIn: "LightSpeedIn",
    rollIn: "toczyć się",
    flash: "błysk",
    shake: "potrząsnąć",
    flip: "trzepnięcie",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "zanikanie",
    fadeOutDown: "zanikanie w dół",
    fadeOutDownBig: "zanikanieDownDuży",
    fadeOutRight: "zanikanie w prawo",
    fadeOutRightBig: "fadeOutRightDuży",
    fadeOutUp: "zanikanieUp",
    bounceOutDown: "odbijanie się w dół",
    bounceOutRight: "BounceOutRight",
    bounceOutUp: "odbijanie się",
    zoomOut: "pomniejsz",
    zoomOutDown: "powiększ w dół",
    zoomOutRight: "powiększ w prawo",
    slideOutRight: "slideOutRight",
    slideOutUp: "slajdOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "LightSpeedOut",
    rollOut: "wdrożenie",
    flipInY: "flipInY",
    "Text Animation": "Animacja tekstu",
    "Animation In": "Animacja w",
    "Animation Out": "Animacja wyłączona",
    "Auto play time (time in MS)": "Czas automatycznego odtwarzania (czas w MS)",
    "Animation time (time in MS)": "Czas animacji (czas w MS)",
    "Auto play time (time in Second)": "Czas automatycznego odtwarzania (czas w sekundach)",
    "Background Color": "Kolor tła",
    "Space between slide(px)": "Odstęp między slajdami (px)",
    visible: "widoczny",
    invisible: "niewidzialny",
    "Promotional & Countdown Bar": "Pasek promocyjny i odliczający",
    "Free Shipping Bar": "Pasek darmowej wysyłki",
    "Add Slide": "Dodaj slajd",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "W przypadku planu DARMOWEGO widoczny jest tylko 1 slajd. Aby aktywować Wszystkie slajdy, zasubskrybuj Plan Premium.",
    Pricing: "cennik",
    "No Animation Found": "Nie znaleziono animacji",
    "No Preview, Add announcement Bar": "Brak podglądu, dodaj pasek ogłoszeń",
    "Update successfully": "Aktualizacja pomyślnie",
    Enable: "Włączać",
    Disable: "Wyłączyć",
    successfully: "z powodzeniem",
    "Delete successfully": "Usuń pomyślnie",
    "Copy successfully": "Skopiuj pomyślnie",
    "Reorder successfully": "Zmień kolejność pomyślnie",
    "Announcement Message": "Wiadomość ogłoszeniowa",
    "Call to Action": "Wezwanie do działania",
    Timer: "Regulator czasowy",
    Style: "Styl",
    "Background Type": "Typ tła",
    "Mobile Style": "Styl mobilny",
    "Schedule Display": "Wyświetlanie harmonogramu",
    Update: "Aktualizacja",
    "Change Font": "Zmień czcionkę",
    "Font Family": "Rodzina czcionek",
    "Font Style": "Styl czcionki",
    Normal: "Normalna",
    Italic: "italski",
    Oblique: "Skośny",
    Unset: "Nieoprawny",
    "Font Weight": "Grubość czcionki",
    Bold: "Pogrubiony",
    "Message Font Size": "Rozmiar czcionki wiadomości",
    "Message Text color": "Kolor tekstu wiadomości",
    Type: "Typ",
    None: "Nic",
    Button: "Przycisk",
    "Entire clickable bar": "Cały klikalny pasek",
    "Add a simple link": "Dodaj prosty link",
    "Add coupon placement": "Dodaj umiejscowienie kuponu",
    "Linked Url": "Połączony adres URL",
    "Background Hover Color": "Kolor tła",
    "Text Hover Color": "Kolor dymku tekstowego",
    "Button Text": "Przycisk tekstowy",
    "Copied Text": "Skopiowany tekst",
    "Open in the new tab": "Otwórz w nowej karcie",
    URL: "Adres URL",
    "Font Size": "Rozmiar czcionki",
    "Button Radius": "Promień przycisku",
    "Button color": "Kolor przycisku",
    "Button Text color": "Kolor tekstu przycisku",
    "Button Hover Color": "Kolor najechania przyciskiem",
    "button Text HoverColor": "przycisk Tekst HoverColor",
    "Timer Setting": "Ustawienie timera",
    "Timer Type": "Typ timera",
    Date: "Data",
    "Select Reapt Time": "Wybierz Czas reakcji",
    "repeated Hours": "powtarzane godziny",
    "Normal Timer": "Normalny minutnik",
    "Auto repeat timer": "Timer automatycznego powtarzania",
    Minute: "Minuta",
    Hour: "Godzina",
    Day: "Dzień",
    "Remove Timer When Time End": "Usuń timer po zakończeniu czasu",
    "Timer Separator": "Separator timera",
    "Countdown Timer color": "Kolor minutnika",
    "Timer Text Size": "Rozmiar tekstu timera",
    "Timer Text Setting": "Ustawienie tekstu timera",
    "Day Text": "Tekst dnia",
    "Hour Text": "Tekst godzinowy",
    "Minute Text": "Tekst minutowy",
    "Second Text": "Drugi tekst",
    "Background Image": "Zdjęcie w tle",
    "Gradient Background": "Tło Gradientowe",
    "Style & Color For Mobile": "Styl i kolor dla telefonów komórkowych",
    "Timer Background": "Tło zegara",
    "Timer Text Color": "Kolor tekstu timera",
    "Button Color": "Kolor przycisku",
    "Button Text Color": "Kolor tekstu przycisku",
    "Button Text Hover Color": "Kolor najechania tekstem przycisku",
    "Button Text Size": "Rozmiar tekstu przycisku",
    "Always Display": "Zawsze wyświetlaj",
    "Only Display Within The Following Period Of Time": "Wyświetlaj tylko w następnym okresie",
    "Start Time": "Czas rozpoczęcia",
    "End Time": "Koniec czasu",
    "Advance Setting": "Ustawienie zaawansowane",
    "Country Filter": "Filtr kraju",
    Visibility: "Widoczność",
    "Desktop and Mobile": "Komputer stacjonarny i mobilny",
    "Only Desktop": "Tylko komputer stacjonarny",
    "Only Mobile": "Tylko mobilne",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "KIEROWANIE NA ŹRÓDŁO UŻYTKOWNIKA (odwiedzający pochodzący z linku zawierającego poniższy kod UTM, np.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Wybierz opcję Strona",
    Include: "Włączać",
    Exclude: "Wykluczać",
    "Currency Configuration": "Konfiguracja waluty",
    Message: "Wiadomość",
    "Currency Symbol": "Symbol waluty",
    "Currency Position": "Pozycja walutowa",
    Before: "Zanim",
    After: "Po",
    "money Class": "Klasa pieniędzy",
    "Initial Message": "Początkowa wiadomość",
    "Shipping Goal": "Cel wysyłki",
    "Progress Message": "Wiadomość o postępie",
    "Progress goal": "Cel postępu",
    "Goal Message": "Wiadomość o celu",
    "Shipping Price Color": "Cena wysyłki Kolor",
    "Shipping Price Size": "Rozmiar ceny wysyłki",
    "Shipping Font Weight": "Waga czcionki wysyłkowej",
    "* When user first time visit": "* Podczas pierwszej wizyty użytkownika",
    "* When user add item to the cart e.g": "* Gdy użytkownik doda przedmiot do koszyka, np.:",
    "* When cart value is greater than": "* Gdy wartość koszyka jest większa niż",
    "Show On Selected Countries": "Pokaż w wybranych krajach",
    "Show On Selected Pages": "Pokaż na wybranych stronach",
    All: "Wszystko",
    Home: "Dom",
    Cart: "Wózek",
    Collection: "Kolekcja",
    Product: "Produkt",
    Custom: "Zwyczaj",
    Page: "Strona",
    Blog: "Bloga",
    "Url is required": "Adres URL jest wymagany",
    "Day Text is required": "Tekst dnia jest wymagany",
    "Hour Text is required": "Tekst godziny jest wymagany",
    "Minute Text is required": "Wymagany jest tekst minutowy",
    "Second Text is required": "Wymagany jest drugi tekst",
    "Start Time is required": "Wymagany jest czas rozpoczęcia",
    "End Time is required": "Godzina zakończenia jest wymagana",
    "Created successfully": "Utworzono pomyślnie",
    "United States": "Stany Zjednoczone",
    Canada: "Kanada",
    Australia: "Australia",
    "New Zealand": "Nowa Zelandia",
    Germany: "Niemcy",
    India: "Indie",
    Afghanistan: "Afganistan",
    "land Islands": "wyspy lądowe",
    Albania: "Albania",
    Algeria: "Algieria",
    "American Samoa": "Samoa Amerykańskie",
    AndorrA: "AndoraA",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarktyda",
    "Antigua and Barbuda": "Antigua i Barbuda",
    Argentina: "Argentyna",
    Armenia: "Armenia",
    Aruba: "Aruba",
    Austria: "Austria",
    Azerbaijan: "Azerbejdżan",
    Bahamas: "Bahamy",
    Bahrain: "Bahrajn",
    Bangladesh: "Bangladesz",
    Barbados: "Barbados",
    Belarus: "Białoruś",
    Belgium: "Belgia",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermudy",
    Bhutan: "Bhutan",
    Bolivia: "Boliwia",
    "Bosnia and Herzegovina": "Bośnia i Hercegowina",
    Botswana: "Botswana",
    "Bouvet Island": "Wyspa Bouveta",
    Brazil: "Brazylia",
    "British Indian Ocean Territory": "Brytyjskie Terytorium Oceanu Indyjskiego",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bułgaria",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Kambodża",
    Cameroon: "Kamerun",
    "Cape Verde": "Wyspy Zielonego Przylądka",
    "Cayman Islands": "Kajmany",
    "Central African Republic": "Republika Środkowoafrykańska",
    Chad: "Czad",
    Chile: "Chile",
    China: "Chiny",
    "Christmas Island": "Wyspa Bożego Narodzenia",
    "Cocos (Keeling) Islands": "Wyspy Kokosowe (Keelinga).",
    Colombia: "Kolumbia",
    Comoros: "Komory",
    Congo: "Kongo",
    "Congo, The Democratic Republic of the": "Kongo, Demokratyczna Republika",
    "Cook Islands": "Wyspy Cooka",
    "Costa Rica": "Kostaryka",
    "Cote D'Ivoire": "Wybrzeże Kości Słoniowej",
    Croatia: "Chorwacja",
    Cuba: "Kuba",
    Cyprus: "Cypr",
    "Czech Republic": "Republika Czeska",
    Denmark: "Dania",
    Djibouti: "Dżibuti",
    Dominica: "Dominika",
    "Dominican Republic": "Republika Dominikany",
    Ecuador: "Ekwador",
    Egypt: "Egipt",
    "El Salvador": "Salwador",
    "Equatorial Guinea": "Gwinea Równikowa",
    Eritrea: "Erytrea",
    Estonia: "Estonia",
    Ethiopia: "Etiopia",
    "Falkland Islands (Malvinas)": "Falklandy (Malwiny)",
    "Faroe Islands": "Wyspy Owcze",
    Fiji: "Fidżi",
    Finland: "Finlandia",
    France: "Francja",
    "French Guiana": "Gujana Francuska",
    "French Polynesia": "Polinezja Francuska",
    "French Southern Territories": "Francuskie Terytoria Południowe",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Gruzja",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Grecja",
    Greenland: "Grenlandia",
    Grenada: "Grenada",
    Guadeloupe: "Gwadelupa",
    Guam: "Guam",
    Guatemala: "Gwatemala",
    Guernsey: "Guernsey",
    Guinea: "Gwinea",
    "Guinea-Bissau": "Gwinea Bissau",
    Guyana: "Gujana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Wyspy Heard i McDonalda",
    "Holy See (Vatican City State)": "Stolica Apostolska (Państwo Watykańskie)",
    Honduras: "Honduras",
    "Hong Kong": "Hongkong",
    Hungary: "Węgry",
    Iceland: "Islandia",
    Indonesia: "Indonezja",
    "Iran, Islamic Republic Of": "Iran (Islamska Republika",
    Iraq: "Irak",
    Ireland: "Irlandia",
    "Isle of Man": "Wyspa Man",
    Israel: "Izrael",
    Italy: "Włochy",
    Jamaica: "Jamajka",
    Japan: "Japonia",
    Jersey: "Golf",
    Jordan: "Jordania",
    Kazakhstan: "Kazachstan",
    Kenya: "Kenia",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Korea, Republika Ludowo-Demokratyczna",
    "Korea, Republic of": "Republika Korei",
    Kuwait: "Kuwejt",
    Kyrgyzstan: "Kirgistan",
    "Lao People'S Democratic Republic": "Laotańska Republika Ludowo-Demokratyczna",
    Latvia: "Łotwa",
    Lebanon: "Liban",
    Lesotho: "Lesoto",
    Liberia: "Liberia",
    "Libyan Arab Jamahiriya": "Libijska Arabska Dżamahirija",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Litwa",
    Luxembourg: "Luksemburg",
    Macao: "Makao",
    "Macedonia, The Former Yugoslav Republic of": "Macedonia, Była Jugosłowiańska Republika",
    Madagascar: "Madagaskar",
    Malawi: "Malawi",
    Malaysia: "Malezja",
    Maldives: "Malediwy",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Wyspy Marshalla",
    Martinique: "Martynika",
    Mauritania: "Mauretania",
    Mauritius: "Mauritius",
    Mayotte: "Majotta",
    Mexico: "Meksyk",
    "Micronesia, Federated States of": "Mikronezja, Sfederowane Stany",
    "Moldova, Republic of": "Mołdawia, Republika",
    Monaco: "Monako",
    Mongolia: "Mongolia",
    Montenegro: "Czarnogóra",
    Montserrat: "Montserrat",
    Morocco: "Maroko",
    Mozambique: "Mozambik",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Holandia",
    "Netherlands Antilles": "Antyle Holenderskie",
    "New Caledonia": "Nowa Kaledonia",
    Nicaragua: "Nikaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Nie",
    "Norfolk Island": "Wyspa Norfolk",
    "Northern Mariana Islands": "Mariany Północne",
    Norway: "Norwegia",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Teretorium Paleństynskie, Okupowane",
    Panama: "Panama",
    "Papua New Guinea": "Papua Nowa Gwinea",
    Paraguay: "Paragwaj",
    Peru: "Peru",
    Philippines: "Filipiny",
    Pitcairn: "Pitcairn",
    Poland: "Polska",
    Portugal: "Portugalia",
    "Puerto Rico": "Portoryko",
    Qatar: "Katar",
    Reunion: "Zjazd",
    Romania: "Rumunia",
    "Russian Federation": "Federacja Rosyjska",
    RWANDA: "RWANDA",
    "Saint Helena": "Święta Helena",
    "Saint Kitts and Nevis": "Saint Kitts i Nevis",
    "Saint Lucia": "święta Lucia",
    "Saint Pierre and Miquelon": "Saint-Pierre i Miquelon",
    "Saint Vincent and the Grenadines": "Saint Vincent i Grenadyny",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Wyspy Świętego Tomasza i Książęca",
    "Saudi Arabia": "Arabia Saudyjska",
    Senegal: "Senegal",
    Serbia: "Serbia",
    Seychelles: "Seszele",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapur",
    Slovakia: "Słowacja",
    Slovenia: "Słowenia",
    "Solomon Islands": "Wyspy Salomona",
    Somalia: "Somali",
    "South Africa": "Afryka Południowa",
    "South Georgia and the South Sandwich Islands": "Georgia Południowa i Sandwich Południowy",
    Spain: "Hiszpania",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard i Jan Mayen",
    Swaziland: "Suazi",
    Sweden: "Szwecja",
    Switzerland: "Szwajcaria",
    "Syrian Arab Republic": "Republika Syryjsko-Arabska",
    "Taiwan, Province of China": "Tajwan, prowincja Chin",
    Tajikistan: "Tadżykistan",
    "Tanzania, United Republic of": "Tanzania, Zjednoczona Republika",
    Thailand: "Tajlandia",
    "Timor-Leste": "Timor Wschodni",
    Togo: "Iść",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Tryidda i Tobago",
    Tunisia: "Tunezja",
    Turkey: "Indyk",
    Turkmenistan: "Turkmenia",
    "Turks and Caicos Islands": "Wyspy Turks i Caicos",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraina",
    "United Arab Emirates": "Zjednoczone Emiraty Arabskie",
    "United Kingdom": "Zjednoczone Królestwo",
    "United States Minor Outlying Islands": "Stany Zjednoczone Dalekie Wyspy Mniejsze",
    Uruguay: "Urugwaj",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Wenezuela",
    "Viet Nam": "Wietnam",
    "Virgin Islands, British": "Wyspy Dziewicze, Wielka Brytania",
    "Virgin Islands, U.S.": "Wyspy Dziewicze, USA",
    "Wallis and Futuna": "Wallis i Futuna",
    "Western Sahara": "Sahara Zachodnia",
    Yemen: "Jemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Odblokuj wszystkie schematy dzięki naszemu planowi premium",
    "Billed Monthly": "Rozliczane miesięcznie",
    "Billed Annually": "Rozliczane rocznie",
    "Save 30%": "Zaoszczędź 30%",
    Premium100Title:
      "Jako pierwszy użytkownik zapewniamy Cię, że ze wszystkich naszych funkcji premium będziesz mógł korzystać bezpłatnie. Nie musisz się martwić stroną z cenami, ponieważ możesz swobodnie uzyskać dostęp do wszystkich naszych funkcji premium, bez żadnych opłat. Nie odinstalowuj naszej aplikacji, aby móc dalej korzystać z naszych usług.",
    Premium100ReviewLine:
      " Jeśli podoba Ci się nasza aplikacja, zostaw nam recenzję. Pomoże nam to zmotywować się do tworzenia nowych funkcji.",
    "Check Our Current Pricing": "Sprawdź nasz aktualny cennik",
    "Leave Review": "Opuść recenzję",
    "We're sorry to see you go!": "Przykro nam że odchodzisz!",
    "Cancel Plan": "Anuluj plan",
    "Sync Plan": "Plan synchronizacji",
    "Disccount applied": "Zastosowano rabat",
    Apply: "Stosować",
    "Your code(s)": "Twój kod(y)",
    "and discount have been applied successfully": "i zniżka zostały pomyślnie zastosowane",
    "Your entered promocode is not correct, Enter a valid code":
      "Wprowadzony kod promocyjny jest nieprawidłowy. Wprowadź prawidłowy kod",
    "days trial left": "pozostało dni próbne",
    Upgrade: "Aktualizacja",
    "days free trial, No Credit card required":
      "dni bezpłatnego okresu próbnego, karta kredytowa nie jest wymagana",
    Month: "Miesiąc",
    Year: "Rok",
    Unlimited: "Nieograniczony",
    "Enter Promocode": "Wpisz kod promocyjny",
    "Please Choose a Cancellation Reason": "Wybierz powód anulowania",
    "No Longer Needed?": "Nie jest już potrzebne?",
    "Didn't Meet Expectations": "Nie spełnił oczekiwań",
    "Cost Concerns": "Obawy dotyczące kosztów",
    "Technical Issues": "Problemy techniczne",
    "Found an Alternative": "Znaleziono alternatywę",
    Complexity: "Złożoność",
    "Lack of Features": "Brak funkcji",
    "Poor Customer Support": "Słaba obsługa klienta",
    "Business Closure or Change": "Zamknięcie firmy lub zmiana",
    "Temporary Pause": "Tymczasowa przerwa",
    "Performance Issues": "Problemy z wydajnością",
    Other: "Inny",
    "Mention Your Specific Reason Here": "Podaj tutaj swój konkretny powód",
    Start: "Początek",
    "Day Free Trial": "Dzień bezpłatnej wersji próbnej",
    "Please Select One Option": "Proszę wybrać jedną opcję",
    "Plan cancelled successfully": "Plan anulowany pomyślnie",
    "7 days free trial, No Credit card required":
      "7-dniowy bezpłatny okres próbny, karta kredytowa nie jest wymagana",
    "Your remaining trial days are": "Pozostałe dni próbne to",
    "You have used": "Użyłeś",
    "days.": "dni.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Nie pozostały już żadne dni próbne. Skorzystałeś już z 7-dniowego bezpłatnego okresu próbnego.",
    "Upgrade your plan now": "Uaktualnij swój plan już teraz",
    "Unlimited Slides": "Nieograniczona liczba slajdów",
    "20+ Animation In & Out": "Ponad 20 animacji wchodzących i wychodzących",
    "Live Chat Support": "Wsparcie przez czat na żywo",
    "Priority, 24*7 Urgent setup and support": "Priorytet, 24*7 Pilna konfiguracja i wsparcie",
    "Rich Text Editor": "Bogaty edytor tekstu",
    "One Slide(banner)": "Jeden slajd (baner)",
    "Repeated Countdown timer": "Powtarzający się licznik czasu",
    "Fully Customisable": "W pełni konfigurowalny",
    "Background-image": "Zdjęcie w tle",
    "Custom Css": "Niestandardowe CSS",
    "Enable Our App": "Włącz naszą aplikację",
    "Book Onboarding Demo": "Zarezerwuj Demo wprowadzające",
    Next: "Następny",
    Finish: "Skończyć",
    Prev: "Poprzednia",
    "App is not enable please click on the Enable App button to enable it.":
      "Aplikacja nie jest włączona. Kliknij przycisk Włącz aplikację, aby ją włączyć.",
    "This field is required": "To pole jest wymagane",
    disableButtonTooltip: "Nie możesz uaktualnić planu miesięcznego, ponieważ korzystasz z planu rocznego!",
    "Choose plan": "Wybierz plan",
    "Purchase Plan": "Plan zakupów",
    Continue: "Kontynuować",
    "Image Optimization": "Optymalizacja obrazu",
    "AI Metatags": "Metatagi AI",
    "Grand Total": "Łączna suma",
    "Metatags Edit": "Edytuj metatagi",
    Products: "Produkty",
    "Upgrade plan": "Plan aktualizacji",
    "Your product count is": "Liczba Twoich produktów to",
    "so your suitable plan is": "więc twój odpowiedni plan to",
    "Enjoy a": "Ciesz się",
    "lifetime discount": "dożywotnia zniżka",
    discountBanner:
      " Skorzystaj z dożywotniej zniżki, zapewniając stałe oszczędności i poprawiając swoje doświadczenia dzięki naszym produktom i usługom premium.",
    "Images for Optimization every year after trial period end":
      "Obrazy do optymalizacji co roku po zakończeniu okresu próbnego",
    "AI Meta Tags Credit for every year after trial period end":
      "Kredyt AI Meta Tags na każdy rok po zakończeniu okresu próbnego",
    "Images for Optimization every month after trial period end":
      "Obrazy do optymalizacji co miesiąc po zakończeniu okresu próbnego",
    "AI Meta Tags Credit for every Month after trial period end":
      "Kredyt AI Meta Tags za każdy miesiąc po zakończeniu okresu próbnego",
    "Optimize your google page speed": "Zoptymalizuj szybkość swojej strony Google",
    "50 Product Meta tags Optimize, Image alt": "50 metatagów produktu Optymalizacja, alt obrazu",
    "Product Meta tags Optimize, Image alt": "Metatagi produktu Optymalizacja, alt obrazu",
    "AI ImageAltText Credit for every year after trial period end":
      "Kredyt AI ImageAltText za każdy rok po zakończeniu okresu próbnego",
    "25 AI ImageAltText Credit": "25 kredytów AI ImageAltText",
    "AI ImageAltText Credit for every Month after trial period end":
      "Kredyt AI ImageAltText za każdy miesiąc po zakończeniu okresu próbnego",
    "Contact Bar": "Pasek kontaktowy",
    "Add To Cart Bar": "Dodaj do paska koszyka",
    "Multiple Position": "Wiele pozycji",
    lowMsgStart:
      "Ta oferta jest specjalnie zaprojektowana dla Ciebie, ponieważ właśnie uruchomiłeś swój sklep Shopify",
    lowMsgMiddle: "Nasz",
    lowMsgEnd: "rabat to nasz sposób na wsparcie Cię w tych trudnych, ale ekscytujących czasach.",
    mediumMsgStart: "Ta oferta jest specjalnie zaprojektowana dla Ciebie, ponieważ uruchomiłeś swój sklep Shopify",
    mediumMsgMiddle: "Nasz",
    mediumMsgEnd: "rabat to nasz sposób na wsparcie Cię w tych trudnych, ale ekscytujących czasach.",
    importantMsgStart:
      "Ta oferta jest specjalnie zaprojektowana dla Ciebie, ponieważ uruchomiłeś swój sklep Shopify",
    importantMsgMiddle: "Nasz",
    importantMsgEnd: "rabat to nasz sposób na wsparcie Cię w tych trudnych, ale ekscytujących czasach.",
    veryImportantMsgStart:
      "Ta oferta jest specjalnie zaprojektowana dla Ciebie, ponieważ otworzyłeś swój sklep Shopify",
    veryImportantMsgMiddle: "Jesteś dla nas bardzo ważnym i dojrzałym kupcem. Nasz",
    veryImportantMsgEnd: "Rabat ma na celu pokazanie, jak wiele dla nas znaczysz.",
    generalMsg:
      "Nasza aplikacja Shopify jest dostosowana do potrzeb uznanych firm, takich jak Twoja. Został zaprojektowany do bezproblemowej obsługi dużych wolumenów i skomplikowanych operacji. ",
    lowTitleStart: "Specjalne wsparcie dla nowych przedsiębiorców:",
    lowTitleEnd: "Zniżka, ponieważ dopiero zacząłeś",
    mediumTitleStart: "Specjalne wsparcie dla przedsiębiorców:",
    mediumTitleEnd: "Zniżka na początek",
    importantTitleStart: "Specjalne wsparcie dla przedsiębiorców:",
    importantTitleEnd: "Zniżka na początek",
    veryImportantTitleStart: "Gratuluję bycia",
    veryImportantTitleEnd: "w Shopify",
    month: "miesiąc",
    "year and": "rok i",
    ago: "temu",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Dodaj kredyt AI (1 kredyt AI/10 centów) (10 kredytów AI/1 $)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Dodaj obraz AltText Kredyt AI (1 kredyt AI/4 ¢) (25 kredytów AI/1 $)",
    "Monthly AI AltText Credit": "Miesięczny kredyt AI AltText",
    "Yearly AI AltText Credit": "Roczny kredyt AI AltText",
    "Purchase AI AltText Credit": "Kup kredyt AI AltText",
    "ImageAltText Credit": "Kredyt ImageAltText",
    "Your credits are finished; please upgrade your plan.": "Twoje kredyty się skończyły; uaktualnij swój plan.",
    "Your credits are finished; you can buy more credits from here.":
      "Twoje kredyty się skończyły; możesz tutaj kupić więcej kredytów.",
    "This offer expire in": "Ta oferta wygasa w",
    "Hurry Up!": "Pośpiesz się!",
    Current: "Aktualny",
    "Discount applied": "Zastosowano rabat",
    "trial left": "pozostała próba",
    "info banner":
      "Po kliknięciu przycisku Skanuj obraz strony głównej nasza aplikacja przeskanuje tylko obraz strony głównej. Aby zoptymalizować ten obraz, kliknij przycisk Optymalizuj ręcznie",
    "Optimize Images": "Optymalizuj obrazy",
    image: "obraz",
    images: "obrazy",
    Filename: "Nazwa pliku",
    Images: "Obrazy",
    Setting: "Ustawienie",
    "Saved(in %)": "Zapisano (w%)",
    Action: "Działanie",
    "Product Image": "obraz produktu",
    "product image": "obraz produktu",
    gif: "gif",
    Homepage: "Strona główna",
    "Manage Announcement": "Zarządzaj ogłoszeniem",
    "No Announcements Found": "Nie znaleziono żadnych ogłoszeń",
    Position: "Pozycja",
    "Campaign Title": "Tytuł kampanii",
    Visible: "Widoczny",
    Invisible: "Niewidzialny",
    Views: "Wyświetlenia",
    Clicks: "Kliknięcia",
    Submits: "Przesyła",
    "Above Add to cart Button": "Powyżej przycisku Dodaj do koszyka",
    "Below Add to cart Button": "Poniżej przycisku Dodaj do koszyka",
    Targeting: "Kierowanie",
    "Rotating Animation Setting": "Ustawienie animacji obrotowej",
    "Marquee Animation Setting": "Ustawienie animacji markizy",
    "Show to visitors coming form then specific website": "Pokaż odwiedzającym przychodzącym z konkretnej witryny",
    "Add your website URL": "Dodaj adres URL swojej witryny",
    "Banner Display Start Time": "Czas rozpoczęcia wyświetlania baneru",
    "Banner Display End Time": "Czas zakończenia wyświetlania baneru",
    "Create Campaign": "Utwórz kampanię",
    "Select Announcement Bar": "Wybierz pasek ogłoszeń",
    "Please select template.": "Proszę wybrać szablon.",
    Previous: "Poprzedni",
    "Promotion bar": "Pasek promocyjny",
    "Add To Cart": "Dodaj do koszyka",
    Embeded: "Osadzony",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Powiadom klientów o nadchodzących wyprzedażach, ofertach lub ustaw alerty dotyczące stanu magazynowego.",
    "Increase your order value by using or Free Shipping Bar.":
      "Zwiększ wartość swojego zamówienia korzystając z paska darmowej wysyłki.",
    "Conveniently add items to your cart with a single click!":
      "Wygodnie dodawaj produkty do koszyka jednym kliknięciem!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Wybierz subskrypcję i otrzymuj specjalne zniżki bezpośrednio do swojej skrzynki odbiorczej",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Wyróżnij swoje oferty specjalne za pomocą osadzonego paska wyświetlanego przed i za przyciskiem Dodaj do koszyka.",
    Select: "Wybierać",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Dodaj kod UTM „Ukryj baner” (np. Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Uwzględnij Utm",
    "Exclude Utm": "Wyklucz Utm",
    "Campaign Design": "Projektowanie kampanii",
    "Background Setting": "Ustawienia tła",
    "Target Setting": "Wyznaczanie celów",
    Scheduling: "Harmonogramowanie",
    Rotating: "Obracanie",
    Marquee: "Duży namiot",
    "Repeat Timer Date": "Powtórz datę timera",
    "Select Repeat Time": "Wybierz czas powtarzania",
    "Repeated Hours": "Powtarzane godziny",
    Border: "Granica",
    Bashed: "Zmiażdżony",
    "Multi Rotating": "Wieloobrotowy",
    Contacts: "Łączność",
    Email: "E-mail",
    "First Name": "Imię",
    "Last Name": "Nazwisko",
    Phone: "Telefon",
    "You have unsaved changes": "masz niezapisane zmiany",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Twoja kampania zawiera niezapisane zmiany. Zmiany zostaną utracone, jeśli wyjdziesz bez zapisywania.",
    "Leave widthout saving": "Pozostaw zapisywanie szerokości",
    "Save Changes": "Zapisz zmiany",
    Announcement: "Ogłoszenie",
    Feedback: "Informacja zwrotna",
    "Recipe Instructions": "Instrukcje dotyczące przepisu",
    "Visit Help Center": "Odwiedź Centrum pomocy",
    "Schedule Meeting": "Zaplanowane spotkanie",
    "Setup guide": "Przewodnik konfiguracji",
    "Use this personalized guide to get your store up and running":
      "Skorzystaj z tego spersonalizowanego przewodnika, aby uruchomić swój sklep",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Aby rozpocząć wykonywanie działań niezbędnych do włączenia naszej aplikacji, kliknięcie przycisku przeniesie Cię na stronę rozszerzeń, następnie wystarczy kliknąć Zapisz i wrócić tutaj",
    "Enable our app": "Włącz naszą aplikację",
    "Learn more": "Ucz się więcej",
    "Skip it": "Pomiń to",
    steps: "kroki",
    minutes: "minuty",
    "Mark as done": "Oznacz jako wykonane",
    "Mark as not done": "Oznacz jako niezakończone",
    "You have completed all the steps": "Wykonałeś wszystkie kroki",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Aktywuj i analizuj prędkość swojej witryny, aby plasować swój sklep wyżej w wynikach wyszukiwania.",
    "Google Page Speed Optimization": "Optymalizacja szybkości strony Google",
    "Activate Google Page Speed": "Aktywuj Google Page Speed",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Włącz narzędzie Google Page Speed, aby ocenić wydajność swojej witryny i zidentyfikować możliwości zwiększenia szybkości",
    "Enable Speed Analysis": "Włącz analizę prędkości",
    "Review Speed Analysis Report": "Przejrzyj raport analizy prędkości",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Zapoznaj się ze szczegółowym raportem analizy szybkości, aby poznać aktualne wskaźniki szybkości witryny i wskazać obszary wymagające poprawy.",
    "Go to Reports": "Przejdź do raportów",
    Hello: "Cześć",
    "Let's get your store ready for success": "Przygotujmy Twój sklep na sukces",
    "Finish later": "Dokończ później",
    "Continue onboarding": "Kontynuuj wdrażanie",
    "Check image optimization features": "Sprawdź funkcje optymalizacji obrazu",
    "Explore Optimization Features": "Poznaj funkcje optymalizacji",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Zapoznaj się z szeroką gamą dostępnych narzędzi do optymalizacji obrazu. Zobacz, jak możesz poprawić prędkość ładowania strony i SEO, optymalizując rozmiary i formaty obrazów.",
    "Go to Image Optimization": "Przejdź do Optymalizacji obrazu",
    "Automate Your Image Workflow": "Zautomatyzuj przepływ pracy z obrazami",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Skonfiguruj automatyzację, aby bezproblemowo optymalizować nowe obrazy podczas ich przesyłania, zapewniając spójne działanie w całej witrynie.",
    "Go to Automation": "Przejdź do Automatyki",
    "Execute a Bulk Optimization": "Wykonaj optymalizację zbiorczą",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Wykonaj zbiorczą optymalizację, aby skutecznie ulepszyć wiele obrazów jednocześnie, co może znacznie wydłużyć czas ładowania Twojej witryny.",
    "Go to bulk operations": "Przejdź do operacji zbiorczych",
    "Broken Links Management": "Zarządzanie uszkodzonymi linkami",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Zautomatyzuj wykrywanie i naprawę uszkodzonych linków, aby poprawić komfort użytkowania i rankingi SEO.",
    "Review Detected Broken Links": "Przejrzyj wykryte uszkodzone linki",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Sprawdź listę niedziałających linków identyfikowanych automatycznie przez nasz system, aby poznać ich wpływ na nawigację w Twojej witrynie.",
    "View Broken Links": "Zobacz uszkodzone linki",
    "Address Broken Links": "Adresuj uszkodzone linki",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Skorzystaj z naszych narzędzi, aby szybko naprawić lub przekierować uszkodzone linki, poprawiając integralność swojej witryny i satysfakcję użytkowników.",
    "Resolve Broken Links": "Napraw uszkodzone linki",
    "Automate for Efficiency": "Automatyzuj, aby zwiększyć wydajność",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Skonfiguruj automatyczną naprawę, aby wyprzedzić wszelkie przyszłe uszkodzone linki i zapewnić ciągły stan witryny.",
    "Enable Automation": "Włącz automatyzację",
    "Meta Tags Management": "Zarządzanie metatagami",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Zoptymalizuj widoczność swojej witryny i ranking w wyszukiwarkach dzięki naszej przyjaznej dla użytkownika funkcji Meta Tagi.",
    "Explore Meta Tag Options": "Poznaj opcje metatagów",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Zapoznaj się z różnymi opcjami edycji i automatyzacji metatagów dostępnych dla poszczególnych produktów i stron.",
    "Explore Meta Tags": "Przeglądaj metatagi",
    "Edit and Optimize": "Edytuj i optymalizuj",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Zanurz się w edytowaniu metatytułów, opisów i tekstów alternatywnych obrazów, aby poprawić SEO swojej witryny i dostępność dla użytkowników.",
    "Start Editing": "Rozpocznij edycję",
    "Automate for Consistency": "Automatyzuj, aby uzyskać spójność",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Skonfiguruj reguły automatyzacji dla metatagów, aby zachować spójność i wydajność na stronach produktów.",
    "Set Automation": "Ustaw automatyzację",
    "Schema Markup": "Oznaczenia schematu",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Wykorzystaj znaczniki schematu, aby poprawić reprezentację treści w wynikach wyszukiwania i przyciągnąć więcej kliknięć.",
    "Learn About Schema Options": "Dowiedz się więcej o opcjach schematu",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Zapoznaj się z różnymi dostępnymi typami znaczników schematu, takimi jak produkt, lokalna firma, często zadawane pytania i inne, aby zrozumieć ich zalety.",
    "Explore Schema Types": "Przeglądaj typy schematów",
    "Activate Key Schemas": "Aktywuj kluczowe schematy",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Wybierz i włącz kluczowe schematy dla swojej witryny, takie jak schemat produktu dla handlu elektronicznego lub schemat lokalnego biznesu dla sklepów fizycznych.",
    "Go to Schemas": "Przejdź do Schematów",
    "Customize Schema Details": "Dostosuj szczegóły schematu",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Dostosuj ustawienia każdego typu schematu, aby dokładnie reprezentować Twoją firmę lub produkty w wynikach wyszukiwania.",
    "Test and Validate Schemas": "Testuj i weryfikuj schematy",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Przetestuj swoje schematy za pomocą narzędzi takich jak narzędzie Google do testowania danych strukturalnych, aby upewnić się, że są poprawnie zaimplementowane.",
    "Test Schemas": "Schematy testowe",
    "Add Breadcrumbs": "Dodaj bułkę tartą",
    "Add Breadcrumbs to your store": "Dodaj bułkę tartą do swojego sklepu",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Aby zapewnić lepsze doświadczenie użytkownika, musisz dodać bułkę tartą do swojego sklepu.",
    "How to add breadcrumbs": "Jak dodać bułkę tartą",
    "Understand how to add and configure breadcrumbs in your store.":
      "Dowiedz się, jak dodawać i konfigurować bułkę tartą w swoim sklepie.",
    "Google search console": "Konsola wyszukiwania Google",
    "Connect google search console to sync it with our app.":
      "Podłącz konsolę wyszukiwania Google, aby zsynchronizować ją z naszą aplikacją.",
    "How to connect GSC.": "Jak podłączyć GSC.",
    "Understand how to connect and use google search console in our app.":
      "Dowiedz się, jak połączyć się z konsolą wyszukiwania Google i korzystać z niej w naszej aplikacji.",
    "Go to GSC": "Idź do GSC",
    "Go to Breadcrumbs Design": "Przejdź do projektu bułki tartej",
    "Start Onboarding": "Rozpocznij wdrażanie",
    "Go to Homepage": "Wróć do strony głównej",
    "Go to Onboarding": "Przejdź do Onboardingu",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Zapoznaj się z naszym przyjaznym dla użytkownika przewodnikiem po aplikacji, który ma na celu lepsze zrozumienie. Aby rozpocząć, kliknij „Rozpocznij wdrażanie”. W dowolnym momencie będziesz mógł wrócić do strony głównej.",
    "Please enable our app extension.": "Włącz nasze rozszerzenie aplikacji.",
    "Generate Meta tags": "Wygeneruj metatagi",
    "Test description a litle bit longer that title": "Opis testu trochę dłuższy niż tytuł",
    "Suggested for you": "Sugerowane dla Ciebie",
    "Enable Google page speed": "Włącz szybkość strony Google",
    "Connect GSC": "Połącz GSC",
    "Enable Image Optimize Automation": "Włącz automatyzację optymalizacji obrazu",
    "Automate Meta tags": "Automatyzuj metatagi",
    "Automate Broken Links": "Automatyzuj uszkodzone linki",
    "Enhance SEO with automatically generated meta tags.":
      "Ulepsz SEO dzięki automatycznie generowanym metatagom.",
    "Improve website performance by optimizing images.":
      "Popraw wydajność witryny internetowej, optymalizując obrazy.",
    "Boost website speed by enabling Google Page Speed.": "Zwiększ szybkość witryny, włączając Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Zwiększ widoczność wyszukiwania, łącząc się z Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Usprawnij optymalizację obrazu dzięki zautomatyzowanym procesom.",
    "Improve SEO by automating the generation of meta tags.": "Popraw SEO, automatyzując generowanie metatagów.",
    "Improve UX with automated detect and handle, broken links.":
      "Popraw UX dzięki automatycznemu wykrywaniu i obsłudze uszkodzonych linków.",
    "Learn About Add Announcement": "Dowiedz się więcej o dodawaniu ogłoszenia",
    "Skip And Add Announcement": "Pomiń i dodaj ogłoszenie",
    "Learn more about": "Dowiedz się więcej o",
    "Add Announcement": "Dodaj ogłoszenie",
    "Announcement Bar": "Pasek ogłoszeń",
    "Rate us!": "Oceń nas!",
    "How would you Love this app?": "Jak pokochałbyś tę aplikację?",
    "Enter Your Feedback Here": "Wpisz tutaj swoją opinię",
    "Leave Us a Review !!": "Zostaw nam recenzję!!",
    "If you like our app features then please leave us a review !!":
      "Jeśli podobają Ci się funkcje naszej aplikacji, zostaw nam recenzję !!",
    "If you like our free features then please leave us a review !!":
      "Jeśli podobają Ci się nasze bezpłatne funkcje, zostaw nam recenzję !!",
    "Update Successfully": "Aktualizacja pomyślnie",
    "Uninstall App": "Odinstaluj aplikację",
    "Contact Our Support": "Skontaktuj się z naszym wsparciem",
    "Leave a message": "Zostaw wiadomość",
    "Please Choose a UnInstallation Reason": "Wybierz powód deinstalacji",
    "Are you facing any issues understanding the features of our app?":
      "Czy masz problemy ze zrozumieniem funkcji naszej aplikacji?",
    "Please Choose at least one reason": "Proszę wybrać przynajmniej jeden powód",
    "Thank You For Reaching Out": "Dziękujemy za kontakt",
    "Contact Support": "Skontaktuj się z pomocą techniczną",
    "Get Help from Our Support Team": "Uzyskaj pomoc od naszego zespołu wsparcia",
    "Select a reason": "Wybierz powód",
    "Not getting how to use or setup": "Nie rozumiem, jak używać i konfigurować",
    "Poor customer support": "Słaba obsługa klienta",
    "Performance issues": "Problemy z wydajnością",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Nasz zespół pomocy technicznej jest obecnie niedostępny w weekendy i będzie dostępny w dni powszednie, zgodnie z Twoją strefą czasową ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " ponieważ działamy z Indii. Nadal możesz zostawić wiadomość. Prosimy spodziewać się pewnego opóźnienia w naszej odpowiedzi. Dziękuję za Twoją cierpliwość.",
    "Our support team is partially available according to your time zone from ":
      "Nasz zespół wsparcia jest częściowo dostępny w zależności od Twojej strefy czasowej ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " ponieważ działamy z Indii. W tym czasie udzielenie odpowiedzi może zająć od 30 minut do godziny. Proszę zostawić wiadomość, a my odpowiemy tak szybko, jak to możliwe. Dziękuję za Twoją cierpliwość.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Nasz zespół pomocy technicznej jest obecnie niedostępny i będzie dostępny w zależności od Twojej strefy czasowej ",
    to: "Do",
    "Did not meet my expectations": "Nie spełnił moich oczekiwań",
    "Feature Limitations": "Ograniczenia funkcji",
    "Banner doesn't set in my app": "Baner nie ustawia się w mojej aplikacji",
    "Banner is not show properly": "Baner nie jest wyświetlany prawidłowo",
    "Confusing Set Multi Position and Multi Animation": "Mylący zestaw wielu pozycji i wielu animacji",
    "Sync Profile": "Synchronizuj profil",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
