import modifyData from "../Language/pt.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Habilitado",
    Disabled: "Desabilitado",
    "Embed is currently disabled": "A incorporação está desativada no momento",
    "Enable App": "Habilitar aplicativo",
    "1. Click on Enable App.": "1. Clique em Habilitar aplicativo.",
    "Well done!! you have successfully enable our app.":
      "Bom trabalho!! você habilitou nosso aplicativo com sucesso.",
    "2. Enable": "2. Habilitar",
    "App Embed as shown in image and save setting.":
      "Incorporar o aplicativo conforme mostrado na imagem e salvar a configuração.",
    "Multi Announcement Bar": "Barra de anúncios múltiplos",
    "Click on the Enable Now button to enable it.": "Clique no botão Habilitar agora para habilitá-lo.",
    "Enable Announcement Bar to get started": "Ative a barra de anúncios para começar",
    "Enable Now": "Ativar agora",
    "Sync Status": "Status de sincronização",
    Done: "Feito",
    No: "Não",
    Found: "Encontrado",
    Add: "Adicionar",
    Search: "Procurar",
    Showing: "Mostrando",
    of: "de",
    "results, at most": "resultados, no máximo",
    "per page": "por página",
    "Oops! Something went wrong.": "Ops! Algo deu errado.",
    "Let's try that again, please refresh the page.": "Vamos tentar novamente, atualize a página.",
    "If you're still stuck, contact us by chat support or":
      "Se você ainda tiver dúvidas, entre em contato conosco pelo suporte por chat ou",
    "support@webrexstudio.com": "suporte@webrexstudio.com",
    "so we can help!": "então podemos ajudar!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Selecione qualquer 3 recursos que você deseja configurar em alta prioridade ou de maior interesse",
    "Add ": "Adicionar ",
    "These is premium feature": "Este é um recurso premium",
    "Go to pricing": "Ir para preços",
    Save: "Salvar",
    Minimum: "Mínimo",
    Maximum: "Máximo",
    "images are required": "imagens são obrigatórias",
    and: "e",
    "images are allowed": "imagens são permitidas",
    Disconnect: "desconectar",
    "Sign In with Google": "Faça login no Google",
    "Oops! Something went wrong. Admin token is malformed":
      "Ops! Algo deu errado. O token de administrador está malformado",
    "If you're still stuck, contact": "Se você ainda estiver preso, entre em contato",
    Premium: "Prêmio",
    Unlock: "Desbloquear",
    "Unlock advanced features!": "Desbloqueie recursos avançados!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webbrex. Todos os direitos reservados.",
    "Privacy Policy": "política de Privacidade",
    "Terms of Service": "Termos de serviço",
    "Go to Shopify App": "Acesse o aplicativo Shopify",
    "Review Us": "Avalie-nos",
    Cancel: "Cancelar",
    "Review Popup Show": "Revise o programa pop-up",
    "click on review us": "clique em nos avaliar",
    "Note: Feel free to leave a star rating without writing a review!":
      "Observação: sinta-se à vontade para deixar uma avaliação com estrelas sem escrever um comentário!",
    Help: "Ajuda",
    "Help Button Click": "Clique no botão Ajuda",
    Confirm: "confirme",
    On: "Sobre",
    Off: "Desligado",
    Price: "Preço",
    Settings: "Configurações",
    Animation: "Animação",
    "My Profile": "Meu perfil",
    "My Subscription": "Minha assinatura",
    "Store Name": "Nome da loja",
    "Store URL": "URL da loja",
    "Email ID": "Identificação do email",
    "Phone Number": "Número de telefone",
    Country: "País",
    Currency: "Moeda",
    "Subscription Name": "Nome da assinatura",
    "Select language": "Selecione o idioma",
    "Announcement setting": "Configuração de anúncio",
    "Animation setting": "Configuração de animação",
    Selector: "Seletor",
    "Save Setting": "Salvar configuração",
    "My Announcements": "Meus anúncios",
    "Add bar": "Adicionar barra",
    Number: "Número",
    Title: "Título",
    "Create At": "Criar em",
    "Slide Activation": "Ativação de slides",
    Status: "Status",
    Actions: "Ações",
    "Save order": "Salvar pedido",
    "Reorder Slides": "Reordenar slides",
    position: "posição",
    Top: "Principal",
    "Sticky Top": "Parte superior pegajosa",
    "Bottom Fix": "Correção inferior",
    "Custom Position": "Posição personalizada",
    "Custom Position *Add Class or id of Selected Element.":
      "Posição personalizada *Adicionar classe ou id do elemento selecionado.",
    "Bar Padding (px)": "Preenchimento de barra (px)",
    "Add Remove Button": "Adicionar botão Remover",
    "Choose icon color": "Escolha a cor do ícone",
    "Custom css": "CSS customizado",
    fadeIn: "aparecimento gradual",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "fadeInUp",
    bounceInDown: "saltarInDown",
    bounceInLeft: "saltarInLeft",
    bounceInUp: "saltarInUp",
    zoomIn: "mais Zoom",
    zoomInDown: "zoomInDown",
    zoomInLeft: "zoomInLeft",
    slideInLeft: "slideInLeft",
    slideInUp: "deslizar para cima",
    slideInDown: "slideInDown",
    lightSpeedIn: "lightSpeedIn",
    rollIn: "rolar para dentro",
    flash: "clarão",
    shake: "sacudir",
    flip: "virar",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "desaparecer",
    fadeOutDown: "fadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fadeOutUp",
    bounceOutDown: "saltarOutDown",
    bounceOutRight: "saltarOutRight",
    bounceOutUp: "saltarOutUp",
    zoomOut: "Reduzir o zoom",
    zoomOutDown: "zoomOutDown",
    zoomOutRight: "zoomOutRight",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "sair da cama",
    flipInY: "virarInY",
    "Text Animation": "Animação de texto",
    "Animation In": "Animação em",
    "Animation Out": "Animação fora",
    "Auto play time (time in MS)": "Tempo de reprodução automática (tempo em MS)",
    "Animation time (time in MS)": "Tempo de animação (tempo em MS)",
    "Auto play time (time in Second)": "Tempo de reprodução automática (tempo em segundos)",
    "Background Color": "Cor de fundo",
    "Space between slide(px)": "Espaço entre o slide (px)",
    visible: "visível",
    invisible: "invisível",
    "Promotional & Countdown Bar": "Barra promocional e de contagem regressiva",
    "Free Shipping Bar": "Barra de frete grátis",
    "Add Slide": "Adicionar slide",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Apenas 1 slide está visível para o plano GRATUITO. Para ativar Todos os slides, assine o Plano Premium.",
    Pricing: "Preços",
    "No Animation Found": "Nenhuma animação encontrada",
    "No Preview, Add announcement Bar": "Sem visualização, adicionar barra de anúncio",
    "Update successfully": "Atualização com sucesso",
    Enable: "Habilitar",
    Disable: "Desativar",
    successfully: "com sucesso",
    "Delete successfully": "Excluir com sucesso",
    "Copy successfully": "Copiar com sucesso",
    "Reorder successfully": "Reordenar com sucesso",
    "Announcement Message": "Mensagem de anúncio",
    "Call to Action": "Chamada para ação",
    Timer: "Cronômetro",
    Style: "Estilo",
    "Background Type": "Tipo de plano de fundo",
    "Mobile Style": "Estilo móvel",
    "Schedule Display": "Exibição de programação",
    Update: "Atualizar",
    "Change Font": "Alterar fonte",
    "Font Family": "Família de fontes",
    "Font Style": "Estilo de fonte",
    Normal: "Normal",
    Italic: "itálico",
    Oblique: "Oblíquo",
    Unset: "Desativar",
    "Font Weight": "Espessura da fonte",
    Bold: "Audacioso",
    "Message Font Size": "Tamanho da fonte da mensagem",
    "Message Text color": "Cor do texto da mensagem",
    Type: "Tipo",
    None: "Nenhum",
    Button: "Botão",
    "Entire clickable bar": "Barra clicável inteira",
    "Add a simple link": "Adicione um link simples",
    "Add coupon placement": "Adicionar posicionamento de cupom",
    "Linked Url": "URL vinculado",
    "Background Hover Color": "Cor de foco de fundo",
    "Text Hover Color": "Cor de passagem do texto",
    "Button Text": "Botão de texto",
    "Copied Text": "Texto copiado",
    "Open in the new tab": "Abrir na nova aba",
    URL: "URL",
    "Font Size": "Tamanho da fonte",
    "Button Radius": "Raio do botão",
    "Button color": "Cor do botao",
    "Button Text color": "Cor do texto do botão",
    "Button Hover Color": "Cor do botão flutuante",
    "button Text HoverColor": "botão Texto HoverColor",
    "Timer Setting": "Configuração do temporizador",
    "Timer Type": "Tipo de temporizador",
    Date: "Data",
    "Select Reapt Time": "Selecione Tempo de Reaptação",
    "repeated Hours": "Horas repetidas",
    "Normal Timer": "Temporizador normal",
    "Auto repeat timer": "Temporizador de repetição automática",
    Minute: "Minuto",
    Hour: "Hora",
    Day: "Dia",
    "Remove Timer When Time End": "Remover o cronômetro quando o tempo terminar",
    "Timer Separator": "Separador de temporizador",
    "Countdown Timer color": "Cor do temporizador de contagem regressiva",
    "Timer Text Size": "Tamanho do texto do temporizador",
    "Timer Text Setting": "Configuração de texto do temporizador",
    "Day Text": "Texto do dia",
    "Hour Text": "Texto da hora",
    "Minute Text": "Texto Minuto",
    "Second Text": "Segundo Texto",
    "Background Image": "Imagem de fundo",
    "Gradient Background": "Fundo gradiente",
    "Style & Color For Mobile": "Estilo e cor para celular",
    "Timer Background": "Fundo do temporizador",
    "Timer Text Color": "Cor do texto do temporizador",
    "Button Color": "Cor do botao",
    "Button Text Color": "Cor do texto do botão",
    "Button Text Hover Color": "Cor de foco do texto do botão",
    "Button Text Size": "Tamanho do texto do botão",
    "Always Display": "Sempre exibir",
    "Only Display Within The Following Period Of Time": "Exibir apenas dentro do seguinte período de tempo",
    "Start Time": "Hora de início",
    "End Time": "Fim do tempo",
    "Advance Setting": "Configuração avançada",
    "Country Filter": "Filtro de país",
    Visibility: "Visibilidade",
    "Desktop and Mobile": "Computador e celular",
    "Only Desktop": "Somente área de trabalho",
    "Only Mobile": "Somente celular",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "SEGMENTAÇÃO DA FONTE DO USUÁRIO (visitantes provenientes de um link incluindo o seguinte código UTM, por exemplo, Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Selecione a página",
    Include: "Incluir",
    Exclude: "Excluir",
    "Currency Configuration": "Configuração de moeda",
    Message: "Mensagem",
    "Currency Symbol": "Símbolo monetário",
    "Currency Position": "Posição da Moeda",
    Before: "Antes",
    After: "Depois",
    "money Class": "classe de dinheiro",
    "Initial Message": "Mensagem Inicial",
    "Shipping Goal": "Meta de envio",
    "Progress Message": "Mensagem de progresso",
    "Progress goal": "Meta de progresso",
    "Goal Message": "Mensagem de meta",
    "Shipping Price Color": "Cor do preço de envio",
    "Shipping Price Size": "Tamanho do preço de envio",
    "Shipping Font Weight": "Peso da fonte de envio",
    "* When user first time visit": "* Quando o usuário visita pela primeira vez",
    "* When user add item to the cart e.g": "* Quando o usuário adiciona um item ao carrinho, por exemplo:",
    "* When cart value is greater than": "*Quando o valor do carrinho é maior que",
    "Show On Selected Countries": "Mostrar em países selecionados",
    "Show On Selected Pages": "Mostrar nas páginas selecionadas",
    All: "Todos",
    Home: "Lar",
    Cart: "Carrinho",
    Collection: "Coleção",
    Product: "produtos",
    Custom: "Personalizado",
    Page: "Página",
    Blog: "Blogue",
    "Url is required": "O URL é obrigatório",
    "Day Text is required": "O texto do dia é obrigatório",
    "Hour Text is required": "O texto da hora é obrigatório",
    "Minute Text is required": "O texto do minuto é obrigatório",
    "Second Text is required": "O segundo texto é obrigatório",
    "Start Time is required": "A hora de início é obrigatória",
    "End Time is required": "O horário de término é obrigatório",
    "Created successfully": "Criado com sucesso",
    "United States": "Estados Unidos",
    Canada: "Canadá",
    Australia: "Austrália",
    "New Zealand": "Nova Zelândia",
    Germany: "Alemanha",
    India: "Índia",
    Afghanistan: "Afeganistão",
    "land Islands": "ilhas terrestres",
    Albania: "Albânia",
    Algeria: "Argélia",
    "American Samoa": "Samoa Americana",
    AndorrA: "Andorra",
    Angola: "Angola",
    Anguilla: "Anguila",
    Antarctica: "Antártica",
    "Antigua and Barbuda": "Antígua e Barbuda",
    Argentina: "Argentina",
    Armenia: "Armênia",
    Aruba: "Aruba",
    Austria: "Áustria",
    Azerbaijan: "Azerbaijão",
    Bahamas: "Bahamas",
    Bahrain: "Bahrein",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Bielorrússia",
    Belgium: "Bélgica",
    Belize: "Belize",
    Benin: "Benim",
    Bermuda: "Bermudas",
    Bhutan: "Butão",
    Bolivia: "Bolívia",
    "Bosnia and Herzegovina": "Bósnia e Herzegovina",
    Botswana: "Botsuana",
    "Bouvet Island": "Ilha Bouvet",
    Brazil: "Brasil",
    "British Indian Ocean Territory": "Território Britânico do Oceano Índico",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgária",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Camboja",
    Cameroon: "Camarões",
    "Cape Verde": "cabo Verde",
    "Cayman Islands": "Ilhas Cayman",
    "Central African Republic": "República Centro-Africana",
    Chad: "Chade",
    Chile: "Chile",
    China: "China",
    "Christmas Island": "Ilha do Natal",
    "Cocos (Keeling) Islands": "Ilhas Cocos (Keeling)",
    Colombia: "Colômbia",
    Comoros: "Comores",
    Congo: "Congo",
    "Congo, The Democratic Republic of the": "Congo, República Democrática do",
    "Cook Islands": "Ilhas Cook",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Costa do Marfim",
    Croatia: "Croácia",
    Cuba: "Cuba",
    Cyprus: "Chipre",
    "Czech Republic": "República Checa",
    Denmark: "Dinamarca",
    Djibouti: "Djibuti",
    Dominica: "Domínica",
    "Dominican Republic": "República Dominicana",
    Ecuador: "Equador",
    Egypt: "Egito",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Guiné Equatorial",
    Eritrea: "Eritreia",
    Estonia: "Estônia",
    Ethiopia: "Etiópia",
    "Falkland Islands (Malvinas)": "Ilhas Falkland (Malvinas)",
    "Faroe Islands": "ilhas Faroe",
    Fiji: "Fiji",
    Finland: "Finlândia",
    France: "França",
    "French Guiana": "Guiana Francesa",
    "French Polynesia": "Polinésia Francesa",
    "French Southern Territories": "Territórios Franceses do Sul",
    Gabon: "Gabão",
    Gambia: "Gâmbia",
    Georgia: "Geórgia",
    Ghana: "Gana",
    Gibraltar: "Gibraltar",
    Greece: "Grécia",
    Greenland: "Groenlândia",
    Grenada: "Granada",
    Guadeloupe: "Guadalupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guiné",
    "Guinea-Bissau": "Guiné-Bissau",
    Guyana: "Guiana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Ilha Heard e Ilhas Mcdonald",
    "Holy See (Vatican City State)": "Santa Sé (Cidade do Vaticano)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Hungria",
    Iceland: "Islândia",
    Indonesia: "Indonésia",
    "Iran, Islamic Republic Of": "Irã (Republic Islâmica do Irã",
    Iraq: "Iraque",
    Ireland: "Irlanda",
    "Isle of Man": "Ilha de Man",
    Israel: "Israel",
    Italy: "Itália",
    Jamaica: "Jamaica",
    Japan: "Japão",
    Jersey: "Jersey",
    Jordan: "Jordânia",
    Kazakhstan: "Cazaquistão",
    Kenya: "Quênia",
    Kiribati: "Quiribáti",
    "Korea, Democratic People'S Republic of": "Coréia, República Popular Democrática da",
    "Korea, Republic of": "Republica da Coréia",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Quirguistão",
    "Lao People'S Democratic Republic": "República Democrática Popular do Laos",
    Latvia: "Letônia",
    Lebanon: "Líbano",
    Lesotho: "Lesoto",
    Liberia: "Libéria",
    "Libyan Arab Jamahiriya": "Jamahiriya Árabe Líbia",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lituânia",
    Luxembourg: "Luxemburgo",
    Macao: "Macau",
    "Macedonia, The Former Yugoslav Republic of": "Macedónia, Antiga República Jugoslava da",
    Madagascar: "Madagáscar",
    Malawi: "Maláui",
    Malaysia: "Malásia",
    Maldives: "Maldivas",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Ilhas Marshall",
    Martinique: "Martinica",
    Mauritania: "Mauritânia",
    Mauritius: "Maurício",
    Mayotte: "Maiote",
    Mexico: "México",
    "Micronesia, Federated States of": "Micronésia, Estados Federados da",
    "Moldova, Republic of": "Moldávia, República da",
    Monaco: "Mônaco",
    Mongolia: "Mongólia",
    Montenegro: "Montenegro",
    Montserrat: "Montserrate",
    Morocco: "Marrocos",
    Mozambique: "Moçambique",
    Myanmar: "Mianmar",
    Namibia: "Namíbia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Holanda",
    "Netherlands Antilles": "Antilhas Holandesas",
    "New Caledonia": "Nova Caledônia",
    Nicaragua: "Nicarágua",
    Niger: "Níger",
    Nigeria: "Nigéria",
    Niue: "Niue",
    "Norfolk Island": "Ilha Norfolk",
    "Northern Mariana Islands": "Ilhas Marianas do Norte",
    Norway: "Noruega",
    Oman: "Omã",
    Pakistan: "Paquistão",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Território Palestino, Ocupado",
    Panama: "Panamá",
    "Papua New Guinea": "Papua Nova Guiné",
    Paraguay: "Paraguai",
    Peru: "Peru",
    Philippines: "Filipinas",
    Pitcairn: "Pitcairn",
    Poland: "Polônia",
    Portugal: "Portugal",
    "Puerto Rico": "Porto Rico",
    Qatar: "Catar",
    Reunion: "Reunião",
    Romania: "Romênia",
    "Russian Federation": "Federação Russa",
    RWANDA: "RUANDA",
    "Saint Helena": "Santa Helena",
    "Saint Kitts and Nevis": "São Cristóvão e Nevis",
    "Saint Lucia": "Santa Lúcia",
    "Saint Pierre and Miquelon": "São Pedro e Miquelon",
    "Saint Vincent and the Grenadines": "São Vicente e Granadinas",
    Samoa: "Samoa",
    "San Marino": "São Marino",
    "Sao Tome and Principe": "São Tomé e Príncipe",
    "Saudi Arabia": "Arábia Saudita",
    Senegal: "Senegal",
    Serbia: "Sérvia",
    Seychelles: "Seicheles",
    "Sierra Leone": "Serra Leoa",
    Singapore: "Cingapura",
    Slovakia: "Eslováquia",
    Slovenia: "Eslovênia",
    "Solomon Islands": "Ilhas Salomão",
    Somalia: "Somália",
    "South Africa": "África do Sul",
    "South Georgia and the South Sandwich Islands": "Geórgia do Sul e Ilhas Sandwich do Sul",
    Spain: "Espanha",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudão",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard e Jan Mayen",
    Swaziland: "Suazilândia",
    Sweden: "Suécia",
    Switzerland: "Suíça",
    "Syrian Arab Republic": "República Árabe da Síria",
    "Taiwan, Province of China": "Taiwan, província da China",
    Tajikistan: "Tadjiquistão",
    "Tanzania, United Republic of": "Tanzânia, República Unida da",
    Thailand: "Tailândia",
    "Timor-Leste": "Timor-Leste",
    Togo: "Ir",
    Tokelau: "Toquelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd e Tobago",
    Tunisia: "Tunísia",
    Turkey: "Peru",
    Turkmenistan: "Turcomenistão",
    "Turks and Caicos Islands": "Ilhas Turcas e Caicos",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ucrânia",
    "United Arab Emirates": "Emirados Árabes Unidos",
    "United Kingdom": "Reino Unido",
    "United States Minor Outlying Islands": "Ilhas Menores Distantes dos Estados Unidos",
    Uruguay: "Uruguai",
    Uzbekistan: "Uzbequistão",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnã",
    "Virgin Islands, British": "Ilhas Virgens, Britânicas",
    "Virgin Islands, U.S.": "Ilhas Virgens, EUA",
    "Wallis and Futuna": "Wallis e Futuna",
    "Western Sahara": "Saara Ocidental",
    Yemen: "Iémen",
    Zambia: "Zâmbia",
    Zimbabwe: "Zimbábue",
    "Unlock All Schema with our Premium Plan": "Desbloqueie todos os esquemas com nosso plano Premium",
    "Billed Monthly": "Faturado Mensalmente",
    "Billed Annually": "Cobrado anualmente",
    "Save 30%": "Economize 30%",
    Premium100Title:
      "Como um usuário inicial, garantimos que você desfrutará de todos os nossos recursos premium sem nenhum custo para você. Não há necessidade de se preocupar com a página de preços, pois você pode acessar gratuitamente todos os nossos recursos premium sem quaisquer custos. Não desinstale nosso aplicativo para continuar aproveitando nosso serviço.",
    Premium100ReviewLine:
      " Se você gosta do nosso aplicativo, deixe-nos uma avaliação. Isso nos ajuda a ficar motivados no desenvolvimento de novos recursos.",
    "Check Our Current Pricing": "Verifique nossos preços atuais",
    "Leave Review": "Deixar comentário",
    "We're sorry to see you go!": "Lamentamos ver você partir!",
    "Cancel Plan": "Cancelar plano",
    "Sync Plan": "Plano de sincronização",
    "Disccount applied": "Desconto aplicado",
    Apply: "Aplicar",
    "Your code(s)": "Seu(s) código(s)",
    "and discount have been applied successfully": "e o desconto foi aplicado com sucesso",
    "Your entered promocode is not correct, Enter a valid code":
      "O código promocional inserido não está correto. Insira um código válido",
    "days trial left": "dias restantes de teste",
    Upgrade: "Atualizar",
    "days free trial, No Credit card required": "dias de teste gratuito, sem necessidade de cartão de crédito",
    Month: "Mês",
    Year: "Ano",
    Unlimited: "Ilimitado",
    "Enter Promocode": "Insira o código promocional",
    "Please Choose a Cancellation Reason": "Escolha um motivo de cancelamento",
    "No Longer Needed?": "Não é mais necessário?",
    "Didn't Meet Expectations": "Não atendeu às expectativas",
    "Cost Concerns": "Preocupações com custos",
    "Technical Issues": "Problemas técnicos",
    "Found an Alternative": "Encontrou uma alternativa",
    Complexity: "Complexidade",
    "Lack of Features": "Falta de recursos",
    "Poor Customer Support": "Fraco suporte ao cliente",
    "Business Closure or Change": "Fechamento ou mudança de negócios",
    "Temporary Pause": "Pausa temporária",
    "Performance Issues": "Problemas de desempenho",
    Other: "Outro",
    "Mention Your Specific Reason Here": "Mencione seu motivo específico aqui",
    Start: "Começar",
    "Day Free Trial": "Teste gratuito de um dia",
    "Please Select One Option": "Por favor selecione uma opção",
    "Plan cancelled successfully": "Plano cancelado com sucesso",
    "7 days free trial, No Credit card required": "Teste gratuito de 7 dias, sem necessidade de cartão de crédito",
    "Your remaining trial days are": "Seus dias de teste restantes são",
    "You have used": "Você usou",
    "days.": "dias.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Não há dias de teste restantes. Você já usou o teste gratuito de 7 dias.",
    "Upgrade your plan now": "Atualize seu plano agora",
    "Unlimited Slides": "Apresentações ilimitadas",
    "20+ Animation In & Out": "Mais de 20 animações dentro e fora",
    "Live Chat Support": "Suporte por chat ao vivo",
    "Priority, 24*7 Urgent setup and support":
      "Prioridade, configuração e suporte urgentes 24 horas por dia, 7 dias por semana",
    "Rich Text Editor": "Editor de Rich Text",
    "One Slide(banner)": "Um slide (banner)",
    "Repeated Countdown timer": "Temporizador de contagem regressiva repetido",
    "Fully Customisable": "Totalmente personalizável",
    "Background-image": "Imagem de fundo",
    "Custom Css": "CSS customizado",
    "Enable Our App": "Habilite nosso aplicativo",
    "Book Onboarding Demo": "Reserve uma demonstração de integração",
    Next: "Próximo",
    Finish: "Terminar",
    Prev: "Anterior",
    "App is not enable please click on the Enable App button to enable it.":
      "O aplicativo não está habilitado, clique no botão Habilitar aplicativo para habilitá-lo.",
    "This field is required": "Este campo é obrigatório",
    disableButtonTooltip: "Você não pode atualizar o plano mensal porque está em um plano anual!",
    "Choose plan": "Escolha o plano",
    "Purchase Plan": "Plano de compra",
    Continue: "Continuar",
    "Image Optimization": "Otimização de imagem",
    "AI Metatags": "Metatags de IA",
    "Grand Total": "Total geral",
    "Metatags Edit": "Edição de metatags",
    Products: "Produtos",
    "Upgrade plan": "Plano de atualização",
    "Your product count is": "Sua contagem de produtos é",
    "so your suitable plan is": "então seu plano adequado é",
    "Enjoy a": "Desfrute de um",
    "lifetime discount": "desconto vitalício",
    discountBanner:
      " Aproveite um desconto vitalício, garantindo economias perpétuas e aprimorando sua experiência com nossos produtos e serviços premium.",
    "Images for Optimization every year after trial period end":
      "Imagens para otimização todos os anos após o término do período de avaliação",
    "AI Meta Tags Credit for every year after trial period end":
      "Crédito de meta tags AI para cada ano após o término do período de avaliação",
    "Images for Optimization every month after trial period end":
      "Imagens para otimização todos os meses após o término do período de avaliação",
    "AI Meta Tags Credit for every Month after trial period end":
      "Crédito de Meta Tags AI para cada mês após o término do período de avaliação",
    "Optimize your google page speed": "Otimize a velocidade da sua página do Google",
    "50 Product Meta tags Optimize, Image alt": "50 Meta tags de produto Otimizar, Imagem alt",
    "Product Meta tags Optimize, Image alt": "Meta tags de produto Otimizar, Imagem alt",
    "AI ImageAltText Credit for every year after trial period end":
      "Crédito AI ImageAltText para cada ano após o término do período de avaliação",
    "25 AI ImageAltText Credit": "25 Crédito AI ImageAltText",
    "AI ImageAltText Credit for every Month after trial period end":
      "Crédito AI ImageAltText para cada mês após o término do período de avaliação",
    "Contact Bar": "Barra de contato",
    "Add To Cart Bar": "Barra Adicionar ao carrinho",
    "Multiple Position": "Posição múltipla",
    lowMsgStart: "Esta oferta foi especialmente desenvolvida para você, que acabou de iniciar sua loja no Shopify",
    lowMsgMiddle: "Nosso",
    lowMsgEnd: "desconto é a nossa maneira de apoiá-lo durante esses tempos desafiadores, mas emocionantes.",
    mediumMsgStart: "Esta oferta foi projetada especialmente para você, que iniciou sua loja no Shopify",
    mediumMsgMiddle: "Nosso",
    mediumMsgEnd: "desconto é a nossa maneira de apoiá-lo durante esses tempos desafiadores, mas emocionantes.",
    importantMsgStart: "Esta oferta foi projetada especialmente para você, que iniciou sua loja no Shopify",
    importantMsgMiddle: "Nosso",
    importantMsgEnd: "desconto é a nossa maneira de apoiá-lo durante esses tempos desafiadores, mas emocionantes.",
    veryImportantMsgStart: "Esta oferta foi especialmente desenvolvida para você, que abriu sua loja no Shopify",
    veryImportantMsgMiddle: "Você é um comerciante muito importante e maduro para nós. Nosso",
    veryImportantMsgEnd: "desconto é para mostrar o quanto você significa para nós.",
    generalMsg:
      "Nosso aplicativo Shopify é adaptado para atender às necessidades de empresas estabelecidas como a sua. Ele foi projetado para lidar perfeitamente com grandes volumes e operações complexas. ",
    lowTitleStart: "Apoio Especial para Novos Empreendedores:",
    lowTitleEnd: "Desconto quando você acabou de começar",
    mediumTitleStart: "Apoio Especial para Empreendedores:",
    mediumTitleEnd: "Desconto quando você começou",
    importantTitleStart: "Apoio Especial para Empreendedores:",
    importantTitleEnd: "Desconto quando você começou",
    veryImportantTitleStart: "Parabéns por ser",
    veryImportantTitleEnd: "na Shopify",
    month: "mês",
    "year and": "ano e",
    ago: "atrás",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Adicionar crédito de IA (1 crédito de IA/10 centavos) (10 créditos de IA/US$ 1)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Adicionar imagem altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )",
    "Monthly AI AltText Credit": "Crédito mensal AI AltText",
    "Yearly AI AltText Credit": "Crédito AI AltText anual",
    "Purchase AI AltText Credit": "Compre crédito AI AltText",
    "ImageAltText Credit": "Crédito de imagemAltText",
    "Your credits are finished; please upgrade your plan.": "Seus créditos terminaram; atualize seu plano.",
    "Your credits are finished; you can buy more credits from here.":
      "Seus créditos terminaram; você pode comprar mais créditos aqui.",
    "This offer expire in": "Esta oferta expira em",
    "Hurry Up!": "Se apresse!",
    Current: "Atual",
    "Discount applied": "Desconto aplicado",
    "trial left": "teste restante",
    "info banner":
      "Quando você clica no botão Digitalizar imagem da página inicial, nosso aplicativo verifica apenas a imagem da página inicial. Para otimizar esta imagem, clique no botão Otimizar manualmente",
    "Optimize Images": "Otimizar imagens",
    image: "imagem",
    images: "imagens",
    Filename: "Nome do arquivo",
    Images: "Imagens",
    Setting: "Contexto",
    "Saved(in %)": "Salvo (em%)",
    Action: "Ação",
    "Product Image": "Imagem do Produto",
    "product image": "Imagem do Produto",
    gif: "gif",
    Homepage: "Pagina inicial",
    "Manage Announcement": "Gerenciar anúncio",
    "No Announcements Found": "Nenhum anúncio encontrado",
    Position: "Posição",
    "Campaign Title": "Título da campanha",
    Visible: "Visível",
    Invisible: "Invisível",
    Views: "Visualizações",
    Clicks: "Cliques",
    Submits: "Envia",
    "Above Add to cart Button": "Acima do botão Adicionar ao carrinho",
    "Below Add to cart Button": "Abaixo do botão Adicionar ao carrinho",
    Targeting: "Alvejando",
    "Rotating Animation Setting": "Configuração de animação rotativa",
    "Marquee Animation Setting": "Configuração de animação de letreiro",
    "Show to visitors coming form then specific website":
      "Mostrar aos visitantes o formulário e o site específico",
    "Add your website URL": "Adicione o URL do seu site",
    "Banner Display Start Time": "Horário de início da exibição do banner",
    "Banner Display End Time": "Horário de término da exibição do banner",
    "Create Campaign": "Criar campanha",
    "Select Announcement Bar": "Selecione a barra de anúncios",
    "Please select template.": "Selecione o modelo.",
    Previous: "Anterior",
    "Promotion bar": "Barra de promoção",
    "Add To Cart": "Adicionar ao carrinho",
    Embeded: "Incorporado",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Alerte os clientes sobre próximas vendas, ofertas ou defina alertas de estoque.",
    "Increase your order value by using or Free Shipping Bar.":
      "Aumente o valor do seu pedido usando nossa barra de frete grátis.",
    "Conveniently add items to your cart with a single click!":
      "Adicione itens ao seu carrinho com apenas um clique!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Selecione para assinar e receber descontos especiais diretamente na sua caixa de entrada",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Destaque suas ofertas especiais com uma barra incorporada, exibida antes e depois do botão Adicionar ao carrinho.",
    Select: "Selecione",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Adicionar código UTM para ocultar banner (por exemplo, Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Incluir Utm",
    "Exclude Utm": "Excluir Utm",
    "Campaign Design": "Design de campanha",
    "Background Setting": "Cenário de fundo",
    "Target Setting": "Definição de metas",
    Scheduling: "Agendamento",
    Rotating: "Girando",
    Marquee: "Marquee",
    "Repeat Timer Date": "Repetir data do temporizador",
    "Select Repeat Time": "Selecione Repetir Tempo",
    "Repeated Hours": "Horas repetidas",
    Border: "Fronteira",
    Bashed: "Espancado",
    "Multi Rotating": "Multi Rotativo",
    Contacts: "Contatos",
    Email: "E-mail",
    "First Name": "Primeiro nome",
    "Last Name": "Sobrenome",
    Phone: "Telefone",
    "You have unsaved changes": "Você tem alterações não salvas",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Sua campanha tem alterações não salvas. As alterações serão perdidas se você sair sem salvar.",
    "Leave widthout saving": "Sair sem salvar",
    "Save Changes": "Salvar alterações",
    Announcement: "Anúncio",
    Feedback: "Opinião",
    "Recipe Instructions": "Instruções de receita",
    "Visit Help Center": "Visite a Central de Ajuda",
    "Schedule Meeting": "Reunião cronograma",
    "Setup guide": "Guia de Configuração",
    "Use this personalized guide to get your store up and running":
      "Use este guia personalizado para colocar sua loja em funcionamento",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Para começar a obter ações você precisa habilitar nosso aplicativo, clicar no botão irá levá-lo para a página de extensões, então você só precisa clicar em salvar lá e voltar aqui",
    "Enable our app": "Habilite nosso aplicativo",
    "Learn more": "Saber mais",
    "Skip it": "Pule isso",
    steps: "passos",
    minutes: "minutos",
    "Mark as done": "Marcar como concluído",
    "Mark as not done": "Marcar como não concluído",
    "You have completed all the steps": "Você concluiu todas as etapas",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Ative e analise a velocidade do seu site para classificar sua loja em uma posição mais elevada nos resultados de pesquisa.",
    "Google Page Speed Optimization": "Otimização de velocidade de página do Google",
    "Activate Google Page Speed": "Ative o Google Page Speed",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Ative a ferramenta Google Page Speed para avaliar o desempenho do seu site e identificar oportunidades de aumento de velocidade",
    "Enable Speed Analysis": "Ativar análise de velocidade",
    "Review Speed Analysis Report": "Revise o relatório de análise de velocidade",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Examine o relatório detalhado de análise de velocidade para entender as métricas de velocidade atuais do seu site e identificar áreas para melhoria.",
    "Go to Reports": "Ir para Relatórios",
    Hello: "Olá",
    "Let's get your store ready for success": "Vamos preparar sua loja para o sucesso",
    "Finish later": "Termine mais tarde",
    "Continue onboarding": "Continuar a integração",
    "Check image optimization features": "Verifique os recursos de otimização de imagem",
    "Explore Optimization Features": "Explore os recursos de otimização",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Familiarize-se com a variedade de ferramentas de otimização de imagens disponíveis. Veja como você pode melhorar a velocidade de carregamento da página e o SEO otimizando tamanhos e formatos de imagens.",
    "Go to Image Optimization": "Vá para Otimização de imagem",
    "Automate Your Image Workflow": "Automatize seu fluxo de trabalho de imagens",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Configure a automação para otimizar perfeitamente novas imagens à medida que são carregadas, garantindo um desempenho consistente em todo o seu site.",
    "Go to Automation": "Vá para Automação",
    "Execute a Bulk Optimization": "Execute uma otimização em massa",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Execute uma otimização em massa para aprimorar com eficiência várias imagens de uma só vez, o que pode aumentar significativamente o tempo de carregamento do seu site.",
    "Go to bulk operations": "Ir para operações em massa",
    "Broken Links Management": "Gerenciamento de links quebrados",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatize a detecção e reparo de links quebrados para melhorar a experiência do usuário e as classificações de SEO.",
    "Review Detected Broken Links": "Revise links quebrados detectados",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Examine a lista de links quebrados identificados automaticamente pelo nosso sistema para entender o impacto deles na navegação do seu site.",
    "View Broken Links": "Ver links quebrados",
    "Address Broken Links": "Endereço de links quebrados",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Utilize nossas ferramentas para corrigir ou redirecionar rapidamente links quebrados, melhorando a integridade do seu site e a satisfação do usuário.",
    "Resolve Broken Links": "Resolver links quebrados",
    "Automate for Efficiency": "Automatize para eficiência",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Configure a correção automatizada para ficar à frente de quaisquer links quebrados no futuro, garantindo a integridade contínua do site.",
    "Enable Automation": "Habilitar automação",
    "Meta Tags Management": "Gerenciamento de metatags",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Otimize a visibilidade do seu site e a classificação nos mecanismos de pesquisa com nosso recurso de meta tags fácil de usar.",
    "Explore Meta Tag Options": "Explore as opções de metatag",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Familiarize-se com as várias opções de edição e automação de meta tags disponíveis para produtos e páginas individuais.",
    "Explore Meta Tags": "Explorar metatags",
    "Edit and Optimize": "Editar e otimizar",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Mergulhe na edição de metatítulos, descrições e textos alternativos de imagens para aprimorar o SEO do seu site e a acessibilidade do usuário.",
    "Start Editing": "Comece a editar",
    "Automate for Consistency": "Automatize para obter consistência",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Configure regras de automação para suas meta tags para manter a consistência e a eficiência nas páginas de seus produtos.",
    "Set Automation": "Definir automação",
    "Schema Markup": "Marcação de esquema",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Utilize a marcação Schema para melhorar a representação do seu conteúdo nos resultados de pesquisa e atrair mais cliques.",
    "Learn About Schema Options": "Saiba mais sobre as opções de esquema",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Familiarize-se com os diferentes tipos de marcações de esquema disponíveis, como produto, empresa local, perguntas frequentes e muito mais, para compreender seus benefícios.",
    "Explore Schema Types": "Explore os tipos de esquema",
    "Activate Key Schemas": "Ativar esquemas principais",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Escolha e habilite esquemas cruciais para o seu site, como esquema de produto para comércio eletrônico ou esquema de empresa local para lojas físicas.",
    "Go to Schemas": "Vá para Esquemas",
    "Customize Schema Details": "Personalizar detalhes do esquema",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Personalize as configurações de cada tipo de esquema para representar com precisão sua empresa ou produtos nos resultados da pesquisa.",
    "Test and Validate Schemas": "Testar e validar esquemas",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Teste seus esquemas usando ferramentas como a ferramenta de teste de dados estruturados do Google para garantir que sejam implementados corretamente.",
    "Test Schemas": "Esquemas de teste",
    "Add Breadcrumbs": "Adicionar pão ralado",
    "Add Breadcrumbs to your store": "Adicione pão ralado à sua loja",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Para obter uma melhor experiência do usuário, você precisa adicionar localização atual à sua loja.",
    "How to add breadcrumbs": "Como adicionar pão ralado",
    "Understand how to add and configure breadcrumbs in your store.":
      "Entenda como adicionar e configurar breadcrumbs em sua loja.",
    "Google search console": "Console de pesquisa do Google",
    "Connect google search console to sync it with our app.":
      "Conecte o console de pesquisa do Google para sincronizá-lo com nosso aplicativo.",
    "How to connect GSC.": "Como conectar o GSC.",
    "Understand how to connect and use google search console in our app.":
      "Entenda como conectar e usar o Google Search Console em nosso aplicativo.",
    "Go to GSC": "Vá para o GSC",
    "Go to Breadcrumbs Design": "Vá para o Design de Breadcrumbs",
    "Start Onboarding": "Comece a integração",
    "Go to Homepage": "Vá para a página inicial",
    "Go to Onboarding": "Vá para integração",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Explore nosso guia de aplicativos fácil de usar, projetado para aprimorar sua compreensão. Clique em 'Iniciar integração' para começar e você poderá voltar à página inicial a qualquer momento.",
    "Please enable our app extension.": "Ative nossa extensão de aplicativo.",
    "Generate Meta tags": "Gerar metatags",
    "Test description a litle bit longer that title": "Descrição do teste um pouco mais longa que o título",
    "Suggested for you": "Sugerido para você",
    "Enable Google page speed": "Ative a velocidade da página do Google",
    "Connect GSC": "Conecte o GSC",
    "Enable Image Optimize Automation": "Ativar automação de otimização de imagem",
    "Automate Meta tags": "Automatize metatags",
    "Automate Broken Links": "Automatize links quebrados",
    "Enhance SEO with automatically generated meta tags.": "Aprimore o SEO com meta tags geradas automaticamente.",
    "Improve website performance by optimizing images.": "Melhore o desempenho do site otimizando imagens.",
    "Boost website speed by enabling Google Page Speed.":
      "Aumente a velocidade do site ativando o Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Aumente a visibilidade da pesquisa conectando-se ao Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Simplifique a otimização de imagens com processos automatizados.",
    "Improve SEO by automating the generation of meta tags.":
      "Melhore o SEO automatizando a geração de meta tags.",
    "Improve UX with automated detect and handle, broken links.":
      "Melhore a experiência do usuário com detecção e tratamento automatizado de links quebrados.",
    "Learn About Add Announcement": "Saiba mais sobre como adicionar anúncio",
    "Skip And Add Announcement": "Pular e adicionar anúncio",
    "Learn more about": "Aprender mais sobre",
    "Add Announcement": "Adicionar anúncio",
    "Announcement Bar": "Barra de anúncios",
    "Rate us!": "Nos avalie!",
    "How would you Love this app?": "Como você adoraria este aplicativo?",
    "Enter Your Feedback Here": "Insira seu feedback aqui",
    "Leave Us a Review !!": "Deixe-nos um comentário!!",
    "If you like our app features then please leave us a review !!":
      "Se você gosta dos recursos do nosso aplicativo, deixe-nos um comentário !!",
    "If you like our free features then please leave us a review !!":
      "Se você gosta de nossos recursos gratuitos, deixe-nos um comentário!!",
    "Update Successfully": "Atualização com sucesso",
    "Uninstall App": "Desinstalar aplicativo",
    "Contact Our Support": "Entre em contato com nosso suporte",
    "Leave a message": "Deixe um recado",
    "Please Choose a UnInstallation Reason": "Escolha um motivo de desinstalação",
    "Are you facing any issues understanding the features of our app?":
      "Você está enfrentando algum problema para entender os recursos do nosso aplicativo?",
    "Please Choose at least one reason": "Escolha pelo menos um motivo",
    "Thank You For Reaching Out": "Obrigado por entrar em contato",
    "Contact Support": "Contate o suporte",
    "Get Help from Our Support Team": "Obtenha ajuda de nossa equipe de suporte",
    "Select a reason": "Selecione um motivo",
    "Not getting how to use or setup": "Não sei como usar ou configurar",
    "Poor customer support": "Suporte ao cliente ruim",
    "Performance issues": "Problemas de desempenho",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Nossa equipe de suporte está indisponível nos finais de semana e estará disponível durante a semana de acordo com seu fuso horário a partir de ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " já que operamos na Índia. Você ainda pode deixar uma mensagem. Por favor, espere algum atraso em nossa resposta. Obrigado pela sua paciência.",
    "Our support team is partially available according to your time zone from ":
      "Nossa equipe de suporte está parcialmente disponível de acordo com seu fuso horário a partir de ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " já que operamos na Índia. As respostas podem levar de 30 minutos a uma hora durante esse período. Por favor, deixe uma mensagem e responderemos o mais breve possível. Obrigado pela sua paciência.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Nossa equipe de suporte está indisponível no momento e estará disponível de acordo com seu fuso horário a partir de ",
    to: "para",
    "Did not meet my expectations": "Não atendeu às minhas expectativas",
    "Feature Limitations": "Limitações de recursos",
    "Banner doesn't set in my app": "O banner não está definido no meu aplicativo",
    "Banner is not show properly": "O banner não é exibido corretamente",
    "Confusing Set Multi Position and Multi Animation": "Conjunto confuso de múltiplas posições e multianimações",
    "Sync Profile": "Sincronizar Perfil",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
