import modifyData from "../Language/sv.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Aktiverad",
    Disabled: "Inaktiverad",
    "Embed is currently disabled": "Inbäddning är för närvarande inaktiverad",
    "Enable App": "Aktivera appen",
    "1. Click on Enable App.": "1. Klicka på Aktivera app.",
    "Well done!! you have successfully enable our app.": "Bra gjort!! du har framgångsrikt aktiverat vår app.",
    "2. Enable": "2. Aktivera",
    "App Embed as shown in image and save setting.": "App Bädda in enligt bilden och spara inställningen.",
    "Multi Announcement Bar": "Multi Announcement Bar",
    "Click on the Enable Now button to enable it.": "Klicka på knappen Aktivera nu för att aktivera den.",
    "Enable Announcement Bar to get started": "Aktivera meddelandefältet för att komma igång",
    "Enable Now": "Aktivera nu",
    "Sync Status": "Synkroniseringsstatus",
    Done: "Gjort",
    No: "Nej",
    Found: "Hittades",
    Add: "Lägg till",
    Search: "Sök",
    Showing: "Som visar",
    of: "av",
    "results, at most": "resultat som mest",
    "per page": "per sida",
    "Oops! Something went wrong.": "hoppsan! Något gick fel.",
    "Let's try that again, please refresh the page.": "Låt oss försöka igen. Uppdatera sidan.",
    "If you're still stuck, contact us by chat support or":
      "Om du fortfarande har fastnat, kontakta oss via chattsupport eller",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "så vi kan hjälpa till!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Välj valfri 3 funktion som du vill ställa in med hög prioritet eller mest intresserad",
    "Add ": "Lägg till ",
    "These is premium feature": "Dessa är premiumfunktioner",
    "Go to pricing": "Gå till prissättning",
    Save: "Spara",
    Minimum: "Minimum",
    Maximum: "Maximal",
    "images are required": "bilder krävs",
    and: "och",
    "images are allowed": "bilder är tillåtna",
    Disconnect: "Koppla ifrån",
    "Sign In with Google": "Logga in med Google",
    "Oops! Something went wrong. Admin token is malformed":
      "hoppsan! Något gick fel. Administratörstoken är felaktig",
    "If you're still stuck, contact": "Om du fortfarande är fast, kontakta",
    Premium: "Premie",
    Unlock: "Låsa upp",
    "Unlock advanced features!": "Lås upp avancerade funktioner!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Alla rättigheter förbehållna.",
    "Privacy Policy": "Integritetspolicy",
    "Terms of Service": "Användarvillkor",
    "Go to Shopify App": "Gå till Shopify-appen",
    "Review Us": "Granska oss",
    Cancel: "Annullera",
    "Review Popup Show": "Recension Popup Show",
    "click on review us": "klicka på granska oss",
    "Note: Feel free to leave a star rating without writing a review!":
      "Obs: Lämna gärna ett stjärnbetyg utan att skriva en recension!",
    Help: "Hjälp",
    "Help Button Click": "Hjälp-knapp Klicka",
    Confirm: "Bekräfta",
    On: "På",
    Off: "Av",
    Price: "Pris",
    Settings: "inställningar",
    Animation: "Animation",
    "My Profile": "Min profil",
    "My Subscription": "Mitt abonnemang",
    "Store Name": "Affärsnamn",
    "Store URL": "Store URL",
    "Email ID": "E-post ID",
    "Phone Number": "Telefonnummer",
    Country: "Land",
    Currency: "Valuta",
    "Subscription Name": "Prenumerationsnamn",
    "Select language": "Välj språk",
    "Announcement setting": "Annonsinställning",
    "Animation setting": "Animation inställning",
    Selector: "Väljare",
    "Save Setting": "Spara inställning",
    "My Announcements": "Mina meddelanden",
    "Add bar": "Lägg till bar",
    Number: "siffra",
    Title: "Titel",
    "Create At": "Skapa på",
    "Slide Activation": "Skjutaktivering",
    Status: "Status",
    Actions: "Handlingar",
    "Save order": "Spara beställning",
    "Reorder Slides": "Ordna om bilder",
    position: "placera",
    Top: "Topp",
    "Sticky Top": "Sticky Top",
    "Bottom Fix": "Botten Fix",
    "Custom Position": "Anpassad position",
    "Custom Position *Add Class or id of Selected Element.":
      "Anpassad position *Lägg till klass eller id för valt element.",
    "Bar Padding (px)": "Stångstoppning (px)",
    "Add Remove Button": "Lägg till knappen Ta bort",
    "Choose icon color": "Välj ikonfärg",
    "Custom css": "Anpassad CSS",
    fadeIn: "tona in",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "fadeInUp",
    bounceInDown: "bounceInDown",
    bounceInLeft: "bounceInLeft",
    bounceInUp: "bounceInUp",
    zoomIn: "zooma in",
    zoomInDown: "zooma in",
    zoomInLeft: "zooma in till vänster",
    slideInLeft: "slideInLeft",
    slideInUp: "slideInUp",
    slideInDown: "slideInDown",
    lightSpeedIn: "lightSpeedIn",
    rollIn: "rulla in",
    flash: "blixt",
    shake: "skaka",
    flip: "flip",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "tona ut",
    fadeOutDown: "fadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "fadeOutUp",
    bounceOutDown: "bounceOutDown",
    bounceOutRight: "bounceOutRight",
    bounceOutUp: "bounceOutUp",
    zoomOut: "zooma ut",
    zoomOutDown: "zooma ut",
    zoomOutRight: "zooma ut höger",
    slideOutRight: "slideOutRight",
    slideOutUp: "slideOutUp",
    slideOutDown: "slideOutDown",
    lightSpeedOut: "lightSpeedOut",
    rollOut: "rulla ut",
    flipInY: "flipInY",
    "Text Animation": "Textanimering",
    "Animation In": "Animation in",
    "Animation Out": "Animation Ut",
    "Auto play time (time in MS)": "Automatisk uppspelningstid (tid i MS)",
    "Animation time (time in MS)": "Animationstid (tid i MS)",
    "Auto play time (time in Second)": "Automatisk uppspelningstid (tid i sekund)",
    "Background Color": "Bakgrundsfärg",
    "Space between slide(px)": "Mellanrum mellan bild (px)",
    visible: "synlig",
    invisible: "osynlig",
    "Promotional & Countdown Bar": "Kampanj & Countdown Bar",
    "Free Shipping Bar": "Gratis frakt bar",
    "Add Slide": "Lägg till bild",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "Endast 1 bild är synlig för GRATIS plan. För att aktivera Alla bilder, prenumerera på Premium Plan.",
    Pricing: "Prissättning",
    "No Animation Found": "Ingen animering hittades",
    "No Preview, Add announcement Bar": "Ingen förhandsgranskning, Lägg till meddelandefält",
    "Update successfully": "Uppdateringen lyckades",
    Enable: "Gör det möjligt",
    Disable: "Inaktivera",
    successfully: "framgångsrikt",
    "Delete successfully": "Radera framgångsrikt",
    "Copy successfully": "Kopiera framgångsrikt",
    "Reorder successfully": "Beställ om",
    "Announcement Message": "Meddelande",
    "Call to Action": "Uppmaning till handling",
    Timer: "Timer",
    Style: "Stil",
    "Background Type": "Bakgrundstyp",
    "Mobile Style": "Mobil stil",
    "Schedule Display": "Schemavisning",
    Update: "Uppdatering",
    "Change Font": "Ändra teckensnitt",
    "Font Family": "Typsnittsfamilj",
    "Font Style": "Typsnitt",
    Normal: "Vanligt",
    Italic: "Kursiv",
    Oblique: "Sned",
    Unset: "Avaktiverad",
    "Font Weight": "Teckensnittsvikt",
    Bold: "Djärv",
    "Message Font Size": "Meddelande teckenstorlek",
    "Message Text color": "Meddelande Textfärg",
    Type: "Typ",
    None: "Ingen",
    Button: "Knapp",
    "Entire clickable bar": "Hela klickbara fältet",
    "Add a simple link": "Lägg till en enkel länk",
    "Add coupon placement": "Lägg till kupongplacering",
    "Linked Url": "Länkad URL",
    "Background Hover Color": "Bakgrund Hover Färg",
    "Text Hover Color": "Text Hover Color",
    "Button Text": "Knapp-text",
    "Copied Text": "Kopierad text",
    "Open in the new tab": "Öppna i den nya fliken",
    URL: "URL",
    "Font Size": "Textstorlek",
    "Button Radius": "Knappens radie",
    "Button color": "Knappens färg",
    "Button Text color": "Knapp Textfärg",
    "Button Hover Color": "Knapp Hover Färg",
    "button Text HoverColor": "knapp Text HoverColor",
    "Timer Setting": "Timerinställning",
    "Timer Type": "Timertyp",
    Date: "Datum",
    "Select Reapt Time": "Välj Återtagningstid",
    "repeated Hours": "upprepade timmar",
    "Normal Timer": "Normal timer",
    "Auto repeat timer": "Timer för automatisk upprepning",
    Minute: "Minut",
    Hour: "Timme",
    Day: "Dag",
    "Remove Timer When Time End": "Ta bort timern när tiden slutar",
    "Timer Separator": "Timerseparator",
    "Countdown Timer color": "Färg för nedräkningstimer",
    "Timer Text Size": "Timer textstorlek",
    "Timer Text Setting": "Timer textinställning",
    "Day Text": "Dag Text",
    "Hour Text": "Timmetext",
    "Minute Text": "Minute Text",
    "Second Text": "Andra texten",
    "Background Image": "Bakgrundsbild",
    "Gradient Background": "Gradient bakgrund",
    "Style & Color For Mobile": "Stil och färg för mobil",
    "Timer Background": "Timer bakgrund",
    "Timer Text Color": "Timer textfärg",
    "Button Color": "Knapp färg",
    "Button Text Color": "Knappens textfärg",
    "Button Text Hover Color": "Knapp Text Hover Färg",
    "Button Text Size": "Knappens textstorlek",
    "Always Display": "Visa alltid",
    "Only Display Within The Following Period Of Time": "Visas endast inom följande tidsperiod",
    "Start Time": "Starttid",
    "End Time": "Sluttid",
    "Advance Setting": "Avancerad inställning",
    "Country Filter": "Landsfilter",
    Visibility: "Synlighet",
    "Desktop and Mobile": "Desktop och mobil",
    "Only Desktop": "Endast skrivbord",
    "Only Mobile": "Endast mobil",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "ANVÄNDARKÄLLINRIKTNING (Besökare som kommer från en länk inklusive denna följande UTM-kod, t.ex. Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Välj sida",
    Include: "Omfatta",
    Exclude: "Utesluta",
    "Currency Configuration": "Valutakonfiguration",
    Message: "Meddelande",
    "Currency Symbol": "Valutasymbol",
    "Currency Position": "Valutaposition",
    Before: "Innan",
    After: "Efter",
    "money Class": "pengar Klass",
    "Initial Message": "Inledande meddelande",
    "Shipping Goal": "Fraktmål",
    "Progress Message": "Framstegsmeddelande",
    "Progress goal": "Framstegsmål",
    "Goal Message": "Målmeddelande",
    "Shipping Price Color": "Frakt Pris Färg",
    "Shipping Price Size": "Frakt Pris Storlek",
    "Shipping Font Weight": "Frakttypsnittsvikt",
    "* When user first time visit": "* När användaren besöker första gången",
    "* When user add item to the cart e.g": "* När användaren lägger till föremål i kundvagnen, t.ex.:",
    "* When cart value is greater than": "* När kundvagnens värde är större än",
    "Show On Selected Countries": "Visa på utvalda länder",
    "Show On Selected Pages": "Visa på utvalda sidor",
    All: "Allt",
    Home: "Hem",
    Cart: "Vagn",
    Collection: "Samling",
    Product: "Produkt",
    Custom: "Beställnings",
    Page: "Sida",
    Blog: "Blogg",
    "Url is required": "URL krävs",
    "Day Text is required": "Dagtext krävs",
    "Hour Text is required": "Timmetext krävs",
    "Minute Text is required": "Minute Text krävs",
    "Second Text is required": "Andra texten krävs",
    "Start Time is required": "Starttid krävs",
    "End Time is required": "Sluttid krävs",
    "Created successfully": "Skapat framgångsrikt",
    "United States": "Förenta staterna",
    Canada: "Kanada",
    Australia: "Australien",
    "New Zealand": "Nya Zeeland",
    Germany: "Tyskland",
    India: "Indien",
    Afghanistan: "Afghanistan",
    "land Islands": "land öar",
    Albania: "Albanien",
    Algeria: "Algeriet",
    "American Samoa": "Amerikanska Samoa",
    AndorrA: "AndorrA",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarktis",
    "Antigua and Barbuda": "Antigua och Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenien",
    Aruba: "Aruba",
    Austria: "Österrike",
    Azerbaijan: "Azerbajdzjan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrain",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belgien",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermuda",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    "Bosnia and Herzegovina": "Bosnien och Hercegovina",
    Botswana: "Botswana",
    "Bouvet Island": "Bouvetön",
    Brazil: "Brasilien",
    "British Indian Ocean Territory": "Brittiska territoriet i Indiska oceanen",
    "Brunei Darussalam": "Brunei Darussalam",
    Bulgaria: "Bulgarien",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Kambodja",
    Cameroon: "Kamerun",
    "Cape Verde": "Cap Verde",
    "Cayman Islands": "Caymanöarna",
    "Central African Republic": "Centralafrikanska republiken",
    Chad: "Tchad",
    Chile: "Chile",
    China: "Kina",
    "Christmas Island": "Julön",
    "Cocos (Keeling) Islands": "Cocos (Keeling) Islands",
    Colombia: "Colombia",
    Comoros: "Komorerna",
    Congo: "Kongo",
    "Congo, The Democratic Republic of the": "Kongo, Demokratiska republiken",
    "Cook Islands": "Cooköarna",
    "Costa Rica": "Costa Rica",
    "Cote D'Ivoire": "Elfenbenskusten",
    Croatia: "Kroatien",
    Cuba: "Kuba",
    Cyprus: "Cypern",
    "Czech Republic": "Tjeckien",
    Denmark: "Danmark",
    Djibouti: "Djibouti",
    Dominica: "Dominica",
    "Dominican Republic": "Dominikanska republiken",
    Ecuador: "Ecuador",
    Egypt: "Egypten",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Ekvatorialguinea",
    Eritrea: "Eritrea",
    Estonia: "Estland",
    Ethiopia: "Etiopien",
    "Falkland Islands (Malvinas)": "Falklandsöarna (Malvinas)",
    "Faroe Islands": "Färöarna",
    Fiji: "Fiji",
    Finland: "Finland",
    France: "Frankrike",
    "French Guiana": "Franska Guyana",
    "French Polynesia": "Franska Polynesien",
    "French Southern Territories": "franska södra territorierna",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgien",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Grekland",
    Greenland: "Grönland",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    "Guinea-Bissau": "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Heard Island och Mcdonald Islands",
    "Holy See (Vatican City State)": "Heliga stolen (Vatikanstaten)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Ungern",
    Iceland: "Island",
    Indonesia: "Indonesien",
    "Iran, Islamic Republic Of": "Iran, Islamiska republiken",
    Iraq: "Irak",
    Ireland: "Irland",
    "Isle of Man": "ö av man",
    Israel: "Israel",
    Italy: "Italien",
    Jamaica: "Jamaica",
    Japan: "Japan",
    Jersey: "Jersey",
    Jordan: "Jordanien",
    Kazakhstan: "Kazakstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Korea, Demokratiska folkrepubliken",
    "Korea, Republic of": "Korea, Republiken av",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kirgizistan",
    "Lao People'S Democratic Republic": "Demokratiska folkrepubliken Laos",
    Latvia: "Lettland",
    Lebanon: "Libanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    "Libyan Arab Jamahiriya": "Libyens arabiska Jamahiriya",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Litauen",
    Luxembourg: "Luxemburg",
    Macao: "Macao",
    "Macedonia, The Former Yugoslav Republic of": "Makedonien, fd jugoslaviska republiken",
    Madagascar: "Madagaskar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldiverna",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Marshallöarna",
    Martinique: "Martinique",
    Mauritania: "Mauretanien",
    Mauritius: "Mauritius",
    Mayotte: "Mayotte",
    Mexico: "Mexiko",
    "Micronesia, Federated States of": "Mikronesien, federerade stater av",
    "Moldova, Republic of": "Moldavien, Republiken",
    Monaco: "Monaco",
    Mongolia: "mongoliet",
    Montenegro: "Montenegro",
    Montserrat: "Montserrat",
    Morocco: "Marocko",
    Mozambique: "Moçambique",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Nederländerna",
    "Netherlands Antilles": "Nederländska Antillerna",
    "New Caledonia": "Nya Kaledonien",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    "Norfolk Island": "Norfolkön",
    "Northern Mariana Islands": "Nordmarianerna",
    Norway: "Norge",
    Oman: "oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Palestinska territoriet, ockuperat",
    Panama: "Panama",
    "Papua New Guinea": "Papua Nya Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Filippinerna",
    Pitcairn: "Pitcairn",
    Poland: "Polen",
    Portugal: "Portugal",
    "Puerto Rico": "Puerto Rico",
    Qatar: "Qatar",
    Reunion: "Återförening",
    Romania: "Rumänien",
    "Russian Federation": "Ryska Federationen",
    RWANDA: "RWANDA",
    "Saint Helena": "Sankt Helena",
    "Saint Kitts and Nevis": "Saint Kitts och Nevis",
    "Saint Lucia": "Saint Lucia",
    "Saint Pierre and Miquelon": "Saint Pierre och Miquelon",
    "Saint Vincent and the Grenadines": "Saint Vincent och Grenadinerna",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tomé och Principe",
    "Saudi Arabia": "Saudiarabien",
    Senegal: "Senegal",
    Serbia: "Serbien",
    Seychelles: "Seychellerna",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovakien",
    Slovenia: "Slovenien",
    "Solomon Islands": "Salomonöarna",
    Somalia: "Somalia",
    "South Africa": "Sydafrika",
    "South Georgia and the South Sandwich Islands": "South Georgia och South Sandwich Islands",
    Spain: "Spanien",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard och Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Sverige",
    Switzerland: "Schweiz",
    "Syrian Arab Republic": "Syrien Arabrepubliken",
    "Taiwan, Province of China": "Taiwan, provinsen Kina",
    Tajikistan: "Tadzjikistan",
    "Tanzania, United Republic of": "Tanzania, Förenade republiken",
    Thailand: "Thailand",
    "Timor-Leste": "Östtimor",
    Togo: "Togo",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd och Tobago",
    Tunisia: "Tunisien",
    Turkey: "Kalkon",
    Turkmenistan: "Turkmenistan",
    "Turks and Caicos Islands": "Turks- och Caicosöarna",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraina",
    "United Arab Emirates": "Förenade arabemiraten",
    "United Kingdom": "Storbritannien",
    "United States Minor Outlying Islands": "Förenta staternas mindre avlägsna öar",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands, British": "Jungfruöarna, brittiska",
    "Virgin Islands, U.S.": "Jungfruöarna, USA",
    "Wallis and Futuna": "Wallis och Futuna",
    "Western Sahara": "Västra Sahara",
    Yemen: "Jemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
    "Unlock All Schema with our Premium Plan": "Lås upp alla scheman med vår premiumplan",
    "Billed Monthly": "Faktureras månadsvis",
    "Billed Annually": "Faktureras årligen",
    "Save 30%": "Spara 30 %",
    Premium100Title:
      "Som en tidig användare försäkrar vi dig att alla våra premiumfunktioner du kommer att njuta av utan kostnad för dig. Det finns ingen anledning att vara orolig över prissidan eftersom du fritt kan komma åt alla våra premiumfunktioner utan några avgifter. Vänligen avinstallera inte vår app för att fortsätta njuta av vår tjänst.",
    Premium100ReviewLine:
      " Om du gillar vår app vänligen lämna oss en recension. Det hjälper oss att bli motiverade när vi utvecklar nya funktioner.",
    "Check Our Current Pricing": "Kontrollera vår aktuella prissättning",
    "Leave Review": "Lämna recension",
    "We're sorry to see you go!": "Vi är ledsna att se dig gå!",
    "Cancel Plan": "Avbryt plan",
    "Sync Plan": "Synkroniseringsplan",
    "Disccount applied": "Rabatten tillämpas",
    Apply: "Tillämpa",
    "Your code(s)": "Dina koder",
    "and discount have been applied successfully": "och rabatten har tillämpats framgångsrikt",
    "Your entered promocode is not correct, Enter a valid code":
      "Din angivna kampanjkod är inte korrekt. Ange en giltig kod",
    "days trial left": "dagars provtid kvar",
    Upgrade: "Uppgradera",
    "days free trial, No Credit card required": "dagars gratis provperiod, inget kreditkort krävs",
    Month: "Månad",
    Year: "År",
    Unlimited: "Obegränsat",
    "Enter Promocode": "Ange kampanjkod",
    "Please Choose a Cancellation Reason": "Vänligen välj en avbokningsorsak",
    "No Longer Needed?": "Behövs inte längre?",
    "Didn't Meet Expectations": "Uppfyllde inte förväntningarna",
    "Cost Concerns": "Kostnadsbekymmer",
    "Technical Issues": "Tekniska problem",
    "Found an Alternative": "Hittade ett alternativ",
    Complexity: "Komplexitet",
    "Lack of Features": "Brist på funktioner",
    "Poor Customer Support": "Dålig kundsupport",
    "Business Closure or Change": "Stängning eller förändring av företag",
    "Temporary Pause": "Tillfällig paus",
    "Performance Issues": "Prestandaproblem",
    Other: "Övrig",
    "Mention Your Specific Reason Here": "Nämn din specifika anledning här",
    Start: "Start",
    "Day Free Trial": "Dags gratis provperiod",
    "Please Select One Option": "Välj ett alternativ",
    "Plan cancelled successfully": "Planen avbröts",
    "7 days free trial, No Credit card required": "7 dagars gratis provperiod, inget kreditkort krävs",
    "Your remaining trial days are": "Dina återstående provdagar är",
    "You have used": "Du har använt",
    "days.": "dagar.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Inga provdagar kvar. Du har redan använt den 7-dagars gratis provperioden.",
    "Upgrade your plan now": "Uppgradera din plan nu",
    "Unlimited Slides": "Obegränsade bilder",
    "20+ Animation In & Out": "20+ Animation In & Out",
    "Live Chat Support": "Live Chat Support",
    "Priority, 24*7 Urgent setup and support": "Prioritet, 24*7 Brådskande installation och support",
    "Rich Text Editor": "Rich Text Editor",
    "One Slide(banner)": "One Slide (banner)",
    "Repeated Countdown timer": "Upprepad nedräkningstimer",
    "Fully Customisable": "Fullt anpassningsbar",
    "Background-image": "Bakgrundsbild",
    "Custom Css": "Anpassad CSS",
    "Enable Our App": "Aktivera vår app",
    "Book Onboarding Demo": "Boka Onboarding Demo",
    Next: "Nästa",
    Finish: "Avsluta",
    Prev: "Föreg",
    "App is not enable please click on the Enable App button to enable it.":
      "Appen är inte aktiverad, klicka på knappen Aktivera app för att aktivera den.",
    "This field is required": "Detta fält är obligatoriskt",
    disableButtonTooltip: "Du kan inte uppgradera månadsplanen eftersom du har en årsprenumeration!",
    "Choose plan": "Välj plan",
    "Purchase Plan": "Köpplan",
    Continue: "Fortsätta",
    "Image Optimization": "Bildoptimering",
    "AI Metatags": "AI-metataggar",
    "Grand Total": "Totalsumma",
    "Metatags Edit": "Metataggar Redigera",
    Products: "Produkter",
    "Upgrade plan": "Uppgradera plan",
    "Your product count is": "Ditt produktantal är",
    "so your suitable plan is": "så din lämpliga plan är",
    "Enjoy a": "Njut av en",
    "lifetime discount": "livstidsrabatt",
    discountBanner:
      " Omfamna en livstidsrabatt, säkra eviga besparingar och förbättra din upplevelse med våra premiumprodukter och tjänster.",
    "Images for Optimization every year after trial period end":
      "Bilder för optimering varje år efter provperiodens slut",
    "AI Meta Tags Credit for every year after trial period end":
      "AI Meta Tags Kredit för varje år efter provperiodens slut",
    "Images for Optimization every month after trial period end":
      "Bilder för optimering varje månad efter provperiodens slut",
    "AI Meta Tags Credit for every Month after trial period end":
      "AI Meta Tags kredit för varje månad efter provperiodens slut",
    "Optimize your google page speed": "Optimera hastigheten på din Google-sida",
    "50 Product Meta tags Optimize, Image alt": "50 Product Metataggar Optimera, Bild alt",
    "Product Meta tags Optimize, Image alt": "Produktmetataggar Optimera, Bild alt",
    "AI ImageAltText Credit for every year after trial period end":
      "AI ImageAltText-kredit för varje år efter provperiodens slut",
    "25 AI ImageAltText Credit": "25 AI ImageAltText Credit",
    "AI ImageAltText Credit for every Month after trial period end":
      "AI ImageAltText-kredit för varje månad efter provperiodens slut",
    "Contact Bar": "Kontakta Bar",
    "Add To Cart Bar": "Lägg till i varukorgen Bar",
    "Multiple Position": "Flera positioner",
    lowMsgStart:
      "Detta erbjudande är speciellt utformat för dig, eftersom du precis har startat din Shopify-butik",
    lowMsgMiddle: "Vår",
    lowMsgEnd: "rabatt är vårt sätt att stödja dig under dessa utmanande men spännande tider.",
    mediumMsgStart: "Det här erbjudandet är speciellt utformat för dig när du har startat din Shopify-butik",
    mediumMsgMiddle: "Vår",
    mediumMsgEnd: "rabatt är vårt sätt att stödja dig under dessa utmanande men spännande tider.",
    importantMsgStart: "Det här erbjudandet är speciellt utformat för dig när du har startat din Shopify-butik",
    importantMsgMiddle: "Vår",
    importantMsgEnd: "rabatt är vårt sätt att stödja dig under dessa utmanande men spännande tider.",
    veryImportantMsgStart:
      "Detta erbjudande är speciellt utformat för dig, eftersom du har öppnat din Shopify-butik",
    veryImportantMsgMiddle: "Du är en mycket viktig och mogen köpman för oss. Vår",
    veryImportantMsgEnd: "rabatten är för att visa hur mycket du betyder för oss.",
    generalMsg:
      "Vår Shopify-app är skräddarsydd för att möta behoven hos etablerade företag som ditt. Den är utformad för att hantera höga volymer och komplexa operationer sömlöst. ",
    lowTitleStart: "Särskilt stöd för nya entreprenörer:",
    lowTitleEnd: "Rabatt som du precis har börjat",
    mediumTitleStart: "Särskilt stöd för entreprenörer:",
    mediumTitleEnd: "Rabatt som du började",
    importantTitleStart: "Särskilt stöd för entreprenörer:",
    importantTitleEnd: "Rabatt som du började",
    veryImportantTitleStart: "Grattis till att du är",
    veryImportantTitleEnd: "i Shopify",
    month: "månad",
    "year and": "år och",
    ago: "sedan",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )":
      "Lägg till AI-kredit (1 AI-kredit/10¢) (10 AI-kredit/$1)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Lägg till bild altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )",
    "Monthly AI AltText Credit": "Månatlig AI AltText-kredit",
    "Yearly AI AltText Credit": "Årlig AI AltText Credit",
    "Purchase AI AltText Credit": "Köp AI AltText Credit",
    "ImageAltText Credit": "ImageAltText Credit",
    "Your credits are finished; please upgrade your plan.": "Dina poäng är klara; uppgradera din plan.",
    "Your credits are finished; you can buy more credits from here.":
      "Dina poäng är klara; du kan köpa fler krediter härifrån.",
    "This offer expire in": "Detta erbjudande löper ut om",
    "Hurry Up!": "Skynda dig!",
    Current: "Nuvarande",
    "Discount applied": "Rabatt tillämpas",
    "trial left": "rättegång kvar",
    "info banner":
      "När du klickar på knappen Skanna bild på hemsidan kommer vår app bara att skanna startsidans bild. För att optimera bilden klickar du på Optimera-knappen manuellt",
    "Optimize Images": "Optimera bilder",
    image: "bild",
    images: "bilder",
    Filename: "Filnamn",
    Images: "Bilder",
    Setting: "Miljö",
    "Saved(in %)": "Sparad (i %)",
    Action: "Handling",
    "Product Image": "Produktbild",
    "product image": "produktbild",
    gif: "gif",
    Homepage: "Hemsida",
    "Manage Announcement": "Hantera meddelande",
    "No Announcements Found": "Inga meddelanden hittades",
    Position: "Placera",
    "Campaign Title": "Kampanjens titel",
    Visible: "Synlig",
    Invisible: "Osynlig",
    Views: "Visningar",
    Clicks: "Klick",
    Submits: "Skickar in",
    "Above Add to cart Button": "Ovan Lägg till i varukorg Knapp",
    "Below Add to cart Button": "Nedan Lägg till i varukorg-knappen",
    Targeting: "Inriktning",
    "Rotating Animation Setting": "Roterande animationsinställning",
    "Marquee Animation Setting": "Marquee Animation Inställning",
    "Show to visitors coming form then specific website":
      "Visa för besökare kommande form sedan specifik webbplats",
    "Add your website URL": "Lägg till din webbadress",
    "Banner Display Start Time": "Starttid för bannervisning",
    "Banner Display End Time": "Sluttid för bannervisning",
    "Create Campaign": "Skapa kampanj",
    "Select Announcement Bar": "Välj meddelandefält",
    "Please select template.": "Välj mall.",
    Previous: "Tidigare",
    "Promotion bar": "Kampanjbar",
    "Add To Cart": "Lägg till i varukorgen",
    Embeded: "Inbäddad",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Varna kunder om kommande försäljningar, erbjudanden eller ställ in lagervarningar.",
    "Increase your order value by using or Free Shipping Bar.":
      "Öka ditt beställningsvärde genom att använda eller Free Shipping Bar.",
    "Conveniently add items to your cart with a single click!":
      "Lägg bekvämt till varor i din varukorg med ett enda klick!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Välj att prenumerera och få specialrabatter direkt till din inkorg",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Markera dina specialerbjudanden med en inbäddad stapel, som visas före och efter knappen Lägg till i kundvagn.",
    Select: "Välja",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Lägg till Hide Banner UTM-kod (t.ex. Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Inkludera Utm",
    "Exclude Utm": "Uteslut Utm",
    "Campaign Design": "Kampanjdesign",
    "Background Setting": "Bakgrundsinställning",
    "Target Setting": "Målinställning",
    Scheduling: "Schemaläggning",
    Rotating: "Roterande",
    Marquee: "Tält",
    "Repeat Timer Date": "Upprepa timerdatum",
    "Select Repeat Time": "Välj Upprepa tid",
    "Repeated Hours": "Upprepade timmar",
    Border: "Gräns",
    Bashed: "Bashed",
    "Multi Rotating": "Multi Roterande",
    Contacts: "Kontakter",
    Email: "E-post",
    "First Name": "Förnamn",
    "Last Name": "Efternamn",
    Phone: "Telefon",
    "You have unsaved changes": "Du har osparade ändringar",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Din kampanj har osparade ändringar. Ändringar går förlorade om du lämnar utan att spara.",
    "Leave widthout saving": "Lämna bredd utan att spara",
    "Save Changes": "Spara ändringar",
    Announcement: "Meddelande",
    Feedback: "Respons",
    "Recipe Instructions": "Receptinstruktioner",
    "Visit Help Center": "Besök hjälpcentret",
    "Schedule Meeting": "Schemalägg möte",
    "Setup guide": "Installationsguide",
    "Use this personalized guide to get your store up and running":
      "Använd den här personliga guiden för att få igång din butik",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "För att börja få åtgärder måste du aktivera vår app, Klicka på knappen tar dig till tilläggssidan, sedan behöver du bara klicka på spara där och komma tillbaka hit",
    "Enable our app": "Aktivera vår app",
    "Learn more": "Läs mer",
    "Skip it": "Skippa det",
    steps: "steg",
    minutes: "minuter",
    "Mark as done": "markera som klar",
    "Mark as not done": "Markera inte som klar",
    "You have completed all the steps": "Du har slutfört alla steg",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Aktivera och analysera din webbplats hastighet för att ranka din butik högre i sökresultaten.",
    "Google Page Speed Optimization": "Google Page Speed Optimization",
    "Activate Google Page Speed": "Aktivera Google Page Speed",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Aktivera Google Page Speed-verktyget för att bedöma din webbplats prestanda och identifiera möjligheter till hastighetsförbättring",
    "Enable Speed Analysis": "Aktivera hastighetsanalys",
    "Review Speed Analysis Report": "Granska hastighetsanalysrapport",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Granska den detaljerade hastighetsanalysrapporten för att förstå din webbplats aktuella hastighetsstatistik och peka ut områden för förbättringar.",
    "Go to Reports": "Gå till Rapporter",
    Hello: "Hallå",
    "Let's get your store ready for success": "Låt oss göra din butik redo för framgång",
    "Finish later": "Avsluta senare",
    "Continue onboarding": "Fortsätt ombordstigning",
    "Check image optimization features": "Kontrollera bildoptimeringsfunktionerna",
    "Explore Optimization Features": "Utforska optimeringsfunktioner",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Bekanta dig med utbudet av bildoptimeringsverktyg som finns tillgängliga. Se hur du kan förbättra sidladdningshastigheter och SEO genom att optimera bildstorlekar och format.",
    "Go to Image Optimization": "Gå till Bildoptimering",
    "Automate Your Image Workflow": "Automatisera ditt bildarbetsflöde",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Ställ in automatisering för att sömlöst optimera nya bilder när de laddas upp, vilket säkerställer konsekvent prestanda på hela din webbplats.",
    "Go to Automation": "Gå till Automation",
    "Execute a Bulk Optimization": "Utför en bulkoptimering",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Utför en massoptimering för att effektivt förbättra flera bilder samtidigt, vilket avsevärt kan öka din webbplats laddningstid.",
    "Go to bulk operations": "Gå till bulkverksamhet",
    "Broken Links Management": "Hantering av brutna länkar",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Automatisera upptäckt och reparation av trasiga länkar för att förbättra användarupplevelsen och SEO-rankingen.",
    "Review Detected Broken Links": "Granska upptäckta trasiga länkar",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Granska listan över trasiga länkar som identifieras automatiskt av vårt system för att förstå deras inverkan på din webbplats navigering.",
    "View Broken Links": "Visa brutna länkar",
    "Address Broken Links": "Adress brutna länkar",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Använd våra verktyg för att snabbt fixa eller omdirigera trasiga länkar, vilket förbättrar din webbplats integritet och användarnöjdhet.",
    "Resolve Broken Links": "Lös trasiga länkar",
    "Automate for Efficiency": "Automatisera för effektivitet",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Konfigurera automatisk korrigering för att ligga steget före eventuella framtida trasiga länkar, vilket säkerställer kontinuerlig webbplatshälsa.",
    "Enable Automation": "Aktivera automatisering",
    "Meta Tags Management": "Hantering av metataggar",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Optimera din webbplats synlighet och sökmotorrankning med vår användarvänliga Meta Tags-funktion.",
    "Explore Meta Tag Options": "Utforska metataggalternativ",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Bekanta dig med de olika redigerings- och automatiseringsalternativen för metataggar som finns tillgängliga för enskilda produkter och sidor.",
    "Explore Meta Tags": "Utforska metataggar",
    "Edit and Optimize": "Redigera och optimera",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Fördjupa dig i att redigera metatitlar, beskrivningar och bild-alt-texter för att förbättra din webbplatss SEO och användartillgänglighet.",
    "Start Editing": "Börja redigera",
    "Automate for Consistency": "Automatisera för konsekvens",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Ställ in automatiseringsregler för dina metataggar för att upprätthålla konsekvens och effektivitet på dina produktsidor.",
    "Set Automation": "Ställ in Automation",
    "Schema Markup": "Schema Markup",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "Använd Schema-uppmärkning för att förbättra ditt innehålls representation i sökresultat och locka fler klick.",
    "Learn About Schema Options": "Lär dig mer om schemaalternativ",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Bekanta dig med de olika typerna av Schema-uppmärkningar som finns tillgängliga, som produkt, lokala företag, vanliga frågor och mer, för att förstå fördelarna med dem.",
    "Explore Schema Types": "Utforska schematyper",
    "Activate Key Schemas": "Aktivera nyckelscheman",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "Välj och aktivera viktiga scheman för din webbplats, som Produktschema för e-handel eller Lokalt företagsschema för fysiska butiker.",
    "Go to Schemas": "Gå till Schema",
    "Customize Schema Details": "Anpassa schemadetaljer",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "Anpassa inställningarna för varje schematyp för att korrekt representera ditt företag eller dina produkter i sökresultaten.",
    "Test and Validate Schemas": "Testa och validera scheman",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Testa dina scheman med hjälp av verktyg som Googles testverktyg för strukturerade data för att säkerställa att de är korrekt implementerade.",
    "Test Schemas": "Testscheman",
    "Add Breadcrumbs": "Tillsätt ströbröd",
    "Add Breadcrumbs to your store": "Lägg till brödsmulor i din butik",
    "To get better user experience you need to add breadcrumbs to your store.":
      "För att få en bättre användarupplevelse måste du lägga till brödsmulor i din butik.",
    "How to add breadcrumbs": "Hur man lägger till ströbröd",
    "Understand how to add and configure breadcrumbs in your store.":
      "Förstå hur du lägger till och konfigurerar brödsmulor i din butik.",
    "Google search console": "Google sökkonsol",
    "Connect google search console to sync it with our app.":
      "Anslut google sökkonsol för att synkronisera den med vår app.",
    "How to connect GSC.": "Hur man ansluter GSC.",
    "Understand how to connect and use google search console in our app.":
      "Förstå hur du ansluter och använder Google Search Console i vår app.",
    "Go to GSC": "Gå till GSC",
    "Go to Breadcrumbs Design": "Gå till Breadcrumbs Design",
    "Start Onboarding": "Börja onboarding",
    "Go to Homepage": "Gå till hemsidan",
    "Go to Onboarding": "Gå till Onboarding",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      'Utforska vår användarvänliga appguide utformad för att öka din förståelse. Klicka på "Starta onboarding" för att börja, så kan du komma till hemsidan igen när som helst.',
    "Please enable our app extension.": "Vänligen aktivera vårt apptillägg.",
    "Generate Meta tags": "Generera metataggar",
    "Test description a litle bit longer that title": "Testbeskrivningen är lite längre än titeln",
    "Suggested for you": "Föreslog för dig",
    "Enable Google page speed": "Aktivera Google sidhastighet",
    "Connect GSC": "Anslut GSC",
    "Enable Image Optimize Automation": "Aktivera Image Optimize Automation",
    "Automate Meta tags": "Automatisera metataggar",
    "Automate Broken Links": "Automatisera brutna länkar",
    "Enhance SEO with automatically generated meta tags.": "Förbättra SEO med automatiskt genererade metataggar.",
    "Improve website performance by optimizing images.":
      "Förbättra webbplatsens prestanda genom att optimera bilder.",
    "Boost website speed by enabling Google Page Speed.":
      "Öka webbplatsens hastighet genom att aktivera Google Page Speed.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Förbättra söksynlighet genom att ansluta till Google Search Console.",
    "Streamline image optimization with automated processes.":
      "Effektivisera bildoptimering med automatiserade processer.",
    "Improve SEO by automating the generation of meta tags.":
      "Förbättra SEO genom att automatisera genereringen av metataggar.",
    "Improve UX with automated detect and handle, broken links.":
      "Förbättra UX med automatisk upptäcka och hantera trasiga länkar.",
    "Learn About Add Announcement": "Läs mer om Lägg till meddelande",
    "Skip And Add Announcement": "Hoppa över och lägg till meddelande",
    "Learn more about": "Lära sig mer om",
    "Add Announcement": "Lägg till meddelande",
    "Announcement Bar": "Meddelandefält",
    "Rate us!": "Gradera oss!",
    "How would you Love this app?": "Hur skulle du älska den här appen?",
    "Enter Your Feedback Here": "Ange din feedback här",
    "Leave Us a Review !!": "Lämna oss en recension!!",
    "If you like our app features then please leave us a review !!":
      "Om du gillar våra appfunktioner, vänligen lämna oss en recension !!",
    "If you like our free features then please leave us a review !!":
      "Om du gillar våra gratisfunktioner, vänligen lämna oss en recension !!",
    "Update Successfully": "Uppdatering framgångsrikt",
    "Uninstall App": "Avinstallera appen",
    "Contact Our Support": "Kontakta vår support",
    "Leave a message": "Lämna ett meddelande",
    "Please Choose a UnInstallation Reason": "Välj en orsak till avinstallation",
    "Are you facing any issues understanding the features of our app?":
      "Står du inför några problem med att förstå funktionerna i vår app?",
    "Please Choose at least one reason": "Välj minst en anledning",
    "Thank You For Reaching Out": "Tack för att du tog kontakt",
    "Contact Support": "Kontakta supporten",
    "Get Help from Our Support Team": "Få hjälp av vårt supportteam",
    "Select a reason": "Välj en anledning",
    "Not getting how to use or setup": "Förstår inte hur man använder eller ställer in",
    "Poor customer support": "Dålig kundsupport",
    "Performance issues": "Prestandaproblem",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Vårt supportteam är för närvarande inte tillgängligt på helger och kommer att vara tillgängligt på vardagar enligt din tidszon från kl ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " eftersom vi verkar från Indien. Du kan fortfarande lämna ett meddelande. Vänligen förvänta dig en viss försening i vårt svar. Tack för ditt tålamod.",
    "Our support team is partially available according to your time zone from ":
      "Vårt supportteam är delvis tillgängligt beroende på din tidszon från ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " eftersom vi verkar från Indien. Svar kan ta 30 minuter till en timme under denna tid. Lämna ett meddelande så svarar vi så snart som möjligt. Tack för ditt tålamod.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Vårt supportteam är för närvarande inte tillgängligt och kommer att vara tillgängligt enligt din tidszon från kl ",
    to: "till",
    "Did not meet my expectations": "Uppfyllde inte mina förväntningar",
    "Feature Limitations": "Funktionsbegränsningar",
    "Banner doesn't set in my app": "Banner sätts inte i min app",
    "Banner is not show properly": "Banner visas inte korrekt",
    "Confusing Set Multi Position and Multi Animation": "Förvirrande Set Multi Position och Multi Animation",
    "Sync Profile": "Synkronisera profil",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
