import modifyData from "../Language/tr.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "Etkinleştirilmiş",
    Disabled: "Engelli",
    "Embed is currently disabled": "Yerleştirme şu anda devre dışı",
    "Enable App": "Uygulamayı Etkinleştir",
    "1. Click on Enable App.": "1. Uygulamayı Etkinleştir'e tıklayın.",
    "Well done!! you have successfully enable our app.": "Tebrikler!! Uygulamamızı başarıyla etkinleştirdiniz.",
    "2. Enable": "2. Etkinleştir",
    "App Embed as shown in image and save setting.":
      "Uygulamayı resimde gösterildiği gibi yerleştirin ve ayarı kaydedin.",
    "Multi Announcement Bar": "Çoklu Anons Çubuğu",
    "Click on the Enable Now button to enable it.": "Etkinleştirmek için Şimdi Etkinleştir düğmesine tıklayın.",
    "Enable Announcement Bar to get started": "Başlamak için Duyuru Çubuğunu etkinleştirin",
    "Enable Now": "Şuan etkin",
    "Sync Status": "Senkronizasyon Durumu",
    Done: "Tamamlamak",
    No: "HAYIR",
    Found: "Kurmak",
    Add: "Eklemek",
    Search: "Aramak",
    Showing: "Gösterilen",
    of: "ile ilgili",
    "results, at most": "sonuçlar, en fazla",
    "per page": "Sayfa başına",
    "Oops! Something went wrong.": "Hata! Bir şeyler yanlış gitti.",
    "Let's try that again, please refresh the page.": "Tekrar deneyelim, lütfen sayfayı yenileyin.",
    "If you're still stuck, contact us by chat support or":
      "Hala takılıp kalırsanız sohbet desteği aracılığıyla bizimle iletişime geçin veya",
    "support@webrexstudio.com": "destek@webrexstudio.com",
    "so we can help!": "böylece yardımcı olabiliriz!",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "Yüksek önceliğe veya en çok ilgilendiğinize ayarlamak istediğiniz 3 özellikten herhangi birini seçin",
    "Add ": "Eklemek ",
    "These is premium feature": "Bunlar premium özelliktir",
    "Go to pricing": "Fiyatlandırmaya git",
    Save: "Kaydetmek",
    Minimum: "Asgari",
    Maximum: "Maksimum",
    "images are required": "resimler gerekli",
    and: "Ve",
    "images are allowed": "görsellere izin veriliyor",
    Disconnect: "Bağlantıyı kes",
    "Sign In with Google": "Google ile giriş yap",
    "Oops! Something went wrong. Admin token is malformed":
      "Hata! Bir şeyler yanlış gitti. Yönetici jetonu hatalı biçimlendirilmiş",
    "If you're still stuck, contact": "Hala takılıp kaldıysanız iletişime geçin",
    Premium: "Ödül",
    Unlock: "Kilidini aç",
    "Unlock advanced features!": "Gelişmiş özelliklerin kilidini açın!",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex. Her hakkı saklıdır.",
    "Privacy Policy": "Gizlilik Politikası",
    "Terms of Service": "Kullanım Şartları",
    "Go to Shopify App": "Shopify Uygulamasına gidin",
    "Review Us": "Bizi İnceleyin",
    Cancel: "İptal etmek",
    "Review Popup Show": "Açılır Pencere Gösterisini İncele",
    "click on review us": "bizi inceleyin tıklayın",
    "Note: Feel free to leave a star rating without writing a review!":
      "Not: Yorum yazmadan yıldız derecelendirmesi bırakmaktan çekinmeyin!",
    Help: "Yardım",
    "Help Button Click": "Yardım Düğmesine Tıklayın",
    Confirm: "Onaylamak",
    On: "Açık",
    Off: "Kapalı",
    Price: "Fiyat",
    Settings: "Ayarlar",
    Animation: "Animasyon",
    "My Profile": "Benim profilim",
    "My Subscription": "Üyeliğim",
    "Store Name": "Dükkan adı",
    "Store URL": "Mağaza URL'si",
    "Email ID": "Email kimliği",
    "Phone Number": "Telefon numarası",
    Country: "Ülke",
    Currency: "Para birimi",
    "Subscription Name": "Abonelik Adı",
    "Select language": "Dil Seçin",
    "Announcement setting": "Duyuru ayarı",
    "Animation setting": "Animasyon ayarı",
    Selector: "Seçici",
    "Save Setting": "Ayarı Kaydet",
    "My Announcements": "Duyurularım",
    "Add bar": "Çubuk ekle",
    Number: "Sayı",
    Title: "Başlık",
    "Create At": "Oluşturma Tarihi",
    "Slide Activation": "Slayt Aktivasyonu",
    Status: "Durum",
    Actions: "Hareketler",
    "Save order": "Siparişi kaydet",
    "Reorder Slides": "Slaytları Yeniden Sırala",
    position: "konum",
    Top: "Tepe",
    "Sticky Top": "Yapışkan Üst",
    "Bottom Fix": "Alt Düzeltme",
    "Custom Position": "Özel Konum",
    "Custom Position *Add Class or id of Selected Element.":
      "Özel Konum *Seçili Öğenin Sınıfını veya kimliğini ekleyin.",
    "Bar Padding (px)": "Çubuk Dolgusu (px)",
    "Add Remove Button": "Ekle Kaldır Düğmesi",
    "Choose icon color": "Simge rengini seçin",
    "Custom css": "Özel css",
    fadeIn: "fadeIn",
    fadeInDown: "fadeInDown",
    fadeInDownBig: "fadeInDownBig",
    fadeInLeft: "fadeInLeft",
    fadeInLeftBig: "fadeInLeftBig",
    fadeInUp: "FadeInUp",
    bounceInDown: "sıçramaInDown",
    bounceInLeft: "sıçramaInLeft",
    bounceInUp: "sıçramaInUp",
    zoomIn: "Yakınlaştır",
    zoomInDown: "zoomInDown",
    zoomInLeft: "zoomInLeft",
    slideInLeft: "slaytInLeft",
    slideInUp: "slaytInUp",
    slideInDown: "slaytInDown",
    lightSpeedIn: "ışıkHızGirişi",
    rollIn: "rollIn",
    flash: "flaş",
    shake: "sallamak",
    flip: "çevir",
    flipInX: "flipInX",
    flipOutX: "flipOutX",
    fadeOut: "solma",
    fadeOutDown: "fadeOutDown",
    fadeOutDownBig: "fadeOutDownBig",
    fadeOutRight: "fadeOutRight",
    fadeOutRightBig: "fadeOutRightBig",
    fadeOutUp: "FadeOutUp",
    bounceOutDown: "sıçramaOutDown",
    bounceOutRight: "sıçramaOutRight",
    bounceOutUp: "sıçramaOutUp",
    zoomOut: "uzaklaştır",
    zoomOutDown: "yakınlaştırDışarıAşağı",
    zoomOutRight: "zoomOutRight",
    slideOutRight: "slaytOutRight",
    slideOutUp: "slaytOutUp",
    slideOutDown: "slaytOutDown",
    lightSpeedOut: "ışıkHızÇıkış",
    rollOut: "açarak yaymak",
    flipInY: "flipInY",
    "Text Animation": "Metin Animasyonu",
    "Animation In": "Animasyon Girişi",
    "Animation Out": "Animasyon Çıkışı",
    "Auto play time (time in MS)": "Otomatik oynatma süresi (MS'deki süre)",
    "Animation time (time in MS)": "Animasyon süresi (MS'deki süre)",
    "Auto play time (time in Second)": "Otomatik oynatma süresi (Saniye cinsinden süre)",
    "Background Color": "Arka plan rengi",
    "Space between slide(px)": "Slayt arasındaki boşluk (px)",
    visible: "görünür",
    invisible: "görünmez",
    "Promotional & Countdown Bar": "Promosyon ve Geri Sayım Çubuğu",
    "Free Shipping Bar": "Ücretsiz Kargo Barı",
    "Add Slide": "Slayt Ekle",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "ÜCRETSİZ plan için yalnızca 1 slayt görünür. Tüm slaytları etkinleştirmek için Premium Plana abone olun.",
    Pricing: "Fiyatlandırma",
    "No Animation Found": "Animasyon Bulunamadı",
    "No Preview, Add announcement Bar": "Önizleme Yok, Duyuru Ekle Çubuğu",
    "Update successfully": "Başarıyla güncelle",
    Enable: "Olanak vermek",
    Disable: "Devre dışı bırakmak",
    successfully: "başarıyla",
    "Delete successfully": "Başarıyla sil",
    "Copy successfully": "Başarıyla kopyalandı",
    "Reorder successfully": "Başarılı bir şekilde yeniden sıralayın",
    "Announcement Message": "Duyuru Mesajı",
    "Call to Action": "Eylem çağrısı",
    Timer: "Zamanlayıcı",
    Style: "Stil",
    "Background Type": "Arka Plan Türü",
    "Mobile Style": "Mobil Stil",
    "Schedule Display": "Program Ekranı",
    Update: "Güncelleme",
    "Change Font": "Yazı Tipini Değiştir",
    "Font Family": "Font ailesi",
    "Font Style": "Yazı stili",
    Normal: "Normal",
    Italic: "İtalik",
    Oblique: "Eğik",
    Unset: "Ayarlanmadı",
    "Font Weight": "Yazı Tipi Ağırlığı",
    Bold: "Gözü pek",
    "Message Font Size": "Mesaj Yazı Tipi Boyutu",
    "Message Text color": "Mesaj Metni rengi",
    Type: "Tip",
    None: "Hiçbiri",
    Button: "Düğme",
    "Entire clickable bar": "Tıklanabilir çubuğun tamamı",
    "Add a simple link": "Basit bir bağlantı ekleyin",
    "Add coupon placement": "Kupon yerleşimi ekle",
    "Linked Url": "Bağlantılı URL",
    "Background Hover Color": "Arka Plan Vurgu Rengi",
    "Text Hover Color": "Metnin Vurgu Rengi",
    "Button Text": "Düğme Metni",
    "Copied Text": "Kopyalanan Metin",
    "Open in the new tab": "Yeni sekmede aç",
    URL: "URL'si",
    "Font Size": "Yazı Boyutu",
    "Button Radius": "Düğme Yarıçapı",
    "Button color": "Düğme rengi",
    "Button Text color": "Düğme Metin rengi",
    "Button Hover Color": "Düğme Vurgu Rengi",
    "button Text HoverColor": "düğmesi Metin HoverColor",
    "Timer Setting": "Zamanlayıcı Ayarı",
    "Timer Type": "Zamanlayıcı Türü",
    Date: "Tarih",
    "Select Reapt Time": "Yeniden Uyum Süresini Seçin",
    "repeated Hours": "tekrarlanan Saatler",
    "Normal Timer": "Normal Zamanlayıcı",
    "Auto repeat timer": "Otomatik tekrarlama zamanlayıcısı",
    Minute: "Dakika",
    Hour: "Saat",
    Day: "Gün",
    "Remove Timer When Time End": "Zaman Bittiğinde Zamanlayıcıyı Kaldır",
    "Timer Separator": "Zamanlayıcı Ayırıcı",
    "Countdown Timer color": "Geri Sayım Sayacı rengi",
    "Timer Text Size": "Zamanlayıcı Metin Boyutu",
    "Timer Text Setting": "Zamanlayıcı Metin Ayarı",
    "Day Text": "Gün Metni",
    "Hour Text": "Saat Metni",
    "Minute Text": "Dakika Metni",
    "Second Text": "İkinci Metin",
    "Background Image": "Arka plan görüntüsü",
    "Gradient Background": "Gradyan Arka Planı",
    "Style & Color For Mobile": "Mobil Cihazlar İçin Stil ve Renk",
    "Timer Background": "Zamanlayıcı Arka Planı",
    "Timer Text Color": "Zamanlayıcı Metin Rengi",
    "Button Color": "Düğme rengi",
    "Button Text Color": "Düğme Metin Rengi",
    "Button Text Hover Color": "Düğme Metni Vurgu Rengi",
    "Button Text Size": "Düğme Metin Boyutu",
    "Always Display": "Her Zaman Göster",
    "Only Display Within The Following Period Of Time": "Yalnızca Takip Eden Süre İçerisinde Görüntülenir",
    "Start Time": "Başlangıç saati",
    "End Time": "Bitiş zamanı",
    "Advance Setting": "Gelişmiş Ayar",
    "Country Filter": "Ülke Filtresi",
    Visibility: "Görünürlük",
    "Desktop and Mobile": "Masaüstü ve Mobil",
    "Only Desktop": "Yalnızca Masaüstü",
    "Only Mobile": "Yalnızca Mobil",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "KULLANICI KAYNAĞI HEDEFLEME (Aşağıdaki UTM Kodunu İçeren Bir Bağlantıdan Gelen Ziyaretçiler, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Select Page": "Sayfa Seçin",
    Include: "Katmak",
    Exclude: "Hariç tutmak",
    "Currency Configuration": "Para Birimi Yapılandırması",
    Message: "İleti",
    "Currency Symbol": "Para Birimi Sembolü",
    "Currency Position": "Döviz Pozisyonu",
    Before: "Önce",
    After: "Sonrasında",
    "money Class": "para Sınıfı",
    "Initial Message": "İlk Mesaj",
    "Shipping Goal": "Nakliye Hedefi",
    "Progress Message": "İlerleme Mesajı",
    "Progress goal": "İlerleme hedefi",
    "Goal Message": "Hedef Mesajı",
    "Shipping Price Color": "Nakliye Fiyatı Renk",
    "Shipping Price Size": "Nakliye Fiyatı Boyutu",
    "Shipping Font Weight": "Nakliye Yazı Tipi Ağırlığı",
    "* When user first time visit": "* Kullanıcı ilk kez ziyaret ettiğinde",
    "* When user add item to the cart e.g": "* Kullanıcı sepete ürün eklediğinde, örneğin:",
    "* When cart value is greater than": "* Sepet değeri şundan büyük olduğunda:",
    "Show On Selected Countries": "Seçilen Ülkelerde Göster",
    "Show On Selected Pages": "Seçilen Sayfalarda Göster",
    All: "Tüm",
    Home: "Ev",
    Cart: "Araba",
    Collection: "Toplamak",
    Product: "Ürün",
    Custom: "Gelenek",
    Page: "Sayfa",
    Blog: "Blog",
    "Url is required": "URL gerekli",
    "Day Text is required": "Gün Metni gerekli",
    "Hour Text is required": "Saat Metni gerekli",
    "Minute Text is required": "Dakika Metni gerekli",
    "Second Text is required": "İkinci Metin gerekli",
    "Start Time is required": "Başlangıç Zamanı gerekli",
    "End Time is required": "Bitiş Zamanı gerekli",
    "Created successfully": "Başarıyla oluşturuldu",
    "United States": "Amerika Birleşik Devletleri",
    Canada: "Kanada",
    Australia: "Avustralya",
    "New Zealand": "Yeni Zelanda",
    Germany: "Almanya",
    India: "Hindistan",
    Afghanistan: "Afganistan",
    "land Islands": "kara Adaları",
    Albania: "Arnavutluk",
    Algeria: "Cezayir",
    "American Samoa": "Amerikan Samoası",
    AndorrA: "Andorra",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarktika",
    "Antigua and Barbuda": "Antigua ve Barbuda",
    Argentina: "Arjantin",
    Armenia: "Ermenistan",
    Aruba: "Aruba",
    Austria: "Avusturya",
    Azerbaijan: "Azerbaycan",
    Bahamas: "Bahamalar",
    Bahrain: "Bahreyn",
    Bangladesh: "Bangladeş",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belçika",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermuda",
    Bhutan: "Butan",
    Bolivia: "Bolivya",
    "Bosnia and Herzegovina": "Bosna Hersek",
    Botswana: "Botsvana",
    "Bouvet Island": "Bouvet Adası",
    Brazil: "Brezilya",
    "British Indian Ocean Territory": "Britanya Hint Okyanusu Bölgesi",
    "Brunei Darussalam": "Brunei Sultanlığı",
    Bulgaria: "Bulgaristan",
    "Burkina Faso": "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Kamboçya",
    Cameroon: "Kamerun",
    "Cape Verde": "Yeşil Burun Adaları",
    "Cayman Islands": "Cayman Adaları",
    "Central African Republic": "Orta Afrika Cumhuriyeti",
    Chad: "Çad",
    Chile: "Şili",
    China: "Çin",
    "Christmas Island": "Noel Adası",
    "Cocos (Keeling) Islands": "Cocos (Keeling) Adaları",
    Colombia: "Kolombiya",
    Comoros: "Komorlar",
    Congo: "Kongo",
    "Congo, The Democratic Republic of the": "Kongo, Demokratik Cumhuriyeti",
    "Cook Islands": "Cook Adaları",
    "Costa Rica": "Kosta Rika",
    "Cote D'Ivoire": "Fildişi Sahili",
    Croatia: "Hırvatistan",
    Cuba: "Küba",
    Cyprus: "Kıbrıs",
    "Czech Republic": "Çek Cumhuriyeti",
    Denmark: "Danimarka",
    Djibouti: "Cibuti",
    Dominica: "Dominika",
    "Dominican Republic": "Dominik Cumhuriyeti",
    Ecuador: "Ekvador",
    Egypt: "Mısır",
    "El Salvador": "El Salvador",
    "Equatorial Guinea": "Ekvator Ginesi",
    Eritrea: "Eritre",
    Estonia: "Estonya",
    Ethiopia: "Etiyopya",
    "Falkland Islands (Malvinas)": "Falkland Adaları (Malvinas)",
    "Faroe Islands": "Faroe Adaları",
    Fiji: "Fiji",
    Finland: "Finlandiya",
    France: "Fransa",
    "French Guiana": "Fransız Guyanası",
    "French Polynesia": "Fransız Polinezyası",
    "French Southern Territories": "Fransız Güney Toprakları",
    Gabon: "Gabon",
    Gambia: "Gambiya",
    Georgia: "Gürcistan",
    Ghana: "Gana",
    Gibraltar: "Cebelitarık",
    Greece: "Yunanistan",
    Greenland: "Grönland",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Gine",
    "Guinea-Bissau": "Gine-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    "Heard Island and Mcdonald Islands": "Heard Adası ve Mcdonald Adaları",
    "Holy See (Vatican City State)": "Vatikan (Vatikan Şehir Devleti)",
    Honduras: "Honduras",
    "Hong Kong": "Hong Kong",
    Hungary: "Macaristan",
    Iceland: "İzlanda",
    Indonesia: "Endonezya",
    "Iran, Islamic Republic Of": "İran İslam Cumhuriyeti",
    Iraq: "Irak",
    Ireland: "İrlanda",
    "Isle of Man": "Man Adası",
    Israel: "İsrail",
    Italy: "İtalya",
    Jamaica: "Jamaika",
    Japan: "Japonya",
    Jersey: "Jersey",
    Jordan: "Ürdün",
    Kazakhstan: "Kazakistan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    "Korea, Democratic People'S Republic of": "Kore Demokratik Halk Cumhuriyeti",
    "Korea, Republic of": "Kore Cumhuriyeti",
    Kuwait: "Kuveyt",
    Kyrgyzstan: "Kırgızistan",
    "Lao People'S Democratic Republic": "Lao Demokratik Halk Cumhuriyeti",
    Latvia: "Letonya",
    Lebanon: "Lübnan",
    Lesotho: "Lesoto",
    Liberia: "Liberya",
    "Libyan Arab Jamahiriya": "Libya Arap Cemahiriyesi",
    Liechtenstein: "Lihtenştayn",
    Lithuania: "Litvanya",
    Luxembourg: "Lüksemburg",
    Macao: "Makao",
    "Macedonia, The Former Yugoslav Republic of": "Makedonya, Eski Yugoslav Cumhuriyeti",
    Madagascar: "Madagaskar",
    Malawi: "Malawi",
    Malaysia: "Malezya",
    Maldives: "Maldivler",
    Mali: "Mali",
    Malta: "Malta",
    "Marshall Islands": "Marşal Adaları",
    Martinique: "Martinik",
    Mauritania: "Moritanya",
    Mauritius: "Mauritius",
    Mayotte: "Mayotte",
    Mexico: "Meksika",
    "Micronesia, Federated States of": "Mikronezya, Federal Devletler",
    "Moldova, Republic of": "Moldova Cumhuriyeti",
    Monaco: "Monako",
    Mongolia: "Moğolistan",
    Montenegro: "Karadağ",
    Montserrat: "Montserrat",
    Morocco: "Fas",
    Mozambique: "Mozambik",
    Myanmar: "Myanmar",
    Namibia: "Namibya",
    Nauru: "Nauru'lu",
    Nepal: "Nepal",
    Netherlands: "Hollanda",
    "Netherlands Antilles": "Hollanda Antilleri",
    "New Caledonia": "Yeni Kaledonya",
    Nicaragua: "Nikaragua",
    Niger: "Nijer",
    Nigeria: "Nijerya",
    Niue: "Niue",
    "Norfolk Island": "Norfolk Adası",
    "Northern Mariana Islands": "Kuzey Mariana Adaları",
    Norway: "Norveç",
    Oman: "Umman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    "Palestinian Territory, Occupied": "Filistin Arazisi, İşgal altında",
    Panama: "Panama",
    "Papua New Guinea": "Papua Yeni Gine",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Filipinler",
    Pitcairn: "Pitcairn",
    Poland: "Polonya",
    Portugal: "Portekiz",
    "Puerto Rico": "Porto Riko",
    Qatar: "Katar",
    Reunion: "Yeniden Birleşme",
    Romania: "Romanya",
    "Russian Federation": "Rusya Federasyonu",
    RWANDA: "RUANDA",
    "Saint Helena": "Aziz Helena",
    "Saint Kitts and Nevis": "Saint Kitts ve Nevis",
    "Saint Lucia": "Aziz Lucia",
    "Saint Pierre and Miquelon": "Saint Pierre ve Miquelon",
    "Saint Vincent and the Grenadines": "Saint Vincent ve Grenadinler",
    Samoa: "Samoa",
    "San Marino": "San Marino",
    "Sao Tome and Principe": "Sao Tome ve Principe",
    "Saudi Arabia": "Suudi Arabistan",
    Senegal: "Senegal",
    Serbia: "Sırbistan",
    Seychelles: "Seyşeller",
    "Sierra Leone": "Sierra Leone",
    Singapore: "Singapur",
    Slovakia: "Slovakya",
    Slovenia: "Slovenya",
    "Solomon Islands": "Solomon Adaları",
    Somalia: "Somali",
    "South Africa": "Güney Afrika",
    "South Georgia and the South Sandwich Islands": "Güney Georgia ve Güney Sandwich Adaları",
    Spain: "ispanya",
    "Sri Lanka": "Sri Lanka",
    Sudan: "Sudan",
    Surilabel: "Surilabel",
    "Svalbard and Jan Mayen": "Svalbard ve Jan Mayen",
    Swaziland: "Svaziland",
    Sweden: "İsveç",
    Switzerland: "İsviçre",
    "Syrian Arab Republic": "Suriye Arap Cumhuriyeti",
    "Taiwan, Province of China": "Tayvan, Çin'in bölgesi",
    Tajikistan: "Tacikistan",
    "Tanzania, United Republic of": "Tanzanya, Birleşik Cumhuriyeti",
    Thailand: "Tayland",
    "Timor-Leste": "Doğu Timor",
    Togo: "Gitmek",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    "Triidd and Tobago": "Triidd ve Tobago",
    Tunisia: "Tunus",
    Turkey: "Türkiye",
    Turkmenistan: "Türkmenistan",
    "Turks and Caicos Islands": "Turks ve Caicos Adaları",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukrayna",
    "United Arab Emirates": "Birleşik Arap Emirlikleri",
    "United Kingdom": "Birleşik Krallık",
    "United States Minor Outlying Islands": "Amerika Birleşik Devletleri Küçük Dış Adaları",
    Uruguay: "Uruguay",
    Uzbekistan: "Özbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    "Viet Nam": "Vietnam",
    "Virgin Islands, British": "Virgin Adaları, Britanya",
    "Virgin Islands, U.S.": "Virgin Adaları, ABD",
    "Wallis and Futuna": "Wallis ve Futuna",
    "Western Sahara": "Batı Sahra",
    Yemen: "Yemen",
    Zambia: "Zambiya",
    Zimbabwe: "Zimbabve",
    "Unlock All Schema with our Premium Plan": "Premium Planımızla Tüm Şemaların Kilidini Açın",
    "Billed Monthly": "Aylık Faturalandırılır",
    "Billed Annually": "Yıllık Faturalandırılır",
    "Save 30%": "%30 tasarruf edin",
    Premium100Title:
      "İlk kullanıcı olarak, tüm premium özelliklerimizden hiçbir ücret ödemeden yararlanacağınızın garantisini veriyoruz. Tüm premium özelliklerimize hiçbir ücret ödemeden özgürce erişebileceğiniz için fiyatlandırma sayfası konusunda endişelenmenize gerek yok. Hizmetimizden yararlanmaya devam etmek için lütfen uygulamamızı kaldırmayın.",
    Premium100ReviewLine:
      " Uygulamamızı beğendiyseniz lütfen bize inceleme bırakın. Bu, yeni özellikler geliştirmeye motive olmamıza yardımcı olur.",
    "Check Our Current Pricing": "Güncel Fiyatlarımızı Kontrol Edin",
    "Leave Review": "Görüş bildirin",
    "We're sorry to see you go!": "Gittiğinizi gördüğümüz için üzgünüz!",
    "Cancel Plan": "Planı İptal Et",
    "Sync Plan": "Senkronizasyon Planı",
    "Disccount applied": "İndirim uygulandı",
    Apply: "Uygula",
    "Your code(s)": "Kod(lar)ınız",
    "and discount have been applied successfully": "ve indirim başarıyla uygulandı",
    "Your entered promocode is not correct, Enter a valid code":
      "Girdiğiniz promosyon kodu doğru değil, Geçerli bir kod girin",
    "days trial left": "deneme süresi kaldı",
    Upgrade: "Güncelleme",
    "days free trial, No Credit card required": "gün ücretsiz deneme, Kredi kartı gerekmez",
    Month: "Ay",
    Year: "Yıl",
    Unlimited: "Sınırsız",
    "Enter Promocode": "Promosyon kodunu girin",
    "Please Choose a Cancellation Reason": "Lütfen İptal Nedenini Seçiniz",
    "No Longer Needed?": "Artık İhtiyaç Yok mu?",
    "Didn't Meet Expectations": "Beklentileri Karşılayamadım",
    "Cost Concerns": "Maliyet Kaygıları",
    "Technical Issues": "Teknik sorunlar",
    "Found an Alternative": "Bir Alternatif Buldum",
    Complexity: "Karmaşıklık",
    "Lack of Features": "Özelliklerin Eksikliği",
    "Poor Customer Support": "Yetersiz Müşteri Desteği",
    "Business Closure or Change": "İşletme Kapanması veya Değişikliği",
    "Temporary Pause": "Geçici Duraklatma",
    "Performance Issues": "Performans sorunları",
    Other: "Diğer",
    "Mention Your Specific Reason Here": "Özel Nedeninizi Burada Belirtin",
    Start: "Başlangıç",
    "Day Free Trial": "Günlük Ücretsiz Deneme",
    "Please Select One Option": "Lütfen bir seçeneği seçin",
    "Plan cancelled successfully": "Plan başarıyla iptal edildi",
    "7 days free trial, No Credit card required": "7 günlük ücretsiz deneme, Kredi kartı gerekmez",
    "Your remaining trial days are": "Kalan deneme günleriniz",
    "You have used": "kullandın",
    "days.": "günler.",
    "No trial days remaining. You have already used the 7-day free trial.":
      "Deneme günü kalmadı. 7 günlük ücretsiz deneme sürümünü zaten kullandınız.",
    "Upgrade your plan now": "Planınızı şimdi yükseltin",
    "Unlimited Slides": "Sınırsız Slayt",
    "20+ Animation In & Out": "20+ Animasyon Giriş ve Çıkış",
    "Live Chat Support": "Canlı Sohbet Desteği",
    "Priority, 24*7 Urgent setup and support": "Öncelik, 7/24 Acil kurulum ve destek",
    "Rich Text Editor": "Zengin metin editörü",
    "One Slide(banner)": "Bir Slayt(afiş)",
    "Repeated Countdown timer": "Tekrarlanan Geri Sayım sayacı",
    "Fully Customisable": "Tamamen Özelleştirilebilir",
    "Background-image": "Arka plan görüntüsü",
    "Custom Css": "Özel Css",
    "Enable Our App": "Uygulamamızı Etkinleştirin",
    "Book Onboarding Demo": "Kitap İlk Katılım Demosu",
    Next: "Sonraki",
    Finish: "Sona ermek",
    Prev: "Önceki",
    "App is not enable please click on the Enable App button to enable it.":
      "Uygulama etkin değil, lütfen etkinleştirmek için Uygulamayı Etkinleştir düğmesine tıklayın.",
    "This field is required": "Bu alan gereklidir",
    disableButtonTooltip: "Yıllık planda olduğunuz için aylık planı yükseltemezsiniz!",
    "Choose plan": "Planı seçin",
    "Purchase Plan": "Satın Alma Planı",
    Continue: "Devam etmek",
    "Image Optimization": "Görüntü Optimizasyonu",
    "AI Metatags": "Yapay Zeka Meta Etiketleri",
    "Grand Total": "Genel Toplam",
    "Metatags Edit": "Meta Etiketleri Düzenle",
    Products: "Ürünler",
    "Upgrade plan": "Yükseltme planı",
    "Your product count is": "Ürün sayınız:",
    "so your suitable plan is": "yani uygun planınız",
    "Enjoy a": "Tadını çıkarın",
    "lifetime discount": "ömür boyu indirim",
    discountBanner:
      " Ömür boyu indirimden yararlanın, sürekli tasarruf sağlayın ve birinci sınıf ürün ve hizmetlerimizle deneyiminizi geliştirin.",
    "Images for Optimization every year after trial period end":
      "Deneme süresi sona erdikten sonra her yıl Optimizasyona yönelik görseller",
    "AI Meta Tags Credit for every year after trial period end":
      "Deneme süresi sona erdikten sonra her yıl için AI Meta Etiketler Kredisi",
    "Images for Optimization every month after trial period end":
      "Deneme süresi bittikten sonra her ay Optimizasyona yönelik görseller",
    "AI Meta Tags Credit for every Month after trial period end":
      "Deneme süresi sona erdikten sonra her Ay için AI Meta Etiketler Kredisi",
    "Optimize your google page speed": "Google sayfa hızınızı optimize edin",
    "50 Product Meta tags Optimize, Image alt": "50 Ürün Meta etiketi Optimize Etme, Resim alt",
    "Product Meta tags Optimize, Image alt": "Ürün Meta etiketleri Optimize Etme, Resim alt",
    "AI ImageAltText Credit for every year after trial period end":
      "Deneme süresi sona erdikten sonraki her yıl için AI ImageAltText Kredisi",
    "25 AI ImageAltText Credit": "25 AI ImageAltText Kredisi",
    "AI ImageAltText Credit for every Month after trial period end":
      "Deneme süresi sona erdikten sonra her Ay için AI ImageAltText Kredisi",
    "Contact Bar": "İletişim Çubuğu",
    "Add To Cart Bar": "Sepete Ekle Çubuğu",
    "Multiple Position": "Çoklu Pozisyon",
    lowMsgStart: "Shopify mağazanızı yeni başlattığınız için bu teklif sizin için özel olarak tasarlanmıştır",
    lowMsgMiddle: "Bizim",
    lowMsgEnd: "İndirim, bu zorlu ama heyecan verici zamanlarda sizi destekleme yöntemimizdir.",
    mediumMsgStart: "Shopify mağazanızı başlattığınız için bu teklif sizin için özel olarak tasarlanmıştır",
    mediumMsgMiddle: "Bizim",
    mediumMsgEnd: "İndirim, bu zorlu ama heyecan verici zamanlarda sizi destekleme yöntemimizdir.",
    importantMsgStart: "Shopify mağazanızı başlattığınız için bu teklif sizin için özel olarak tasarlanmıştır",
    importantMsgMiddle: "Bizim",
    importantMsgEnd: "İndirim, bu zorlu ama heyecan verici zamanlarda sizi destekleme yöntemimizdir.",
    veryImportantMsgStart: "Shopify mağazanızı açtığınız için bu teklif sizin için özel olarak tasarlanmıştır",
    veryImportantMsgMiddle: "Siz bizim için çok önemli ve olgun bir tüccarsınız. Bizim",
    veryImportantMsgEnd: "indirim bizim için ne kadar önemli olduğunuzu göstermektir.",
    generalMsg:
      "Shopify uygulamamız sizinki gibi köklü işletmelerin ihtiyaçlarını karşılayacak şekilde özel olarak tasarlanmıştır. Yüksek hacimli ve karmaşık işlemleri sorunsuz bir şekilde gerçekleştirecek şekilde tasarlanmıştır. ",
    lowTitleStart: "Yeni Girişimcilere Özel Destek:",
    lowTitleEnd: "Yeni başladığınız için indirim",
    mediumTitleStart: "Girişimcilere Özel Destek:",
    mediumTitleEnd: "Başladığınız gibi indirim",
    importantTitleStart: "Girişimcilere Özel Destek:",
    importantTitleEnd: "Başladığınız gibi indirim",
    veryImportantTitleStart: "Olduğunuz için tebrikler",
    veryImportantTitleEnd: "Shopify'da",
    month: "ay",
    "year and": "yıl ve",
    ago: "evvel",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )": "AI Kredisi Ekle (1 AI Kredisi/10¢) (10 AI Kredisi/1$)",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "Resim ekle altText AI Kredisi (1 AI Kredisi/4¢) (25 AI Kredisi/1$)",
    "Monthly AI AltText Credit": "Aylık AI AltText Kredisi",
    "Yearly AI AltText Credit": "Yıllık AI AltText Kredisi",
    "Purchase AI AltText Credit": "AI AltText Kredisi satın alın",
    "ImageAltText Credit": "ImageAltText Kredisi",
    "Your credits are finished; please upgrade your plan.": "Kredileriniz bitti; lütfen planınızı yükseltin.",
    "Your credits are finished; you can buy more credits from here.":
      "Kredileriniz bitti; buradan daha fazla kredi satın alabilirsiniz.",
    "This offer expire in": "Bu teklifin süresi şu tarihte dolacaktır:",
    "Hurry Up!": "Acele etmek!",
    Current: "Akım",
    "Discount applied": "İndirim uygulandı",
    "trial left": "deneme kaldı",
    "info banner":
      "Ana Sayfa Görüntüsünü Tara düğmesini tıkladığınızda, uygulamamız yalnızca ana sayfa görüntüsünü tarayacaktır. Bu görüntüyü optimize etmek için lütfen Optimize Et düğmesini manuel olarak tıklayın.",
    "Optimize Images": "Görselleri Optimize Edin",
    image: "resim",
    images: "Görüntüler",
    Filename: "Dosya adı",
    Images: "Görüntüler",
    Setting: "Ayar",
    "Saved(in %)": "Kaydedildi (% olarak)",
    Action: "Aksiyon",
    "Product Image": "Ürün resmi",
    "product image": "Ürün resmi",
    gif: "gif",
    Homepage: "Ana sayfa",
    "Manage Announcement": "Duyuruları Yönet",
    "No Announcements Found": "Hiçbir Duyuru Bulunamadı",
    Position: "Konum",
    "Campaign Title": "Kampanya Başlığı",
    Visible: "Görünür",
    Invisible: "Görünmez",
    Views: "Görüntüleme",
    Clicks: "Tıklamalar",
    Submits: "Gönderilenler",
    "Above Add to cart Button": "Yukarıda Sepete Ekle Düğmesi",
    "Below Add to cart Button": "Aşağıda Sepete Ekle Düğmesi",
    Targeting: "Hedefleme",
    "Rotating Animation Setting": "Dönen Animasyon Ayarı",
    "Marquee Animation Setting": "Seçim Çerçevesi Animasyon Ayarı",
    "Show to visitors coming form then specific website":
      "Daha sonra belirli bir web sitesinden gelen ziyaretçilere gösterin",
    "Add your website URL": "Web sitenizin URL'sini ekleyin",
    "Banner Display Start Time": "Banner Gösterim Başlangıç Saati",
    "Banner Display End Time": "Banner Gösterim Bitiş Saati",
    "Create Campaign": "Kampanya Oluştur",
    "Select Announcement Bar": "Duyuru Çubuğunu Seçin",
    "Please select template.": "Lütfen şablonu seçin.",
    Previous: "Öncesi",
    "Promotion bar": "Promosyon çubuğu",
    "Add To Cart": "Sepete ekle",
    Embeded: "Gömülü",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "Müşterilerinizi yaklaşan satışlar, teklifler hakkında uyarın veya envanter uyarıları ayarlayın.",
    "Increase your order value by using or Free Shipping Bar.":
      "Ücretsiz Kargo Bar'ı kullanarak siparişinizin değerini artırın.",
    "Conveniently add items to your cart with a single click!": "Tek tıkla sepetinize ürün ekleyin!",
    "Select to subscribe and receive special discounts directly to your inbox":
      "Abone olmayı seçin ve doğrudan gelen kutunuza özel indirimler alın",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "Sepete Ekle butonundan önce ve sonra görüntülenen gömülü bir çubukla özel tekliflerinizi vurgulayın.",
    Select: "Seçme",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "Gizle Banner UTM kodunu ekleyin (Örn.Ref=Facebook, Ref=Web, Utm_source=Google...)",
    "Include Utm": "Utm'yi dahil et",
    "Exclude Utm": "Utm'yi hariç tut",
    "Campaign Design": "Kampanya Tasarımı",
    "Background Setting": "Arka Plan Ayarı",
    "Target Setting": "Hedef Belirleme",
    Scheduling: "Zamanlama",
    Rotating: "Döndürme",
    Marquee: "Çadır",
    "Repeat Timer Date": "Tekrar Zamanlayıcı Tarihi",
    "Select Repeat Time": "Tekrar Zamanını Seçin",
    "Repeated Hours": "Tekrarlanan Saatler",
    Border: "Sınır",
    Bashed: "Vurulmuş",
    "Multi Rotating": "Çoklu Döndürme",
    Contacts: "Kişiler",
    Email: "E-posta",
    "First Name": "İlk adı",
    "Last Name": "Soy isim",
    Phone: "Telefon",
    "You have unsaved changes": "kaydedilmemiş değişiklikleriniz mevcut",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "Kampanyanızda kaydedilmemiş değişiklikler var. Kaydetmeden ayrılırsanız değişiklikler kaybolacaktır.",
    "Leave widthout saving": "Tasarrufun genişliğini bırakın",
    "Save Changes": "Değişiklikleri Kaydet",
    Announcement: "Duyuru",
    Feedback: "Geri bildirim",
    "Recipe Instructions": "Tarif Talimatları",
    "Visit Help Center": "Yardım Merkezini Ziyaret Edin",
    "Schedule Meeting": "Toplantı Planla",
    "Setup guide": "Kurulum rehberi",
    "Use this personalized guide to get your store up and running":
      "Mağazanızı çalışır duruma getirmek için bu kişiselleştirilmiş kılavuzu kullanın",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "Eylemleri almaya başlamak için uygulamamızı etkinleştirmeniz gerekir, düğmeye tıkladığınızda uzantılar sayfasına yönlendirilirsiniz, ardından orada kaydetip buraya geri dönmeniz yeterlidir.",
    "Enable our app": "Uygulamamızı etkinleştirin",
    "Learn more": "Daha fazla bilgi edin",
    "Skip it": "Bunu atlayın",
    steps: "adımlar",
    minutes: "dakika",
    "Mark as done": "tamamlandı olarak işaretle",
    "Mark as not done": "Tamamlanmadı olarak işaretle",
    "You have completed all the steps": "Tüm adımları tamamladınız",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "Mağazanızı arama sonuçlarında daha üst sıralara çıkarmak için sitenizin hızını etkinleştirin ve analiz edin.",
    "Google Page Speed Optimization": "Google Sayfa Hızı Optimizasyonu",
    "Activate Google Page Speed": "Google Sayfa Hızını Etkinleştirin",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "Sitenizin performansını değerlendirmek ve hızı artırma fırsatlarını belirlemek için Google Sayfa Hızı aracını etkinleştirin",
    "Enable Speed Analysis": "Hız Analizini Etkinleştir",
    "Review Speed Analysis Report": "Hız Analizi Raporunu İnceleyin",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "Sitenizin mevcut hız ölçümlerini anlamak ve iyileştirilecek alanları belirlemek için ayrıntılı hız analizi raporunu inceleyin.",
    "Go to Reports": "Raporlara Git",
    Hello: "Merhaba",
    "Let's get your store ready for success": "Mağazanızı başarıya hazırlayalım",
    "Finish later": "Daha sonra bitir",
    "Continue onboarding": "İlk katılıma devam edin",
    "Check image optimization features": "Görüntü optimizasyon özelliklerini kontrol edin",
    "Explore Optimization Features": "Optimizasyon Özelliklerini Keşfedin",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "Mevcut görüntü optimizasyon araçlarına aşina olun. Resim boyutlarını ve formatlarını optimize ederek sayfa yükleme hızlarını ve SEO'yu nasıl iyileştirebileceğinizi görün.",
    "Go to Image Optimization": "Görüntü Optimizasyonuna Git",
    "Automate Your Image Workflow": "Görüntü İş Akışınızı Otomatikleştirin",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "Yeni görselleri yüklenirken sorunsuz bir şekilde optimize etmek için otomasyonu kurun ve sitenizde tutarlı performans sağlayın.",
    "Go to Automation": "Otomasyona Git",
    "Execute a Bulk Optimization": "Toplu Optimizasyon Gerçekleştirin",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "Aynı anda birden fazla görseli verimli bir şekilde geliştirmek için toplu optimizasyon gerçekleştirin; bu, sitenizin yükleme süresini önemli ölçüde artırabilir.",
    "Go to bulk operations": "Toplu işlemlere git",
    "Broken Links Management": "Kırık Bağlantılar Yönetimi",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "Kullanıcı deneyimini ve SEO sıralamalarını geliştirmek için bozuk bağlantıların tespitini ve onarılmasını otomatikleştirin.",
    "Review Detected Broken Links": "Tespit Edilen Kırık Bağlantıları İnceleyin",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "Sitenizin gezinmesi üzerindeki etkilerini anlamak için sistemimiz tarafından otomatik olarak tanımlanan bozuk bağlantıların listesini inceleyin.",
    "View Broken Links": "Kırık Bağlantıları Görüntüle",
    "Address Broken Links": "Kırık Bağlantıların Adresi",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "Bozuk bağlantıları hızlı bir şekilde düzeltmek veya yeniden yönlendirmek için araçlarımızı kullanın, böylece sitenizin bütünlüğünü ve kullanıcı memnuniyetini artırın.",
    "Resolve Broken Links": "Kırık Bağlantıları Çözün",
    "Automate for Efficiency": "Verimlilik için Otomatikleştirin",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "Gelecekteki kopuk bağlantılardan bir adım önde olmak ve site sağlığının sürekli olmasını sağlamak için otomatik düzeltmeyi ayarlayın.",
    "Enable Automation": "Otomasyonu Etkinleştir",
    "Meta Tags Management": "Meta Etiket Yönetimi",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "Kullanıcı dostu Meta Etiketler özelliğimizle sitenizin görünürlüğünü ve arama motoru sıralamasını optimize edin.",
    "Explore Meta Tag Options": "Meta Etiket Seçeneklerini Keşfedin",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "Bireysel ürünler ve sayfalar için mevcut olan çeşitli meta etiket düzenleme ve otomasyon seçenekleriyle tanışın.",
    "Explore Meta Tags": "Meta Etiketleri Keşfedin",
    "Edit and Optimize": "Düzenle ve Optimize Et",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "Sitenizin SEO'sunu ve kullanıcı erişilebilirliğini geliştirmek için meta başlıkları, açıklamaları ve resim alt metinlerini düzenlemeye dalın.",
    "Start Editing": "Düzenlemeye Başla",
    "Automate for Consistency": "Tutarlılık için Otomatikleştirin",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "Ürün sayfalarınızda tutarlılığı ve verimliliği korumak amacıyla meta etiketleriniz için otomasyon kuralları ayarlayın.",
    "Set Automation": "Otomasyonu Ayarla",
    "Schema Markup": "Şema İşaretlemesi",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "İçeriğinizin arama sonuçlarındaki temsilini geliştirmek ve daha fazla tıklama çekmek için Şema işaretlemesinden yararlanın.",
    "Learn About Schema Options": "Şema Seçenekleri Hakkında Bilgi Edinin",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "Avantajlarını anlamak için Ürün, Yerel İşletme, SSS ve daha fazlası gibi mevcut farklı Şema işaretleme türleri hakkında bilgi edinin.",
    "Explore Schema Types": "Şema Türlerini Keşfedin",
    "Activate Key Schemas": "Anahtar Şemaları Etkinleştirin",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "E-ticaret için Ürün Şeması veya fiziksel mağazalar için Yerel İşletme Şeması gibi siteniz için önemli şemaları seçin ve etkinleştirin.",
    "Go to Schemas": "Şemalara git",
    "Customize Schema Details": "Şema Ayrıntılarını Özelleştir",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "İşletmenizi veya ürünlerinizi arama sonuçlarında doğru şekilde temsil etmek için her şema türünün ayarlarını özelleştirin.",
    "Test and Validate Schemas": "Şemaları Test Edin ve Doğrulayın",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "Doğru şekilde uygulandıklarından emin olmak için şemalarınızı Google'ın Yapılandırılmış Veri Test Aracı gibi araçları kullanarak test edin.",
    "Test Schemas": "Test Şemaları",
    "Add Breadcrumbs": "İçerik Kırıntıları Ekle",
    "Add Breadcrumbs to your store": "Mağazanıza Ekmek Kırıntıları ekleyin",
    "To get better user experience you need to add breadcrumbs to your store.":
      "Daha iyi bir kullanıcı deneyimi elde etmek için mağazanıza kırıntıları eklemeniz gerekir.",
    "How to add breadcrumbs": "Ekmek kırıntıları nasıl eklenir",
    "Understand how to add and configure breadcrumbs in your store.":
      "Mağazanıza içerik kırıntılarını nasıl ekleyeceğinizi ve yapılandıracağınızı öğrenin.",
    "Google search console": "Google arama konsolu",
    "Connect google search console to sync it with our app.":
      "Uygulamamızla senkronize etmek için Google arama konsolunu bağlayın.",
    "How to connect GSC.": "GSC'ye nasıl bağlanılır?",
    "Understand how to connect and use google search console in our app.":
      "Uygulamamızda Google Search Console'a nasıl bağlanacağınızı ve kullanacağınızı öğrenin.",
    "Go to GSC": "GSC'ye git",
    "Go to Breadcrumbs Design": "Breadcrumbs Tasarımına Git",
    "Start Onboarding": "İlk Katılımı Başlatın",
    "Go to Homepage": "Ana sayfaya git",
    "Go to Onboarding": "İlk Katılıma Git",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "Anlayışınızı geliştirmek için tasarlanmış kullanıcı dostu uygulama kılavuzumuzu keşfedin. Başlamak için 'İlk Katılımı Başlat'ı tıklayın; istediğiniz zaman ana sayfaya tekrar gelebilirsiniz.",
    "Please enable our app extension.": "Lütfen uygulama uzantımızı etkinleştirin.",
    "Generate Meta tags": "Meta etiketleri oluştur",
    "Test description a litle bit longer that title": "Test açıklaması bu başlıktan biraz daha uzun",
    "Suggested for you": "Sizin için önerildi",
    "Enable Google page speed": "Google sayfa hızını etkinleştir",
    "Connect GSC": "GSC'yi bağlayın",
    "Enable Image Optimize Automation": "Görüntü Optimize Etme Otomasyonunu Etkinleştir",
    "Automate Meta tags": "Meta etiketlerini otomatikleştirin",
    "Automate Broken Links": "Kırık Bağlantıları Otomatikleştirin",
    "Enhance SEO with automatically generated meta tags.":
      "Otomatik olarak oluşturulan meta etiketlerle SEO'yu geliştirin.",
    "Improve website performance by optimizing images.":
      "Görselleri optimize ederek web sitesi performansını artırın.",
    "Boost website speed by enabling Google Page Speed.":
      "Google Sayfa Hızını etkinleştirerek web sitesi hızını artırın.",
    "Enhance search visibility by connecting to Google Search Console.":
      "Google Search Console'a bağlanarak arama görünürlüğünü artırın.",
    "Streamline image optimization with automated processes.":
      "Otomatik süreçlerle görüntü optimizasyonunu kolaylaştırın.",
    "Improve SEO by automating the generation of meta tags.":
      "Meta etiketlerin oluşturulmasını otomatikleştirerek SEO'yu iyileştirin.",
    "Improve UX with automated detect and handle, broken links.":
      "Otomatik algılama ve işleme, bozuk bağlantılar ile kullanıcı deneyimini iyileştirin.",
    "Learn About Add Announcement": "Duyuru Ekleme Hakkında Bilgi Edinin",
    "Skip And Add Announcement": "Atla ve Duyuru Ekle",
    "Learn more about": "Hakkında daha fazla öğren",
    "Add Announcement": "Duyuru Ekle",
    "Announcement Bar": "Duyuru Çubuğu",
    "Rate us!": "Bizi değerlendirin!",
    "How would you Love this app?": "Bu uygulamayı nasıl seversiniz?",
    "Enter Your Feedback Here": "Geri Bildiriminizi Buraya Girin",
    "Leave Us a Review !!": "Bize Bir İnceleme Yazın!!",
    "If you like our app features then please leave us a review !!":
      "Uygulamamızın özelliklerini beğendiyseniz lütfen bize bir inceleme bırakın !!",
    "If you like our free features then please leave us a review !!":
      "Ücretsiz özelliklerimizi beğendiyseniz lütfen bize bir inceleme bırakın !!",
    "Update Successfully": "Başarıyla Güncelle",
    "Uninstall App": "Uygulamayı Kaldır",
    "Contact Our Support": "Desteğimizle İletişime Geçin",
    "Leave a message": "Mesaj bırakın",
    "Please Choose a UnInstallation Reason": "Lütfen bir Kaldırma Nedeni Seçin",
    "Are you facing any issues understanding the features of our app?":
      "Uygulamamızın özelliklerini anlamada herhangi bir sorunla karşılaşıyor musunuz?",
    "Please Choose at least one reason": "Lütfen en az bir neden seçin",
    "Thank You For Reaching Out": "Ulaştığınız için teşekkür ederiz",
    "Contact Support": "İletişim desteği",
    "Get Help from Our Support Team": "Destek Ekibimizden Yardım Alın",
    "Select a reason": "Bir sebep seçin",
    "Not getting how to use or setup": "Nasıl kullanılacağını veya kurulacağını anlayamıyorum",
    "Poor customer support": "Kötü müşteri desteği",
    "Performance issues": "Performans sorunları",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "Destek ekibimiz şu anda hafta sonları hizmet dışıdır ve saat diliminize göre hafta içi günlerde hizmetinizde olacaktır. ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " Hindistan'dan faaliyet gösterdiğimiz için. Yine de mesaj bırakabilirsiniz. Lütfen yanıtımızda biraz gecikme bekleyin. Sabrınız için teşekkürler.",
    "Our support team is partially available according to your time zone from ":
      "Destek ekibimiz, saat diliminize göre kısmen hizmetinizdedir. ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " Hindistan'dan faaliyet gösterdiğimiz için. Bu süre zarfında yanıtların verilmesi 30 dakika ile bir saat arasında sürebilir. Lütfen mesaj bırakın, mümkün olan en kısa sürede yanıt vereceğiz. Sabrınız için teşekkürler.",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "Destek ekibimiz şu anda kullanılamıyor ve saat diliminize göre şu tarihten itibaren hizmetinizde olacaktır: ",
    to: "ile",
    "Did not meet my expectations": "Beklentilerimi karşılamadı",
    "Feature Limitations": "Özellik Sınırlamaları",
    "Banner doesn't set in my app": "Banner uygulamamda ayarlanmıyor",
    "Banner is not show properly": "Banner düzgün gösterilmiyor",
    "Confusing Set Multi Position and Multi Animation": "Kafa Karıştıran Set Çoklu Pozisyon ve Çoklu Animasyon",
    "Sync Profile": "Profili Senkronize Et",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
