import modifyData from "../Language/zh.json";
import { mergeLanguage } from "../Utils/Index";

const data = {
  common: {
    Enabled: "启用",
    Disabled: "残疾人",
    "Embed is currently disabled": "嵌入当前已禁用",
    "Enable App": "启用应用程序",
    "1. Click on Enable App.": "1. 单击启用应用程序。",
    "Well done!! you have successfully enable our app.": "做得好！！您已成功启用我们的应用程序。",
    "2. Enable": "2. 启用",
    "App Embed as shown in image and save setting.": "如图所示嵌入应用程序并保存设置。",
    "Multi Announcement Bar": "多公告栏",
    "Click on the Enable Now button to enable it.": "单击立即启用按钮将其启用。",
    "Enable Announcement Bar to get started": "启用公告栏即可开始",
    "Enable Now": "立即启用",
    "Sync Status": "同步状态",
    Done: "完毕",
    No: "不",
    Found: "成立",
    Add: "添加",
    Search: "搜索",
    Showing: "显示中",
    of: "的",
    "results, at most": "结果最多",
    "per page": "每页",
    "Oops! Something went wrong.": "哎呀！出了些问题。",
    "Let's try that again, please refresh the page.": "我们再试一次，请刷新页面。",
    "If you're still stuck, contact us by chat support or": "如果您仍然遇到困难，请通过聊天支持联系我们或",
    "support@webrexstudio.com": "support@webrexstudio.com",
    "so we can help!": "所以我们可以提供帮助！",
    "Select any 3 feature that you want to setup on high priority or most interested":
      "选择您想要设置为高优先级或最感兴趣的任意 3 个功能",
    "Add ": "添加 ",
    "These is premium feature": "这是高级功能",
    "Go to pricing": "前往定价",
    Save: "节省",
    Minimum: "最低限度",
    Maximum: "最大限度",
    "images are required": "需要图片",
    and: "和",
    "images are allowed": "允许使用图像",
    Disconnect: "断开",
    "Sign In with Google": "使用 Google 登录",
    "Oops! Something went wrong. Admin token is malformed": "哎呀！出了些问题。管理令牌格式错误",
    "If you're still stuck, contact": "如果您仍然遇到困难，请联系",
    Premium: "优质的",
    Unlock: "开锁",
    "Unlock advanced features!": "解锁高级功能！",
    "© 2021 Webrex. All rights reserved.": "© 2021 Webrex。版权所有。",
    "Privacy Policy": "隐私政策",
    "Terms of Service": "服务条款",
    "Go to Shopify App": "转到 Shopify 应用程序",
    "Review Us": "评价我们",
    Cancel: "取消",
    "Review Popup Show": "评论弹出窗口",
    "click on review us": "点击评论我们",
    "Note: Feel free to leave a star rating without writing a review!": "注意：无需撰写评论即可留下星级！",
    Help: "帮助",
    "Help Button Click": "单击帮助按钮",
    Confirm: "确认",
    On: "在",
    Off: "离开",
    Price: "价格",
    Settings: "设置",
    Animation: "动画片",
    "My Profile": "我的简历",
    "My Subscription": "我的订阅",
    "Store Name": "店铺名称",
    "Store URL": "商店网址",
    "Email ID": "电子邮件ID",
    "Phone Number": "电话号码",
    Country: "国家",
    Currency: "货币",
    "Subscription Name": "订阅名称",
    "Select language": "选择语言",
    "Announcement setting": "公告设置",
    "Animation setting": "动画设定",
    Selector: "选择器",
    "Save Setting": "保存设置",
    "My Announcements": "我的公告",
    "Add bar": "添加栏",
    Number: "数字",
    Title: "标题",
    "Create At": "创建于",
    "Slide Activation": "滑动激活",
    Status: "地位",
    Actions: "行动",
    "Save order": "保存订单",
    "Reorder Slides": "重新排序幻灯片",
    position: "位置",
    Top: "顶部",
    "Sticky Top": "粘顶",
    "Bottom Fix": "底部固定",
    "Custom Position": "自定义位置",
    "Custom Position *Add Class or id of Selected Element.": "自定义位置 *添加所选元素的类或 ID。",
    "Bar Padding (px)": "条形内边距 (px)",
    "Add Remove Button": "添加删除按钮",
    "Choose icon color": "选择图标颜色",
    "Custom css": "自定义CSS",
    fadeIn: "淡入",
    fadeInDown: "淡入淡出",
    fadeInDownBig: "淡入淡出大",
    fadeInLeft: "向左淡入",
    fadeInLeftBig: "淡入左大",
    fadeInUp: "淡入淡出",
    bounceInDown: "向下弹跳",
    bounceInLeft: "向左弹跳",
    bounceInUp: "弹起",
    zoomIn: "放大",
    zoomInDown: "缩小",
    zoomInLeft: "向左放大",
    slideInLeft: "向左滑动",
    slideInUp: "向上滑动",
    slideInDown: "向下滑动",
    lightSpeedIn: "光速输入",
    rollIn: "滚入",
    flash: "闪光",
    shake: "摇",
    flip: "翻动",
    flipInX: "翻转输入X",
    flipOutX: "翻转X",
    fadeOut: "消退",
    fadeOutDown: "淡出向下",
    fadeOutDownBig: "淡出淡出大",
    fadeOutRight: "右淡出",
    fadeOutRightBig: "淡出右大",
    fadeOutUp: "淡出向上",
    bounceOutDown: "弹跳向下",
    bounceOutRight: "右弹跳",
    bounceOutUp: "弹跳向上",
    zoomOut: "缩小",
    zoomOutDown: "缩小缩小",
    zoomOutRight: "向右缩小",
    slideOutRight: "右滑出",
    slideOutUp: "向上滑动",
    slideOutDown: "滑出向下",
    lightSpeedOut: "光速输出",
    rollOut: "推出",
    flipInY: "翻转Y",
    "Text Animation": "文字动画",
    "Animation In": "动画输入",
    "Animation Out": "动画输出",
    "Auto play time (time in MS)": "自动播放时间（以毫秒为单位的时间）",
    "Animation time (time in MS)": "动画时间（以毫秒为单位的时间）",
    "Auto play time (time in Second)": "自动播放时间（时间以秒为单位）",
    "Background Color": "背景颜色",
    "Space between slide(px)": "幻灯片间距(px)",
    visible: "可见的",
    invisible: "无形的",
    "Promotional & Countdown Bar": "促销及倒计时栏",
    "Free Shipping Bar": "免费送货酒吧",
    "Add Slide": "添加幻灯片",
    "Only 1 slide is visible for FREE plan. To activate All slides subscribe Premium Plan.":
      "免费计划仅显示 1 张幻灯片。要激活所有幻灯片，请订阅高级计划。",
    Pricing: "价钱",
    "No Animation Found": "未找到动画",
    "No Preview, Add announcement Bar": "无预览，添加公告栏",
    "Update successfully": "更新成功",
    Enable: "使能够",
    Disable: "禁用",
    successfully: "成功地",
    "Delete successfully": "删除成功",
    "Copy successfully": "复制成功",
    "Reorder successfully": "重新订购成功",
    "Announcement Message": "公告信息",
    "Call to Action": "呼吁采取行动",
    Timer: "定时器",
    Style: "风格",
    "Background Type": "背景类型",
    "Mobile Style": "手机风格",
    "Schedule Display": "时间表显示",
    Update: "更新",
    "Change Font": "更改字体",
    "Font Family": "字体系列",
    "Font Style": "字体样式",
    Normal: "普通的",
    Italic: "斜体",
    Oblique: "斜",
    Unset: "取消设置",
    "Font Weight": "字体粗细",
    Bold: "大胆的",
    "Message Font Size": "消息字体大小",
    "Message Text color": "消息文字颜色",
    Type: "类型",
    None: "没有任何",
    Button: "按钮",
    "Entire clickable bar": "整个可点击栏",
    "Add a simple link": "添加一个简单的链接",
    "Add coupon placement": "添加优惠券放置",
    "Linked Url": "链接网址",
    "Background Hover Color": "背景悬停颜色",
    "Text Hover Color": "文本悬停颜色",
    "Button Text": "按钮文字",
    "Copied Text": "复制的文本",
    "Open in the new tab": "在新选项卡中打开",
    URL: "网址",
    "Font Size": "字体大小",
    "Button Radius": "按钮半径",
    "Button color": "按钮颜色",
    "Button Text color": "按钮文字颜色",
    "Button Hover Color": "按钮悬停颜色",
    "button Text HoverColor": "按钮文本悬停颜色",
    "Timer Setting": "定时器设定",
    "Timer Type": "定时器类型",
    Date: "日期",
    "Select Reapt Time": "选择捕捉时间",
    "repeated Hours": "重复小时数",
    "Normal Timer": "普通定时器",
    "Auto repeat timer": "自动重复定时器",
    Minute: "分钟",
    Hour: "小时",
    Day: "天",
    "Remove Timer When Time End": "时间结束时删除计时器",
    "Timer Separator": "定时器分隔符",
    "Countdown Timer color": "倒数计时器颜色",
    "Timer Text Size": "计时器文字大小",
    "Timer Text Setting": "定时器文本设置",
    "Day Text": "日文",
    "Hour Text": "小时文本",
    "Minute Text": "分钟文本",
    "Second Text": "第二段文字",
    "Background Image": "背景图",
    "Gradient Background": "渐变背景",
    "Style & Color For Mobile": "手机款式和颜色",
    "Timer Background": "定时器背景",
    "Timer Text Color": "计时器文字颜色",
    "Button Color": "按钮颜色",
    "Button Text Color": "按钮文字颜色",
    "Button Text Hover Color": "按钮文本悬停颜色",
    "Button Text Size": "按钮文字大小",
    "Always Display": "始终显示",
    "Only Display Within The Following Period Of Time": "仅在以下时间段内显示",
    "Start Time": "开始时间",
    "End Time": "时间结束",
    "Advance Setting": "高级设定",
    "Country Filter": "国家过滤器",
    Visibility: "能见度",
    "Desktop and Mobile": "桌面和移动设备",
    "Only Desktop": "仅桌面版",
    "Only Mobile": "仅限移动设备",
    "USER SOURCE TARGETING (Visitors Coming From A Link Including This Following UTM Code, Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "用户源定位（来自包含以下 UTM 代码的链接的访问者，例如 Ref=Facebook、Ref=Web、Utm_source=Google...）",
    "Select Page": "选择页面",
    Include: "包括",
    Exclude: "排除",
    "Currency Configuration": "货币配置",
    Message: "信息",
    "Currency Symbol": "货币符号",
    "Currency Position": "货币头寸",
    Before: "前",
    After: "后",
    "money Class": "金钱类",
    "Initial Message": "初始消息",
    "Shipping Goal": "出货目标",
    "Progress Message": "进度信息",
    "Progress goal": "进度目标",
    "Goal Message": "目标讯息",
    "Shipping Price Color": "运费颜色",
    "Shipping Price Size": "运费尺寸",
    "Shipping Font Weight": "运送字体粗细",
    "* When user first time visit": "* 用户第一次访问时",
    "* When user add item to the cart e.g": "* 当用户将商品添加到购物车时，例如：",
    "* When cart value is greater than": "* 当购物车价值大于",
    "Show On Selected Countries": "在选定的国家/地区显示",
    "Show On Selected Pages": "在选定页面上显示",
    All: "全部",
    Home: "家",
    Cart: "大车",
    Collection: "收藏",
    Product: "产品",
    Custom: "风俗",
    Page: "页",
    Blog: "博客",
    "Url is required": "网址为必填项",
    "Day Text is required": "需要日期文本",
    "Hour Text is required": "小时 文字为必填项",
    "Minute Text is required": "需要分钟文本",
    "Second Text is required": "需要第二个文本",
    "Start Time is required": "开始时间为必填项",
    "End Time is required": "结束时间为必填项",
    "Created successfully": "创建成功",
    "United States": "美国",
    Canada: "加拿大",
    Australia: "澳大利亚",
    "New Zealand": "新西兰",
    Germany: "德国",
    India: "印度",
    Afghanistan: "阿富汗",
    "land Islands": "陆地岛屿",
    Albania: "阿尔巴尼亚",
    Algeria: "阿尔及利亚",
    "American Samoa": "美属萨摩亚",
    AndorrA: "安道尔A",
    Angola: "安哥拉",
    Anguilla: "安圭拉",
    Antarctica: "南极洲",
    "Antigua and Barbuda": "安提瓜和巴布达",
    Argentina: "阿根廷",
    Armenia: "亚美尼亚",
    Aruba: "阿鲁巴岛",
    Austria: "奥地利",
    Azerbaijan: "阿塞拜疆",
    Bahamas: "巴哈马",
    Bahrain: "巴林",
    Bangladesh: "孟加拉国",
    Barbados: "巴巴多斯",
    Belarus: "白俄罗斯",
    Belgium: "比利时",
    Belize: "伯利兹",
    Benin: "贝宁",
    Bermuda: "百慕大",
    Bhutan: "不丹",
    Bolivia: "玻利维亚",
    "Bosnia and Herzegovina": "波斯尼亚和黑塞哥维那",
    Botswana: "博茨瓦纳",
    "Bouvet Island": "布维岛",
    Brazil: "巴西",
    "British Indian Ocean Territory": "英属印度洋领地",
    "Brunei Darussalam": "文莱达鲁萨兰国",
    Bulgaria: "保加利亚",
    "Burkina Faso": "布基纳法索",
    Burundi: "布隆迪",
    Cambodia: "柬埔寨",
    Cameroon: "喀麦隆",
    "Cape Verde": "佛得角",
    "Cayman Islands": "开曼群岛",
    "Central African Republic": "中非共和国",
    Chad: "乍得",
    Chile: "智利",
    China: "中国",
    "Christmas Island": "圣诞岛",
    "Cocos (Keeling) Islands": "科科斯（基林）群岛",
    Colombia: "哥伦比亚",
    Comoros: "科摩罗",
    Congo: "刚果",
    "Congo, The Democratic Republic of the": "刚果民主共和国",
    "Cook Islands": "库克群岛",
    "Costa Rica": "哥斯达黎加",
    "Cote D'Ivoire": "科特迪瓦",
    Croatia: "克罗地亚",
    Cuba: "古巴",
    Cyprus: "塞浦路斯",
    "Czech Republic": "捷克共和国",
    Denmark: "丹麦",
    Djibouti: "吉布提",
    Dominica: "多米尼加",
    "Dominican Republic": "多明尼加共和国",
    Ecuador: "厄瓜多尔",
    Egypt: "埃及",
    "El Salvador": "萨尔瓦多",
    "Equatorial Guinea": "赤道几内亚",
    Eritrea: "厄立特里亚",
    Estonia: "爱沙尼亚",
    Ethiopia: "埃塞俄比亚",
    "Falkland Islands (Malvinas)": "福克兰群岛（马尔维纳斯）",
    "Faroe Islands": "法罗群岛",
    Fiji: "斐济",
    Finland: "芬兰",
    France: "法国",
    "French Guiana": "法属圭亚那",
    "French Polynesia": "法属波利尼西亚",
    "French Southern Territories": "法属南部领土",
    Gabon: "加蓬",
    Gambia: "冈比亚",
    Georgia: "乔治亚州",
    Ghana: "加纳",
    Gibraltar: "直布罗陀",
    Greece: "希腊",
    Greenland: "格陵兰",
    Grenada: "格林纳达",
    Guadeloupe: "瓜德罗普岛",
    Guam: "关岛",
    Guatemala: "危地马拉",
    Guernsey: "根西岛",
    Guinea: "几内亚",
    "Guinea-Bissau": "几内亚比绍",
    Guyana: "圭亚那",
    Haiti: "海地",
    "Heard Island and Mcdonald Islands": "赫德岛和麦克唐纳群岛",
    "Holy See (Vatican City State)": "罗马教廷（梵蒂冈城国）",
    Honduras: "洪都拉斯",
    "Hong Kong": "香港",
    Hungary: "匈牙利",
    Iceland: "冰岛",
    Indonesia: "印度尼西亚",
    "Iran, Islamic Republic Of": "伊朗伊斯兰共和国",
    Iraq: "伊拉克",
    Ireland: "爱尔兰",
    "Isle of Man": "马恩岛",
    Israel: "以色列",
    Italy: "意大利",
    Jamaica: "牙买加",
    Japan: "日本",
    Jersey: "球衣",
    Jordan: "约旦",
    Kazakhstan: "哈萨克斯坦",
    Kenya: "肯尼亚",
    Kiribati: "基里巴斯",
    "Korea, Democratic People'S Republic of": "朝鲜民主主义人民共和国",
    "Korea, Republic of": "韩国",
    Kuwait: "科威特",
    Kyrgyzstan: "吉尔吉斯斯坦",
    "Lao People'S Democratic Republic": "老挝人民民主共和国",
    Latvia: "拉脱维亚",
    Lebanon: "黎巴嫩",
    Lesotho: "莱索托",
    Liberia: "利比里亚",
    "Libyan Arab Jamahiriya": "阿拉伯利比亚民众国",
    Liechtenstein: "列支敦士登",
    Lithuania: "立陶宛",
    Luxembourg: "卢森堡",
    Macao: "澳门",
    "Macedonia, The Former Yugoslav Republic of": "马其顿、前南斯拉夫共和国",
    Madagascar: "马达加斯加",
    Malawi: "马拉维",
    Malaysia: "马来西亚",
    Maldives: "马尔代夫",
    Mali: "马里",
    Malta: "马耳他",
    "Marshall Islands": "马绍尔群岛",
    Martinique: "马提尼克岛",
    Mauritania: "毛里塔尼亚",
    Mauritius: "毛里求斯",
    Mayotte: "马约特岛",
    Mexico: "墨西哥",
    "Micronesia, Federated States of": "密克罗尼西亚联邦",
    "Moldova, Republic of": "摩尔多瓦共和国",
    Monaco: "摩纳哥",
    Mongolia: "蒙古",
    Montenegro: "黑山",
    Montserrat: "蒙特塞拉特",
    Morocco: "摩洛哥",
    Mozambique: "莫桑比克",
    Myanmar: "缅甸",
    Namibia: "纳米比亚",
    Nauru: "瑙鲁",
    Nepal: "尼泊尔",
    Netherlands: "荷兰",
    "Netherlands Antilles": "荷属安的列斯",
    "New Caledonia": "新喀里多尼亚",
    Nicaragua: "尼加拉瓜",
    Niger: "尼日尔",
    Nigeria: "尼日利亚",
    Niue: "纽埃",
    "Norfolk Island": "诺福克岛",
    "Northern Mariana Islands": "北马里亚纳群岛",
    Norway: "挪威",
    Oman: "阿曼",
    Pakistan: "巴基斯坦",
    Palau: "帕劳",
    "Palestinian Territory, Occupied": "巴勒斯坦被占领土",
    Panama: "巴拿马",
    "Papua New Guinea": "巴布亚新几内亚",
    Paraguay: "巴拉圭",
    Peru: "秘鲁",
    Philippines: "菲律宾",
    Pitcairn: "皮特凯恩",
    Poland: "波兰",
    Portugal: "葡萄牙",
    "Puerto Rico": "波多黎各",
    Qatar: "卡塔尔",
    Reunion: "团圆",
    Romania: "罗马尼亚",
    "Russian Federation": "俄罗斯联邦",
    RWANDA: "卢旺达",
    "Saint Helena": "圣赫勒拿岛",
    "Saint Kitts and Nevis": "圣基茨和尼维斯",
    "Saint Lucia": "圣卢西亚",
    "Saint Pierre and Miquelon": "圣皮埃尔和密克隆群岛",
    "Saint Vincent and the Grenadines": "圣文森特和格林纳丁斯",
    Samoa: "萨摩亚",
    "San Marino": "圣马力诺",
    "Sao Tome and Principe": "圣多美和普林西比",
    "Saudi Arabia": "沙特阿拉伯",
    Senegal: "塞内加尔",
    Serbia: "塞尔维亚",
    Seychelles: "塞舌尔",
    "Sierra Leone": "塞拉利昂",
    Singapore: "新加坡",
    Slovakia: "斯洛伐克",
    Slovenia: "斯洛文尼亚",
    "Solomon Islands": "所罗门群岛",
    Somalia: "索马里",
    "South Africa": "南非",
    "South Georgia and the South Sandwich Islands": "南乔治亚岛和南桑威奇群岛",
    Spain: "西班牙",
    "Sri Lanka": "斯里兰卡",
    Sudan: "苏丹",
    Surilabel: "苏瑞标签",
    "Svalbard and Jan Mayen": "斯瓦尔巴群岛和扬马延岛",
    Swaziland: "斯威士兰",
    Sweden: "瑞典",
    Switzerland: "瑞士",
    "Syrian Arab Republic": "阿拉伯叙利亚共和国",
    "Taiwan, Province of China": "中国台湾省",
    Tajikistan: "塔吉克斯坦",
    "Tanzania, United Republic of": "坦桑尼亚联合共和国",
    Thailand: "泰国",
    "Timor-Leste": "东帝汶",
    Togo: "多哥",
    Tokelau: "托克劳",
    Tonga: "汤加",
    "Triidd and Tobago": "特里德和多巴哥",
    Tunisia: "突尼斯",
    Turkey: "火鸡",
    Turkmenistan: "土库曼斯坦",
    "Turks and Caicos Islands": "特克斯和凯科斯群岛",
    Tuvalu: "图瓦卢",
    Uganda: "乌干达",
    Ukraine: "乌克兰",
    "United Arab Emirates": "阿拉伯联合酋长国",
    "United Kingdom": "英国",
    "United States Minor Outlying Islands": "美国本土外小岛屿",
    Uruguay: "乌拉圭",
    Uzbekistan: "乌兹别克斯坦",
    Vanuatu: "瓦努阿图",
    Venezuela: "委内瑞拉",
    "Viet Nam": "越南",
    "Virgin Islands, British": "英属维尔京群岛",
    "Virgin Islands, U.S.": "美国维尔京群岛",
    "Wallis and Futuna": "瓦利斯和富图纳群岛",
    "Western Sahara": "撒哈拉沙漠西部",
    Yemen: "也门",
    Zambia: "赞比亚",
    Zimbabwe: "津巴布韦",
    "Unlock All Schema with our Premium Plan": "使用我们的高级计划解锁所有架构",
    "Billed Monthly": "按月计费",
    "Billed Annually": "按年计费",
    "Save 30%": "节省 30%",
    Premium100Title:
      "作为早期用户，我们向您保证，您将免费享受我们所有的高级功能。无需担心定价页面，因为您可以免费使用我们所有的高级功能。请不要卸载我们的应用程序以继续享受我们的服务。",
    Premium100ReviewLine: " 如果您喜欢我们的应用程序，请给我们留下评论。这有助于我们有动力开发新功能。",
    "Check Our Current Pricing": "查看我们当前的定价",
    "Leave Review": "留下评论",
    "We're sorry to see you go!": "看到你离开我们感到很遗憾！",
    "Cancel Plan": "取消计划",
    "Sync Plan": "同步计划",
    "Disccount applied": "适用折扣",
    Apply: "申请",
    "Your code(s)": "您的代码",
    "and discount have been applied successfully": "并且折扣已成功应用",
    "Your entered promocode is not correct, Enter a valid code": "您输入的促销代码不正确，请输入有效代码",
    "days trial left": "还剩几天试用期",
    Upgrade: "升级",
    "days free trial, No Credit card required": "天免费试用，无需信用卡",
    Month: "月",
    Year: "年",
    Unlimited: "无限",
    "Enter Promocode": "输入促销代码",
    "Please Choose a Cancellation Reason": "请选择取消原因",
    "No Longer Needed?": "不再需要？",
    "Didn't Meet Expectations": "没有达到预期",
    "Cost Concerns": "成本问题",
    "Technical Issues": "技术问题",
    "Found an Alternative": "找到了替代方案",
    Complexity: "复杂",
    "Lack of Features": "缺乏特色",
    "Poor Customer Support": "客户支持不佳",
    "Business Closure or Change": "企业关闭或变更",
    "Temporary Pause": "暂时暂停",
    "Performance Issues": "性能问题",
    Other: "其他",
    "Mention Your Specific Reason Here": "在此说明您的具体原因",
    Start: "开始",
    "Day Free Trial": "天免费试用",
    "Please Select One Option": "请选择一项",
    "Plan cancelled successfully": "计划取消成功",
    "7 days free trial, No Credit card required": "7 天免费试用，无需信用卡",
    "Your remaining trial days are": "您剩余的试用天数是",
    "You have used": "您已使用过",
    "days.": "天。",
    "No trial days remaining. You have already used the 7-day free trial.":
      "没有剩余试用天数。您已经使用了 7 天免费试用版。",
    "Upgrade your plan now": "立即升级您的计划",
    "Unlimited Slides": "无限幻灯片",
    "20+ Animation In & Out": "20+ 动画输入和输出",
    "Live Chat Support": "实时聊天支持",
    "Priority, 24*7 Urgent setup and support": "优先，24*7 紧急设置和支持",
    "Rich Text Editor": "富文本编辑器",
    "One Slide(banner)": "一张幻灯片（横幅）",
    "Repeated Countdown timer": "重复倒数计时器",
    "Fully Customisable": "完全可定制",
    "Background-image": "背景图",
    "Custom Css": "自定义 CSS",
    "Enable Our App": "启用我们的应用程序",
    "Book Onboarding Demo": "预订入职演示",
    Next: "下一个",
    Finish: "结束",
    Prev: "上一篇",
    "App is not enable please click on the Enable App button to enable it.":
      "应用程序未启用，请单击“启用应用程序”按钮将其启用。",
    "This field is required": "此字段是必需的",
    disableButtonTooltip: "您无法升级月度套餐，因为您使用的是年度套餐！",
    "Choose plan": "选择计划",
    "Purchase Plan": "采购计划",
    Continue: "继续",
    "Image Optimization": "图像优化",
    "AI Metatags": "人工智能元标签",
    "Grand Total": "累计",
    "Metatags Edit": "元标签 编辑",
    Products: "产品",
    "Upgrade plan": "升级计划",
    "Your product count is": "您的产品数量是",
    "so your suitable plan is": "所以你合适的计划是",
    "Enjoy a": "享受一个",
    "lifetime discount": "终身折扣",
    discountBanner: " 享受终身折扣，确保永久节省并增强您对我们优质产品和服务的体验。",
    "Images for Optimization every year after trial period end": "试用期结束后每年进行优化的图像",
    "AI Meta Tags Credit for every year after trial period end": "试用期结束后每年可获得 AI 元标签积分",
    "Images for Optimization every month after trial period end": "试用期结束后每月进行优化的图像",
    "AI Meta Tags Credit for every Month after trial period end": "试用期结束后每个月的 AI 元标签积分",
    "Optimize your google page speed": "优化您的 Google 页面速度",
    "50 Product Meta tags Optimize, Image alt": "50 个产品元标签优化、图像替代",
    "Product Meta tags Optimize, Image alt": "产品元标签优化、图像替代",
    "AI ImageAltText Credit for every year after trial period end": "试用期结束后每年可获得 AI ImageAltText 积分",
    "25 AI ImageAltText Credit": "25 AI ImageAltText 学分",
    "AI ImageAltText Credit for every Month after trial period end": "试用期结束后每月可获得 AI ImageAltText 积分",
    "Contact Bar": "联系栏",
    "Add To Cart Bar": "添加到购物车栏",
    "Multiple Position": "多个位置",
    lowMsgStart: "此优惠专为您设计，因为您刚刚开设 Shopify 商店",
    lowMsgMiddle: "我们的",
    lowMsgEnd: "折扣是我们在这个充满挑战而又激动人心的时刻为您提供支持的方式。",
    mediumMsgStart: "此优惠是专为您设计的，因为您已经开设了 Shopify 商店",
    mediumMsgMiddle: "我们的",
    mediumMsgEnd: "折扣是我们在这个充满挑战而又激动人心的时刻为您提供支持的方式。",
    importantMsgStart: "此优惠是专为您设计的，因为您已经开设了 Shopify 商店",
    importantMsgMiddle: "我们的",
    importantMsgEnd: "折扣是我们在这个充满挑战而又激动人心的时刻为您提供支持的方式。",
    veryImportantMsgStart: "此优惠是专门为您设计的，因为您已经开设了 Shopify 商店",
    veryImportantMsgMiddle: "您对我们来说是一位非常重要且成熟的商人。我们的",
    veryImportantMsgEnd: "折扣是为了表明您对我们的意义。",
    generalMsg:
      "我们的 Shopify 应用程序专为满足像您这样的老牌企业的需求而量身定制。它旨在无缝处理大量和复杂的操作。 ",
    lowTitleStart: "新创业者特别支持：",
    lowTitleEnd: "折扣刚开始",
    mediumTitleStart: "创业者特别支持：",
    mediumTitleEnd: "一开始就有折扣",
    importantTitleStart: "创业者特别支持：",
    importantTitleEnd: "一开始就有折扣",
    veryImportantTitleStart: "恭喜您成为",
    veryImportantTitleEnd: "在 Shopify 中",
    month: "月",
    "year and": "年和",
    ago: "前",
    "Add AI Credit (1 AI Credit/10¢) (10 AI Credit/$1 )": "添加 AI 积分（1 AI 积分/10 美分）（10 AI 积分/1 美元）",
    "Add image altText AI Credit (1 AI Credit/4¢) (25 AI Credit/$1 )":
      "添加图像 altText AI 积分（1 AI 积分/4 美分）（25 AI 积分/1 美元）",
    "Monthly AI AltText Credit": "每月 AI AltText 积分",
    "Yearly AI AltText Credit": "年度 AI AltText 积分",
    "Purchase AI AltText Credit": "购买 AI AltText 积分",
    "ImageAltText Credit": "图片替代文字来源",
    "Your credits are finished; please upgrade your plan.": "你的学分已经完成；请升级您的计划。",
    "Your credits are finished; you can buy more credits from here.":
      "你的学分已经完成；您可以从这里购买更多积分。",
    "This offer expire in": "此优惠将于",
    "Hurry Up!": "赶快！",
    Current: "当前的",
    "Discount applied": "已应用折扣",
    "trial left": "试用左",
    "info banner": "当您单击扫描主页图像按钮时，我们的应用程序将仅扫描主页图像。要优化此图像，请手动单击优化按钮",
    "Optimize Images": "优化图像",
    image: "图像",
    images: "图片",
    Filename: "文件名",
    Images: "图片",
    Setting: "环境",
    "Saved(in %)": "节省（%）",
    Action: "行动",
    "Product Image": "产品图片",
    "product image": "产品图片",
    gif: "动图",
    Homepage: "主页",
    "Manage Announcement": "管理公告",
    "No Announcements Found": "没有找到公告",
    Position: "位置",
    "Campaign Title": "活动标题",
    Visible: "可见的",
    Invisible: "无形的",
    Views: "视图",
    Clicks: "点击次数",
    Submits: "提交",
    "Above Add to cart Button": "上方的“添加到购物车”按钮",
    "Below Add to cart Button": "下方加入购物车按钮",
    Targeting: "定位",
    "Rotating Animation Setting": "旋转动画设置",
    "Marquee Animation Setting": "跑马灯动画设置",
    "Show to visitors coming form then specific website": "向来自特定网站的访客显示",
    "Add your website URL": "添加您的网站网址",
    "Banner Display Start Time": "横幅显示开始时间",
    "Banner Display End Time": "横幅显示结束时间",
    "Create Campaign": "创建活动",
    "Select Announcement Bar": "选择公告栏",
    "Please select template.": "请选择模板。",
    Previous: "以前的",
    "Promotion bar": "促销栏",
    "Add To Cart": "添加到购物车",
    Embeded: "嵌入式",
    "Alert customers of upcoming sales, offers, or set inventory alerts.":
      "提醒客户即将进行的销售或优惠，或设置库存警报。",
    "Increase your order value by using or Free Shipping Bar.": "通过使用或免费送货栏来增加您的订单价值。",
    "Conveniently add items to your cart with a single click!": "只需单击一下即可方便地将商品添加到您的购物车！",
    "Select to subscribe and receive special discounts directly to your inbox":
      "选择订阅并直接在收件箱中收到特别折扣",
    "Highlight your special offers with an embedded bar, displayed before and after the Add to Cart button.":
      "使用嵌入的栏突出显示您的特别优惠，显示在“添加到购物车”按钮之前和之后。",
    Select: "选择",
    "Add Hide Banner UTM code (Eg.Ref=Facebook, Ref=Web, Utm_source=Google...)":
      "添加隐藏横幅 UTM 代码（例如 Ref=Facebook、Ref=Web、Utm_source=Google...）",
    "Include Utm": "包括 Utm",
    "Exclude Utm": "排除 Utm",
    "Campaign Design": "活动设计",
    "Background Setting": "背景设定",
    "Target Setting": "目标设定",
    Scheduling: "调度",
    Rotating: "旋转",
    Marquee: "选框",
    "Repeat Timer Date": "重复定时器日期",
    "Select Repeat Time": "选择重复时间",
    "Repeated Hours": "重复小时数",
    Border: "边界",
    Bashed: "受到重击",
    "Multi Rotating": "多旋转",
    Contacts: "联系方式",
    Email: "电子邮件",
    "First Name": "名",
    "Last Name": "姓",
    Phone: "电话",
    "You have unsaved changes": "您有未保存的更改",
    "Your campaign has unsaved changes. Changes will be lost if you leave without saving.":
      "您的广告系列有未保存的更改。如果您离开时未保存，更改将会丢失。",
    "Leave widthout saving": "留出宽度节省",
    "Save Changes": "保存更改",
    Announcement: "公告",
    Feedback: "反馈",
    "Recipe Instructions": "食谱说明",
    "Visit Help Center": "访问帮助中心",
    "Schedule Meeting": "安排会议",
    "Setup guide": "设置指南",
    "Use this personalized guide to get your store up and running": "使用此个性化指南来建立和运营您的商店",
    "To start getting actions you need to enable our app, Click on the button will take you to the extensions page, then you just need to click save there and come back here":
      "要开始获取启用我们的应用程序所需的操作，单击按钮将带您进入扩展页面，然后您只需单击“保存”并返回此处",
    "Enable our app": "启用我们的应用程序",
    "Learn more": "了解更多",
    "Skip it": "跳过它",
    steps: "脚步",
    minutes: "分钟",
    "Mark as done": "标为已完成",
    "Mark as not done": "标记为未完成",
    "You have completed all the steps": "您已完成所有步骤",
    "Activate and analyze your site's speed, to rank your store higher on search results.":
      "激活并分析您网站的速度，以使您的商店在搜索结果中排名更高。",
    "Google Page Speed Optimization": "谷歌页面速度优化",
    "Activate Google Page Speed": "激活 Google 页面速度",
    "Enable the Google Page Speed tool to assess your site's performance and identify opportunities for speed enhancement":
      "启用 Google Page Speed 工具来评估您网站的性能并确定提高速度的机会",
    "Enable Speed Analysis": "启用速度分析",
    "Review Speed Analysis Report": "查看速度分析报告",
    "Examine the detailed speed analysis report to understand your site's current speed metrics and pinpoint areas for improvement.":
      "检查详细的速度分析报告，了解您站点当前的速度指标并查明需要改进的领域。",
    "Go to Reports": "前往报告",
    Hello: "你好",
    "Let's get your store ready for success": "让我们为您的商店取得成功做好准备",
    "Finish later": "稍后完成",
    "Continue onboarding": "继续入职",
    "Check image optimization features": "检查图像优化功能",
    "Explore Optimization Features": "探索优化功能",
    "Familiarize yourself with the range of image optimization tools available. See how you can improve page load speeds and SEO by optimizing image sizes and formats.":
      "熟悉各种可用的图像优化工具。了解如何通过优化图像大小和格式来提高页面加载速度和 SEO。",
    "Go to Image Optimization": "转到图像优化",
    "Automate Your Image Workflow": "自动化您的图像工作流程",
    "Set up automation to seamlessly optimize new images as they are uploaded, ensuring consistent performance across your site.":
      "设置自动化以在上传新图像时无缝优化它们，确保整个网站的性能一致。",
    "Go to Automation": "前往自动化",
    "Execute a Bulk Optimization": "执行批量优化",
    "Perform a bulk optimization to efficiently enhance multiple images at once, which can significantly boost your site's loading time.":
      "执行批量优化以一次有效地增强多个图像，这可以显着缩短网站的加载时间。",
    "Go to bulk operations": "进入批量操作",
    "Broken Links Management": "失效链接管理",
    "Automate the detection and repair of broken links to enhance user experience and SEO rankings.":
      "自动检测和修复损坏的链接，以增强用户体验和 SEO 排名。",
    "Review Detected Broken Links": "检查检测到的损坏链接",
    "Examine the list of broken links identified automatically by our system to understand their impact on your site's navigation.":
      "检查我们的系统自动识别的损坏链接列表，以了解它们对您网站导航的影响。",
    "View Broken Links": "查看损坏的链接",
    "Address Broken Links": "地址损坏的链接",
    "Utilize our tools to quickly fix or redirect broken links, improving your site's integrity and user satisfaction.":
      "利用我们的工具快速修复或重定向损坏的链接，提高网站的完整性和用户满意度。",
    "Resolve Broken Links": "解决损坏的链接",
    "Automate for Efficiency": "自动化提高效率",
    "Set up automated fix to stay ahead of any future broken links, ensuring continuous site health.":
      "设置自动修复，以领先于未来任何损坏的链接，确保网站持续健康。",
    "Enable Automation": "启用自动化",
    "Meta Tags Management": "元标签管理",
    "Optimize your site's visibility and search engine ranking with our user-friendly Meta Tags feature.":
      "使用我们用户友好的元标签功能优化您网站的可见性和搜索引擎排名。",
    "Explore Meta Tag Options": "探索元标记选项",
    "Get acquainted with the various meta tag editing and automation options available for individual products and pages.":
      "熟悉可用于各个产品和页面的各种元标记编辑和自动化选项。",
    "Explore Meta Tags": "探索元标签",
    "Edit and Optimize": "编辑与优化",
    "Dive into editing meta titles, descriptions, and image alt texts to enhance your site's SEO and user accessibility.":
      "深入编辑元标题、描述和图像替代文本，以增强网站的搜索引擎优化和用户可访问性。",
    "Start Editing": "开始编辑",
    "Automate for Consistency": "自动化以实现一致性",
    "Set up automation rules for your meta tags to maintain consistency and efficiency across your product pages.":
      "为元标记设置自动化规则，以保持产品页面的一致性和效率。",
    "Set Automation": "设置自动化",
    "Schema Markup": "模式标记",
    "Utilize Schema markup to enhance your content's representation in search results and attract more clicks.":
      "利用架构标记增强内容在搜索结果中的表现并吸引更多点击。",
    "Learn About Schema Options": "了解架构选项",
    "Familiarize yourself with the different types of Schema markups available, such as Product, Local Business, FAQ, and more, to understand their benefits.":
      "熟悉可用的不同类型的架构标记，例如产品、本地业务、常见问题解答等，以了解它们的好处。",
    "Explore Schema Types": "探索架构类型",
    "Activate Key Schemas": "激活密钥架构",
    "Choose and enable crucial schemas for your site, like Product Schema for e-commerce or Local Business Schema for physical stores.":
      "为您的网站选择并启用关键架构，例如电子商务的产品架构或实体店的本地业务架构。",
    "Go to Schemas": "转到架构",
    "Customize Schema Details": "自定义架构详细信息",
    "Customize the settings of each schema type to accurately represent your business or products in search results.":
      "自定义每种架构类型的设置，以在搜索结果中准确表示您的业务或产品。",
    "Test and Validate Schemas": "测试和验证模式",
    "Test your schemas using tools like Google's Structured Data Testing Tool to ensure they are correctly implemented.":
      "使用 Google 结构化数据测试工具等工具测试您的架构，以确保它们正确实现。",
    "Test Schemas": "测试模式",
    "Add Breadcrumbs": "添加面包屑",
    "Add Breadcrumbs to your store": "将面包屑添加到您的商店",
    "To get better user experience you need to add breadcrumbs to your store.":
      "为了获得更好的用户体验，您需要向商店添加面包屑。",
    "How to add breadcrumbs": "如何添加面包屑",
    "Understand how to add and configure breadcrumbs in your store.": "了解如何在商店中添加和配置面包屑。",
    "Google search console": "谷歌搜索控制台",
    "Connect google search console to sync it with our app.": "连接谷歌搜索控制台以将其与我们的应用程序同步。",
    "How to connect GSC.": "如何连接 GSC。",
    "Understand how to connect and use google search console in our app.":
      "了解如何在我们的应用程序中连接和使用谷歌搜索控制台。",
    "Go to GSC": "前往全球服务中心",
    "Go to Breadcrumbs Design": "转到面包屑设计",
    "Start Onboarding": "开始入职",
    "Go to Homepage": "去首页",
    "Go to Onboarding": "前往入职",
    "Explore our user-friendly app guide designed to enhance your understanding. Click 'Start Onboarding' to begin, and you can come to homepage again anytime.":
      "探索我们用户友好的应用程序指南，旨在增强您的理解。单击“开始入职”即可开始，您可以随时再次回到主页。",
    "Please enable our app extension.": "请启用我们的应用扩展。",
    "Generate Meta tags": "生成元标签",
    "Test description a litle bit longer that title": "测试描述比标题稍长一点",
    "Suggested for you": "为您推荐",
    "Enable Google page speed": "启用 Google 页面速度",
    "Connect GSC": "连接 GSC",
    "Enable Image Optimize Automation": "启用图像优化自动化",
    "Automate Meta tags": "自动化元标签",
    "Automate Broken Links": "自动断开链接",
    "Enhance SEO with automatically generated meta tags.": "使用自动生成的元标记增强 SEO。",
    "Improve website performance by optimizing images.": "通过优化图像来提高网站性能。",
    "Boost website speed by enabling Google Page Speed.": "通过启用 Google Page Speed 提高网站速度。",
    "Enhance search visibility by connecting to Google Search Console.":
      "通过连接到 Google Search Console 增强搜索可见性。",
    "Streamline image optimization with automated processes.": "通过自动化流程简化图像优化。",
    "Improve SEO by automating the generation of meta tags.": "通过自动生成元标记来改进 SEO。",
    "Improve UX with automated detect and handle, broken links.": "通过自动检测和处理损坏的链接来改善用户体验。",
    "Learn About Add Announcement": "了解添加公告",
    "Skip And Add Announcement": "跳过并添加公告",
    "Learn more about": "学习更多关于",
    "Add Announcement": "添加公告",
    "Announcement Bar": "公告栏",
    "Rate us!": "给我们评分！",
    "How would you Love this app?": "您如何喜欢这款应用？",
    "Enter Your Feedback Here": "在此输入您的反馈",
    "Leave Us a Review !!": "给我们留下评论！",
    "If you like our app features then please leave us a review !!":
      "如果您喜欢我们的应用功能，请给我们留下评论！！",
    "If you like our free features then please leave us a review !!":
      "如果您喜欢我们的免费功能，请给我们留下评论！",
    "Update Successfully": "更新成功",
    "Uninstall App": "卸载应用程序",
    "Contact Our Support": "联系我们的支持",
    "Leave a message": "留言",
    "Please Choose a UnInstallation Reason": "请选择卸载原因",
    "Are you facing any issues understanding the features of our app?":
      "您在理解我们的应用程序的功能时遇到任何问题吗？",
    "Please Choose at least one reason": "请选择至少一个原因",
    "Thank You For Reaching Out": "感谢您的联系",
    "Contact Support": "联系支持",
    "Get Help from Our Support Team": "从我们的支持团队获得帮助",
    "Select a reason": "选择原因",
    "Not getting how to use or setup": "不知道如何使用或设置",
    "Poor customer support": "客户支持不佳",
    "Performance issues": "性能问题",
    "Our support team is currently unavailable on weekends and will be available on weekdays according to your time zone from ":
      "我们的支持团队目前在周末无法提供服务，并将根据您所在时区在工作日提供服务 ",
    " as we operate from India. You can still leave a message. Please expect some delay in our response. Thank you for your patience.":
      " 因为我们在印度运营。您仍然可以留言。我们的回复可能会有所延迟。感谢您的耐心等待。",
    "Our support team is partially available according to your time zone from ":
      "根据您所在的时区，我们的支持团队部分可用 ",
    " as we operate from India. Responses may take 30 minutes to an hour during this time. Please leave a message, and we'll respond as soon as possible. Thank you for your patience.":
      " 因为我们在印度运营。在此期间，回复可能需要 30 分钟到 1 小时。请留言，我们会尽快回复。感谢您的耐心等待。",
    "Our support team is currently unavailable and will be available according to your time zone from ":
      "我们的支持团队目前无法提供服务，将根据您所在的时区从 ",
    to: "到",
    "Did not meet my expectations": "没有达到我的期望",
    "Feature Limitations": "功能限制",
    "Banner doesn't set in my app": "我的应用中未设置横幅",
    "Banner is not show properly": "横幅无法正常显示",
    "Confusing Set Multi Position and Multi Animation": "混淆设置多位置和多动画",
    "Sync Profile": "同步配置文件",
  },
};
let finalLanguage = mergeLanguage(modifyData, data);

export default finalLanguage;
